### PR TITLE
Opencl bernoulli logit lpmf

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Implements `bernoulli_logit_lpmf` using OpenCL, enabling it to use GPUs.

## Tests

The new implementation is tested.

## Side Effects

None.

## Release notes

Implemented `bernoulli_logit_lpmf` using OpenCL, enabling it to use GPUs.

## Checklist

- [ ] Math issue #2152 

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
Benchmark results are more or less as expected:

bernoulli_logit_lpmf_cl

**Comment by wds15** [comment]
Can you post the benchmark code please? I just used this as a base for my own and there were some more details which I needed to get straight for the reduce_sum. Thanks.

Looks anyway already nice.

**Comment by t4c1** [comment]
Benchmark code is here: https://gist.github.com/t4c1/8bb4ca33426754ca855ec88f8100ec44

It is more or less the same as one for `bernoulli_lpmf`, except benchmarking different function.

**Comment by wds15** [comment]
Here is a commented version of the reduce_sum with my changes:

```c++
struct reduce_sum_functor {
  var operator()(const std::vector<stan::math::var>& theta, int start, int end,
                 std::ostream* msgs, const std::vector<int>& y) {
//    std::ostringstream o;
//    o << "start: " << start << ", end: " << end << ", given size: "
//              << theta.size() << "\n";
//    std::cout << o.str();
 // y[end+1] should actually segfault
    std::vector<int> y_slice(&y[start], &y[end+1]);
    return bernoulli_logit_lpmf(y_slice, theta);
  }
};

static void benchmark_reduce_sum(benchmark::State& state) {
  const int N = state.range(0);

  std::vector<int> n(N);
  for (int i = 0; i < N; i++) {
    n[i] = Eigen::Array<int, Eigen::Dynamic, 1>::Random(1).abs()(0) % 2;
  }
  VectorXd theta_val = VectorXd::Random(N).array().abs();

  for (auto _ : state) {
    std::vector<var> theta;
    theta.reserve(N);
    for (int i = 0; i < N; i++) {
      theta.push_back(theta_val[i]);
    }

    auto start = std::chrono::high_resolution_clock::now();

    var lp = reduce_sum<reduce_sum_functor>(theta, std::max(1, N / 16), nullptr,
                                            n);
    lp.grad();

    auto end = std::chrono::high_resolution_clock::now();
    state.SetIterationTime(
        std::chrono::duration_cast<std::chrono::duration<double>>(end - start)
            .count());

    // doing this will wipe out the theta var vector!
    recover_memory();
  }
}
```

so I would use a nested thing

```c++
struct reduce_sum_functor {
  var operator()(const std::vector<stan::math::var>& theta, int start, int end,
                 std::ostream* msgs, const std::vector<int>& y) {
//    std::ostringstream o;
//    o << "start: " << start << ", end: " << end << ", given size: "
//              << theta.size() << "\n";
//    std::cout << o.str();
    std::vector<int> y_slice(y.begin() + start, y.begin() + end + 1);
    return bernoulli_logit_lpmf(y_slice, theta);
  }
};

static void benchmark_reduce_sum(benchmark::State& state) {
  const int N = state.range(0);

  std::vector<int> n(N);
  for (int i = 0; i < N; i++) {
    n[i] = Eigen::Array<int, Eigen::Dynamic, 1>::Random(1).abs()(0) % 2;
  }
  VectorXd theta_val = VectorXd::Random(N).array().abs();

  for (auto _ : state) {
    start_nested();
    std::vector<var> theta;
    theta.reserve(N);
    for (int i = 0; i < N; i++) {
      theta.push_back(theta_val[i]);
    }

    auto start = std::chrono::high_resolution_clock::now();

    var lp = reduce_sum<reduce_sum_functor>(theta, std::max(1, N / 16), nullptr,
                                            n);
    lp.grad();

    auto end = std::chrono::high_resolution_clock::now();
    state.SetIterationTime(
        std::chrono::duration_cast<std::chrono::duration<double>>(end - start)
            .count());

    recover_memory_nested();
  }
}
```

**Comment by t4c1** [comment]
> // doing this will wipe out the theta var vector!

That is ok - it is recreated every iteration.

> // y[end+1] should actually segfault

Are you sure? I thought reduce_sum is returning the index of the last element for `end`. While `std::vector` constructor requires index of (iterator to) element past the end.

**Comment by t4c1** [comment]
I just figured I posted wrong graph. This one should be the correct one. No major differences, just GPU speedup is a bit larger.

**Comment by wds15** [comment]
> That is ok - it is recreated every iteration.

No, that will wipe out the vari's from `theta` if I am not mistaken. The copy constructor does only link the vari's, but not create a new one.

**Comment by t4c1** [comment]
Yeah and that is fine. Varis are also recreated by putting double values into a vector of vars in `theta.push_back(theta_val[i]);`.

**Comment by wds15** [comment]
But you are putting a var into the push_back, but the vari with that var is wiped out.

Anyway... maybe I look into this for myself.

**Comment by t4c1** [comment]
>> But you are putting a var into the push_back

Nope. `theta_val` contains doubles. It is declared as: ` VectorXd theta_val = ...`

**Comment by wds15** [comment]
Ahh... oki doki!

**Review by rok-cesnovar — APPROVED** [review]
Looks good!

**Pull request merged**
