### PR TITLE
vectorize atan2

### PR DESCRIPTION
**Pull request by spinkney**
## Summary

Vectorized atan2 and added a unit test.

## Tests

There was no unit test for atan2 so I added for the scalar and vectorized cases.

## Release notes

The function `atan2` is vectorized on both the inputs.

## Checklist

- [x] Math issue #2809 

- [x] Copyright holder: Sean Pinkney

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by andrjohns — CHANGES_REQUESTED** [review]
Looks great! Can you just add `mix` tests for the vectorised implementations ([example with beta here](https://github.com/stan-dev/math/blob/develop/test/unit/math/mix/fun/beta_test.cpp)), and then this is good to go

**Comment by spinkney** [comment]
@andrjohns 2 questions

1. `stan::test::expect_common_nonzero_binary(f);` this errors out for `atan2`, do you know why?
2. On the 2nd test in that beta file if I do it on `atan2` I'm getting this error (as well as a bunch after)
`test/unit/math/mix/fun/atan2_test.cpp:42:12: error: no matching function for call to 'atan2'
    return atan2(x1, x2);`

**Comment by andrjohns** [comment]
So the 2nd error is caused by the `expect_ad_matvar` test, because the `atan2` function doesn't have an overload for `var_value<Eigen>` types, like the `beta` function, so you can just remove those tests.

What was the `expect_common_nonzero_binary` error? I can't find it in the logs above sorry

**Comment by spinkney** [comment]
Yes, I just added the overload :). I thought it would just work without it, lol. Once I push we'll be able to see the `expect_common_nonzero_binary` errors.

**Comment by spinkney** [comment]
The first error that comes up is
```bash
./test/unit/math/expect_near_rel.hpp:77: Failure
Value of: stan::math::is_nan(x1) && stan::math::is_nan(x2)
  Actual: false
Expected: true
expect_near_rel(0, nan)
expect_near_rel; require items x1(0) = x2(0): gradient() grad for finite diff vs auto diff

./test/unit/math/expect_near_rel.hpp:77: Failure
Value of: stan::math::is_nan(x1) && stan::math::is_nan(x2)
  Actual: false
Expected: true
expect_near_rel(0, nan)
expect_near_rel; require items x1(0) = x2(0): gradient_fvar() grad

```

**Comment by andrjohns** [comment]
I checked the values being used by the `expect_common_nonzero_binary` function, and it looks like the error occurs when the first argument to `atan2` is infinite. You can reproduce with:
```cpp
  stan::test::expect_ad(f, stan::math::INFTY, 1.0);
```

I would guess that there needs to be a check for finite values in the gradient calculations, otherwise one of the intermediate calculations results in a `nan` being returned

**Comment by spinkney** [comment]
That makes sense but I don't know how to achieve this. I tried a bunch of combinations of
```c++
  if (is_inf(a.val()) || is_nan(a.val()) || is_inf(b.val()) || is_nan(b.val())) {
     return make_callback_var(
      std::atan2(a.val(), b.val()), [a, b](const auto& vi) mutable {
        a.adj() += 0;
        b.adj() += 0;
      });
  }
```
and I'm not even sure that would work or is "idiomatic c++". I think I'll have to leave this unless you or someone else can fix the issue.

**Comment by spinkney** [comment]
@andrjohns I think I'll comment out `expect_common_nonzero_binary` and just test the derivative manually. Talking to @rok-cesnovar it seems that finite differences is failing for infinite input (as you noted too). However, I can't figure out how to just test expect_equal to nan for a _derivative_.

**Comment by andrjohns** [comment]
> @andrjohns I think I'll comment out `expect_common_nonzero_binary` and just test the derivative manually. Talking to @rok-cesnovar it seems that finite differences is failing for infinite input (as you noted too). However, I can't figure out how to just test expect_equal to nan for a _derivative_.

Sounds good to me! Ping me when this is ready for another look

**Comment by spinkney** [comment]
> I can't figure out how to just test expect_equal to nan for a _derivative_.

@andrjohns, would you be able to help with this?

**Comment by rok-cesnovar** [comment]
This is good to go now, right?

**Review by andrjohns — APPROVED** [review]
LGTM, thanks @spinkney!

**Pull request merged**
