### PR TITLE
[CI] Add additional quick checks for GPU and threading tests on PRs

### PR DESCRIPTION
**Pull request by seantalts**
Since we moved the GPU tests to be run only on merge, I've seen a couple of times where the PR passes tests but fails when the GPU tests are run on develop (likely due to the differing hardware on Jenkins vs developer machines). I'm adding a quick GPU test and threading test check phase to test suite to run on PRs, but leaving the full Unit Tests with the compile-time GPU and thread flags for only on merge.

The first test run should fail the GPU tests; I'll then commit fixes for those (hopefully) and push and merge once they pass the 2nd time.

- [ ] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses: Columbia University
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
notifying @bbbales2

**Comment by syclik** [comment]
Why are GPU tests only run on merge? Wouldn't it make sense to only run on
PRs when the changed files include something in the GPU directory?

If this is how we're going to proceed, can you describe the process you
want to take? If on merge, GPU tests fail, should we just undo the merge,
no questions asked?

**Comment by seantalts** [comment]
The Jenkins functionality for running tests when something in a subdirectory changes doesn't seem to work with stashes. Which tests were run was changed by community consensus a while back with your approval - I'll let you investigate if you want historical notes. The tests I'm adding on top of that approved process are just the GPU ones and they run relatively quickly (though they require a node with a GPU), so hopefully it's not too burdensome to add this additional check. I would expect failures on merge to develop maybe 1 in 1000 times after this change goes through as it would have to be that some non-GPU unit test fails only when `STAN_OPENCL` is defined. If you want to undo the merge when that happens feel free.

**Comment by syclik** [comment]
Thanks for the explaination. Mind pointing me to the thread? It doesn't
seem like those changes were documented appropriately on the wiki.

**Comment by syclik** [comment]
@seantalts: I couldn't find it on discourse. Could you point me in the
right direction?

**Pull request merged**
