### PR TITLE
Remove argument decorators from GPU kernel signatures

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

Removes read_only, write_only, and read_write from the arguments in the GPU kernel signature. The Windows OpenCL driver reserves read_only, write_only, and read_write argument decorators for pipes and image type arguments so our tests are failing on Rok's Windows test machine. The decorators are mostly a 'nice-ity' so we can remove them without much impact.

## Tests

Same tests as before

```cpp
./runTests.py -j8 test/unit/math/gpu/
```
## Checklist

- [x] Math issue #1034

- [x] Copyright holder: (fill in copyright holder information)

Steve Bronder, Rok Češnovar, and Erik Štrumbelj

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
We can maybe just use `const __global` instead of `__global read_only`. The OpenCL standard states: 
> The const qualifier can also be used with the __global qualifier to specify a read-only buffer memory object.

We can also use const with all non-global parameters, since we never change them.

**Comment by rok-cesnovar** [comment]
I think using the `const` qualifier will suffice for the kernels that we currently have. I dont see a case where `__constant` would be useful. 

It makes no sense to use caching for the simple parameters like `rows` and such, they all get loaded in registers anyways.

Using `__constant` for the simple kernels has no real benefit. In the only non-trivial kernels we currently have (matrix multiply), we use local memory instead of caching, which is a lot faster, if you can use it.
For future kernels we can just evaluate each case to see if it could be useful.

**Comment by SteveBronder** [comment]
Word that makes sense. Let's leave const out for now and revisit it later

**Comment by rok-cesnovar** [comment]
Agreed. I will open up an issue for a argument refactor (use size_t where applicable etc) that I will take care of this week. I have re-checked this PR and it looks fine.  Thanks Steve!

**Pull request merged**
