### PR TITLE
upgrade to Boost 1.65.1, fixes #680

### LINKED ISSUE #680: upgrade to boost 1.65.1
#### Summary:
MPI support is broken in 1.64.0 and BH is at 1.65

#### Description:
MPI things cannot be build with this.

#### Reproducible Steps:
try to build MPI libs from boost 1.64.0 - it fails

#### Current Output:
NaN

#### Expected Output:
Things should just build.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Upgrade to Boost 1.65.1

#### Intended Effect:

Catch up to the CRAN BH package.  Pave the way for MPI.

#### How to Verify:

Tests.

#### Side Effects:

No.

#### Documentation:

n/a

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
as proposed on discourse...should I add boost build, mpi + serialization to this?

**Comment by bob-carpenter** [comment]
@syclik:  Of course I'll fix this---didn't realize we had version numbers referenced in stan-dev/math

@wds15:  Either way is OK with me:  merge this then create a new pull request for the build stuff, or you can just take over this one.  I'm not sure what needs to be added myself or where it should go or how it should integrate with existing builds.

**Comment by wds15** [comment]
hmm... ok, maybe go ahead and merge this as is. We anyway need another issue+pull for getting the mpi build stuff into stan-math.

**Comment by bob-carpenter** [comment]
No idea what's going on here.  Now there's a numerical error in ADVI upstream that's blocking this merge.

**Comment by bob-carpenter** [comment]
I tracked down the issue here, which is that the upstream ADVI tests brittly coded `#if BOOST_VERSION > 106400`.  I'll create an issue to fix this in `stan-dev/stan` and submit a pull request, then circle back to this issue.

**Comment by bob-carpenter** [comment]
OK.  It's waiting on an upstream patch that had hard-coded 1.64
into a unit test. 

Boost build can go in with MPI build in this repo (stan-dev/math).

**Comment by bob-carpenter** [comment]
jenkins, retest this please

**Comment by bob-carpenter** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
@seantalts  I don't think the Jenkins retest is working.

**Comment by seantalts** [comment]
Woops, yes, I switched it over to the new pipelines - if you look under "Retrying a job" [here](http://discourse.mc-stan.org/t/new-jenkins-jobs-tutorial/2383) you can see how to do it. I kicked off this one just now.

**Comment by bob-carpenter** [comment]
Thanks, @seantalts.

**Comment by seantalts** [comment]
So this is passing now and we should ignore the X on the "default" check, since that one isn't being run anymore.

**Comment by bob-carpenter** [comment]
Cool.  Thanks for the heads up on that, too.  @syclik --- I made the change you requested, but it needs your approval to merge.

**Comment by wds15** [comment]
Was there a reason to not remove boost 1.64.0? Right now we have both versions in develop (only 1.65.1 gets used as I can see it).

**Comment by seantalts** [comment]
Good catch - I'm guessing we can take it out now. I'll make a PR deleting it.

**Comment by bob-carpenter** [comment]
My mistake---should've deleted it.

**Pull request merged**
