### PR TITLE
Feature/issue 48 cholesky decompose

### PR DESCRIPTION
**Pull request by rtrangucci**
This was an open pull request from stan-dev/stan
stan-dev/stan#1385

### CODE REVIEW

**Comment by rtrangucci** [comment]
@syclik the cost of letting branches float around for a long time... test/unit/math/mix/mat/fun/cholesky_decompose_test.cpp is the test that failed because of (now) invalid input matrices in the derivative tests. I'm going to write a cholesky_decompose()-specific suite of finite diff and auto diff derivative tests, but as @bob-carpenter and I were talking about yesterday, we'll need something more general for other non-scalar-valued functions in the future.

**Comment by rtrangucci** [comment]
@syclik The test that failed, prim/mat/err/check_pos_definite_test.cpp passes on my computer...

**Comment by syclik** [comment]
yeah... same here. I'm trying to run it on the linux vm on the laptop to
see if it trips there.

**Comment by syclik** [comment]
I'm seeing the failure on the linux vm, but not on Mac.
This test fails: `test/unit/math/mix/mat/fun/mdivide_right_spd_test`
```
[ RUN      ] AgradMixMatrixMdivideRightSPD.matrix_d_row_vector_ffv4
[       OK ] AgradMixMatrixMdivideRightSPD.matrix_d_row_vector_ffv4 (0 ms)
[ RUN      ] AgradMixMatrixMdivideRightSPD.ffv_exceptions
test/unit/math/mix/mat/fun/mdivide_right_spd_test.cpp:1484: Failure
Expected: mdivide_right_spd(rvf1, fd1) throws an exception of type std::domain_error.
  Actual: it throws nothing.
[  FAILED  ] AgradMixMatrixMdivideRightSPD.ffv_exceptions (1 ms)
[----------] 38 tests from AgradMixMatrixMdivideRightSPD (10 ms total)

[----------] Global test environment tear-down
[==========] 38 tests from 1 test case ran. (11 ms total)
[  PASSED  ] 37 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AgradMixMatrixMdivideRightSPD.ffv_exceptions
```

There might be others that fail too. That was the first one that was triggered.

**Comment by rtrangucci** [comment]
@syclik any luck? I'm confused, especially because these tests passed the first go around...

**Comment by rtrangucci** [comment]
Not sure what happened here, but this one also passed unit tests. This is
the error that was thrown at the end of tests:

[WARNINGS] Parsing warnings in console log with parser GNU C Compiler 4 (gcc)
[WARNINGS] Computing warning deltas based on reference build #82
[WARNINGS] Ignore new warnings since this is the first valid build
[WARNINGS] Plug-in Result: Failed - <a href="warningsResult">1
warning</a> exceeds the threshold of 0 by 1
Build step 'Scan for compiler warnings' changed build result to FAILURE
Recording test results
Finished: FAILURE



Rob

**Comment by syclik** [comment]
The last one failed... the current build is almost done testing.

**Comment by syclik** [comment]
There's a unsigned int warning in one of the tests.

**Comment by syclik** [comment]
test/unit/math/mix/mat/fun/cholesky_decompose_test.cpp:152:28:
warning: comparison of integers of different signs: 'size_t' (aka
'unsigned long') and 'int' [-Wsign-compare]
      for (size_t k = 0; k < numels; ++k)
                         ~ ^ ~~~~~~

**Comment by rtrangucci** [comment]
thx, fixed it.


Rob

**Comment by syclik** [comment]
@rtrangucci, looks good. I'm going to merge with develop and kick off a new set of tests just to see if anything else trips.

**Pull request merged**
