### PR TITLE
Fixes #667 - Change string back to char*

### LINKED ISSUE #667: Change std::string back to char* (PR #584) for performance reasons
#### Summary:
We changed from char* to std::string in #584, issue #460.

This was bad for performance. We should
- [ ] revert #584 
- [ ] reopen #460 (C++11 should be able to do this without the performance hit)

#### Reproducible Steps:
Run the performance tests. No other behavior changed.

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by seantalts**
Automating it was easier than dealing with the merge conflicts. Need to check I did it correctly. Here's my automation code:

```
find stan test -name *.hpp -or -name *.cpp | xargs  sed -i '' -e '/#include <string>/d' # assumes nothing else uses strings
find stan test -name *.cpp -or -name *.hpp | xargs  sed -i '' -e 's/const std::string&/const char*/g'
find stan test -name *.cpp -or -name *.hpp | xargs  sed -i '' -e 's/const std::string /const char* /g'
git checkout test/unit/util.hpp stan/math/version.hpp
```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University 

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Thanks! I'll walk through the changed files one by one to make sure it's ok.

**Comment by bgoodri** [comment]
`git grep -F -l "const std::string&"` is better than find. See

https://github.com/stan-dev/stan/issues/2381#issuecomment-338497009

**Comment by bbbales2** [comment]
Thumbed through most of this. The library source looks mostly good. It's in the tests where things seem to be different.

The replacements in:
test/unit/math/prim/arr/functor/mock_throwing_ode_functor.hpp, math/test/unit/math/rev/arr/err/out_of_range_test.cpp, and math/stan/math/rev/mat/functor/cvodes_utils.hpp don't seem to have ever been char*s for instance.

Not sure if any of those cause bugs. Maybe there's a way to get the list of files changed in the char* -> std::string commits and only do this replacement on them?

**Comment by seantalts** [comment]
okay, I used this command instead to get the list of files:
```git diff-tree --no-commit-id --name-only -r -m 6fc8e2a598ec1839f82deb0ba81853d0faad5df5```

Now shows that it's changed the same number of files as PR #584. Slightly less changes than #584 but that PR also had some whitespace changes. Think it's good to go.

**Comment by bob-carpenter** [comment]
Looks good to me.  I spot checked and used the following grep to make sure there weren't `std::string` arguments in the error-handling functions:

```
~/cmdstan/stan/lib/stan_math/stan/math(feature/0667-char2str)$ grep std::string */*/err/*.hpp

prim/arr/err/check_ordered.hpp:          std::string msg1_str(msg1.str());
prim/arr/err/check_ordered.hpp:          std::string msg2_str(msg2.str());
prim/mat/err/check_column_index.hpp:      std::stringstream msg;
prim/mat/err/check_column_index.hpp:      std::string msg_str(msg.str());
prim/mat/err/check_corr_matrix.hpp:          std::string msg_str(msg.str());
prim/mat/err/check_ldlt_factor.hpp:        std::string msg_str(msg.str());
prim/mat/err/check_lower_triangular.hpp:            std::stringstream msg;
prim/mat/err/check_lower_triangular.hpp:            std::string msg_str(msg.str());
prim/mat/err/check_matching_dims.hpp:        std::string msg_str(msg.str());
prim/mat/err/check_ordered.hpp:          std::string msg1_str(msg1.str());
prim/mat/err/check_ordered.hpp:          std::string msg2_str(msg2.str());
prim/mat/err/check_positive_ordered.hpp:        std::string msg_str(msg.str());
prim/mat/err/check_range.hpp:      std::stringstream msg;
prim/mat/err/check_range.hpp:      std::string msg_str(msg.str());
prim/mat/err/check_row_index.hpp:      std::stringstream msg;
prim/mat/err/check_row_index.hpp:      std::string msg_str(msg.str());
prim/mat/err/check_simplex.hpp:        std::stringstream msg;
prim/mat/err/check_simplex.hpp:        std::string msg_str(msg.str());
prim/mat/err/check_simplex.hpp:          std::string msg_str(msg.str());
prim/mat/err/check_std_vector_index.hpp:      std::stringstream msg;
prim/mat/err/check_std_vector_index.hpp:      std::string msg_str(msg.str());
prim/mat/err/check_symmetric.hpp:            std::string msg1_str(msg1.str());
prim/mat/err/check_symmetric.hpp:            std::string msg2_str(msg2.str());
prim/mat/err/check_unit_vector.hpp:        std::stringstream msg;
prim/mat/err/check_unit_vector.hpp:        std::string msg_str(msg.str());
prim/mat/err/check_vector.hpp:      std::string msg_str(msg.str());
prim/mat/err/validate_non_negative_index.hpp:        std::stringstream msg;
prim/mat/err/validate_non_negative_index.hpp:        std::string msg_str(msg.str());
prim/scal/err/check_2F1_converges.hpp:      std::stringstream msg;
prim/scal/err/check_3F2_converges.hpp:      std::stringstream msg;
prim/scal/err/check_bounded.hpp:              std::stringstream msg;
prim/scal/err/check_bounded.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_bounded.hpp:              std::stringstream msg;
prim/scal/err/check_bounded.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_consistent_size.hpp:      std::stringstream msg;
prim/scal/err/check_consistent_size.hpp:      std::string msg_str(msg.str());
prim/scal/err/check_greater.hpp:              std::stringstream msg;
prim/scal/err/check_greater.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_greater.hpp:              std::stringstream msg;
prim/scal/err/check_greater.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_greater_or_equal.hpp:              std::stringstream msg;
prim/scal/err/check_greater_or_equal.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_greater_or_equal.hpp:              std::stringstream msg;
prim/scal/err/check_greater_or_equal.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_less.hpp:              std::stringstream msg;
prim/scal/err/check_less.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_less.hpp:              std::stringstream msg;
prim/scal/err/check_less.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_less_or_equal.hpp:              std::stringstream msg;
prim/scal/err/check_less_or_equal.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_less_or_equal.hpp:              std::stringstream msg;
prim/scal/err/check_less_or_equal.hpp:              std::string msg_str(msg.str());
prim/scal/err/check_positive_size.hpp:        std::stringstream msg;
prim/scal/err/check_positive_size.hpp:        std::string msg_str(msg.str());
prim/scal/err/check_size_match.hpp:      std::string msg_str(msg.str());
prim/scal/err/check_size_match.hpp:      std::string updated_name_str(updated_name.str());
prim/scal/err/check_size_match.hpp:      std::string msg_str(msg.str());
prim/scal/err/domain_error_vec.hpp:      std::string vec_name(vec_name_stream.str());
```

**Comment by seantalts** [comment]
Ah, there were some new files added since August 3rd that use the new string stuff... Need to figure out how to find those properly... oye

**Comment by seantalts** [comment]
Jenkins, retest this please.

(Want to use the faster distribution tests that just got merged)

**Pull request merged**
