### PR TITLE
WIP: Debugging OpenCL broadcasting tests' crashes

### PR DESCRIPTION
**Pull request by t4c1**
Thanks for submitting a pull request! Please remove this text when submitting.

Start by filling in the Summary, Tests, and Side Effects sections of this pull request and then work through the handy checklist at the bottom. If anything significant is missing, the pull request may be closed until it's ready. The full guidebook on how pull requests are reviewed is here: [Code Review Guidelines](https://github.com/stan-dev/math/wiki/Developer-Doc#code-review-guidelines).

## Summary

Describe the contents of the pull request. The issue describes the problem that needs to be fixed, whereas the text here should help the reviewer figure out to what extent this pull request solves the issue.

Describe implementation details and any relevant information that would help the code reviewer understand this pull request. If there is anything special you need to draw someone's attention to, do it here. Link to any related pull requests or Discourse threads.

## Tests

Describe the new tests with the pull request.

For bug fixes there should be a new test that would fail if the patch weren't in place (so that the bug could be caught if it comes up again).

For new features there should be at least one test showing the expected behavior and one test that demonstrates error handling. Be aware the reviewer will very likely ask for more tests than this, but it's a start.

## Side Effects

Are there any side effects that we should be aware of?

## Release notes

Replace this text with a short note on what will change if this pull request is merged in which case this will be included in the release notes.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
The crash happens in `program.build()`. Looking at the arguments to this call, nothing looks wrong, so this must be a bug in the kernel compiler. There is not much we can do to fix this. We could try to update the OpenCL drivers on the mac that is failing. @serban-nicusor-toptal could you do that? 

I will also try to simplify the generated kernels a bit in attempt to work around this.

**Comment by serban-nicusor-toptal** [comment]
Hey, current version is: `  Platform Version                                OpenCL 1.2 (Jun 15 2018 20:52:09)`
I will now try to update it.

**Comment by serban-nicusor-toptal** [comment]
Hey @t4c1 I think `OpenCL 1.2` is the last version we can support on the mac as written in the Apple Support forums [here](https://support.apple.com/en-us/HT202823) please correct me if I'm wrong.

**Comment by rok-cesnovar** [comment]
Yeah, OpenCL 1.2 is the latest OpenCL version we can support on MacOS. But can we maybe upgrade the GPU driver?

**Comment by serban-nicusor-toptal** [comment]
Mac has GPU drivers tied to the OS and I couldn't find an update for the Drivers, just some not needed ones.

```
Software Update Tool
Copyright 2002-2015 Apple Inc.

Finding available software    
Software Update found the following new or updated software:
   * iTunes Device Support Update-
        iTunes Device Support Update ( ), 105805K [recommended] [restart]
   * iTunesX-12.8.2
        iTunes (12.8.2), 273614K [recommended]
```

Sorry I couldn't help, let me know if there's anything else I can do.

**Comment by SteveBronder** [comment]
@rok-cesnovar @serban-nicusor-catena is it possible to identify which Jenkins machine / opencl version this is breaking for? Talking to @t4c1 it sounded like this may be a bug directly in the opencl impl when compiling programs

**Comment by SteveBronder** [comment]
Could we use pocl on the mac instead of the default mac implementation? tmk most macs now don't come with OpenCL do they?

**Comment by serban-nicusor-toptal** [comment]
I think it comes by defaut, I've tried on a mac-mini using clinfo.
`bew install clinfo`

I'm getting `OpenCL 1.2 (Jun 8 2020 17:36:15)`, the only thing I've installed was `XCode Developer Tools` from the Store. I've also found this in the opencl [repo](https://github.com/s-u/OpenCL/blob/master/INSTALL):

```
Type: GPU, CPU
Vendor: Apple
This OpenCL implementation is part of Mac OS X 10.6 (Snow Leopard) and
Max OS X 10.7 (Lion) operating systems. The OpenCL package has been
successfully tested with nVidia GPU devices (only single-precision is
supported on the devices available to us).
The OpenCL framework is part of the OS so no additional libraries need
to be installed.
```

Although I'm not sure if it's applicable for all versions, couldn't find anything on their forums.

**Comment by t4c1** [comment]
It seems the workaround from #2215 does not for for the mac, so we can not use it for running OpenCL tests anymore.

**Pull request closed without merging**
