### PR TITLE
Upgrade Boost to 1.81

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR upgrades the bundled boost version to 1.81, using the `lib/upgrade-boost.sh` script. 1.81 is the current version in the R `BH` headers.'

## Tests

N/A current tests should still pass

## Side Effects

N/A

## Release notes

Updated Boost headers to v1.81

## Checklist

- [ ] Math issue #(issue number)

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by syclik — CHANGES_REQUESTED** [review]
@andrjohns, thanks for doing this! 

There's a file that was missed in the script that needs to be modified by hand. `doxgyen/README.md`. I'm seeing L11 and L76.

**Comment by syclik** [comment]
Has R's BH package been bumped to 1.81 or is that concern irrelevant now?

**Comment by andrjohns** [comment]
> Has R's BH package been bumped to 1.81 or is that concern irrelevant now?

Yep, 1.81 is the current version of `BH`

**Review by syclik — APPROVED** [review]
Thank you!

**Comment by WardBrian** [comment]
After this cmdstan's build has a new warning:

```
In file included from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/detail/yield_k.hpp:23,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/detail/spinlock.hpp:42,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/smart_ptr/shared_ptr.hpp:29,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/shared_ptr.hpp:17,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/date_time/time_clock.hpp:17,
                 from stan/lib/stan_math/lib/boost_1.81.0/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from src/cmdstan/arguments/arg_seed.hpp:5,
                 from src/cmdstan/arguments/arg_random.hpp:4,
                 from src/cmdstan/command.hpp:9,
                 from src/cmdstan/main.cpp:1:
stan/lib/stan_math/lib/boost_1.81.0/boost/config/pragma_message.hpp:24:34: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   24 | # define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
      |                                  ^~~~~~~
stan/lib/stan_math/lib/boost_1.81.0/boost/config/pragma_message.hpp:24:34: note: in definition of macro ‘BOOST_PRAGMA_MESSAGE’
   24 | # define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
      |                                  ^~~~~~~
stan/lib/stan_math/lib/boost_1.81.0/boost/iterator.hpp:10:1: note: in expansion of macro ‘BOOST_HEADER_DEPRECATED’
   10 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

It's not immediately clear to me what we can do - it sounds like boost is including its own deprecated header?

**Comment by andrjohns** [comment]
I had a look at the error, looks like it's a Stan header including `<boost/iterator.hpp>`:
```
In file included from stan/src/stan/services/pathfinder/multi.hpp:19:
stan/lib/stan_math/lib/boost_1.81.0/boost/iterator.hpp:10:1: warning: This header is deprecated. Use <iterator> instead. [-W#pragma-messages]
   10 | BOOST_HEADER_DEPRECATED("<iterator>")
```

I believe that [this line](https://github.com/stan-dev/stan/blob/ec089daf9a3f4a5ea9a0e2e2fa4427e4b99c0604/src/stan/services/pathfinder/multi.hpp#L19) just needs to be changed to `<iterator>`

**Comment by WardBrian** [comment]
I think that `boost/iterator.hpp` and `iterator` are only equivalent in C++20 and later

**Pull request merged**
