### PR TITLE
Update develop after patch release

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

This updates the develop branch with the changes merged to master for the patch release which were https://github.com/stan-dev/math/pull/2365 https://github.com/stan-dev/math/pull/2366 and https://github.com/stan-dev/math/pull/2371

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal did this as a PR just so we have everything triple checked.

**Comment by hsbadr** [comment]
@rok-cesnovar I've tested this and it looks good to me. One more thing: the version number, release notes, and tags need to be updated on https://github.com/stan-dev/stan/tree/develop after `v2.26.1`.

**Comment by rok-cesnovar** [comment]
Oh, right, we need to do that as well. Thanks!

**Comment by rok-cesnovar** [comment]
https://github.com/stan-dev/cmdstan/pull/985 and https://github.com/stan-dev/stan/pull/3007 will handle that.

**Review by t4c1 — APPROVED** [review]

**Pull request merged**
