### PR TITLE
Split full unit tests

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Splits the full unit test in three parts and runs them in parallel.

## Tests

/

## Side Effects

/

## Checklist

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@andrjohns have you maybe figured out what is behind this failure with the address sanitizer. Should we disable it for the time being until we figure this out?

**Comment by andrjohns** [comment]
No idea sorry!

**Comment by SteveBronder** [comment]
Did we switch to using g++? I thought we previously used clang for sanitizing?

**Comment by rok-cesnovar** [comment]
We did, but it fails with the same error regardless. And no one can reproduce locally. I am tempted to remove it temporarily as its been clogging up development the last few weeks. We should re-add it before the release though.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal this is ready for review when you have time. Gets the full unit tests down to 45minutes.

**Review by serban-nicusor-toptal — APPROVED** [review]
LGTM! Thanks.

Address sanitizer should be hopefully fixed by: https://github.com/stan-dev/math/pull/2702

**Pull request merged**
