### PR TITLE
Feature/0370 cpp11 cmath funs

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Remove `math.h` includes for `log1p`, `log1m` and `acosh` and always delegate to Boost (no more ifdefing on MSVC).

#### Intended Effect:

Trial to see if I can go ahead and get rid of all the `math.h` includes in the same way.

#### How to Verify:

Unit tests updated.

#### Side Effects:

Stan programs will now throw errors as soon as it gets an error in one of these functions rather than just returning NaN or infinite values.

#### Documentation:

Yes, in the C++ API.  We haven't documented exact error conditions in the Stan language manual yet.

#### Reviewer Suggestions: 

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@bob-carpenter, the current tests fail. You can run this to verify (it'll take a while to compile):
```
 ./runTests.py test/prob/beta/beta_ccdf_log_00000_generated_v_test.cpp
```
I haven't traced through where it throws this exception, but I'm going to guess it's with the `inc_beta()` function or the `grad_reg_inc_beta()` function.

**Comment by syclik** [comment]
These are minimal tests showing the problem. I haven't hunted down the actual cause for the exception.
```
#include <stan/math/rev/scal.hpp>
#include <gtest/gtest.h>

TEST(beta_ccdf, failure1) {
  double UB = 1;
  double alpha = 1;
  stan::math::var beta = 1;
  EXPECT_NO_THROW(stan::math::beta_ccdf_log(UB, alpha, beta));
}

TEST(beta_ccdf, failure2) {
  double UB = 1;
  stan::math::var alpha = 1;
  double beta = 1;
  EXPECT_NO_THROW(stan::math::beta_ccdf_log(UB, alpha, beta));
}

TEST(beta_ccdf, failure3) {
  double UB = 1;
  stan::math::var alpha = 1;
  stan::math::var beta = 1;
  EXPECT_NO_THROW(stan::math::beta_ccdf_log(UB, alpha, beta));
}

TEST(beta_ccdf, passes) {
  double UB = 1;
  double alpha = 1;
  double beta = 1;
  EXPECT_NO_THROW(stan::math::beta_ccdf_log(UB, alpha, beta));
}
```

**Comment by syclik** [comment]
I've narrowed it down. This used to work and now it doesn't:
```
#include <stan/math/prim/scal.hpp>
#include <gtest/gtest.h>

TEST(grad_reg_inc_beta, failure1) {
  double g1 = 0;
  double g2 = 0;
  double alpha = 1.0;
  double beta = 1.0;
  double y = 1.0;
  double digamma_alpha = stan::math::digamma(alpha);
  double digamma_beta = stan::math::digamma(beta);
  double digamma_sum = stan::math::digamma(alpha + beta);
  double betafunc = std::exp(stan::math::lbeta(alpha, beta));

  stan::math::grad_reg_inc_beta(g1, g2, alpha, beta, y,
                                digamma_alpha, digamma_beta, digamma_sum,
                                betafunc);
}
```

Those were the values that's being called from `beta_ccdf_log()`.

**Comment by syclik** [comment]
@bob-carpenter, I've added a unit test that's going to fail on this branch. We can decide whether to change the behavior of `grad_reg_inc_beta()` or to deal with it some other way. I've just pushed it and the failing test is here:
`test/unit/math/prim/scal/fun/grad_reg_inc_beta_test.cpp`

I'm going to doc the function now.

**Comment by bob-carpenter** [comment]
Going to move this to do all functions at once.

**Pull request closed without merging**
