### PR TITLE
Throw when computing inverse of a size 0 matrix

### LINKED ISSUE #1463: inverse should have consistent errors on size 0 inputs
## Description
There's a test that's currently commented out in test/unit/math/mix/mat/fun/inverse_test.cpp because it fails, due to inconsistent behaviour of `inverse` on size 0 inputs between prim and rev.

That test could be replaced with the following, which is more general:

```
Eigen::MatrixXd t2(0, 0);
stan::test::expect_ad(f, t2);
```

It will work after making prim throw on size 0 inputs.

### PR DESCRIPTION
**Pull request by mcol**
## Summary

Fixes #1463.

## Tests

Added test mentioned in the issue and another one too.

## Side Effects

None.

## Checklist

- [X] Math issue #1463

- [X] Copyright holder: Marco Colombo

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

**Comment by mcol** [comment]
While we are here we could perhaps remove this other comment:
```
  // fails with assertion from Eigen
  // stan::test::expect_ad(f, t);
```

If I understand correctly, expect_ad doesn't work with `t` being an `Eigen::Matrix<stan::math::var, -1, -1>`, so this will never be valid code.

**Comment by bob-carpenter** [comment]
expect_ad(f, x) should work when x is a matrix of any shape, including 0 x 0.  If it doesn't, it's a bug.

**Comment by mcol** [comment]
The problem there is that it's Matrix of `stan::math::var`: that comment is wrong, as the test doesn't fail, it doesn't even compile.

**Comment by bob-carpenter** [comment]
I misunderstood---I missed the var.  You're right the framework doesn't work with var inputs!

**Pull request merged**
