### PR TITLE
Fixes for RTools 3.5

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Current develop fails with RTools 3.5 tests. This PR fixes that by removing the use of some C++ features only available with compilers that have full C++14 support.

Also splits one failing test in two (the test was too big for RTools 3.5).

No release notes as this is just fixing develop.

## Tests

/

## Side Effects

/

## Checklist

- [x] Math issue N/A

- [x] Copyright holder: Tadej Ciglarič, Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@syclik this is blocking the https://github.com/stan-dev/cmdstan/pull/924 cmdstan PR (we test that models compile with RTools 3.5 in cmdstan as well).

**Comment by rok-cesnovar** [comment]
Ready for review.

**Comment by syclik** [comment]
I can’t see the diff on my phone. I’ll check on it later.

**Comment by bbbales2** [comment]
Oh it says there in the comments, cool.

**Comment by syclik** [comment]
Thanks, Ben and Rok!

**Pull request merged**
