### PR TITLE
nngp_loglikelihood

### PR DESCRIPTION
**Pull request by LuZhangstat**
#### Submisison Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks for submitting the pull request.  It needs to be reformulated to conform to our dependency requirements.  At the very least:

1.  remove all dependencies on R and all associated data and binary files

2.  add unit tests for the function that explores all possible instantiation patterns.  this one's going to be tricky because it's an 8-argument density, so there are 2^8 = 256 possible type instantiations of those arguments.  There's a framework for testing probability functions that you could use, but I'm not sure it'll handle 8 argument densities.  Is there a way to break out the kernel into a single argument so that different kernels could be used and it cuts down on number of arguments?

3.  conform to Cpplint style guidelines

4.  declare copyright holder

5.  maybe it's clear to other people who use NNGPs, but the name of the variables and descriptions weren't clear to me.  Is there an open-access reference somewhere like Wikipedia we could cite?

6.  Rather than writing things like `int M = neardist.cols();    // no. of neighbors` you can just provide a more informative name for `M` --- self documnting code is better than doc.

7.  get rid of useless comments like "check dimension matching" before calling `check_size_match` --- if you can tell what something does from reading the code, don't document it.  Assume the reader knows C++ very well.

8.  get rid of erroneous comments like `VectorXd Uw(N);       // Uw(N) = temp_w(N) = Y - X * beta`  (this is not correct --- Uw is just defined to be a vector of size N, it doesn't get that value until later).  Again, feel free to rename vaiables things like `Y_minus_X_times_beta` if it makes the code clearer.

9.  In your loop, you set the (k, k) indexes twice --- you need to change the initial point for the second loop to `k = j + 1`.  Overassigning is an efficiency drain for autodiff because a bunch of expressions get created and differentiated then thrown away.

10.  You can't use `std::exp(...)` on a templated argument.  You need to use `using std::exp;` and then just `exp(...)` in order to enable argument-dependent lookup.  this would've been exposed when you tested the instantiations.

11.  in the loop to set `temp_distM(k, k)` you should just compute the value once and reuse.  Redundant calculations are a huge time sink for autodiff for same reason as above.  Also, I don't like `temp` in names.  In fact, you should save this at a higher scope because you reuse the quantity later.

12.  `V((i+1))`  doesn't need redundant parens.   And we want space around operators.

13.  spaces between symbols and curly braces

In terms of addressing the second issue, is there a way to break out the kernel so it's not built into the function?  That would

**Comment by LuZhangstat** [comment]
Hi Bob,

    Thank you so much for your instructions! I learn a lot from it.

    I have some suggestions for solving the second problem. I can write a
function for getting the "neardist", "neardistM" and "nearind" from the
coordinates of the observation locations. Then the generated distance
matrixes can be used in the calculation of log-likelihood so that we don't
need to test possible types for these three arguments. However, since these
three matrixes are only needed to be calculated once in the whole MCMC
process, one might want to have a separate step to get those matrixes, save
them and then call them later in the MCMC process. I don't know how to
realize that. Would you please give me some advice on this?

    Besides, I can write the main for-loop into a separate function, the
number of arguments for that function will be reduced to four.

    I will change my code according to your comments. Thank you again for
all your help, and please feel free to give me suggestions.

Sincerely,

Lu Zhang

**Comment by bob-carpenter** [comment]
> I have some suggestions for solving the second problem. I can write a
> function for getting the "neardist", "neardistM" and "nearind" from the
> coordinates of the observation locations. Then the generated distance
> matrixes can be used in the calculation of log-likelihood so that we don't
> need to test possible types for these three arguments. However, since these
> three matrixes are only needed to be calculated once in the whole MCMC
> process, one might want to have a separate step to get those matrixes, save
> them and then call them later in the MCMC process. I don't know how to
> realize that. Would you please give me some advice on this?

If they only depend on data, define them in the transformed data block.
If they depend on parameters, define them as local variables in the model
block.  Either way, you can reuse them after they're defined.

**Comment by LuZhangstat** [comment]
Got it! Thank you very much!

Best,

Lu Zhang

**Comment by bob-carpenter** [comment]
@LuZhangstat  The pull request isn't complete.  At the very least, we need to know who holds copyright to what you're submitting and get permission to release code under BSD and doc under CC BY.  But it'd also be nice to have a short description about what the pull request adds.  Thanks.

**Comment by LuZhangstat** [comment]
Okay, I will add it later, thank you very much!

Merry Christmas!

Lu Zhang

**Comment by bob-carpenter** [comment]
This one's been in process several months, so I'm closing it.  @LuZhangstat if you want to open it again later, feel free.

**Comment by LuZhangstat** [comment]
Okay, sorry for that. Thank you very much!

Sincerely,

Lu Zhang

**Pull request closed without merging**
