### PR TITLE
Removing the last varis that need their C++ destructors called

### PR DESCRIPTION
**Pull request by bbbales2**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [ ] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

I'm working on removing the dependency of a bunch of varis on the C++ heap (https://github.com/stan-dev/math/issues/565)

This is super preliminary. Mostly interested in how many of the tests I broke.

#### Intended Effect:

That's in the summary!

#### How to Verify:

tbd

#### Side Effects:

tbd

#### Documentation:

tbd

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bbbales2** [comment]
@bob-carpenter We should meet and talk about this branch next week. It's not finished, but at least a basic grepping for chainable_alloc says it's all been removed.

I've rewritten quite a lot of stuff. I wanna make sure the design patterns and stuff are all good before I go around tightening the bolts.

**Comment by bbbales2** [comment]
Yeah, I'm not gonna finish it before I head back to SB.

**Comment by bbbales2** [comment]
But for people of the future, look at the comments on https://github.com/stan-dev/math/issues/565 to get the status of this unfinished pull req.

**Comment by syclik** [comment]
Lol. Just at yourself. You'll thank me for that in the future.

**Pull request closed without merging**
