### PR TITLE
Feature/issue-stan-2462 overload autocorrelation/covariance

### PR DESCRIPTION
**Pull request by roualdes**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This PR replaces https://github.com/stan-dev/math/pull/790 and the sloppy git work found within

Overload `stan::math::autocovariance` and `stan::math::autocorrelation` to

1. reduce copying within current effective_sample_size calculations, and
2. allow new signature for effective_sample_size to be used by pystan/rstan.

#### Intended Effect:

Reduce copying and increases access to effective_sample_size calculations for pystan/rstan.

#### How to Verify:

`make clean && ./runTests.py -j2 test/unit/math/prim/mat/fun/`

will call two new tests within autocorrelation_test.cpp and autocovariance_test.cpp

#### Side Effects:

None intended.

#### Documentation:

Document new functions' signatures.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

California State University, Chico

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Yes, the memory must be fully allocated in the `std::vector` before passing into an `Eigen::Map`.  The map keeps a pointer to the memory and delegates calls to its indexing operation  `T operator()(int i)` off to the raw memory in the standard vector.

Can the problem be fixed by resizing the relevant `std::vector` argument?

**Comment by roualdes** [comment]
Short story: resizing the `std::vector`s passes the appropriate checks on my machine.  The latest commit/push includes this change.

Long story: trying to `reserve` sufficient space, instead of resizing, did not work.  For whatever reason `reserve` was my first thought.  Googling around reminded me that reserve can invalidate pointers/references.  The consensus was less clear for `resize`.  But if you're confident that `resize` won't invalidate pointers/references across all OS/compiler combinations, then I'm content with this solution.

**Comment by roualdes** [comment]
This resize strategy is fine.  My thinking about invalidating references/pointers was stuck in the world of `array`s, where the array variable name is the really just a pointer to the 0th element's address.

Here, and I verified, the `std::vector` gets its own address, different from the address of the 0th element of the data.  Since we are passing the address of the vector, we can freely change (once, before putting any data into the `std::vector`) the address of the data to be stored within the `std::vector` without affecting the address of the `std::vector` itself.

Thanks for the great thought, @bob-carpenter, and thanks for the education in C++!

**Comment by bob-carpenter** [comment]
Resize vs. reserve is subtle.  

```
vector<foo> x;
x.reserve(10000);
// x.size() == 0 here
```

will allocate the memory for 10K instances of `foo`, but it won't call any constructors.  It's good for when you want to allocate the memory once then use `push_back` or `emplace_back`.  The latter is a C++11 feature that lets you construct the object directly in the memory allocated by the `std::vector` rather than constructing on the stack and copying into the vector.  The `vector` itself will be on the stack, and that consists of a size and a pointer to memory on the heap.  The resize changes that memory on the heap and has the `vector` point to the new memory that's big enough.  Getting familiar with `std::vector` or `Eigen::Matrix` and their differences is very useful.  They're nice instances of the RAII pattern (resource allocation is initialization), which you need to know to use C++ effectively.

In constrast,

```
vector<foo> x;
x.resize(10000);
// x.size() = 10000
```

Now you get 10000 instances on the stack and 10000 calls to the nullary constructor `foo()`.  This isn't good if you have expensive objects to construct.  Given that we have `double` values, this will be fine---no constructor overhead there.

**Comment by bob-carpenter** [comment]
Thanks for updating, by the way.  Is this ready for final review?

**Comment by bob-carpenter** [comment]
Yes, that's right.  The `std::vector` itself will live on the stack (it's an object containing fields for the size of the vector, size of memory allocated, and pointer to heap memory).  The raw memory is encapsulate din the RAII pattern (allocated on construction, reallocated on resize, deallocated on destruction through the destructor).  As soon as the vector goes out of scope on the function-call stack, its heap memory is collected through its destructor.

**Comment by roualdes** [comment]
I appreciate your time to offer me some words on `std::vector`s.  Yes, ready for final review.  Thanks.

**Comment by syclik** [comment]
@bob-carpenter, I'll assume you're reviewing this pull request. If you're not, please let me know.

**Comment by bob-carpenter** [comment]
Yes, just coming up for air.  I'll deal with this one and the MPI one.

**Pull request merged**
