### PR TITLE
Eigen elementwise functions with autodiff variables (#1)

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This is the first batch of elementwise functions to add the use of Eigen's elementwise functions for calculating the values and gradients of containers of autodiff variables. The following functions are included in this pull:

- ```acos```
- ```asin```
- ```atan```
- ```ceil```
- ```cos```
- ```cosh```
- ```exp```
- ```fabs```
- ```floor```
- ```inv```

I can also break this pull out into smaller chunks if there's too much to review easily in this one.

## Tests
No tests added, as current behaviour should not change

## Side Effects
N/A

## Checklist

- [x] Math issue #1783 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
It doesn't seem like the benchmarks we generally run cover these functions. Would you mind writing up a benchmark for this in perf_math?

**Comment by andrjohns** [comment]
Good call! Ill get on that

**Comment by andrjohns** [comment]
Good thinking Steve, looks like this actually does worse:
```
andrew@Lappinux:~/perf-math$ ./matstuff
2020-03-21 11:20:09
Running ./matstuff
Run on (8 X 4000 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 8192K (x1)
--------------------------------------------------
Benchmark           Time           CPU Iterations
--------------------------------------------------
Exp_Old      31270268 ns   31274997 ns         24
Exp_New      38605496 ns   38612270 ns         14
```
I'd guess that the performance benefits are outweighed by having to repeatedly traverse the input matrix

**Comment by SteveBronder** [comment]
Huh! That's suprising, traversal could be it. Could you share the branch / try running it with

```
./matstuff --benchmark_repetitions=20 --benchmark_report_aggregates_only=true
```

**Comment by SteveBronder** [comment]
You can also test it with multiple sizes by using something like 

```cpp
// in benchmark
// use state.range(0) etc to set sizes
// https://github.com/google/benchmark#passing-arguments
Eigen::Matrix<stan::math::var, -1, -1> Sigma(state.range(0), state.range(0))
//...
// run for sizes 100, 200, ..., 1900, 2000
BENCHMARK(mat_bench)->DenseRange(100, 2000, 100);
```

**Comment by t4c1** [comment]
We probably won't be able to improve on appy_scalar_unary performance for autodiff variables until we redesign matrices. We need to store values and derivatives/adjoints in separate matrices to reduce amount of copying needed and enable vectorization.

**Comment by bbbales2** [comment]
@bob-carpenter is interested in this too (https://github.com/stan-dev/math/issues/1787)

Could you share your code you used to bench this stuff? I've been surprised trying to optimize some related things as well.

Maybe a couple things to try:
1. Instead of the vector expressions, write for loops

2. Instead of computing the gradients in the chain call, precompute them in the forward pass (as you have the stuff in memory -- may have to do this with for loops) and then just do the adjoint * Jacobian thing in the chain itself (which is fine cause the Jacobians are diagonal).

**Comment by andrjohns** [comment]
Thanks all! Benchmarking code is up in this branch: https://github.com/andrjohns/perf-math/tree/autodiff_elem_testing

I'll do some exploring of the other options

**Comment by andrjohns** [comment]
Closing this while I look into other options, will post any further discussion in the relevant issue (#1783)

**Comment by bob-carpenter** [comment]
Thanks for posting the benchmarking code.

**Pull request closed without merging**
