### PR TITLE
Additional tests for distributions

### PR DESCRIPTION
**Pull request by martinmodrak**
## Summary

Additional tests for distributions to increase coverage. All tests pass with the current codebase.

## Tests

- `bernoulli_logit_lpmf` involves a cutoff, continuity around the cutoff is tested
- `inv_gamma_lpmf` and `weibull_lpmf` had no tests for derivatives. A new test testing all derivatives  against values precomputed byt Mathematica was added.
- adapted the tests from #1497 to `neg_binomial_lpmf` (test against precomputed values from Mathematica, test against complex step, testing continuity at cutoff for `alpha`, testing extreme values of `alpha`)

## Side Effects

None

## Checklist

- [x] Math issue: I decided not to open an math issue for this, as it seemed like clutter. Will open, if desired.

- [x] Copyright holder: Institute of Microbiology of the Czech Academy of Sciences

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This PR needs a merge with recent develop to avoid failure on the upstream. I apologize, there was a lot of churn with this flattening...

**Comment by martinmodrak** [comment]
@rok-cesnovar I merged the develop, but upstream still fails on CmdStan >> Linux interface tests with MPI with 
```
src/cmdstan/command.hpp:55:50: fatal error: stan/math/prim/functor/mpi_cluster.hpp: No such file or directory
```

I believe this is not related to this PR and not sure what to do about it.

@bob-carpenter  May I ask for review on this? It is almost the same tests as written for #1497.

**Comment by rok-cesnovar** [comment]
Yeah, that is weird. On develop this file exists (see https://github.com/stan-dev/math/blob/develop/stan/math/prim/functor/mpi_cluster.hpp), so not usre what is going on. Will monitor.

**Comment by bob-carpenter** [comment]
Sure---I can review this.

**Comment by syclik** [comment]
@martinmodrak, thanks. feel free to merge whenever you feel like it.

The reason we add issues is so we can track what's being changed from release to release. In GitHub, it's still a lot easier to track issues rather than pull requests.

**Pull request merged**
