### PR TITLE
Prettify Website / Require_* doxygen / moving the wiki

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

I really don't like the wiki. I find it hard to remember where is what and things are not terribly well sorted. While I was building the doxygen module for the new `require_*` type traits I figured we have a math site so why not structure it a bit and put stuff over there. 

You can run `make doxygen` to see the new site (You'll need the `graphvis` package installed for making the call graphs).

There's now a tab on the LHS that groups a few of the wiki pages together. Under the modules tab you'll see functions and classes grouped together. 

The goal here is that 'experimental' features or docs we are still working on are in the wiki then once everything is fleshed out and official we move it over to the website.

This also includes instructions inside of the doxygen folder for how to add new .md files to the table of contents.

## Checklist

- [x] Math issue #1396 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@seantalts can we install graphvis on wherever Jenkins is? Would be nice to have the call and callee graphs

**Comment by seantalts** [comment]
Sure! What's the exact steps you need me or Nic to do?

**Comment by SteveBronder** [comment]
Is the OS linux or mac?

For mac

```
brew install graphviz
```

```
apt install graphviz
```

**Comment by seantalts** [comment]
Hmm, can you find a docker image that has that plus whatever other stuff you need and use that? Jenkins makes that pretty easy especially if the docker image exists already. Is this part of doxygen?

**Comment by seantalts** [comment]
Happy to install it on the hardware machines we have and then we could restrict the build to those machines as well, but the docker thing would let it run in more places.

**Comment by SteveBronder** [comment]
This docker file seems to have the right stuff?

https://github.com/BrainTwister/docker-devel-env/tree/master/doxygen-1.8.14

Do we have a repo of dockerfiles available somewhere?

**Comment by SteveBronder** [comment]
Cuz I can probably just slap that stuff on top of our current dockerfile

**Comment by SteveBronder** [comment]
@wds15 if you get some time next week can you check out the .md files for threading I grabbed from the wiki? Just to make sure they are both up to date and are titled right. If you want to make any changes feel free to push directly to the branch

https://github.com/stan-dev/math/pull/1397/files?file-filters%5B%5D=.md#diff-d6281a65fbec195375fbb1a0544e74b1

https://github.com/stan-dev/math/pull/1397/files?file-filters%5B%5D=.md#diff-d251a2d144d438d362397278cdb2aa7c

**Comment by SteveBronder** [comment]
@syclik @bob-carpenter not sure who to tag on review for this. You can run `make doxygen` to see the site locally.

@charlesm93 This might also be a nice place to have docs for the ODE solvers. You can add a `\defgroup` like I have here for the probability distributions then tag the solvers docs with `\ingroup your_ode_solver_tag`

https://github.com/stan-dev/math/pull/1397/files#diff-86921eaf1325ba012f545f449fc93cfcR4

@rok-cesnovar if you have anytime next week can you add some stuff for the section on OpenCL? You can just either push directly or make a branch no worries either way.

You can add the text directly where we make the `opencl` /defgroup

https://github.com/stan-dev/math/pull/1397/files#diff-7be8a76b90a41c3a23528e2b98e3a2a0R6

**Comment by rok-cesnovar** [comment]
Nice work Steve from what I skimmed through. Yes will definitely add some OpenCL docs. Assigning myself.

**Comment by seantalts** [comment]
> Cuz I can probably just slap that stuff on top of our current dockerfile

We don't really have a dockerfile for doxygen stuff (or for anything outside of stanc3, pretty much? There might be one in CmdStan for generating the manual). It'd be really easy to add if you can find a published image on docker hub or we can just add a Dockerfile in the repo here; it might be something simple. I might try with this image first (since building images is slower): nnadeau/docker-doxygen (from https://hub.docker.com/r/nnadeau/docker-doxygen/) and see if that works. I'd add it to Jenkins here but there's a merge conflict; to add it you should just be able to add a top level stage like this:
```
        stage("Doxygen") {
            agent { docker { image 'nnadeau/docker-doxygen'}}
            steps {
                sh "make doxygen"
            }
        }
```

**Comment by SteveBronder** [comment]
Cool! I'm afk atm but will fix that merge when I get a chance. 

Would it be useful for our users (not math but stan language users) if we had a repo of stan docker files? Could also throw them up on dockerhub

**Comment by seantalts** [comment]
I think the typical thing is just to make docker images and upload them to
docker hub (though we could make a repo that automatically creates and tags
new versions and uploads them to docker hub). I'm not really sure what the
size of the audience for those is given most folks who use Stan do it
through RStudio and the cmdstan users I know wouldn't use it through
docker. My calculus here has been that if it was useful to someone they'd
do it and hopefully share it.

**Comment by SteveBronder** [comment]
@seantalts do you know how I unstash inside of the docker container for Jenkins? I looked up some of the sidecar stuff and couldn't figure it out. Gave the below a go but can't sort out the right command

```
        stage("Doxygen") {
          agent { docker {image 'nnadeau/docker-doxygen'}}
          steps {
              deleteDir()
              unstash 'MathSetup'
              sh "mkdir -p doc/api"
            	sh "doxygen doxygen/doxygen.cfg"
          }
          post { always { deleteDir() } }
        }
```

**Comment by seantalts** [comment]
Looks like the unstash claims to be executing successfully but for some reason mkdir -p is failing in a way I didn't think was possible...

**Comment by seantalts** [comment]
Hmm, I can't immediately figure out what's wrong but I'll have more time next week after the release! Sorry about that.

**Comment by SteveBronder** [comment]
Oh! Forgot about release time, yeah we can totally put this on the backburner for now

**Comment by SteveBronder** [comment]
@seantalts would you have a chance tmrw to take a peek at this?

**Comment by seantalts** [comment]
There are merge conflicts btw. What do you want me to look at? I don't see any docker stuff in the Jenkinsfile...

**Comment by SteveBronder** [comment]
@seantalts whups my bad thought I fixed that

Do you know how I unstash inside of the docker container for Jenkins? I looked up some of the sidecar stuff and couldn't figure it out. Gave the below a go but can't sort out the right command

```groovy
        stage("Doxygen") {
          agent { docker {image 'nnadeau/docker-doxygen'}}
          steps {
              deleteDir()
              unstash 'MathSetup'
              sh "mkdir -p doc/api"
            	sh "doxygen doxygen/doxygen.cfg"
          }
          post { always { deleteDir() } }
        }
```

Otherwise we can just slap graphviz on the mac and restrict it to build there

**Comment by seantalts** [comment]
Oh right. That's how you do it. I'm not sure why your `mkdir -p` command is failing. Do you actually need the call to `mkdir`?

**Comment by seantalts** [comment]
You might also try not deleting the dir and not unstashing - Jenkins is supposed to handle that stuff for us hypothetically. I really wish there was a better way to test this stuff locally, but I think it involves running a Jenkins docker image and is not the easiest. You can also play around more quickly with the replay feature: https://www.cloudbees.com/blog/replay-pipeline

**Comment by seantalts** [comment]
The reason we have the unstashes in all the other stages is because github would spuriously fail every now and then.

**Comment by seantalts** [comment]
Wait, nevermind - the whole pipeline is set up not to do a checkout, so you need the `unstash` :/

**Comment by seantalts** [comment]
re: pros and cons of getting docker to work: I don't have a strong opinion, I'll just tell you the stuff I'd take into consideration evaluating the tradeoff. First, if it uses a docker image, it can run on any machine with docker and therefore builds are less likely to queue up with a single bottleneck. It also means we have less manual sys admin dependency hell to deal with w.r.t. keeping each individual machine up to date; eventually it could be a goal to move all of the linux builds to docker (if only we could do the same with Windows and Mac OS X and thus script those dependencies as well). Docker images should make it easier to debug locally as well, though that obviously depends on Jenkins have a normal-ish Docker environment. It tends to run all docker builds as a specific user, which often doesn't have permissions inside the docker image.

Oh, that's probably what it is :P Try
```
                    agent {
                        docker {
                            image  'whatever'
                            args '-u root'
                        }
                    }
```

**Comment by SteveBronder** [comment]
`args '-u root'`

LoL, lemme give it a shot!

**Comment by serban-nicusor-toptal** [comment]
Haha I thought `make` just vanished from the machines xD

You can build your own image like [here](https://github.com/stan-dev/stanc3/blob/master/Jenkinsfile#L37) if you need to extend it See the below Dockerfile.

```
FROM alpine:3.6

RUN apk update && apk add \
  doxygen \
  graphviz \
  ttf-ubuntu-font-family \
  make
```

**Comment by SteveBronder** [comment]
Ty!! Yeah I have to put on my big boy pants and make my own image haha

**Comment by alashworth** [comment]
Would you be interested in making sure this works with the CMake Doxygen build target? I can get you a script that will build it with CMake. If not, nbd, I'll add it to my to-do list.

**Comment by SteveBronder** [comment]
That would be cool! What is the timeline till we can move over to the monorepo? I think as long as the computer has graphviz (and cmake can detect that) then it should be fine

**Comment by alashworth** [comment]
You'd be surprised how often I'd thought: eh, should be fine. For example, currently the math documentation doesn't build on Windows with MikTex. So more testing the merrier, hah. I'll prep the script for you tonight or tomorrow, just plop it in the base source directory and run CMake.

**Comment by alashworth** [comment]
Actually, all you have to do is copy and paste the following into a directory:

```
find_package(Doxygen REQUIRED dot)
file(GLOB_RECURSE stan_public_headers ${PROJECT_SOURCE_DIR}/src/*.hpp)

# un-comment to include these in the built docs. these should be in the same folder relative to here
# set(PROJECT_LOGO stanlogo-main.png)
# set(HTML_FOOTER doxygen-footer.html)
set(DOXYGEN_GENERATE_LATEX NO)
set(DOXYGEN_GENERATE_HTML YES)

doxygen_add_docs(stan_documentation
        ${stan_public_headers}
        COMMENT "Generating documentation...")
```

**Comment by SteveBronder** [comment]
Will ^ install dot if it does not already exist?

**Comment by alashworth** [comment]
No, it just assumes you have Dot installed somewhere where it can find it (usually on $PATH). For a dependency like that I would handle it in Conan, probably by asking it to shell out to the system package manager / Brew / (scoop | chocolatey | msys2)

**Comment by SteveBronder** [comment]
Neat! I'll make the dockerfile for jenkins tonight and look this week to make a PR for the cmake stuff in the monorepo

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal dumb Q, I'm trying to do what you are doing with the dockerfile in stanc3 (dockerfile and jenkinsfile below)

https://github.com/stan-dev/stanc3/blob/master/docker/debian/Dockerfile

https://github.com/stan-dev/stanc3/blob/master/Jenkinsfile

I'm getting an error that Jenkins can't find the dockerfile. Do you know how to make this work? If not then we can just ditch the graphs in the doxygen and build the old way

Jenkins error:

https://jenkins.mc-stan.org/job/Math%20Pipeline/job/PR-1397/43/console

```
java.nio.file.NoSuchFileException: /home/jenkins-slave/jenkins-slave-files/workspace/Math_Pipeline_PR-1397/doxygen/docker/alpine/Dockerfile
```

**Comment by serban-nicusor-toptal** [comment]
Hey, your code looks fine at first look, I would make sure that Jenkins pulls the correct files ( `git status` or `ls -lart doxygen ` ) from this step [here](https://github.com/stan-dev/math/blob/b7380972ca9a621d955ab42c4a8110b16e31456d/Jenkinsfile#L80). Take a look, when I get home later I will be able to debug.

You can also use our docker registry [here](https://registry-ui.mc-stan.org/) if everything else fails.

**Comment by SteveBronder** [comment]
I hope people don't mind but I wanted to show everyone the new site so I slammed up it up live. I think it looks pretty nice!

http://mc-stan.org/math/

**Comment by SteveBronder** [comment]
Nice! Does anyone want to look this over / approve? I think mostly the thing to look at is the Jenkinsfile changes

**Comment by seantalts** [comment]
Am I doing something wrong? The only change I see is that it now updates the Math library documentation whenever we merge to develop?

**Comment by SteveBronder** [comment]
Oh lol forgot I removed stuff.

What do you think is the best way to review this? essentially it just has a bunch of docs and stuff and makes some groups for doxygen modules

**Comment by SteveBronder** [comment]
@seantalts after I fix this conflict can we merge this? I have to keep updating it otherwise

**Comment by SteveBronder** [comment]
@rok-cesnovar @bob-carpenter can we merge this once it passes? It touches a good number of comments so I have to keep dealing with little merge conflicts

Site looks nice tho'!

http://mc-stan.org/math/

**Comment by seantalts** [comment]
Hey yeah sorry, I meant to reply - I think @bob-carpenter or @syclik are the resident doxygen experts. It all looks good to me but I honestly don't know what our policies on doc are at this level.

**Comment by syclik** [comment]
Just took a peek. It looks good. I'll second @seantalts's comment (in his edit): moving doc to GitHub would be great! I know the wiki is supposed to be a git repository, but the interface there is different from the code and not chasing doc in two different places is a good thing.

@SteveBronder, one major comment: the build instructions in the README.md are incorrect. (see https://github.com/stan-dev/math#installation) It's missing a critical part indicating that the TBB must be built, not just have the sources available. It doesn't look like this is something you did. Let me know if you want me to split it out into a different issue or if you wanted to tackle it since you've got all the doc changes happening at once.

**Comment by SteveBronder** [comment]
> @SteveBronder, one major comment: the build instructions in the README.md are incorrect. (see https://github.com/stan-dev/math#installation) It's missing a critical part indicating that the TBB must be built, not just have the sources available. It doesn't look like this is something you did. Let me know if you want me to split it out into a different issue or if you wanted to tackle it since you've got all the doc changes happening at once.

We could solve it here but that's not really something I know about. It may be easier to have @wds15  do that in a separate PR

**Comment by rok-cesnovar** [comment]
Looks great to me!

**Comment by SteveBronder** [comment]
Good to go?

**Comment by SteveBronder** [comment]
Much appreciated!

Apologies to the folks that have to do merge conflicts because I touched your comment docs

**Pull request merged**
