### PR TITLE
clang-format updates

### PR DESCRIPTION
**Pull request by seantalts**
Update the version of `clang-format` used to 2017-11-14 and 319952. Direct Jenkins to auto-format, commit, and push to the branch under PR. Relies on the .gitattributes PR to first fix line endings.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
This needs to wait for #723.

**Comment by seantalts** [comment]
I think this is ready for review. It's just Jenkinsfile (and pre-commit hook performance) changes as well as an automated commit that the Jenkinsfile changes triggered that reformatted the files with the new clang-format version I rolled out on the Jenkins agents. This is the new version specified in the wiki and mentioned on discourse that is the one for Ubuntu, Homebrew, and Macports that are closest to each other in SVN. 

So now if someone has an older version of clang-format installed and it doesn't format things up to this version's standard, Jenkins will autoformat, commit with the version used, and push to the branch (or to a branch on stan-dev/math if the PR came in from a fork). If it did this and came in from a branch on stan-dev/math, the author will get an email that buildbot pushed a commit to their branch. If it came in from a fork, the author will get an explicit email from Jenkins asking them to pull from an autoformat/ branch on stan-dev/math.

**Comment by seantalts** [comment]
[Here ](https://github.com/stan-dev/math/pull/724/files/0b09ce8d0c46e6727b2e55ecd347d10855595d9c..4a31f3bdd99febf88217a6de4ef169e124262ea0) are the non-formatting (well, some formatting slipped in to this link) changes in the diff.

**Comment by seantalts** [comment]
@syclik did you want to review this? Or should I just merge since it's only Jenkinsfile (and slight formatting, just alphabetizing `using` directives)?

**Pull request merged**
