### PR TITLE
upgrade to eigen 3.3.9

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

RcppEigen has upgraded to 3.3.9 (they skipped 3.3.8) https://github.com/RcppCore/RcppEigen/pull/92 so we should too.

Hopefully, this also helps with debugging the issue @bgoodri reported [here](https://github.com/stan-dev/math/issues/2235#issuecomment-739346702)

Changelog for 3.3.9 and 3.3.8 here: http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.9

## Tests

/

## Side Effects

Hopefully none.

## Release notes

Upgraded to Eigen 3.3.9.

## Checklist

- [x] Math issue #2235

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Ok, the header tests are already showing the same issue @bgoodri posted so this should make it simpler to debug.

Paging resident Eigen experts @t4c1 @andrjohns @SteveBronder @bbbales2

**Comment by bgoodri** [comment]
It is a backwards incompatible change relating to NumTraits:
```
In file included from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/matrix_vari.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core.hpp:16,
                 from ./stan/model/model_base.hpp:5,
                 from Module.cpp:2:
/home/ben/r-devel/library/StanHeaders/include/stan/math/rev/mat/fun/Eigen_NumTraits.hpp:200:77: error: wrong number of template arguments (8, should be 9)
                                      RhsStorageOrder, ConjugateRhs, ColMajor> {
                                                                             ^
In file included from /home/ben/r-devel/library/RcppEigen/include/Eigen/Core:454,
                 from /home/ben/r-devel/library/RcppEigen/include/Eigen/Dense:1,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/mat/meta/append_return_type.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/meta.hpp:9,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/memory/stack_alloc.hpp:7,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core.hpp:4,
                 from ./stan/model/model_base.hpp:5,
                 from Module.cpp:2:
/home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/util/BlasUtil.h:35:8: note: provided for ‘template<class Index, class LhsScalar, int LhsStorageOrder, bool ConjugateLhs, class Rh$
 struct general_matrix_matrix_product;
```

**Comment by rok-cesnovar** [comment]
That is a bit bizzare for a patch release.

**Comment by rok-cesnovar** [comment]
I am not sure it helps in any way but this same error pops up with 3.3.8 as well.

**Comment by SteveBronder** [comment]
Yes I saw and am pretty sure I know the fixes. I can tackle this on Monday

**Comment by bgoodri** [comment]
@SteveBronder If you could describe the fix, that would help me upload ASAP a StanHeaders that branches to be backwards compatible and forwards compatible with the Eigen version.

**Comment by SteveBronder** [comment]
Oh I think the only major thing I think is the general matrix matrix thing. That's the only major thing I saw when reading over dirks patches and the new eigen changes

**Comment by bgoodri** [comment]
OK, I presume Monday is fine, but we're holding up whatever is good about
3.3.8 and 3.3.9 migrating to CRAN.

**Comment by rok-cesnovar** [comment]
Yes, general_matrix_matrix_product has gained a template parameter int ResInnerStride. This is internal Eigen stuff so take makes more sense why it could change in a patch release. 

Setting it to 1 enables me to run a few tests. A quick grep of the eigen files shows they always set it to 1 as well.

**Comment by rok-cesnovar** [comment]
Adding the following

```cpp
#if EIGEN_VERSION_AT_LEAST(3,3,8)
template <typename Index, int LhsStorageOrder, bool ConjugateLhs,
          int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride>
struct general_matrix_matrix_product<Index, stan::math::var, LhsStorageOrder,
                                     ConjugateLhs, stan::math::var,
                                     RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride> {
#else
template <typename Index, int LhsStorageOrder, bool ConjugateLhs,
          int RhsStorageOrder, bool ConjugateRhs>
struct general_matrix_matrix_product<Index, stan::math::var, LhsStorageOrder,
                                     ConjugateLhs, stan::math::var,
                                     RhsStorageOrder, ConjugateRhs, ColMajor> {
#endif
```

instead of lines 392-396 here https://github.com/stan-dev/math/blob/develop/stan/math/rev/core/Eigen_NumTraits.hpp#L392 compiles with both 3.3.7 and 3.3.9. I am guessing you need that fix for Stan Headers?

**Comment by bgoodri** [comment]
@rok-cesnovar Thanks. I'll put that branching into StanHeaders once our unit tests pass.

**Comment by rok-cesnovar** [comment]
There seems to be more stuff, unfortunately...

**Comment by rok-cesnovar** [comment]
With https://github.com/stan-dev/math/pull/2238/commits/8f4d51caaa61c7e6bf31611349a9f8956eb6f584 this passes the full unit tests, so I think this might be it. The full test suite should be over in about 5 hours.

**Comment by SteveBronder** [comment]
Changes look fine to me just need to update the readme and should be good

**Review by SteveBronder — APPROVED** [review]

**Pull request merged**
