### PR TITLE
Feature/reduce sum funcs

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

This PR is the first 1/2 of the `reduce_sum` PR. It includes:

1. an [`apply`](https://en.cppreference.com/w/cpp/utility/apply) function on tuples which is a backwards import from C++17's `std::apply`
2. Fixes to `broadcast_array` so that the scalar implimentation has operator's `[ ]` and `=` and a few others defined
3. `accumulate_adjoints` which iterates through a parameter pack and assigns any `var` object or containers of `var`s adjoint values into a contiguous block of memory.
4. `count_vars` iterates over a parameter pack counting the number of `var` objects as well as `var`s in containers
5. `deep_copy_vars`: iterates over a parameter pack while only copying the `var` objects and `var` containers.
6. `save_varis` iterates over a paramater pack of `var` objects and containers storing the `vari` pointers into a contiguous block of memory
7. adds the `inline` keyword to `adj_job_apply` methods and uses eigen map's instead of loops.

## Tests

Tests can be run with

```bash
./runTests.py test/unit/math/prim/functor/apply_test.cpp \
  test/unit/math/rev/functor/adj_jac_apply_test \
  test/unit/math/rev/core/accumulate_adjoints_test.cpp \
  test/unit/math/rev/core/count_vars_test.cpp \
  test/unit/math/rev/core/deep_copy_vars_test.cpp \
  test/unit/math/rev/core/save_varis_test.cpp
```

## Side Effects

None

## Release notes

- Small optimizations for `adj_jac_apply` and internal functions for `parallel_reduce`.

## Checklist

- [x] Math issue #1616

- [x] Copyright holder: Steve Bronder, Ben Bales, Sebastian Weber

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@bbbales2 when we merge this we should squash it because I just took the reduce_sum branch and deleted reduce_sum.

**Comment by SteveBronder** [comment]
@bbbales2 yo I'm having some trouble getting these include orders right now causes Eigen's NumTrait's var specialization to fail

```
make stan/math/rev/fun/Eigen_NumTraits.hpp-test
```

**Comment by SteveBronder** [comment]
That also fails on the reduce_sum branch

**Comment by bbbales2** [comment]
Hmm, maybe just move all the includes to the end of rev/core.hpp? If that works then yeah I probably don't understand core well enough to be messing around there lol and we can move stuff to fun.

**Comment by SteveBronder** [comment]
There's a lot of odd things going on with this PR I'm going to break it up into smaller pieces

**Pull request closed without merging**
