### PR TITLE
Feature/issue 293 refactor integrate ode bdf

### PR DESCRIPTION
**Pull request by wds15**
#### Submisison Checklist

- [X] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
Refactor integrate_ode_bdf to use the specific sensitivity features of CVODES. So instead of exposing a coupled ODE system to CVODES, this change makes use of CVODES sensitivity capabilities allowing CVODES to use better optimized routines for solving such coupled systems.

#### Intended Effect:
As a result of using specific sensitivity features of CVODES, the integrate_ode_bdf integrator becomes robust and a lot faster. The old implementation was vulernable to freeze Stan, for example with a 2-cmt oral PK system or a Michaelis-Menten ODE system. These systems can be integrated in a robust manner with the new implementation.

#### How to Verify:
Run all the tests for integrate_ode_bdf which moved to rev/mat/functor. Also run the respective tests for ode_system, cvodes_ode_data and decouple_ode_states.

#### Side Effects:
ODE subsystems gets refactored and the bits and pieces introduced will allow for a future refactoring of the coupled_ode_system.

#### Documentation:
doxygen comments.

#### Reviewer Suggestions: 
@bob-carpenter @syclik @betanalpha 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is requiring to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
Looks to me as if there is an upstream issue in Stan; or is action on me?

The error message suggests that an integrate_ode call should be replaced with a integrate_ode_bdf call in a regression test of a "good" test-model in Stan.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
@wds15, no need to do anything yet. I just merged things upstream that should make this work.

**Comment by bob-carpenter** [comment]
I thought this one had been merged?  I pushed some minor mods to doc and formatting and pulled repeated cleanup code out into a function.  No change in behavior.

**Comment by syclik** [comment]
Fixes #293.

**Pull request merged**
