### PR TITLE
append col and append row for scalars

### PR DESCRIPTION
**Pull request by randommm**
#### Summary:

Fix issue https://github.com/stan-dev/stan/issues/1347

#### Intended Effect:

Add signatures:

     append_row(vector, scalar)
     append_row(scalar, vector)
     append_col(row_vector, scalar)
     append_col(scalar, row_vector)

And unit tests for them. Added special rev-diff test functions to make sure the vectors were being correctly promoted.

#### How to Verify:

Verify code and test functions.

#### Side Effects:

None.

#### Documentation:

To be included in stan/stan-dev

#### Reviewer Suggestions:

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
I'm still working through some of the upstream problems... not sure why it's behaving the way it's behaving now.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
@randomm @syclik  This one has a conflict and still requires doc for the manual.  I don't know if that's from the new includes or what, but I'd love to have this feature in, as I've needed it a few time in coding models.

* [ ] requires LaTeX doc in manual

**Comment by randommm** [comment]
> still requires doc for the manual.
>
But shouldn't this be done in another pull request in stan-dev/stan?


> I don't know if that's from the new includes or what
>
Exactly! Fixed. But it seems Jenkins has a problem with the doxygen build.

**Comment by bob-carpenter** [comment]
> On Mar 22, 2016, at 12:48 PM, Marco Inacio <notifications@github.com> wrote:
> 
> 
> > still requires doc for the manual.
> >
> But shouldn't this be done in another pull request in stan-dev/stan?

Yes, you're right.

> > I don't know if that's from the new includes or what
> >
> Exactly! Fixed. But it seems Jenkins has a problem with the doxygen build.

Does the doxygen build work on your machine?

- Bob

**Comment by randommm** [comment]
>
> Does the doxygen build work on your machine?
>
Yes, it also build on Jankins machine too, but is giving some odd git 
related errors:

http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20Pull%20Request%20-%20Doc%20-%20Doxygen/245/warnings14Result/source.555/#1

http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20Pull%20Request%20-%20Doc%20-%20Doxygen/245/warnings14Result/source.554/#1

  > /usr/bin/git rev-list 3ef75d9b54fcc1c36d96ca57df3f86367943351c # timeout=10
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 10631 and retry the command.

**Comment by syclik** [comment]
Looks good.

**Pull request merged**
