### PR TITLE
Added STAN_NO_RANGE_CHECKS helper

### PR DESCRIPTION
**Pull request by bbbales2**
## Summary

Added a makefile helper so:

```
STAN_NO_RANGE_CHECKS=true
```

is shorthand for

```
CXXFLAGS += -DSTAN_NO_RANGE_CHECKS
```

## Tests

None

## Release notes

- Allow `STAN_NO_RANGE_CHECKS=true` in `make/local` to turn off range/size checks

## Checklist

- [x] Math issue #2420

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by bbbales2** [comment]
A very complex pull for you to review @rok-cesnovar

**Review by rok-cesnovar — APPROVED** [review]
Free Github pointz! Collect them all.

**Comment by rok-cesnovar** [comment]
Thanks!

**Comment by bbbales2** [comment]
@rok-cesnovar mystery error here: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2437/1/pipeline . Just need to restart tests or seems like something legit?

**Comment by rok-cesnovar** [comment]
This is a configuration issue (although I dont understand why it find the platform in one occasion but not in others).

**Pull request merged**
