### PR TITLE
[WIP] Rewrite operands and partials

### PR DESCRIPTION
**Pull request by SteveBronder**
I'm mostly opening this up because I'm on my little laptop right now and it takes forever to run the distribution tests

## Summary

This is pretty much a top to bottom rewrite of `operands_and_partials`. It's used in all of the probability distributions for storing and then accumulating partial gradients, but tbh I've always been a bit confused by how it works. So this is attempting to simplify it's internal patterns a bit while being more performant. There are 3 major files (prim/rev/fwd) that have changed and I'll go over the particulars of each below.

At a high level, the API has been reworked so developers call 

```cpp
  auto ops_partials = operands_and_partials(theta_ref, beta_ref);
```

which under the hood uses the same mechanics as `reduce_sum`, calling and returning a `operands_and_partials_impl<InputTypes...>` class

The edges are now stored as a tuple and we have a new method `edge<Index>` for accessing them such as 

```cpp
edge<0>(ops_partials).partials_[i] += -1 / Pi;
```

### Prim ops_and_partials

This file has the base implementation for `operands_and_partials_impl`, which uses the same deduction pattern as `reduce_sum_impl` to decide when to use the prim/rev/fwd specializations. I was able to remove all the specialized edges for the different containers that hold double types and it is almost all constexpr besides `partial_` and `partial_vec_`. If we ever move up to `C++17` these two can be removed since they are only accesed in places we would then use `if constexpr`.

This also holds the `operands_and_partials()` function for creating `operands_and_partials_impl` types as well as the `edges()` function for accessing the edges.

The edges now have member functions `partial()` and `operand()` for accessing the respective members of the class. For doubles these are constexpr, but for var etc. these will be either their `partials_` or `partials_vec_`.

### Rev ops and partials

`operands_and_partials_impl` now stores all the edges inside of a tuple. Previously when we called `build()` we would create an array of `vari*` and `double*` and iterate over each of these arrays to store the edges operands and partials. If an edge had a `var<matrix>` type in it we would also need to store those as a seperate tuple. Then the return vari would be a `precomputed_gradients_vari` (which also stored an array of `vari*` and `double*`) that accumulated the precomputed gradients from the forward pass in the reverse pass. But now, each of the edges for var types stores it's members directly in the arena.

 Since this specialization has a gurantee that each of it's edges' operands and partials are already stored in the arena (var) or are trivially copyable (double) we just make two tuples containing the operands and partials and then add a reverse pass callback to accumulate the partials into the operands. I think I can optimize this a bit more to get rid of those two tuples.

Nothing too much has changed with the edges here besides storing their ops and partials into the arena directly. I think with a bit of elbow grease I can also remove all these specializations to have just one edge for `var`.

### Fwd ops and partials

This has the same tuple change as the rev version and a `sum_dx()` function that sums all the `dx()` in the edges. Besies that not too much has changed here. 

## OpenCL ops and partials

I haven't updated this yet since I'm on my little laptop but hopefully this should not need much.

## Tests

This function is used in all of our distribution tests so it should be pretty thoroughly tested. I still need to add tests for the new methods.

## Side Effects

The API is a pretty big change, though I think this was considered internal so idt there's any need for a big version bump.

## Release notes

Refactor operand and partials calculations to reduce memory usage and give better performance for `var<matrix>`

## Checklist

- [ ] Math issue #(issue number)

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@rok-cesnovar @serban-nicusor-catena I'm seeing in the github action that runs the mix and rev tests

```
2021-02-04T19:16:34.3519992Z ./test/unit/math/test_ad.hpp: In function 'stan::test::internal::expect_ad_vv(const stan::test::ad_tolerances&, const F&, const T1&, const T2&)::<lambda(const auto:219&)> [with auto:219 = Eigen::Matrix<stan::math::fvar<double>, -1, 1>; F = mathMixScalFun_multiplyLog_Test::TestBody()::<lambda(const auto:259&, const auto:260&)>; T1 = double; T2 = double]':
2021-02-04T19:16:34.3521762Z ./test/unit/math/test_ad.hpp:463:71: internal compiler error: Segmentation fault
2021-02-04T19:16:34.3522469Z        = [&](const int i) { return [&g, i](const auto& v) { return g(v)[i]; }; };
```

Do you know if that seg fault because the test file is too big?

**Comment by rok-cesnovar** [comment]
Yep, that is a Rtools 3.5 g++ 4.9.3 thing. Its why some of the tests are split up.

**Comment by SteveBronder** [comment]
Ack alright I'll split that apart

**Comment by SteveBronder** [comment]
@t4c1 @rok-cesnovar can one of you look over 

```
./runTests.py test/unit/math/opencl/rev/exp_mod_normal_lpdf_test.cpp
```

Though running the Jenkins tests multiple times it looks like the segfault happens at random?

```
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from ProbDistributionsPareto
[ RUN      ] ProbDistributionsPareto.error_checking
[       OK ] ProbDistributionsPareto.error_checking (368 ms)
[ RUN      ] ProbDistributionsPareto.opencl_matches_cpu_small
[       OK ] ProbDistributionsPareto.opencl_matches_cpu_small (2318 ms)
[ RUN      ] ProbDistributionsPareto.opencl_broadcast_y
[       OK ] ProbDistributionsPareto.opencl_broadcast_y (2158 ms)
[ RUN      ] ProbDistributionsPareto.opencl_broadcast_y_min
[       OK ] ProbDistributionsPareto.opencl_broadcast_y_min (2038 ms)
[ RUN      ] ProbDistributionsPareto.opencl_broadcast_alpha
[       OK ] ProbDistributionsPareto.opencl_broadcast_alpha (2062 ms)
[ RUN      ] ProbDistributionsPareto.opencl_matches_cpu_big
[       OK ] ProbDistributionsPareto.opencl_matches_cpu_big (13 ms)
[----------] 6 tests from ProbDistributionsPareto (8957 ms total)
[----------] Global test environment tear-down
[==========] 6 tests from 1 test suite ran. (8957 ms total)
[  PASSED  ] 6 tests.
Segmentation fault (core dumped)
```

**Comment by SteveBronder** [comment]
Also I've run this locally and can't seem to replicate it

**Comment by t4c1** [comment]
I tried to run this locally, but I can't replicate the segfault.

**Comment by bbbales2** [comment]
@SteveBronder is this ready to review? Can get it tomorrow AM if so

**Comment by SteveBronder** [comment]
No not yet still a few kinks I'm working out with the OpenCL stuff

**Pull request closed without merging**
