### PR TITLE
Update to Boost 1.75.0

### LINKED ISSUE #2339: Upgrade to Boost 1.75.0
## Description

The Boost Headers R package was ugraded to point to Boost 1.75.0, so we should too.

#### Current Version:
v4.0.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Just ran the update script. Fixes #2339 

## Release notes

Updated Boost to 1.75.0.

## Checklist

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Boost 1.72.0 had 22588 files that took 189,6MB of space
Boost 1.75.0 has 23497 files that take 277,8MB of space

Maybe we should think about pruning some more.

**Comment by bbbales2** [comment]
Ooo, @bgoodri reminded me yesterday to check, but if 1.75 includes the Boost fix for the integrator problem (https://github.com/boostorg/math/pull/455#issuecomment-726925634), then we need to roll back the patch in the Stan repo. Checking...

**Comment by bbbales2** [comment]
Looks like the fix is in. I'll open a pull that removes the patch.

**Comment by rok-cesnovar** [comment]
Cool, I am going to look at pruning a few folders. With the removal of stanc2 we need much less of Boost.

**Review by bbbales2 — APPROVED** [review]
Good!

**Pull request merged**
