### PR TITLE
[WIP] Refactor Stan eigen plugins and CWiseUnaryView

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This draft PR is for testing changes to Stan's eigen plugins and to Eigen's `CWiseUnaryView` against downstream. I'll update this description with more information once ready for review.

## Tests

Describe the new tests with the pull request.

For bug fixes there should be a new test that would fail if the patch weren't in place (so that the bug could be caught if it comes up again).

For new features there should be at least one test showing the expected behavior and one test that demonstrates error handling. Be aware the reviewer will very likely ask for more tests than this, but it's a start.

## Side Effects

Are there any side effects that we should be aware of?

## Release notes

Replace this text with a short note on what will change if this pull request is merged in which case this will be included in the release notes.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by andrjohns** [comment]
Some odd OpenCL errors here that I can't replicate locally on Linux:
```
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from indexing_rev
[ RUN      ] indexing_rev.indexing_rev_small
unknown file: Failure
C++ exception with description "compile_kernel: indexing_rev Compilation started
1:4:26: warning: unsupported OpenCL extension 'cl_khr_int64_base_atomics' - ignoring
#pragma OPENCL EXTENSION cl_khr_int64_base_atomics: enable
                         ^
Compilation done
Linking started
Linking done
Device build started
Failed to build device program
Error: unimplemented function(s) used:
_Z12atom_cmpxchgPU3AS1Vmmm is undefined 
CompilerException Failed to parse IR
: Unknown error -11" thrown in the test body.
[  FAILED  ] indexing_rev.indexing_rev_small (653 ms)
[ RUN      ] indexing_rev.indexing_rev_large
unknown file: Failure
C++ exception with description "compile_kernel: indexing_rev Compilation started
2:4:26: warning: unsupported OpenCL extension 'cl_khr_int64_base_atomics' - ignoring
#pragma OPENCL EXTENSION cl_khr_int64_base_atomics: enable
                         ^
Compilation done
Linking started
Linking done
Device build started
Failed to build device program
Error: unimplemented function(s) used:
_Z12atom_cmpxchgPU3AS1Vmmm is undefined 
CompilerException Failed to parse IR
: Unknown error -11" thrown in the test body.
[  FAILED  ] indexing_rev.indexing_rev_large (58 ms)
[----------] 2 tests from indexing_rev (711 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (711 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] indexing_rev.indexing_rev_small
[  FAILED  ] indexing_rev.indexing_rev_large
```
@rok-cesnovar or @SteveBronder any chance you would know if this is related to #2603 or just a Jenkins misconfiguration?

**Comment by SteveBronder** [comment]
!!!!

**Comment by andrjohns** [comment]
Haha are those positive exclamations?

**Comment by SteveBronder** [comment]
Yes! Very happy you were able to sort this out!

**Comment by andrjohns** [comment]
@serban-nicusor-toptal looks like Jenkins is having some odd troubles with Git, would you mind taking a look when you've got a minute? Thanks!

**Comment by andrjohns** [comment]
I've confirmed that this PR also fixes the issue reported in #2268

**Comment by andrjohns** [comment]
Given that the issues are largely caused by Eigen's code itself, I've [opened an issue with them](https://gitlab.com/libeigen/eigen/-/issues/2398) and will submit a PR there. I'll then backport any changes to our headers until we're using a release with the changes.

Closing this for now

**Pull request closed without merging**
