### PR TITLE
OpenCL asynchronous copy of destroyed object bug demo

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

A test showing a bug in how we construct matrix_cl.

## Checklist

- [x] Math issue #1346 

- [x] Copyright holder: Tadej Ciglarič (University of Ljubljana)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
I thought this issue with bot pushing pormating was fixed?

**Comment by SteveBronder** [comment]
@syclik can you check the stanbuildbot email for the approval and use the password Serban sent us to approve our branch? You can also send me the email and I'll take care of it. 

Still not sure why this is happening. @t4c1 I think the build-bot uses clang-format-6 (might be 5). If you use that version then it should not have any fixes

**Comment by SteveBronder** [comment]
Just made a branch with a bugfix for this I'll put up the PR for it tmrw

**Comment by rok-cesnovar** [comment]
Great, thanks to both. Might add this test also.

**Comment by rok-cesnovar** [comment]
Closing this PR as the demo issue it shows will be fixed in #1356 The demo test is included in it.

**Pull request closed without merging**
