### PR TITLE
Bugfix OpenCL distributions not working with row vectors

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Fixes OpenCL implementations of distributions mostly not working with row vectors. This is done by implementing `as_column_vector_or_scalar` for kernel generator expressions and using it in distribution implementations.

I could not fix `dirichlet_lpdf` in `multi_normal_cholesky_lpdf` without performance impacts so these two are still not supporting row vectors in Math. Row vector support for these two can be added in stanc, by transposing row vector arguments.

## Tests
Added many tests for row vectors and tests for `as_column_vector_or_scalar`. `student_t_lpdf` tests failed to compile due to being too large so I split them into two files.

## Side Effects
There are many more tests for OpenCL stuff now potentially significantly increasing testing times.

## Release notes

OpenCL: Fixed OpenCL implementations of distributions mostly not working with row vectors.

## Checklist

- [ ] Math issue #2351 

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@t4c1 Sorry for this, but can you split out the fixes for the distributions that were added for 2.26. We will need to do a patch release and I would then want to include those as well. If we go that route this PR needs to be done to master.

**Comment by bbbales2** [comment]
> I could not fix dirichlet_lpdf in multi_normal_cholesky_lpdf without performance impacts so these two are still not supporting row vectors in Math. Row vector support for these two can be added in stanc, by transposing row vector arguments.

Is it simpler to just take the performance hit for now? Stanc3 logic can be added later if we think that's the better way to handle these things.

Otherwise is this ready for review?

**Comment by t4c1** [comment]
The performance hit version of fix for these two is not exactly trivial, so I would prefer to just properly fix those by transposing row vectors in compiler.

**Comment by t4c1** [comment]
Also cherry-picked version of this is already merged into master, so I think @rok-cesnovar is just waiting for the bugfix release to be completed, before approving this PR as well.

**Comment by bbbales2** [comment]
> so I would prefer to just properly fix those by transposing row vectors in compiler.

Is that something easy to add in the compiler? I really don't know. It sounds confusing to me.

@rok-cesnovar Do we do things like this?

Can we do a compatibility interface in Math at least? So like:

```cpp
template <typename T,
                 require_col_vector_t<T> = nullptr>
auto myfunc(const T&) {
  ... // This is the fast implementation
}

template <typename T,
                 require_not_col_vector_t<T>* = nullptr>
auto myfunc(const T& x) {
  auto y = copy_to_col_vector(x);
  return myfunc(y);
}
```

And then in the future the compiler can do whatever optimizations.

**Comment by t4c1** [comment]
> Can we do a compatibility interface in Math at least? So like:

No. The issue is that we are using the same `matrix_cl` type for both row and col vectors. Only stanc knows at compile time which one a matrix_cl contains.

**Comment by rok-cesnovar** [comment]
> Do we do things like this?

So far no.

the only thing I can see us doing in Math is fun_impl() and the fun() checks whether its a row_vector and calls fun_imp(transpose(y)), or fun_impl(y) if not. 

Not sure if that is doable/performant.

**Comment by bbbales2** [comment]
> Only stanc knows at compile time which one a matrix_cl contains.

Oof. I guess the Math option would be `matrix_cl<Eigen::VectorXd>` vs. `matrix_cl<Eigen::RowVectorXd>` which seems like a lot of trouble?

If `matrix_cl<double>` types are all the same, is it in the transfer from CPU to GPU that is causing problems? Or is this something that comes up when a GPU function passes something to another GPU function?

> The issue is that we are using the same matrix_cl type for both row and col vectors.

The varmat distributions got reverted because `arena_t<Eigen::VectorXd>` and `arena_t<Eigen::RowVectorXd>` weren't playing well together. I put this here just cause it seems similar (found out about this through dist tests). Without the type info, the same fix wouldn't work tho.

Like this is valid Eigen code but it wasn't working with arena types:

```
Eigen::VectorXd a(5);
Eigen::RowVectorXd b = a;
```

There's a patch in `arena_matrix.hpp` here: https://github.com/stan-dev/math/pull/2356/files#diff-4dcedb2d724267e0af41b776bf83e6a402a26fa5f2198a245922813544f804cbR61

**Comment by t4c1** [comment]
> Not sure if that is doable/performant.

We could actually do that, except we would need 4 branches, since 2 arguments can be row vectors. Performance difference would likely be negligible.

> I guess the Math option would be matrix_cl<Eigen::VectorXd> vs. matrix_cl<Eigen::RowVectorXd> which seems like a lot of trouble?

Yep, that would be quite some work.

> is it in the transfer from CPU to GPU that is causing problems? Or is this something that comes up when a GPU function passes something to another GPU function?

No. The issue is that binary functions expect arguments to have the same shape.

> Like this is valid Eigen code but it wasn't working with arena types:

We do not support that with `matrix_cl`s (and adding that would not solve the issue).

**Comment by rok-cesnovar** [comment]
> We could actually do that, except we would need 4 branches, since 2 arguments can be row vectors. Performance difference would likely be negligible.

Oh, right. I am now leaning slightly towards this solution as this makes these distributions work with row_vectors standalone, as part of Stan Math.

**Comment by t4c1** [comment]
Oh, right we can't actually do that. The problem is that we can not differentiate between `Eigen::RowVector` and a `std::vector<Eigen::Vector>` from matrix_cl dimensions if the second one has inner vectors of size 1. We do need to solve this in stanc.

**Comment by rok-cesnovar** [comment]
Argh, ok then :)

**Review by rok-cesnovar — APPROVED** [review]

**Pull request merged**
