### PR TITLE
flip indexes in hmm_marginal doc

### PR DESCRIPTION
**Pull request by syclik**
## Summary

Fixes the doxygen documentation for `hmm_marginal` according to @charlesm93 in #1979. I walked through the code and I believe the indexing is correct after the patch.

## Tests

No new tests. Doc only.

## Side Effects

No side effects.

## Release notes

fixed doxygen documentation of `hmm_marginal`

## Checklist

- [x] Math issue #1979

- [x] Copyright holder: Generable

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by syclik** [comment]
@rok-cesnovar... sorry to bother you... this failure looks bad. It looks like it's in threading; do you know if `develop` is broken right now? Or if this could be some race condition?

**Comment by rok-cesnovar** [comment]
Develop is not broken in the sense that other PR tests are passing, develop fails in the last release cycle were all test machine failures (network error and a GPU problem - https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/activity?branch=develop). 

This seems like a race condition in the tests. I am not super familiar with the reduce sum tests. Will make an issue and restart tests. Thanks for spotting this!

**Comment by syclik** [comment]
Thanks! That’s good to hear that it’s not broken in general. I also don’t know that test well enough to know why it would catch, but if it is a race condition that we hit, we should pay attention. 

Thanks for opening up the new issue.

**Comment by rok-cesnovar** [comment]
@syclik yeah, the test tries to check that we run with multiple threads but will error if the system is clogged up and the entire test is run with one thread. Very unlikely but can happen.

**Pull request merged**
