### PR TITLE
Benchmark improvements

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Contains various small improvements for automatic benchmarking:
- Fixed wrong flag given to benchmark that would cause it to only output aggregate (mean, medain, stdev) values when running multiple repeats
- exclude aggregate values when making a plot
- added option to benchmark OpenCL implementation including only the time for copying var arguments, and not arguments of non-autodiff types (the way OpenCL implementations are often used by Stan)
- Make plots of individual repeats not affect scaling of axes. This way individual extreme measurements can not cause the more relevant plots to be only in a small part of the whole graph.

## Tests
None.

## Side Effects
None.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
random fr, would it be possible to have a flag like `--compare [branch]` that would run the tests for both the current branch and another specified branch?

**Comment by ahartikainen** [comment]
cc @bbbales2 for compare stuff

**Comment by bbbales2** [comment]
It would be handy cause that's the most common comparison we'd be making in Math. I'm not sure how to do it nicely.

Was working on some benchmarking stuff with @ahartikainen to handle comparisons between different branches of cmdstan/stan/math etc, but if it's possible to do a quick comparison here that's great.

**Comment by SteveBronder** [comment]
What we could do is rewrite perf math to essentially just be a python script that does the compare stuff

**Comment by t4c1** [comment]
You can already compare branches by doing for example:
```
git checkout branch1 && ./benchmarks/benchmark.py elt_multiply --csv elt_multiply_1.csv && git checkout branch2 && ./benchmarks/benchmark.py elt_multiply --plot_reference elt_multiply_1.csv --plot window
```

If that is not good enough we can also add an extra flag.

**Comment by rok-cesnovar** [comment]
> You can already compare branches by doing for example:

I think this is good enough. I dont think we need to also deal with git in the benchmark python script.

**Comment by ahartikainen** [comment]
I think taking the code from @bbbales2 repo is enough. By default don't compare but if some flag is enabled, then compare.

**Comment by rok-cesnovar** [comment]
What about adding a separate shell script that does just what @t4c1 wrote?

`./compareBenchmark.sh branch1 branch2 args_for_benchmark`

calls 

`git checkout branch1 && ./benchmarks/benchmark.py args_for_benchmark --csv branch1.csv && git checkout branch2 && ./benchmarks/benchmark.py args_for_benchmark --plot_reference branch1.csv --plot window`

Would also be much less code than to handle it with subprocess in Python.

**Comment by bbbales2** [comment]
A shell script is fine, or I'm also happy to just add a bookmark to Tadej's [comment](https://github.com/stan-dev/math/pull/2290#issuecomment-755154528) in my toolbar for quick copy-pasting.

**Review by bbbales2 — CHANGES_REQUESTED** [review]
These things seem good to me and the changes definitely make the output better:

> Fixed wrong flag given to benchmark that would cause it to only output aggregate
> exclude aggregate values when making a plot
> Make plots of individual repeats not affect scaling of axes.

@rok-cesnovar can you check that the OpenCL stuff runs and then approve/merge?

> added option to benchmark OpenCL implementation including only the time for copying var arguments, and not arguments of non-autodiff types (the way OpenCL implementations are often used by Stan)

**Comment by rok-cesnovar** [comment]
> @rok-cesnovar can you check that the OpenCL stuff runs and then approve/merge?

Been using this branch to make OpenCL benchmarks so this definitely works. Will take a quick look and then merge.

**Review by ahartikainen — APPROVED** [review]
Maybe run once with black?

    python -m black path/to/file

**Review by bbbales2 — APPROVED** [review]

**Pull request merged**
