### PR TITLE
Chris chiasson feature/issue 123 complex numbers with vars

### PR DESCRIPTION
**Pull request by bgoodri**
#### Summary:

Adds tests, some of which do not  compile due to `copysign`

@ChrisChiasson I think if you merge this into your fork, it may show up on the PR in the Stan Math repo.

### CODE REVIEW

**Comment by bgoodri** [comment]
Now, this is appearing on the Stan Math repo. I think we can merge this into the other complex numbers branch in order to best go about fixing the compiler errors there.

**Comment by bgoodri** [comment]
Under g++, there is a test failure with the `proj` function failing to match up with the example at 
https://en.cppreference.com/w/cpp/numeric/complex/proj
due to returning `NaN`.

**Comment by bgoodri** [comment]
@seantalts You are okay with merging this branch into the base branch for #789, which GitHub says can be done without conflicts?

**Comment by seantalts** [comment]
I was saying merging is fine instead of rebasing. If @ChrisChiasson wants this stuff in his branch then one of you should feel free to merge it in? I'm pretty confused about this though. Seems like you need to merge into `ChrisChiasson:feature/issue-123-complex-numbers-with-vars`, not `stan-dev:ChrisChiasson-feature/issue-123-complex-numbers-with-vars`

**Comment by bgoodri** [comment]
Closing this PR. Use #789 .

**Pull request closed without merging**
