### PR TITLE
Move validate_*_index from generated code to Math

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Adds validate_positive_index and validate_unit_vector_index that are now generated with each stanc3 code gen unnecessarily.
Also adds tests for validate_non_negative_index.

## Tests

New tests for all. Added missing for the validate_non_negative_index

## Side Effects

/

## Release notes

Added validate_positive_index and validate_unit_vector_index to clean up generated Stanc3 code.

## Checklist

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bbbales2** [comment]
Looks good but the tests have the same name apparently.

**Comment by rok-cesnovar** [comment]
Ah yes, too much copying and pasting. Fixed.

**Comment by bbbales2** [comment]
@rok-cesnovar added doc

**Comment by rok-cesnovar** [comment]
Thank you!

**Review by bbbales2 — APPROVED** [review]
Good

**Pull request merged**
