### PR TITLE
Split up mix tests further to avoid timeouts.

### PR DESCRIPTION
**Pull request by seantalts**
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Hey @syclik, I saw that this pull request on Travis caused the split tests to take roughly as long (each) as the original combined group and realized this is because `runTests.py` calls `make` on each test file individually if they are specified individually (instead of by folder). So I have added some changes to `runTests.py` to change it so that everything will build as a big group, while keeping the batching behavior we had previously (I forget why the batching was in there but kept its behavior the same).

**Comment by seantalts** [comment]
Does maybe @mitzimorris want to look at my Python changes here? I verified that the same number of tests are run by grepping and counting "OK" in the log messages of both versions.

**Comment by mitzimorris** [comment]
python changes make sense to me!

**Comment by seantalts** [comment]
Awesome, thanks! Will merge when tests are done again.

**Pull request merged**
