### PR TITLE
Fix the GPU tests and re-merge GPU matrix multiply

### PR DESCRIPTION
**Pull request by seantalts**
We approved and then reverted #967. This PR reverts that revert and fixes the tests that were broken.

## Checklist

- [x] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses: Columbia University
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
@rok-cesnovar, the best way to review this is to look at this diff, which only shows the commits I just made on top of what was already in #967 :  https://github.com/stan-dev/math/pull/1027/files/a8616d9815bbe6e21c36b4ae95f382b179990ca5..b33b69a9b7af698fbc68ce57833fdcc6cbf7a3db

Just a couple of minor changes. Particularly curious if there are cooler or more efficient ways to zero out the GPU buffers...

**Comment by SteveBronder** [comment]
Code changes lgtm, much appreciated!

@seantalts how do you feel about setting up Jenkins to test on multiple agents for the GPU code? Not sure if that's overkill, but it feels like we have some pretty hardware / driver specific things and it would be good to make sure something that we change does not mess up on other systems.

@bgoodri does the OpenCL code work again on the linux box? I believe @rok-cesnovar  knows how to set up OpenCL on windows if it's possible to give him access to that box.

**Comment by rok-cesnovar** [comment]
@seantalts thank you for finding this bug! Big mistake on my part. 
I used to run things on a AMD GPU I had on a Windows box in order to find these kind of stuff. AMD+Windows usually throws errors in case of any weird memory accesses in kernels etc that NVIDIAs implementation ignores. I will need to revive those I guess to avoid wasting your time... I apologize.

The only alternative from using the zeros kernel is to use the `enqueueFillBuffer`, but we have not done any research in the execution time of this call versus a compiled kernel. We know that the execution time of zeros is negligible in the context of matrix multiplication and would recommend leaving it the way you did it.

We can always change what `zeros<Entire>` does in the backend once we figure out if there is a faster way. 

I have added this to the list of minor stuff we need to research (together with `enqueueCopyBuffer` that could possibly replace the copy kernel).

**Comment by seantalts** [comment]
Nice, thank you for the thoughtful notes. Let me know how it all goes!

@SteveBronder re: tests - we just weren't running GPU tests before on PRs because that's what the consensus was a while back, but I just added the GPU tests back in to the PR phases just to double check. I think let's see how things go now with the new setup - as it is, most of the developers seem to be on nvidia but the test server is on the seemingly more strict AMD, so we should have good coverage there while that situation persists. I like that the AMD one is very strict and that that's our test bed :)

**Pull request merged**
