### PR TITLE
Flatten mix/fun and finish flattening of /mix

### LINKED ISSUE #1453: MathMixMatFun.add and MathMixMatFun.subtract tests seem to fail randomly?
## Description

After #1424 we've had a couple PRs which look fine fail the MPI unit tests (but pass the GPU branch?)

Ex:

#1445 #1446 #1429 

Not sure what's going on?

If we can find a quick patch for #1424 or understand why that's happening then cool and good otherwise let's do the revert and revert-revert PR

#### Current Version:
v3.0.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

This PR flattens mix/fun and finishes flattening the mix folder by creating the stan/math/mix.hpp header. This again touches a lot of files, but the changes are very simple. Only around 5 files required manual merging, the rest are renaming changes.

## Tests

This also fixes #1453 with https://github.com/stan-dev/math/pull/1584/commits/744fea145f0cc3f55780ca48e81391fc41c9b3cc

## Side Effects

/

## Checklist

- [x] Math issue #937 

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mcol** [comment]
There's the old `MathMixMatFun.add_vec_mat` failure occurring again... Jenkins reports the tolerance to be 0.0001, but the test clearly sets it to be 0.0005, so I don't know what's going on (locally the test passes).

**Comment by rok-cesnovar** [comment]
What is weirder is that the test error seems to be 1. I ran this on my Ubuntu setup with mpi, exact same compiler, and the test passes. This PR only moves the test so this is very bizarre. Will dig into this test a bit more.

**Comment by rok-cesnovar** [comment]
> Jenkins reports the tolerance to be 0.0001, but the test clearly sets it to be 0.0005

That is a good point also yes.

**Comment by rok-cesnovar** [comment]
Ah, I found it.

```
  Eigen::VectorXd v5(5);
  v5 << 1, 2, 3, 4, 5;
  Eigen::VectorXd v5b(5);
  v5 << 2, 3, 4, 5, 6;
  Eigen::VectorXd rv5(5);
  v5 << 1, 2, 3, 4, 5;
  Eigen::VectorXd rv5b(5);
  v5 << 2, 3, 4, 5, 6;
  stan::test::expect_ad(tols, f, v5, v5b);
  stan::test::expect_ad(tols, f, rv5, rv5b);
```
This was probably it all along. Only `v5` is initialized. Will fix this in this PR. `subtract_vec_mat` suffers from the same problem.

**Comment by mcol** [comment]
Well spotted!

**Comment by mcol** [comment]
This is not having an easy time:
```
In file included from test/unit/math/mix/fun/log_mix_test.cpp:1:0:
./test/unit/math/test_ad.hpp: In function 'void stan::test::internal::test_gradient(const stan::test::ad_tolerances&, const F&, const VectorXd&, double, bool)
 [with F = stan::test::internal::expect_ad_helper(const stan::test::ad_tolerances&, const F&, const G&, const VectorXd&, Ts ...)::<lambda(int)>
 [with F = stan::test::internal::expect_ad_vvv(const stan::test::ad_tolerances&, const F&, int, const T2&, const T3&)
 [with F = mathMixScalFun_logMix_Test::TestBody()::<lambda(const auto:46&, const auto:47&, const auto:48&)>; T2 = double; T3 = double]::<lambda(const auto:23&, const auto:24&)>; G = stan::test::internal::expect_ad_vv(const stan::test::ad_tolerances&, const F&, const T1&, const T2&)
 [with F = stan::test::internal::expect_ad_vvv(const stan::test::ad_tolerances&, const F&, int, const T2&, const T3&)
 [with F = mathMixScalFun_logMix_Test::TestBody()::<lambda(const auto:46&, const auto:47&, const auto:48&)>; T2 = double; T3 = double]::<lambda(const auto:23&, const auto:24&)>; T1 = double; T2 = double]::<lambda(const auto:9&)>; Ts = {double, double}]::<lambda(const auto:5&)>]':
./test/unit/math/test_ad.hpp:245:3: internal compiler error: Segmentation fault
   test_gradient(tols, g, x, gx);
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
<builtin>: recipe for target 'test/unit/math/mix/fun/log_mix_test.o' failed
mingw32-make: *** [test/unit/math/mix/fun/log_mix_test.o] Error 1
```
That's on Windows, no issue on Linux

**Comment by mcol** [comment]
I've reproduced it on Windows locally, and it still causes an error in the compiler, but the traceback is slightly different:
```
In file included from ./stan/math/fwd/functor.hpp:4:0,
                 from ./stan/math/fwd.hpp:14,
                 from ./stan/math/mix.hpp:9,
                 from ./test/unit/math/test_ad.hpp:8,
                 from test/unit/math/mix/fun/log_mix_test.cpp:1:
./stan/math/fwd/functor/gradient.hpp: In function 'stan::test::internal::expect_ad_helper(const stan::test::ad_tolerances&, const F&, const G&, const VectorXd&, Ts ...)::<lambda(int)>::<lambda(const auto:5&)>
 [with auto:5 = Eigen::Matrix<stan::math::fvar<double>, -1, 1>; F = mathMixScalFun_logMix_Test::TestBody()::<lambda(const auto:46&, const auto:47&, const auto:48&)>; G = stan::test::internal::expect_ad_vvv(const stan::test::ad_tolerances&, const F&, const T1&, const T2&, const T3&)
 [with F = mathMixScalFun_logMix_Test::TestBody()::<lambda(const auto:46&, const auto:47&, const auto:48&)>; T1 = double; T2 = int; T3 = double]::<lambda(const auto:18&)>; Ts = {double, int, double}]':
./stan/math/fwd/functor/gradient.hpp:47:31: internal compiler error: Segmentation fault
     fvar<T> fx_fvar = f(x_fvar);
                               ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Comment by bob-carpenter** [comment]
Does this bug show up only after flattening?  And it's not a runtime error, but the compiler segfaulting?  We had problems with windows before with the linker running out of memory and crashing, but that was for the language and we refactored it into more translation units to solve the problem.  Are bigger translation units getting compiled after the refactor?

**Comment by bob-carpenter** [comment]
Sorry about that---it's probably my bad in the original version.  There were a few other ones of these that people found---I guess it was just making random tests under Mac.

**Comment by mcol** [comment]
Commenting out the `matMixscalFun` test block solves the segfault (as the file becomes the one before flattening), while commenting out the `mathMixMatFun` test block makes no difference.
For me it's enough to comment out any one of the `stan::test::expect_ad` lines in the 
`void expect_log_mix(const std::vector<double>& p, const std::vector<std::vector<double>>& ds)` function to solve the bug. Both when it fails and when it succeeds, I see memory use for `cc1plus.exe` going over 4.1GB (I have 16GB). 

At `-O2` it still crashes, but at `-O1` it compiles fine. When setting the optimization level to `-O0` I got:
```
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/as.exe: test/unit/math/mix/fun/log_mix_test.o: too many sections (49468)
C:\Users\marco\AppData\Local\Temp\ccJx3Qho.s: Assembler messages:
C:\Users\marco\AppData\Local\Temp\ccJx3Qho.s: Fatal error: can't write test/unit/math/mix/fun/log_mix_test.o: File too big
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/as.exe: test/unit/math/mix/fun/log_mix_test.o: too many sections (49468)
C:\Users\marco\AppData\Local\Temp\ccJx3Qho.s: Fatal error: can't close test/unit/math/mix/fun/log_mix_test.o: File too big
<builtin>: recipe for target 'test/unit/math/mix/fun/log_mix_test.o' failed
mingw32-make: *** [test/unit/math/mix/fun/log_mix_test.o] Error 1
```

**Comment by bob-carpenter** [comment]
> On Jan 5, 2020, at 7:32 PM, Marco Colombo <notifications@github.com> wrote:
> 
> Commenting out the matMixscalFun test block solves the segfault (as the file becomes the one before flattening), while commenting out the mathMixMatFun test block makes no difference.
> For me it's enough to comment out any one of the stan::test::expect_ad lines in the
> void expect_log_mix(const std::vector<double>& p, const std::vector<std::vector<double>>& ds) function to solve the bug. Both when it fails and when it succeeds, I see memory use for cc1plus.exe going over 4.1GB (I have 16GB).

That's a relief that it's a resource issue, not a problem with our code.  Given the behavior outlined above, I'd think breaking the test down into multiple tests would solve this problem.



> At -O2 it still crashes, but at -O1 it compiles fine. When setting the optimization level to -O0 I got:

That's probably because it's including debug output---that can be controlled separately from optimization level, I think.

**Comment by rok-cesnovar** [comment]
> Are bigger translation units getting compiled after the refactor?

Yeah, log_mix_test was one of the rare ones in this flatten where there were tests in multiple subfolder (scal, mat, arr) so this PR merges the scalar tests with the existing array tests. It seems that the one added test in this file caused it to crash due to lack of resources.

> Commenting out the `matMixscalFun` test block solves the segfault

Thanks so much for debugging this one! Will probably split this in multiple files if there is no other non-hacky solution to this problem.

@alashworth Do you have any tricks up your sleave to handle compiling larger test files on Windows? Since you are using jumbo builds you probably already seen this before.

**Comment by alashworth** [comment]
The "easiest" fix is to make sure you are compiling with `-Wa,-mbig-obj`. Then try compiling with a higher optimization level. Past this requires a lot more manual work moving things in and out of translation units, and taking a count of how many templated functions are being created in the .obj file.

**Comment by rok-cesnovar** [comment]
Thanks, trying if seting the flag will work. It doesnt seem as huge of a test file to be needing other tricks: https://github.com/stan-dev/math/blob/5e18d5eb189008175178bd207a8453dbbc152b49/test/unit/math/mix/fun/log_mix_test.cpp Hopefully :)

**Comment by bob-carpenter** [comment]
The only solution we've found in the past is smaller translation units.

> Thanks so much for debugging this one! Will probably split this in multiple files if there is no other non-hacky solution to this problem.

**Comment by rok-cesnovar** [comment]
Yeah, the `big-obj` flag did not work. 

```
g++ -Wa,-mbig-obj -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs      -I lib/tbb_2019_U8/include -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.72.0 -I lib/sundials_4.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1   -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS       -c -MT test/unit/math/mix/fun/log_mix_test.o -M -E -MG -MP -MF test/unit/math/mix/fun/log_mix_test.d test/unit/math/mix/fun/log_mix_test.cpp

g++ -Wa,-mbig-obj -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs      -I lib/tbb_2019_U8/include -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.72.0 -I lib/sundials_4.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1 -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1    -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS        -c -o test/unit/math/mix/fun/log_mix_test.o test/unit/math/mix/fun/log_mix_test.cpp
```

produced the same seg fault, so multiple translation units it is.

@bob-carpenter Should I just split them to log_mix_arr_test.cpp and log_mix_test_scal_test.cpp?

**Comment by bob-carpenter** [comment]
> @bob-carpenter Should I just split them to log_mix_arr_test.cpp and log_mix_test_scal_test.cpp?

That's OK (dropping the double "test" in the scal version) or you could even use log_mix_part1_test.cpp and log_mix_part2_test.cpp to indicate they're part of the same test in some sense.

**Comment by rok-cesnovar** [comment]
I restarted the test with the Stan upstream pointing to your PR @mcol. We should hit green now.

**Comment by mcol** [comment]
I pushed a fix for an include that I introduced on develop, and restarted the job pointing to https://github.com/stan-dev/math/pull/1584. I hope it's alright!

**Comment by rok-cesnovar** [comment]
Sure. Thanks!

**Pull request merged**
