### PR TITLE
Minor cleanup of infrastructure: python script interpreter, makefile doc

### PR DESCRIPTION
**Pull request by syclik**
## Summary

Minor cleanup of infrastructure:
1. updating `runTests.py` and `runChecks.py` shebang to allow for direct execution of script from the command line. I found more python scripts and updated those.
2. removing references to Python2 for cpplint. The current doc is incorrect.

With this change, we can now run `runTests.py` directly.

## Tests

None.

## Side Effects

None.

## Release notes

Minor cleanup of infrastructure: python script interpreter, makefile doc

## Checklist

- [x] Copyright holder: Daniel Lee

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by syclik** [comment]
Threading tests failed with a seg fault. I'm seeing if I can reproduce locally. 

I don't think anything changed here should have caused the failure.

**Comment by syclik** [comment]
I just ran the test and it passed ok. I hope this was a spurious failure.

**Comment by syclik** [comment]
@serban-nicusor-toptal, could you please restart [Jenkins tests](https://jenkins.flatironinstitute.org/job/Stan/job/Math/job/PR-3005/3/display/redirect)? Thank you!

**Review by SteveBronder — APPROVED** [review]
Thanks!

**Pull request merged**
