### PR TITLE
Eigen member function for reading values and derivatives from autodiff matrices

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary 
Adds a member function for more efficient extraction of values and derivatives from matrices of ```var```/```vari```/```fvar<T>```. The following functions are added:

- ```read_fvar()```
- ```read_vi_val_adj()```
- ```read_vi_val```
- ```read_vi_adj()```
- ```read_val_adj()```

And are used like so:
```
  matrix_vi vis(100, 100);
  MatrixXd vals(100, 100);
  MatrixXd adjs(100, 100);

var_matrix.read_vi_val_adj(vis, vals, adjs);
```
## Tests

Tests are added in ```rev```, ```fwd```, and ```mix``` for matrices, vectors, and row-vectors

## Side Effects

N/A

## Release notes

Added Eigen member function for more efficient extraction of values and derivatives from matrices of autodiff variables

## Checklist

- [x] Math issue #1745 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Cool.  We hve to be careful with single index access because some expression templates have different row-major vs. column-major organizations.  That's a plus if we just want to visit the elements.

**Comment by t4c1** [comment]
This just tells Eigen linear access is possible to use for this operation. If some other operation does not support it Eigen won't use it.

**Comment by andrjohns** [comment]
But given that the function is defined with two indexes being passed (```this->rows(), this->cols()```), will it ever call a single-index version of the functor? Wouldn't that need another definition of the function that passes a single index (```this->size()```)?

**Comment by t4c1** [comment]
I am not sure if that would work. a `NullaryExpression(size(), functor)` would be a vector. I think Eigen would not allow to assigning it to a matrix (that has a different number of rows and cols), even if the total number of elements match.

**Comment by andrjohns** [comment]
The question is more, if ```read_fvar``` is defined as ```NullaryExpr(rows, cols, read_fvar_functor)``` which calls ```operator() (Index row, Index col)``` how it would it know to delegate to ```operator() (Index index)``` and which index to pass?

**Comment by t4c1** [comment]
It checks if all operations in an expression support linear indexing and have same memory layout. If they do, it uses linear indexing, with index going between 0 and `expr.size()`. If you are interested in the details look at `AssignEvaluator.h` in Eigen source.

**Comment by andrjohns** [comment]
@t4c1 Just coming back to this now, is this still relevant with the static matrices that are coming for autodiff?

**Comment by t4c1** [comment]
Yes, it is. Static matrices probably won't replace all use of existing matrices. Even if they do, it will not be soon.

**Comment by andrjohns** [comment]
@t4c1 This is ready for re-review. I couldn't specify the functors as having linear access when they were called as member functions, so I've moved them to standalone functions.

So they're called like:
```
matrix_vi vis(100, 100);
MatrixXd vals(100, 100);
MatrixXd adjs(100, 100);

read_vi_val_adj(var_matrix, vis, vals, adjs);
```
Let me know if you have other ideas for a cleaner way!

**Comment by t4c1** [comment]
> I couldn't specify the functors as having linear access when they were called as member functions, so I've moved them to standalone functions.

No problem. I expected that to happen. If you have some time I would be interested in seeing that benchmark repeated now that we correctly do linear access to matrices.

**Comment by andrjohns** [comment]
Re-ran the speed tests:
```
2020-05-14 15:31:41
Running ./EigCopyMethods
Run on (8 X 4000 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 8192 KiB (x1)
Load Average: 0.89, 0.77, 0.35
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
Matrix_EigMethod        3853691 ns      3854510 ns          180
Matrix_EigMethod_New    2538182 ns      2538713 ns          269
Matrix_LoopCMajor       2539482 ns      2539970 ns          276
Matrix_LoopRMajor      17924734 ns     17928505 ns           39

RowVec_EigMethod         146590 ns       146618 ns         4907
RowVec_EigMethod_New     128090 ns       128116 ns         5435
RowVec_Loop              132834 ns       132861 ns         5280

ColVec_EigMethod         177849 ns       177885 ns         3259
ColVec_EigMethod_New     176342 ns       176378 ns         3950
ColVec_Loop              176529 ns       176565 ns         3954
```

Looks like the new method and looping are still pretty neck-and-neck

**Pull request merged**
