### PR TITLE
ARD Priors for GP squared exponential kernel

### PR DESCRIPTION
**Pull request by drezap**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Automatic Relevance Determination (ARD) priors are a model selection tool with Gaussian Processes. For the squared exponential kernel, a vector length scale argument can identify how far along the input space until two inputs become irrelevant. It is useful that the prior length scale (not the posterior) is able to vary so that GP can I identify relevance on different dimensions. It is important that stan users and researchers have more model selection tools that can help assist with research and inference. 

Please see: C. E. Rasmussen & C. K. I. Williams, Gaussian Processes for Machine Learning, chapter 5.

#### Intended Effect:
Add support for ARD priors in cov_exp_quad.hpp

#### How to Verify:
10 additional unit tests to test proficiency of the vector length scale argument.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
COPYWRITE<2018><Andre Zapico>

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks for the pull request.   I'm afraid our process is getting heavier by the year:

* continuous integration now super picky on formatting so that we don't have to address format in reviews--all the cpplint errors need to be fixed and the submitter needs to install precommit hooks for automatic clang formatting

* every pull request needs to have a BSD license with clearly declared copyright holder

* pull requests should address issues---the issue would be where you say what an ARD prior is and why it's desirable (sketches with references preferred to piles of math!)

* if behavior changes, it needs to be unit tested, not just visually inspected---otherwise the testing can just list existing unit tests if behavior doesn't change

**Comment by drezap** [comment]
I should have been more specific. I:  
1) Wrote ~= 12 unit tests that test functionality of vector length scale argument.
2)  I changed name of `l` to `length_scale` for less ambiguity. 
Since the last request I have:
1) updated formatting and installed the clang pre-commit hooks
2) made sure cpplint runs without exceptions.
3) updated license to include my name.

Concerns:

1) am unsure if my code will be compatible with the rest of `stan` because of the `T_l temp exp` init on line 113. Let me know if I should I do something like, `stan::return_type<T_l, T_x>`
2) My code will definitely not be optimal (due to the += notation). I'm happy to return to this  shortly and optimize it, as well as write the analogous `rev` function.

**Comment by drezap** [comment]
Hi - the changes listed above I committed to my fork since this initial pull request, should I open a different pull request or will the changes be included?

**Comment by bob-carpenter** [comment]
`+=` in itself isn't so bad---that gets buffered and turned into a big `sum()` call in Stan if it's autodiff variables.

Thanks for changing `l` to `length_scale`.  I don't mind one-word variable names (we have some disagremeent about this among team members), but `l` is a bad choice all around due to confusability with `1`.  

Thanks for updating all the formatting and listing the licensing.

Unit tests should test intermediates of the wrong type.  Stan won't let you assign an autodiff type back to a `double`.  If you have an expression involving types `T1` and `T2` as arguments, then you need to figure out the scalar promotion.

As to the second question, yes, changes will be included.  I think we need to kick off testing again, which I'll do in the next message.

**Comment by bob-carpenter** [comment]
jenkins, retest this please.

**Comment by seantalts** [comment]
You have to click on the build and replay it or "build with parameters."

**Comment by drezap** [comment]
hi @seantalts was comment to me, and are these tests for the most recent commit?

**Comment by seantalts** [comment]
No, for Bob who tried to use the "jenkins, retest this please." thing that worked until I recently changed it.

**Comment by seantalts** [comment]
And the tests at the bottom are always for the most recent commit, unless something is broken. It seems you have a doxygen error?

**Comment by drezap** [comment]
just to be sure - it says it's merged, but there are still build issues with the formatting. Is this done, or should I fix the issues?

**Comment by seantalts** [comment]
So this got accidentally merged because of a bug in my server-side autoformat stuff (didn't test with forks where people are working directly on develop, which I guess is probably somewhat common). @bob-carpenter was this approved and just waiting for testing? If so I think it will pass here: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/develop/36/pipeline

I can also revert it if you want, it's just slightly hairy and then would have @drezap resubmitting a revert of a revert as another PR so I figured I'd ask if this was basically good and can work from here instead.

**Comment by seantalts** [comment]
(re: your formatting issues - the server fixed them for you)

**Comment by bob-carpenter** [comment]
It looked OK to me.

**Comment by seantalts** [comment]
Okay, sorry about that. @drezap if you have further stuff to add to this, feel free to open a new PR. Sorry for the confusion.

**Pull request merged**
