### PR TITLE
Fix for the cholesky_decompose_test uninitialized vector issue

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Fix the bug in test/unit/math/rev/mat/fun/cholesky_decompose_test.cpp that causes one of input vectors is not fully initialized. 
The vectors that are created are defined as
```
int vec_size = mat_size * (mat_size + 1) / 2;
Eigen::VectorXd test_vec(mat_size);
Eigen::VectorXd test_vals(vec_size);
```
The current for loop used the smaller vector size as the upper limit:
```
for (int i = 0; i < test_vec.size(); ++i) {
    test_vec(i) = stan::math::normal_rng(0.0,0.1,rng);
    if (i < vec_size)
      test_vals(i) = i % 10 / 100.0;
}
``` 
The test_vals vector was therefore not initialized fully.

#### Intended Effect:
Fixing the above mentioned issue

#### How to Verify:
/

#### Side Effects:
/

#### Documentation:
/

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
This is super fun, apparently the formula used to compute the `vec_size`: `int vec_size = mat_size * (mat_size + 1) / 2;` means that `vec_size` is often _but not always_ greater than `mat_size`:

image

**Comment by rok-cesnovar** [comment]
In cases where `mat_size` is a non-negative integer, we only have case where `vec_size` is either equal or greater than `mat_size`.  Both works fine in this solution. In order to avoid all this we could also just split it in two separate for loops.

**Comment by seantalts** [comment]
Nah I think this is fine, good point. Would you mind merging `develop` in and resolving the conflicts? Thanks again! Glad to have this flaky test finally fixed.

**Comment by rok-cesnovar** [comment]
You‘re welcome.  It was bugging me as I got occasional random errors when adding GPU code and decided to have a deeper look. 
I would not mind resolving the conflicts, but I do not have the rights to do that.

**Comment by seantalts** [comment]
The rights? I think you can just do a `git pull upstream develop` on your branch and then push it up to resolve them, if upstream is set with `git remote add upstream git@github.com:stan-dev/math.git` (or the equivalent https if you use that). I can also look into it.

**Comment by rok-cesnovar** [comment]
Ah, nevermind. I will do this immediately.

**Comment by rok-cesnovar** [comment]
I think I managed to do it. Thanks

**Comment by seantalts** [comment]
Jenkins, ok to test.

Thanks again Rok!

**Comment by seantalts** [comment]
A+ Thank you! Cheers on your first merged PR to the Math library 🎉

**Pull request merged**
