### PR TITLE
Feature/issue 1036 add quantile method

### PR DESCRIPTION
**Pull request by Licht-T**
## Summary

This implements the method for evaluating the `q`-th quantile of the specified data.

## Tests

- `test/unit/math/prim/arr/fun/quantile_test.cpp`
- `test/unit/math/prim/mat/fun/quantile_test.cpp`

## Side Effects

No.

## Checklist

- [x] Math issue #1036, and also related to #1106

- [X] Copyright holder: Licht Takeuchi
    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by bob-carpenter** [comment]
We don't allow `scal` to import `arr` or `mat`---the includes have to go the other way.  So if there are specialized implementations for `arr` or `mat`, they should go in the respective directories.

It's always better to template definitions rather than cut-and-pasting.   We can block or unblock `int` with `disable_if` or specialize if it needs a different implementation.  

The implementation of quantiles here isn't particularly efficient as it does a complete sort whereas, for example, you only need to keep 5% of the entries sorted to do a 5% quantile.  Boost has some accumulators which implement the quantiles in a streaming way with minimal memory overhead: https://www.boost.org/doc/libs/1_55_0/doc/html/accumulators/user_s_guide.html

Just to be clear, though, I don't think this the added efficiency is necessary for this PR.

**Comment by syclik** [comment]
@Licht-T, feel free to reopen this PR if you address the review. I'm closing it for now.

**Comment by sakrejda** [comment]
@syclik you said: 

> What was originally specified in the issue was to accept real -- that's the Stan type real. That actually maps into double and var (and hopefully fvar<T> soon).

Since the quantile function itself will never be differentiable for either of its arguments, does it need to be implemented for `var`? Is there a policy about this documented somewhere? We could kick this conversation to discourse if there is one to be had but without more background I would support having functions that are not differentiable take only data arguments and throwing errors on compilation that could be reported via `stanc`.

**Comment by bob-carpenter** [comment]
We don't have any functions other than the functional like ode_integrate that require data arguments.  

I'd be OK restricting other functions.  We didn't want to restrict things like floor because we thought there'd be uses for interpolation functions.  But we should probably just build interpolation functions ourselves for people.

The new parser may support this more easily---the existing one doesn't have a slot in the signatures for ordinary functions to record data only.

**Comment by syclik** [comment]
@sakrejda: I see... I read the issue first.

There hasn't been an policy written explicitly anywhere, but I've always assumed that if some expression using the Math library works for `double`, it should also work for `stan::math::var` and vice versa. Or at least be compilable even if we throw an exception stating that it doesn't work for that instantiation. Does that make sense? I'd rather we write the templated version that works for `stan::math::var` and be done with it. If there's an interpolation that happens, we can autodiff through that too.

**Comment by bob-carpenter** [comment]
The exception are the ODE and algebraic solver and map_rect, all of which specify data-only arguments.  They're not regular functions, though---they're handled separately in the expression grammar as of the current C++ parser.

**Pull request closed without merging**
