### PR TITLE
Issue/upgrade sundials 510 2

### PR DESCRIPTION
**Pull request by wds15**
## Summary

This upgrades Sundials to version 5.1.0

## Tests

Any tests which use the Sundials libraries. For example

```
./test/unit/math/rev/functor/cvodes_ode_data_rev_test.cpp
./test/unit/math/rev/functor/integrate_ode_cvodes_grad_rev_test.cpp
./test/unit/math/rev/functor/cvodes_ode_data_prim_test.cpp
```

## Side Effects

No

## Checklist

- [X] Math issue #1553

- [X] Copyright holder: Sebastian Weber

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

**Comment by wds15** [comment]
@rok-cesnovar is this the windows fail you saw already:

```
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs      -I lib/tbb_2019_U8/include -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.72.0 -I lib/sundials_5.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1   -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS       -c -MT test/unit/math/prim/fun/gamma_q_test.o -M -E -MG -MP -MF test/unit/math/prim/fun/gamma_q_test.d test/unit/math/prim/fun/gamma_q_test.cpp
Cannot contact gelman-group-win2: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
process_begin: CreateProcess(c:\Rtools\mingw_64\bin\mingw32-make.exe, mingw32-make -j16 test/unit/math/prim/fun/gamma_q_test.exe test/unit/math/prim/fun/get_base1_lhs_test.exe test/unit/math/prim/fun/get_base1_test.exe test/unit/math/prim/fun/get_lp_test.exe test/unit/math/prim/fun/gp_dot_prod_cov_test.exe test/unit/math/prim/fun/gp_exponential_cov_test.exe test/unit/math/prim/fun/gp_exp_quad_cov_test.exe test/unit/math/prim/fun/gp_matern32_cov_test.exe test/unit/math/prim/fun/gp_matern52_cov_test.exe test/unit/math/prim/fun/gp_periodic_cov_test.exe test/unit/math/prim/fun/grad_2F1_test.exe test/unit/math/prim/fun/grad_F32_test.exe test/unit/math/prim/fun/grad_reg_inc_beta_test.exe test/unit/math/prim/fun/grad_reg_inc_gamma_test.exe test/unit/math/prim/fun/grad_reg_lower_inc_gamma_test.exe test/unit/math/prim/fun/head_test.exe test/unit/math/prim/fun/hypot_test.exe test/unit/math/prim/fun/identity_transform_test.exe test/unit/math/prim/fun/if_else_test.exe test/unit/math/prim/fun/inc_beta_dda_test.exe, ...) failed.
make (e=6, rc=19): The handle is invalid.

fun/col_test.exe test/unit/math/prim/fun/constants_test.exe test/unit/math/prim/fun/containers_conversion_test.exe test/unit/math/prim/fun/corr_matrix_transform_test.exe test/unit/math/prim/fun/corr_transform_test.exe test/unit/math/prim/fun/cos_test.exe test/unit/math/prim/fun/cov_exp_quad_test.exe test/unit/math/prim/fun/cov_matrix_transform_test.exe test/unit/math/prim/fun/crossprod_test.exe
------------------------------------------------------------
mingw32-make -j16 test/unit/math/prim/fun/csr_extract_u_test.exe test/unit/math/prim/fun/csr_extract_v_test.exe test/unit/math/prim/fun/csr_extract_w_test.exe test/unit/math/prim/fun/csr_matrix_times_vector_test.exe test/unit/math/prim/fun/csr_to_dense_matrix_test.exe test/unit/math/prim/fun/csr_u_to_z_test.exe test/unit/math/prim/fun/cumulative_sum_test.exe test/unit/math/prim/fun/determinant_test.exe test/unit/math/prim/fun/diagonal_test.exe test/unit/math/prim/fun/diag_matrix_test.exe test/unit/math/prim/fun/diag_post_multiply_test.exe test/unit/math/prim/fun/diag_pre_multiply_test.exe test/unit/math/prim/fun/digamma_test.exe test/unit/math/prim/fun/dims_test.exe test/unit/math/prim/fun/distance_test.exe test/unit/math/prim/fun/divide_columns_test.exe test/unit/math/prim/fun/divide_test.exe test/unit/math/prim/fun/dot_self_test.exe test/unit/math/prim/fun/dot_test.exe test/unit/math/prim/fun/eigenvalues_sym_test.exe
------------------------------------------------------------
mingw32-make -j16 test/unit/math/prim/fun/eigenvectors_sym_test.exe test/unit/math/prim/fun/elt_divide_test.exe test/unit/math/prim/fun/elt_multiply_test.exe test/unit/math/prim/fun/erfc_test.exe test/unit/math/prim/fun/erf_test.exe test/unit/math/prim/fun/exp2_test.exe test/unit/math/prim/fun/expm1_test.exe test/unit/math/prim/fun/exp_test.exe test/unit/math/prim/fun/F32_test.exe test/unit/math/prim/fun/fabs_test.exe test/unit/math/prim/fun/factor_cov_matrix_transform_test.exe test/unit/math/prim/fun/falling_factorial_test.exe test/unit/math/prim/fun/fdim_test.exe test/unit/math/prim/fun/fill_test.exe test/unit/math/prim/fun/finite_diff_stepsize_test.exe test/unit/math/prim/fun/floor_test.exe test/unit/math/prim/fun/fmax_test.exe test/unit/math/prim/fun/fma_test.exe test/unit/math/prim/fun/fmin_test.exe test/unit/math/prim/fun/gamma_p_test.exe
------------------------------------------------------------
mingw32-make -j16 test/unit/math/prim/fun/gamma_q_test.exe test/unit/math/prim/fun/get_base1_lhs_test.exe test/unit/math/prim/fun/get_base1_test.exe test/unit/math/prim/fun/get_lp_test.exe test/unit/math/prim/fun/gp_dot_prod_cov_test.exe test/unit/math/prim/fun/gp_exponential_cov_test.exe test/unit/math/prim/fun/gp_exp_quad_cov_test.exe test/unit/math/prim/fun/gp_matern32_cov_test.exe test/unit/math/prim/fun/gp_matern52_cov_test.exe test/unit/math/prim/fun/gp_periodic_cov_test.exe test/unit/math/prim/fun/grad_2F1_test.exe test/unit/math/prim/fun/grad_F32_test.exe test/unit/math/prim/fun/grad_reg_inc_beta_test.exe test/unit/math/prim/fun/grad_reg_inc_gamma_test.exe test/unit/math/prim/fun/grad_reg_lower_inc_gamma_test.exe test/unit/math/prim/fun/head_test.exe test/unit/math/prim/fun/hypot_test.exe test/unit/math/prim/fun/identity_transform_test.exe test/unit/math/prim/fun/if_else_test.exe test/unit/math/prim/fun/inc_beta_dda_test.exe
mingw32-make -j16 test/unit/math/prim/fun/gamma_q_test.exe test/unit/math/prim/fun/get_base1_lhs_test.exe test/unit/math/prim/fun/get_base1_test.exe test/unit/math/prim/fun/get_lp_test.exe test/unit/math/prim/fun/gp_dot_prod_cov_test.exe test/unit/math/prim/fun/gp_exponential_cov_test.exe test/unit/math/prim/fun/gp_exp_quad_cov_test.exe test/unit/math/prim/fun/gp_matern32_cov_test.exe test/unit/math/prim/fun/gp_matern52_cov_test.exe test/unit/math/prim/fun/gp_periodic_cov_test.exe test/unit/math/prim/fun/grad_2F1_test.exe test/unit/math/prim/fun/grad_F32_test.exe test/unit/math/prim/fun/grad_reg_inc_beta_test.exe test/unit/math/prim/fun/grad_reg_inc_gamma_test.exe test/unit/math/prim/fun/grad_reg_lower_inc_gamma_test.exe test/unit/math/prim/fun/head_test.exe test/unit/math/prim/fun/hypot_test.exe test/unit/math/prim/fun/identity_transform_test.exe test/unit/math/prim/fun/if_else_test.exe test/unit/math/prim/fun/inc_beta_dda_test.exe failed
exit now (01/15/20 14:32:14 Eastern Standard Time)
script returned exit code 19
```

**Comment by rok-cesnovar** [comment]
No, this one is new, but based on the error, the connection to the machine errored-out. Just restart the tests I guess. The reason why the machine errored out could be related to #1615

**Comment by wds15** [comment]
This sundials upgrade can and definitely should wait for merge with develop until the release 2.22 of Stan / Stan-Math 3.1 .

**Comment by rok-cesnovar** [comment]
Will approve and merge on Sunday/Monday then. Looks good to me otherwise.

**Comment by wds15** [comment]
Great. Note the changes to the update script. Somehow kinsol got removed from the script, but we use that in the meantime.

**Pull request merged**
