### PR TITLE
Adding Google Benchmark library; upgrade Google Test

### PR DESCRIPTION
**Pull request by syclik**
## Summary

This PR adds Google Benchmark as a library.

Details:

1. A bash script was added to handle the upgrade of Google Benchmark: `lib/upgrade-google-benchmark.sh`
2. Google Benchmark requires Google Test to be nested within in. Google Test has moved from `lib/gtest_1.8.1` to `lib/benchmark_1.5.1/googletest/`.
3. All relevant makefiles have been updated. `GTEST` is still the same path to the library. 
4. Google Test was upgraded from 1.8.1 to the latest (1.10.x).
5. Google Benchmark is not being used yet. Having it here will allow us to use it easily.
6. The modification of `googletest/src/gtest_main.cc` to deal with MPI is handled through the script.

## Tests

No new tests. I spot-checked some tests. Hopefully Google Test didn't change much of their implementation to cause us to fail.

## Side Effects

1. The update to Google Test marks a few of their macros as deprecated. In order to get rid of warnings (which stop our builds) I had to update the distribution tests with :
    - `INSTANTIATE_TYPED_TEST_CASE_P` -> `INSTANTIATE_TYPED_TEST_SUITE_P`
    - add `GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST` to the test fixtures
    - update CmdStan to branch: `feature/math-issue-1852-google-benchmark`. This also addressed the warnings for a test that relied on these macros.

## Release notes

- Upgrade Google Test to v1.10.x.
- Add Google Benchmark as a test dependency.

## Checklist

- [x] Math issue #1852

- [x] Copyright holder: Generable

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
For MPI we need to add this patch https://github.com/stan-dev/math/pull/1052/commits/627a2500dc0d2a0bd265d657605571f14193fa39

**Comment by SteveBronder** [comment]
I'm not totally following why this couldn't be in a different stan repo. What's our goal with adding google benchmark here? imo I'd rather just move [perf-math](https://github.com/seantalts/perf-math) from @seantalts 's profile to `stan-dev` (if he doesn't mind). Then just have some Jenkins job that once a day updates that repo with the latest version of stan (then we can benchmark all of stan instead of just stan-math)

**Comment by syclik** [comment]
@rok-cesnovar, I figured out how to do this without needing to modify the file. Think it's ok if I just roll it into this PR rather than patch dev once then patch this again?

**Comment by syclik** [comment]
I updated the top-level comment to indicate that the MPI handling was done differently. We don't have to modify Google Test anymore!

**Comment by syclik** [comment]
> I'm not totally following why this couldn't be in a different stan repo. What's our goal with adding google benchmark here? imo I'd rather just move [perf-math](https://github.com/seantalts/perf-math) from @seantalts 's profile to `stan-dev` (if he doesn't mind). Then just have some Jenkins job that once a day updates that repo with the latest version of stan (then we can benchmark all of stan instead of just stan-math)

The goal for adding the benchmark library here is that it becomes available for Stan Math and anything that includes Stan Math, which would include Stan, CmdStan, RStan, PyStan, etc.

Stan and CmdStan use the makefiles, so including it at the Math level has it trickle down to all those repos.

In order to use Google Benchmark, Google Test must be embedded inside the folder structure; I checked... there isn't an obvious way to customize location.

As for why we'd want it here... if we're trying to optimize functions in Math, we should be benchmarking. The immediate need is to benchmark a function, improve it, and show that the code improves for the PR. It'd make it a lot easier if we started providing information on how to do this and had all the build hooks to make it happen easily.

Having a running benchmark that runs across version sounds like a good idea, but isn't the primary use case I'm thinking about. If we had the library included here, it'd be available for us to do that. `perf-math` is designed for this use case.

Does that make sense? This PR doesn't include all the hooks to get Benchmark setup.

**Comment by syclik** [comment]
@rok-cesnovar, so... I was mistaken about getting it to work using macros. It was a scoping issue; there's something tricky about the mpi lifecycle that makes it hard to work around the scope.

I'll update the script to modify the file; we definitely want the main file to be updated with the script.

**Comment by rok-cesnovar** [comment]
The cmdstan tests use some stuff that seems to have bee deprecated: https://jenkins.mc-stan.org/job/CmdStan/job/downstream_tests/1894/Windows/new/origin.-54077847/folder.-997512030/source.f7626448-903c-4940-8acf-dcf78e963e14/#143

Guess we need to fix those before merging this.

**Comment by syclik** [comment]
Ah. Thanks. I was looking for how it failed... I'll update CmdStan on a
branch.

**Comment by syclik** [comment]
@rok-cesnovar, this branch on CmdStan squashes that warning: `feature/math-issue-1852-google-benchmark`.

https://github.com/stan-dev/cmdstan/tree/feature/math-issue-1852-google-benchmark

The change is 8 lines in one test file: https://github.com/stan-dev/cmdstan/compare/feature/math-issue-1852-google-benchmark?expand=1

How do I attach a CmdStan upstream branch to the current tests? I think this branch makes it pass and we can go on with an updated Google Test.

**Comment by syclik** [comment]
I just updated the top-level issue to indicate that there's a side-effect. I'm going to create a CmdStan PR now. It'll fail until this PR is merged.

**Comment by rok-cesnovar** [comment]
> How do I attach a CmdStan upstream branch to the current tests?

1. Go to the old Jenkins view for this PR: https://jenkins.mc-stan.org/job/Math%20Pipeline/job/PR-1995/
2. Click Build with parameters
3. in cmdstan_pr write PR-917 (the number of the cmdstan PR)

This will also turn the Cmdstan PR green.

I did that just now, this is just for future reference. I think this is documented somewhere, but can't find it right now.

**Comment by syclik** [comment]
@rok-cesnovar, thanks! Got it... I should be able to figure it out next time (hopefully).

**Comment by syclik** [comment]
Tests passing. Anyone want to review?

**Comment by syclik** [comment]
One thing to do is to check if the actual compilation time has changed drastically. I'll do that now.

**Comment by rok-cesnovar** [comment]
I tagged myself for review, will do tonight or tomorrow morning the latest. I think Google benchmark is not a huge library and am fine adding it. Especially if that makes running ad-hoc benchmarks less of a hassle.

**Comment by syclik** [comment]
Looks like things take a little longer. For distribution tests:

This branch (https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1995/9/pipeline/154): 
51m 23s

A different branch (https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1952/52/pipeline/99):
43m 53s

I'm seeing similar for unit tests.


This is all coming from the upgrade in Google Test, not because Google Benchmark was added. Hopefully we're ok with this... it doesn't hurt any of the actual performance, just the time to build / run tests.

**Comment by SteveBronder** [comment]
> Having a running benchmark that runs across version sounds like a good idea, but isn't the primary use case I'm thinking about. If we had the library included here, it'd be available for us to do that. perf-math is designed for this use case.

I agree performance tests are good! My personal branch of `perf-math` is the insane performance ramblings and rumblings of a madman.

For integrating this with math I think what's important to me is to have some standard structure for adding performance (tests? hypothesis? experiments?) as a part of a PR. So I think we'd have some sort of `performance_experiments` folder with sub folders for each PR. Then some sort of `runPerf.py` python file like `./runTests.py` that can run the perf tests in a file.

**Comment by syclik** [comment]
> For integrating this with math I think what's important to me is to have some standard structure for adding performance (tests? hypothesis? experiments?) as a part of a PR.

Exactly! I'm not completely sure what makes sense yet. I know we need Benchmark or something that has the functionality to even start thinking through it.

Part of the benchmarks need to be transient. For PRs you want to know that the code before the PR and the code after the PR improves performance, but you don't need to keep the difference in performance around.

Then there's benchmarking enough of the library to know if we do something drastic, we'd catch it. Like if we changed the autodiff stack or updating Eigen or Boost.

**Comment by rok-cesnovar** [comment]
We will have to take a look at running tests on Windows with RTools 3.5: https://github.com/stan-dev/math/runs/953577951?check_suite_focus=true

Nothing urgent, but we should see if there is a simple fix for the tests. I can take a look at this next week.

Everything is fine with compiling models with that toolchain as Cmdstan tests are fine: https://github.com/stan-dev/cmdstan/runs/953613133

**Comment by syclik** [comment]
Thanks for pulling that up. To help with the detective work later, the error starts at L546 (the end which can only be reached by scrolling):
```
   ^
lib/benchmark_1.5.1/googletest/googletest/include/gtest/gtest.h:2342:3: note: in expansion of macro 'GTEST_TEST_'
   GTEST_TEST_(test_suite_name, test_name, ::testing::Test, \
   ^
lib/benchmark_1.5.1/googletest/googletest/include/gtest/gtest.h:2348:42: note: in expansion of macro 'GTEST_TEST'
 #define TEST(test_suite_name, test_name) GTEST_TEST(test_suite_name, test_name)
<builtin>: recipe for target 'test/unit/math/mix/fun/gp_periodic_cov_test.o' failed
                                          ^
test/unit/math/mix/fun/gp_periodic_cov_test.cpp:16941:1: note: in expansion of macro 'TEST'
 TEST(AgradMixMath, ffv_gp_periodic_cov2_eigen_vec_nan_values_1) {
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
mingw32-make: *** [test/unit/math/mix/fun/gp_periodic_cov_test.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
it/math/mix/fun/grad_2F1_test.exe test/unit/math/mix/fun/grad_F32_test.exe test/unit/math/mix/fun/grad_reg_inc_beta_test.exe test/unit/math/mix/fun/grad_reg_inc_gamma_test.exe test/unit/math/mix/fun/head_test.exe test/unit/math/mix/fun/hypot_test.exe test/unit/math/mix/fun/identity_constrain_test.exe test/unit/math/mix/fun/imag_test.exe test/unit/math/mix/fun/inc_beta_test.exe test/unit/math/mix/fun/initialize_test.exe test/unit/math/mix/fun/inverse_spd_test.exe
mingw32-make -j2 test/unit/math/mix/fun/fma_test.exe test/unit/math/mix/fun/fmin_test.exe test/unit/math/mix/fun/fmod_test.exe test/unit/math/mix/fun/gamma_p_test.exe test/unit/math/mix/fun/gamma_q_test.exe test/unit/math/mix/fun/get_base1_lhs_test.exe test/unit/math/mix/fun/get_base1_test.exe test/unit/math/mix/fun/gp_matern52_cov_test.exe test/unit/math/mix/fun/gp_periodic_cov_test.exe test/unit/math/mix/fun/grad_2F1_test.exe test/unit/math/mix/fun/grad_F32_test.exe test/unit/math/mix/fun/grad_reg_inc_beta_test.exe test/unit/math/mix/fun/grad_reg_inc_gamma_test.exe test/unit/math/mix/fun/head_test.exe test/unit/math/mix/fun/hypot_test.exe test/unit/math/mix/fun/identity_constrain_test.exe test/unit/math/mix/fun/imag_test.exe test/unit/math/mix/fun/inc_beta_test.exe test/unit/math/mix/fun/initialize_test.exe test/unit/math/mix/fun/inverse_spd_test.exe failed
exit now (08/06/20 12:55:50 Coordinated Universal Time)
##[error]Process completed with exit code 1.
```

There's a seg fault in compiling. Fun.

**Comment by syclik** [comment]
If you have direct access to that particular compiler, can you try:

```
make test/unit/math/mix/fun/gp_periodic_cov_test
```

See if the seg fault is reproducible?

**Comment by rok-cesnovar** [comment]
Segfault in compiling with Rtools 3.5 on Windows is actually common for large test files. And the segfaulting test is quite large. This is always reproducible. 
Will spin up an RTools 3.5 instance on my AWS account and test it out.

**Comment by bbbales2** [comment]
I restored this branch cause it is a pre-`var_value` math library with the Google benchmark library included (so I can use it to benchmark `var_value` against the old `var` s).

**Pull request merged**
