### PR TITLE
delete beta_neg_binomial_lccdf test

### PR DESCRIPTION
**Pull request by lingium**
## Summary

As described by #3117, disable the test for `beta_neg_binomial_lccdf`.

## Tests

NA

## Side Effects

NA

## Release notes

`test/prob/beta_neg_binomial/beta_neg_binomial_ccdf_log_test.hpp` will be deleted if merged.

## Checklist

- [x] Copyright holder: Zhi Ling

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
Instead of deleting it, can we try the following

1. Make a `beta_neg_binomial_tol_lccdf` that exposes the tuning parameters. 
2. Test that with "nice numbers" that are easy to solve with a high tol and low iteration
3. Have tests that use the expect_ad testing framework for the basic `beta_neg_binomial_tol_lccdf`

The prob testing framework is mostly to ensure that all the different varations of scalars and vectors can go into the distributions. But if we just want to test boundaries and things like that then I think it would be better for us to have those in mix/prob testing folder

**Comment by lingium** [comment]
Thanks to Steve's suggestion, after some debugging I found certain magic numbers and now the time for this test should be the same as other distributions. Let’s see how it works on the Jenkins machine.

**Comment by lingium** [comment]
Nice, now the test will not affect continuous integration.
image

**Review by WardBrian — APPROVED** [review]
Looks good, it is indeed _much_ faster!

**Pull request merged**
