### PR TITLE
Revert "Add tests for var_value<Matrix> for univariate distributions"

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Reverts stan-dev/math#2304

@bbbales2 @SteveBronder merging #2304 has broken develop distribution tests. Not sure why exactly it is failing, but either the branch for #2304 has not been updated to recent master before merging or its an issue with row_vector tests that only run on merges. 

I am going to merge the revert and then we can re-do the PR but make sure to run row vector tests as well (we can do that manually on Jenkins)

edit: Jenkins is running distribution tests with row vector to make sure the revert fixes this problem.

### CODE REVIEW

**Comment by bbbales2** [comment]
Cool beans, sounds good. Do you have a link to logs where it was failing?

**Comment by rok-cesnovar** [comment]
Ah forgot to link that: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1040/artifacts

see dist.log.zip

Mind approving so I can merge this over the weekend when Jenkins isnt busy?

**Review by bbbales2 — APPROVED** [review]
I got Github points for the first approving, I'll get Github points for approving the revert, and I intend to get Github points on the next merge :tada: :tada:

**Comment by rok-cesnovar** [comment]
Its free Github points everywhere :)

**Comment by bbbales2** [comment]
Huh, a good ol' fashion segfault

Should be on:
```
./runTests.py test/prob/pareto_type_2/pareto_type_2_00009_generated_vv_test
```

**Comment by rok-cesnovar** [comment]
Yeah, it wasnt a one off thing too, as the next two runs had similar failures.


https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1041/pipeline

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1042/pipeline

**Pull request merged**
