### PR TITLE
Updating using statements for some tests

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary:

This should make the few distribution tests that weren't passing pass.

#### Intended Effect:

Make tests pass by including the right using statements.

#### How to Verify:
Let Jenkins do its work. Check the file diffs.

#### Side Effects:
None. This got broken with another pull request.

#### Documentation:
None required.

#### Reviewer Suggestions: 
Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
These minor include changes are OK if the tests pass

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Whoops. Fixes #365.

**Pull request merged**
