### PR TITLE
Bugfix/issue 1073 matrix exp mulitply: fixes segfault in matrix_exp_multiply

### PR DESCRIPTION
**Pull request by syclik**
## Summary

Fixes a seg fault.

## Tests

Includes a test that seg faults with the current implementation.

## Side Effects

This will add a lot more elements on the autodiff stack, but is correct. (~2600 vs 1.)

## Checklist

- [x] Math issue #1073

- [x] Copyright holder: Generable

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by bob-carpenter** [comment]
This seems like it's going to introduce  a serious performance regression by replacing `matrix_exp_action(A, B);` with  `multiply(matrix_exp(A), B);`.    

I'm fully supportive of correctness taking precedence over efficiency, and the call about whether to take the performance hit on this is @syclik's.  

Nevertheless, I'd like to hear from  @charlesm93 and/or @yizhang-cae about why they didn't fix the bug and whether they care about the performance hit---the move to remove the efficient implementation in this PR may be enough to spur them to fix the original code.  If not, then by all means get someone to review this and merge in the fix for correctness.

**Comment by syclik** [comment]
Yes, it's a performance regression, but the seg fault takes priority. I'd
prefer to see a safe, slow version merged first, then have a new PR for a
safe and fast implementation.

I'm going to try to run this branch on Windows to make sure we can get past
this failure.

**Comment by yizhang-cae** [comment]
I'll take a look later today.

**Comment by syclik** [comment]
Thanks. Would you mind reviewing the PR and approving if it looks ok.

Then we can go back and merge a fix that's efficient when that's available.

**Comment by syclik** [comment]
@yizhang-cae: just FYI, that's not the only time it seg faults. That was
just the one I added an explicit test for that causes a failure.

**Comment by yizhang-cae** [comment]
Thanks. I'm also curious why it doesn't fail on the rest unit tests.

**Comment by syclik** [comment]
Yeah... I really want to find out what's causing it because I think we
might find the problem in other spots. Hopefully you get further than I do.

**Pull request merged**
