### PR TITLE
Feature/issue xxx exponential cov prim

### PR DESCRIPTION
**Pull request by drezap**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Add exponential covariance function to prim with ARD support. This is consistent with with both GMPL (Rasmussen & Williams) and our current quadratic exponential covariance function. Users will be able to switch back and forth between covariance functions easily, per Mike's suggestion on discourse. Please see the latex documentation for description of how I calculate the function and ARD.

#### How to Verify:
Here are the different data types and error message calls I tested:
vec double
vec double double
vec double ARD
vec eigen
vec eigen eigen
vec eigen ARD
vec double double ARD
rvec eigen
rvec eigen ARD
vec eigen rvec eigen
vec eigen rvec eigen ARD
rvec eigen rvec eigen
rvec eigen rvec eigen ARD
eigen mixed
eigen mixed ARD
double domain err training
nan error training
differing x lengths

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Copywrite<2018><Andre Zapico>

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by drezap** [comment]
Hi - can someone please reset the jenkins build? This error is unrelated to stan-dev.

Thanks

**Comment by drezap** [comment]
Jenkins, retest this please.

**Comment by drezap** [comment]
Hi - 

Can someone reset these jenkins tests? I don't think they have anything to do with me.

**Comment by sakrejda** [comment]
It's not letting me re-start but yes it looks like Jenkins had a problem.

**Comment by sakrejda** [comment]
@seantalts sorry, I see the restart button on something else but not on this.

**Comment by drezap** [comment]
Hi - 
Sorry, I can't see the restart for this or #851, is there a work around or should I just do a commit?

**Comment by seantalts** [comment]
Click the little door to exit the fancy GUI and go back to the old one. Not sure why the new one isn't displaying a replay here.

**Comment by sakrejda** [comment]
It looked like the error said that b/c the git pull failed there were no changes (and therefore nothing to restart) so maybe something is not quite perfect with the scripts

**Comment by seantalts** [comment]
Github was just down from what I can tell

**Comment by seantalts** [comment]
Or rather, we had connection problems to it

**Comment by drezap** [comment]
Hi - can some one please review this PR?

**Comment by drezap** [comment]
hi - closing this PR and opening a new one shortly that includes a rev implementation.

**Pull request closed without merging**
