### PR TITLE
Add cdf_log, ccdf_log, and log functions for poisson binomial

### PR DESCRIPTION
**Pull request by dirmeier**
## Summary

Adds `poisson_binomial_log`  `poisson_binomial_cdf_log` and `poisson_binomial_ccdf_log` functions for poisson binomial distribution.

## Tests

Adds tests comparing output of `poisson_binomial_log` to `poisson_binomial_lpmf`, `poisson_binomial_cdf_log` to `poisson_binomial_lcdf` and `poisson_binomial_ccdf_log` to `poisson_binomial_lccdf`.

## Checklist

- [x] Math issue #2317

- [x] Copyright holder: Simon Dirmeier

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by rok-cesnovar — CHANGES_REQUESTED** [review]
This looks good to me. I am requesting changes for another reason. 

The lcdf and lccdf function do not compile for the signature `(int, vector[])` which is
int, std::vector<Eigen::Matrix<double, -1, 1> in Stan Math terms.

Sorry for figuring this out so late.

**Comment by dirmeier** [comment]
> Sorry for figuring this out so late.

No problem, will do tomorrow.

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar ,
I think this fixes it. I am not sure if this template
```
template <typename T_y, typename T_theta,
          typename = std::enable_if_t<
              (std::is_same<int, T_y>::value
               || (is_std_vector<T_y>::value
                   && std::is_same<int, scalar_type_t<T_y>>::value))>,
          typename T_scalar = scalar_type_t<T_theta>>
auto poisson_binomial_log_probs(const T_y& y, const T_theta& theta) {
...
}
```

in [poisson_binomial_log_probs.hpp](https://github.com/stan-dev/math/pull/2318/files#diff-c54f3149c27468b823003178ce9d935a2601a1d2d79f93a73f8f03c16d359d23R55) can be done nicer though.

The tests for  pmf, cdf and ccdf now all check for sth like this:

```
TEST(ProbDistributionsPoissonBinomial, lccdf_works_on_scalar_y_and_vectorial_theta2) {
  using stan::math::poisson_binomial_lccdf;
  using vec = Eigen::Matrix<double, Eigen::Dynamic, 1>;

  vec p(3, 1);
  p << 0.5, 0.2, 0.7;
  int y = 2;
  std::vector<vec> ps{p, p};

  EXPECT_NEAR(-2.65926 * 2.0, poisson_binomial_lccdf(y, ps), 0.001);
}
```

Cheers,
Simon

**Comment by rok-cesnovar** [comment]
Hey @dirmeier,

just now getting back to this, sorry. It seems that some of the functions are still failing the expressions tests.

These are all the tests that run:
```
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_cdf_log(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lccdf(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lcdf(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_log(int[], row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int, vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int, row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int, vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int, row_vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int[], vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int[], row_vector)"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int[], vector[])"
./runTests.py test/expressions --only-function "real poisson_binomial_lpmf(int[], row_vector[])"
./runTests.py test/expressions --only-function "int[] poisson_binomial_rng(vector)"
./runTests.py test/expressions --only-function "int[] poisson_binomial_rng(row_vector)"
./runTests.py test/expressions --only-function "int[] poisson_binomial_rng(vector[])"
./runTests.py test/expressions --only-function "int[] poisson_binomial_rng(row_vector[])"
```
Some of these fail to compile, for example: `./runTests.py test/expressions --only-function "real poisson_binomial_ccdf_log(int, row_vector)"`

Some others fail due to the numbers used in the tests (you may need to add exceptions here https://github.com/stan-dev/math/blob/develop/test/sig_utils.py#L109). By default all values are 0.4. But that is a smaller issue. I can also take care of this one. We first need to make all of these to compile.

Thanks!

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar, thanks, I'll fix it.

**Comment by rok-cesnovar** [comment]
Thanks! No rush, I just listed everything because we do not have any central docs on what we test and how to try it out beforehand.

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar,

I think all functions compile now and all but the ccdf tests run successfully (see for instance below). I'm not sure why these wouldn't work though, since the difference between `lcdf` and `lccdf`  is only an additional call to `log1m_exp` (see [cdf line 59](https://github.com/stan-dev/math/pull/2318/files#diff-c1ecc9138608e438757e6385d9d9d76ef0a572fb4920aa4fb2cd39513bfbb455R59) and [ccdf line 61](https://github.com/stan-dev/math/pull/2318/files#diff-9450e9ce31b2f320f3652e442c630fd22c586c5f03dffe209448c6696e6cdb90R61)). Could you give me a hint how I can debug these tests?

Thanks,
Simon

```
[==========] Running 3 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 1 test from ExpressionTestPrim
[ RUN      ] ExpressionTestPrim.poisson_binomial_ccdf_log0
./test/expressions/expression_test_helpers.hpp:101: Failure
Expected equality of these values:
  a
    Which is: nan
  b
    Which is: nan
Error in file: test/expressions/tests0_test.cpp, on line: 17
[  FAILED  ] ExpressionTestPrim.poisson_binomial_ccdf_log0 (0 ms)
[----------] 1 test from ExpressionTestPrim (0 ms total)

[----------] 1 test from ExpressionTestRev
[ RUN      ] ExpressionTestRev.poisson_binomial_ccdf_log0
./test/expressions/expression_test_helpers.hpp:105: Failure
Expected equality of these values:
  a.val()
    Which is: nan
  b.val()
    Which is: nan
Error in file: test/expressions/tests0_test.cpp, on line: 36
./test/expressions/expression_test_helpers.hpp:141: Failure
Expected equality of these values:
  a.adj()
    Which is: nan
  b.adj()
    Which is: nan
```

**Comment by rok-cesnovar** [comment]
Hey Simon, saw that earlier today and havent yet discovered what is up with that. I think @bbbales2 was looking into it.

**Comment by bbbales2** [comment]
Aye, I think the change is:

```cpp
inline double log1m_exp(double a) {
  using std::exp;
  using std::log;
  if (a >= 0) {
    return NOT_A_NUMBER;
  } else if (a > -0.693147) {
    return log(-expm1(a));  // 0.693147 ~= log(2)                                                                                                                                                                                                                              
  } else {
    return log1m(exp(a));
  }
}
```

Should be:
```cpp
inline double log1m_exp(double a) {
  using std::exp;
  using std::log;
  if (a >= 0) {
    return NOT_A_NUMBER;
  } else if (a > -0.693147) {
    return log(-expm1(a));  // 0.693147 ~= log(2)                                                                                                                                                                                                                              
  } else {
    return log1m(exp(a));
  }
}
```

Fixing that up and I'll push it up

**Comment by bbbales2** [comment]
Ooof, still not working, gradients are blowing up.

For `log1m_exp`:

```cpp
void chain() { avi_->adj_ -= adj_ / expm1(-(avi_->val_)); }
```

`avi_->val_` is the input, so that is 0.0. In the limit the gradient is nasty too.

**Comment by bbbales2** [comment]
@dirmeier I pushed some changes to `stan/math/prim/prob/poisson_binomial_lccdf.hpp` that I'm not totally sure are correct -- I think we just gotta handle this with more if statements. Have a look and see if it's right.

There weren't tests for the length-1 behavior so it might not be right. Might need to add more or adjust the length 1 tests.

Maybe in the end it would be better to rewrite `log1m(log_sum_exp(x))`. I wonder if there is a different way to do this. Like it is like regular `log_sum_exp` with an extra zero appended to the start of `x`.

**Comment by dirmeier** [comment]
Ciao @bbbales2 , sorry, only seeing this now. 

> There weren't tests for the length-1 behavior so it might not be right. Might need to add more or adjust the length 1 tests.

Just to make sure: tests were either of the arguments are vectors of length one or scalars?

Cheers,
S

**Comment by bbbales2** [comment]
Yeah so is the code I added to lccdf correct: https://github.com/stan-dev/math/pull/2318/files#diff-9450e9ce31b2f320f3652e442c630fd22c586c5f03dffe209448c6696e6cdb90R59

I sorta guess and checked, but for length-1 arguments this is numerically stable. I'm not 100% sure it's right though.

**Comment by dirmeier** [comment]
Right, I'll check it and add some test cases.

**Comment by dirmeier** [comment]
Ciao @bbbales2 , thanks for fixing this and adding the tests (didn't notice them before).

> I sorta guess and checked, but for length-1 arguments this is numerically stable. I'm not 100% sure it's right though.

Looks correct to me. 

I added three length 0/1 tests cases for vectorial y which work locally for me, but seem to [break upstream tests](https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2318/8/pipeline). Not sure why.

**Comment by rok-cesnovar** [comment]
Hey @dirmeier, the upstream tests failed because the AWS instances got shutdown. We use the cheaper AWS instances from which we sometimes get kicked out. How rude, but its why they are cheap. Restarted the tests, should be done in ~2hours.

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2318/9/pipeline

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar , could you run it again, please?  Got cancelled, again. Thanks!

**Comment by rok-cesnovar** [comment]
Argh, unlucky. Done: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2318/10/pipeline

**Comment by rok-cesnovar** [comment]
@dirmeier @bbbales2 so this is good to go now once we persuade Jenkins and AWS to cooperate?

**Comment by dirmeier** [comment]
I think it is, but @bbbales2 's call

**Comment by bbbales2** [comment]
Lemme have another look through it later today.

**Comment by bbbales2** [comment]
@dirmeier made some minor changes as I went through, but this looks good to me. Have a look at my changes and if you're happy with em' ping Rok.

**Comment by dirmeier** [comment]
Thanks @bbbales2 . Looks go to me.

**Review by rok-cesnovar — APPROVED** [review]
Thanks!

**Pull request merged**
