### PR TITLE
bugfix/gp_matern52_cov-fails

### PR DESCRIPTION
**Pull request by drezap**
## Summary

This function was failing compilation for the generated C++ due to poor templating. There were also no "zero size" test case.

1. Change `distance` to `dist` variable name.
2. Add `T_l` for return type when using `stan::math::distance`, `stan::math::squared_distance`
3. Adds a test in rev that checks for this compilation error
4. Adds a zero size test case.

## Tests

New test for the compilation error in `stan/math/rev/mat/fun/gp_matern52_cov_test.cpp` and zero size test case in `stan/math/prim/mat/fun/gp_matern52_cov_test.cpp`.

## Side Effects

More tests

## Checklist

- [x] Math issue #1175

- [x] Copyright holder: 2019 Andre Zapico

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by syclik** [comment]
I left a comment on the #1175. I don't quite know what I'm looking at. 

Can you update the issue and the PR?
- What's the bug?
- What is this fixing? 
- Can you write a test case that fails without this patch? (without having to go all the way to Stan to do it, if possible?)

**Comment by drezap** [comment]
@syclik 

If you clone `stan-dev/stan`, you can run `./runTests.py src/test/integration/compile_models_test.cpp`, and the model file `gp_regression_test.stan` will fail compilation for this file.

> Can you write a test case that fails without this patch?

Sure

Can you update the issue and the PR?

sure

**Comment by drezap** [comment]
See updated comments

**Comment by drezap** [comment]
Hey - I'm wondering why Jenkins hasn't run on this yet? And regarding the review, this has all the changes we had discussed plus a zero size check. Ready for review.

**Pull request merged**
