### PR TITLE
Var value normal id glm

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Changes GPU implementation `normal_id_glm_lpdf` to accept `var_value` inputs, allowing diferentiation of `x` and `y`.
New interface still requires `x` and `beta` to be `matrix_cl`s. All other arguments can be either `matrix_cl`s or scalars. (Anything that can be `matrix_cl` can also be `var_value<matrix_cl>`.)

This includs a number of smaller changes:
- Added support for `matrix_cl` to various functions and metaprograms: `is_constant`, `size`, `sum`, `arena_t` (returning a class derived from `matrix_cl` and `chainable_alloc`), `operands_and_partials`, `to_arena`, `dims`
- Reworked `is_matrix_cl` to also return `true` for classes derived from `matrix_cl`
- Some kernel generator expressions now also accept scalars (checks, colwise reductions) and references to scalars (`operator*`)
- A number of files now only include headers they need instead of more general ones
- `elt_divide` now also accepts two scalar arguments
- bugfixed `is_stan_scalar` to return `false` for `var_value<matrix>`
- replaced `+=` in precomputed_gradients with `=` and `+` to make it work with `matrix_cl`
- added `.rows()` and `.cols()` to `var_value` 
- `is_matrix_cl` is moved to prim/meta

## Tests
Modified the tests to test the new interface of `normal_id_glm_lpdf`.

## Side Effects
Interface of GPU `normal_id_glm_lpdf` is completly changed - previous signatures (accepting EIgen types and std vectors) are not accepted anymore.

## Release notes
GPU implementation `normal_id_glm_lpdf` can also be used when derivatives of `x` or `y` are needed.

## Checklist

- [x] Math issue #2013

- [x] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
Some discussion is on #2015.

**Comment by t4c1** [comment]
This force push is fixing my error as I pushed last commit to wrong branch.

**Review by rok-cesnovar — DISMISSED** [review]
The base PR and the subsequent PRs to this branch were all approved independently so we can also approve this.

**Comment by bbbales2** [comment]
Is there any reason this isn't merged?

**Comment by rok-cesnovar** [comment]
Yes, its waiting for my stanc3 coresponding PR that should be opened tomorrow. It would not break any tests if we merged this, but we decided to merge both together anyways.

**Review by rok-cesnovar — APPROVED** [review]

**Pull request merged**
