### PR TITLE
Inline functions

### PR DESCRIPTION
**Pull request by rgiordan**
#### Submisison Checklist

- [X] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
Fixes https://github.com/stan-dev/math/issues/311

#### Intended Effect:
Inline functions allowing stan headers to be included in multiple translation units.

#### How to Verify:
See example in https://github.com/stan-dev/math/issues/311

#### Side Effects:
Perhaps slightly longer compile times, though in my limited testing I didn't notice a difference.

#### Documentation:
None.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
UC Berkeley

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, ok to test.

**Comment by betanalpha** [comment]
Just to be careful to confirm — does Berkeley grant
permission to release contributions under BSD3? Or
have your received an exception?

We just have to be careful as universities are starting
to get more strict about these things!

**Comment by rgiordan** [comment]
I actually have no idea.  Formally, I am a "visiting scholar" at Columbia
this summer, though I am paid by a Berkeley grant.  Will that do?  If not,
I can try to find out.



On Thu, Jul 7, 2016 at 4:52 PM, Michael Betancourt <notifications@github.com
> wrote:

> Just to be careful to confirm — does Berkeley grant
> permission to release contributions under BSD3? Or
> have your received an exception?
>
> We just have to be careful as universities are starting
> to get more strict about these things!
>

**Comment by betanalpha** [comment]
I think it would be prudent — any relevant issues on the Columbia side
would be in any documents you signed.  We had to go through significant
red tape to get the open source okay from Columbia and I don’t think it’s
blanket to any contribution to Stan, but perhaps someone can comment?
No idea if it’s any easier from the Berkeley side.

**Comment by rgiordan** [comment]
Fair enough.  I've sent an email to the Berkeley research group that I'm
part of.  Hopefully someone has some experience with this.

On Thu, Jul 7, 2016 at 5:00 PM, Michael Betancourt <notifications@github.com
> wrote:

> I think it would be prudent — any relevant issues on the Columbia side
> would be in any documents you signed. We had to go through significant
> red tape to get the open source okay from Columbia and I don’t think it’s
> blanket to any contribution to Stan, but perhaps someone can comment?
> No idea if it’s any easier from the Berkeley side.
>
>

**Comment by bob-carpenter** [comment]
Yes, it's blanket to any contribution to Stan now and in the future.

Berkeley's very liberal about allowing open-source.  They're the
"B" in "BSD", after all.  They're also the ones behind AmpLab.

Most universities seem to be OK with open source, though they
often ask you to verify.  Columbia Tech Ventures in the end was surprised
we were asking them because they say they always allow researchers to release
things open source if that's what they want to do.  We could've saved
ourselves a lot of time had we gone to the top earlier.

And no university is going to think it needs to preserve rights to
patches to other software---there's nothing for them to gain from it.
It's the money trail, as usual.

- Bob

**Comment by rgiordan** [comment]
A couple students provided other examples of Berkeley students contributing
to high-profile open source projects (Theano and Apache Spark) as grad
students.

**Comment by betanalpha** [comment]
Sure, I would think the B in BSD would be relevant and that
most universities would be okay with open source, but nothing
seems to be set in stone and if we’re trying to be careful moving
forward we might as well check where we can, no?

**Comment by rgiordan** [comment]
@betanalpha , are you satisfied with the fact that Berkeley students have been contributing to open source projects for a while?  Would you like me to cite specific examples?  Or do you want to hear something from an official administrative body?

**Comment by betanalpha** [comment]
If Bob is fine then I’m fine, although anecdotal precedent seems tricky.

**Comment by syclik** [comment]
I'm ok with the IP issues here. I can't see anyone having a problem with ~20 additions of the inline keyword.

**Comment by syclik** [comment]
There were just a couple things I wanted to see:
- [ ] timing of compilation
- [ ] performance timing

Both can be informal and hopefully I'll get to it soon. We just want to make sure it doesn't add a lot of extra time to compilation or any time to performance.

**Comment by rgiordan** [comment]
That makes sense.  LMK if I can help.  I only have one stan model sitting around (it's the one [here](https://github.com/rgiordan/MicrocreditLRVB/tree/master/inst/stan)), and it didn't make a noticeable difference.  Hopefully you have some ideas about what would be a more meaningful test suite.

**Comment by syclik** [comment]
Thanks. This is all ad hoc testing for the moment. We really need to put together a better testing suite.

(I'm always hoping I run into some literature and implementations on how to do this reliably, but haven't found it.)

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
I verified that this patch doesn't increase the build time or compilation time, at least to anything we can measure reliably.

I ran each of these things 100 times:
1. Compile a model with one of the inlined functions (`example-models/basic_estimators/normal_mixture.stan`)
2. Compile a model without one of the inlined functions (`example-models/bugs_examples/vol1/blocker/blocker.stan`)
3. Run a model with one of the inlined functions for 10 different seeds
4. Run a model without one of the inlined functions for 10 different seeds.

I'm looking at the results and half the tasks are faster and half are slower, but all within a couple percent or less, so I don't think I'm seeing anything systematic.

**Comment by syclik** [comment]
I'll merge this once the tests pass.

**Comment by rgiordan** [comment]
Thanks, Daniel!

**Pull request merged**
