### PR TITLE
[WIP] Closures prototype

### PR DESCRIPTION
**Pull request by nhuurre**
## Summary

See the desing-doc https://github.com/stan-dev/design-docs/pull/6 and the forum discussion https://discourse.mc-stan.org/t/closures-discussion/14932/

A proptotype autodiff interface for closures.

This builds on the variadic ODEs https://github.com/stan-dev/math/pull/1641

## Checklist

- [ ] Math issue: ???

- [X] Copyright holder: Niko Huurre

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@nhuurre variadic ODEs are in, does this have blockers still?

**Comment by bbbales2** [comment]
@nhuurre Hey Niko, apologies it took me so long to get back to this, but is now a good time to work on this? It would be cool to get closures in for the next release (3 months from now).

**Comment by bbbales2** [comment]
@SteveBronder Oh yeah I was one of the blockers lol.

**Comment by nhuurre** [comment]
Superseded by #2094

**Pull request closed without merging**
