### PR TITLE
Feature/issue sundials 60

### PR DESCRIPTION
**Pull request by wds15**
## Summary

Upgrades Sundials to 6.0.0

This required to introduce the sundials context concept which associates sundials solver ressources to a thread if one wants to. As we do not manage sundials ressources per thread this feature is not used on a per thread basis, but rather a as called basis.

A few functions had to be renamed as some became deprecated.

## Tests

No new tests.

## Side Effects

No.

## Release notes

Upgrade Sundials to 6.0.0

## Checklist

- [X] Math issue #2628

- [X] Copyright holder: Sebastian Weber

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

**Comment by hsbadr** [comment]
@wds15 Can you make the header includes relative? I get the following error with this PR when building RStan:
```c++
cvodes/cvodes_impl.h:23:10: fatal error: sundials_context_impl.h: No such file or directory
   23 | #include "sundials_context_impl.h"
```
This is due to the headers in `src/sundials/` that are included from another subdirectory `src/*/` (e.g., `src/cvodes/` and `src/kinsol/`). Would it make sense to change `#include "sundials_context_impl.h"` in those subdirectories to `#include "../sundials/sundials_context_impl.h"`?

**Comment by wds15** [comment]
@serban-nicusor-toptal could you take a look at the failing upstream cmdstan tests (pipeline run 2947). I don't see an error which makes sense to me and it looks like a system error?

**Comment by serban-nicusor-toptal** [comment]
Checking

**Comment by hsbadr** [comment]
@wds15 Here's the patch that fixes it for me:
```diff
diff --git a/lib/sundials_6.0.0/src/cvodes/cvodes_impl.h b/lib/sundials_6.0.0/src/cvodes/cvodes_impl.h
index a64c4f0f82..638df9f042 100644
--- a/lib/sundials_6.0.0/src/cvodes/cvodes_impl.h
+++ b/lib/sundials_6.0.0/src/cvodes/cvodes_impl.h
@@ -20,7 +20,7 @@
 #include <stdarg.h>

 #include "cvodes/cvodes.h"
-#include "sundials_context_impl.h"
+#include "../sundials/sundials_context_impl.h"

 #ifdef __cplusplus  /* wrapper to enable C++ usage */
 extern "C" {
diff --git a/lib/sundials_6.0.0/src/idas/idas_impl.h b/lib/sundials_6.0.0/src/idas/idas_impl.h
index 8454b00c7d..870d76f29a 100644
--- a/lib/sundials_6.0.0/src/idas/idas_impl.h
+++ b/lib/sundials_6.0.0/src/idas/idas_impl.h
@@ -21,7 +21,7 @@
 #include <stdarg.h>

 #include "idas/idas.h"
-#include "sundials_context_impl.h"
+#include "../sundials/sundials_context_impl.h"

 #ifdef __cplusplus  /* wrapper to enable C++ usage */
 extern "C" {
diff --git a/lib/sundials_6.0.0/src/kinsol/kinsol_impl.h b/lib/sundials_6.0.0/src/kinsol/kinsol_impl.h
index 60043afc9f..784a4c5dc4 100644
--- a/lib/sundials_6.0.0/src/kinsol/kinsol_impl.h
+++ b/lib/sundials_6.0.0/src/kinsol/kinsol_impl.h
@@ -23,8 +23,8 @@
 #include <stdarg.h>

 #include <kinsol/kinsol.h>
-#include "sundials_context_impl.h"
-#include "sundials_iterative_impl.h"
+#include "../sundials/sundials_context_impl.h"
+#include "../sundials/sundials_iterative_impl.h"

 #ifdef __cplusplus  /* wrapper to enable C++ usage */
 extern "C" {
```

**Comment by wds15** [comment]
@hsbadr Thanks! But I really would not want to touch the Sundials sources. I have instead updated the Makefiles to include the directory with the *sundials_context_impl.h* file. The error on the Jenkins machine at least looks to me as if the Jenkins is broken... which means that I actually would expect everything to work...what did not work for you, @hsbadr, before your patch?

**Comment by hsbadr** [comment]
>what did not work for you, @hsbadr, before your patch?

Compiling `libStanHeaders` fails:
```
cvodes/cvodes_impl.h:23:10: fatal error: sundials_context_impl.h: No such file or directory
   23 | #include "sundials_context_impl.h"
```
The compiler expects to find `sundials_context_impl.h` in `src/cvodes` and `src/kinsol`.

Anyway, I can easily fix it in RStan by copying a couple header files from `src/sundials`.

**Comment by wds15** [comment]
@hsbadr I see... that's why I have changed the makefiles to reflect this necessary change:  see https://github.com/stan-dev/math/blob/9d120dc16aa6af4c4e929ec29ee881cdefec8b21/make/compiler_flags#L109

This is a change which should be also needed to compile StanHeaders, indeed.

... still... the Jenkins seems to me to be broken?

**Comment by rok-cesnovar** [comment]
Nic restarted the tests: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2629/5/pipeline

should be green soon.

**Comment by rok-cesnovar** [comment]
I am afraid the CmdStan test error looks legit and is not a Jenkins problem. Have a look here: https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/downstream_tests/2948/pipeline

I am seeing 

```
stan/lib/stan_math/lib/sundials_6.0.0/src/sundials/sundials_profiler.c:108:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]

  clock_gettime(CLOCK_MONOTONIC, entry->tic);

  ^

/usr/local/opt/llvm@6/bin/clang++ -pipe   -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.0.0/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.0.0/src/sunlinsol/dense/sunlinsol_dense.c -o stan/lib/stan_math/lib/sundials_6.0.0/src/sunlinsol/dense/sunlinsol_dense.o

stan/lib/stan_math/lib/sundials_6.0.0/src/sundials/sundials_profiler.c:108:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  clock_gettime(CLOCK_MONOTONIC, entry->tic);
                ^

stan/lib/stan_math/lib/sundials_6.0.0/src/sundials/sundials_profiler.c:118:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
  clock_gettime(CLOCK_MONOTONIC, entry->toc);
  ^
stan/lib/stan_math/lib/sundials_6.0.0/src/sundials/sundials_profiler.c:118:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  clock_gettime(CLOCK_MONOTONIC, entry->toc);
                ^
2 warnings and 2 errors generated.
```

**Comment by wds15** [comment]
Thanks…I will follow this up…it’s odd that this is in the sundials sources as it looks.

**Comment by hsbadr** [comment]
> error: use of undeclared identifier 'CLOCK_MONOTONIC'

This looks like an issue with `_POSIX_C_SOURCE` definition when including `<time.h>`.

In `sundials/sundials_profiler.c`, if MPI is disabled:
```c
#if SUNDIALS_MPI_ENABLED
#include <sundials/sundials_mpi_types.h>
#include <mpi.h>
#elif defined(SUNDIALS_HAVE_POSIX_TIMERS)
/* Minimum POSIX version needed for struct timespec and clock_monotonic */
#if !defined(_POSIX_C_SOURCE) || (_POSIX_C_SOURCE < 199309L)
#define _POSIX_C_SOURCE 199309L
#endif
#include <time.h>
#include <stddef.h>
#include <unistd.h>
#else
#error Either MPI_Wtime or clock_getttime is required but neither were found
#endif
```

So, @wds15, I think adding `-D_POSIX_C_SOURCE=199309L` to the compiler flags may fix it.

**Comment by wds15** [comment]
let's try to drop the profiler stuff from the build...I don't think we need them.

**Comment by wds15** [comment]
Ready for review. @hsbadr ?

**Comment by hsbadr** [comment]
> Ready for review. @hsbadr ?

LGTM. The only thing that I'd reconsider is to not exclude the new profiling (`sundials_profiler.c`). The `CLOCK_MONOTONIC` error is system dependent; CmdStan was built successfully on my system. We could explicitly define `_POSIX_C_SOURCE` (or `CLOCK_MONOTONIC`, if not defined), unless we really don't need SUNDIALS profiling.

Also, my review of this is very limited. So, I'd suggest that someone else review it: @rok-cesnovar @SteveBronder?

**Comment by wds15** [comment]
I would suggest to deal with building the profiling stuff once we start using it. For now it’s not needed and actually increases the build time at no gain for Stan users.

**Review by rok-cesnovar — APPROVED** [review]
We are not using the sundials profiler at this time, so no sense in building it. If a use-case comes up, we will deal with the issues at that point. I would avoid additional compiler flags if we don't have a use case.

**Pull request merged**
