### PR TITLE
[WIP] CMake

### PR DESCRIPTION
**Pull request by seantalts**
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by danluu** [comment]
It looks like getting this clean in CI is blocked on #806 / #810. For reasons that I haven't looked into, adding `-O3` doesn't seem to fix the issue when it's built in this way even though it happens to fix the issue when it's built using the `makefile`. I don't think this is necessarily bad since there's no particular guarantee that the pre-fix code should work.

**Comment by danluu** [comment]
After the latest fixes, all "actual" tests pass in CI and the only failure is because the `cmake` build puts the xml output in a different location from the `makefile` build. That should be pretty easy to fix.

If you use the built-in CMakeLists.txt testing capability there are two test failures because there are two tests that open a file and read from a relative path, and the build "expects" to run in directory, so the relative path needs a `..` to back up to the top level directory. Tests pass when using `runTests.py`.

I think the one thing that's left to do here is to add header files to `CMakeLists.txt`, so that editors "know" about header files in the way they're supposed to, but that should also be pretty easy and not having that done shouldn't block people from being able to use the current `cmake` branch.

**Comment by seantalts** [comment]
If this were to be feature-complete with the existing makefiles, we'd also need to generate the distribution tests (see generateTests in runTest.py, which calls `make generate-tests`).

**Comment by seantalts** [comment]
What flags is this building with? I think there used to be a thing to set it to O3, but now I can't find it. I was hoping to compare compile times to the make version.

**Comment by seantalts** [comment]
I think we should be testing that in this PR, then. I probably won't have time to do much towards this project in the next couple of weeks, though.

**Pull request closed without merging**
