### PR TITLE
Update to use the new array[] syntax for signatures.

### PR DESCRIPTION
**Pull request by seantalts**
## Summary

Updates the expression tests to use the new `array[]` syntax. Needs https://github.com/stan-dev/stanc3/pull/780 to be merged first.

## Tests

This PR updates tests; no new tests were added.

## Side Effects

None.

## Checklist

- [x] Math issue #(issue number)

- [x] Copyright holder: Sean Talts

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by seantalts** [comment]
Hmm, this doesn't work for:
`vector algebra_solver((vector, vector, data array[] real, data array[] int) => vector,
                        vector, vector, array[] real, array[] int)`

I dislike that the internal function signature has a different form than the external one... Maybe we should change them both to use this `=>` arrow notation?

**Comment by seantalts** [comment]
PS these tests don't necessarily need to build stanc, they could just use the file checked into test/integration/signatures/stan_math_sigs.expected. But maybe building and generating is more robust?

**Comment by rok-cesnovar** [comment]
Ok, freeze over and we can get this in now.

> PS these tests don't necessarily need to build stanc, they could just use the file checked into test/integration/signatures/stan_math_sigs.expected. But maybe building and generating is more robust?

Yes, and simpler to test newer functions with local stanc3 when you add them.

@t4c1 can you take a look at this whenever you have time? Tests will not pass until we merge the stanc3 PR, but I will handle persuading Jenkins to give the green light.

**Review by t4c1 — APPROVED** [review]

**Comment by seantalts** [comment]
Woops, really appreciate you guys fixing this up, thank you! I thought I ran it all locally but must have missed some in the output or something.

**Pull request merged**
