### PR TITLE
Generalize multi gp

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Generalizes multi_gp functions to accept Eigen expressions.

## Tests

Tested using expression testing framework.

## Side Effects

None.

## Release notes
Generalized multi_gp functions to accept Eigen expressions.

## Checklist

- [x] Math issue #1470 

- [x] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by wds15** [comment]
It‘s really impressive to see these many „generalize xy“ PRs... is there somewhere a list showing how many are still outstanding? Have there been some performance tests which show the utility of the monster effort? This is not to question what is happening at all... I am just curious.

**Comment by t4c1** [comment]
The reason for so many at once is that I implemented many before, but they were waiting for testing to be implemented before I started opening PRs. I still have a few done that just need PRs.

> is there somewhere a list showing how many are still outstanding?

Kinda. in  `test/expressions/stan_math_sigs_exceptions.expected` is the list of function signatures that are still not tested using expression testing framework.

> Have there been some performance tests which show the utility of the monster effort?

I ran a benchmarks on some of these functions locally, but did not post them anywhere. In general some functions are significantly faster, some are about the same. Regardless of speedups of the functions themselves, this is needed before we can have functions return expressions, which will significantly speedup some models.

**Comment by t4c1** [comment]
I believe we can contain this in math - no changes to compiler will be necessary.

**Comment by bbbales2** [comment]
> Have there been some performance tests which show the utility of the monster effort?

I'm adding benchmarks as part of https://github.com/bbbales2/perf-math/pull/1

You can look through them over here: https://bbbales2.shinyapps.io/math-shiny-perf/

I need to do some work to automate them and record release numbers (so it's clear what code is being benchmarked) and make it easier to browse and find problems.

There have been some good changes (see `mdivide_left_matrix_vector`) and some not so good ones (see `mdivide_left_matrix_matrix`).

**Review by bbbales2 — APPROVED** [review]
Good

**Comment by wds15** [comment]
Cool graphs! What’s up with the variance?

**Comment by bbbales2** [comment]
> What’s up with the variance?

Understated as far as I know lol. Did you find something particularly weird?

Talking to Rok and Steve about formalizing these things if you're interested this: https://github.com/bbbales2/perf-math/pull/1#issuecomment-691246773

**Pull request merged**
