### PR TITLE
Roll back integrate 1d patch

### PR DESCRIPTION
**Pull request by bbbales2**
## Summary

Once #2341 is in we no longer need this integrate_1d patch

## Release notes

- Boost upgrade fixes problem with integrate_1d so custom integrate_1d patch removed

## Checklist

- [x] Math issue #2193

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
What I am wondering here is for the sake of rstan do we want to do: 

```
if Boost < 1.75
  patch
else
 no patch
```

This does introduce those silly ifdefs but people struggling with integrate_1d is also pretty real.

**Comment by bbbales2** [comment]
Oh oh ow so since Rstan uses Boost not from here but the R boost headers, we need to support both? Can rstan require BH 1.75?

**Comment by rok-cesnovar** [comment]
> Can rstan require BH 1.75?

Oh yes it can. ignore me. That should be done. 

Will ping Ben G once we make this PR show the actual changes.

this should be added to StanHeader 2.26 as Boost is already at 1.75 on CRAN now.

**Comment by rok-cesnovar** [comment]
@bgoodri you need this patch in the next release of StanHeaders as well as BH is at 1.75.0 already.

**Review by rok-cesnovar — APPROVED** [review]
Boost 1.75.0 is in so this is good to go.

**Comment by bgoodri** [comment]
I got it. No problem.

**Pull request merged**
