### PR TITLE
Added vectorized rngs and tests for distributions in chapter 55-58 of manual

### PR DESCRIPTION
**Pull request by bbbales2**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This pull req. takes over for https://github.com/stan-dev/math/pull/685. I had trouble getting all the Stan Math updates merged into that branch cleanly vs. just cherry-picking the _rng changes to a new branch.

Notes to reviewer:

1. This includes a fix for #684! I don't think the scaled inverse chi squared random number generator was correct before.

2. pareto_type_2 does not have quantiles tests

3. The wiener pdf doesn't have rngs at all

#### Intended Effect:

Add a bunch of random number generators

#### How to Verify:

```
./runTests.py test/unit/math/prim/scal/prob/
./runTests.py test/unit/math/prim/mat/prob/
```

#### Side Effects:

Hopefully none

#### Documentation:

In the Doxygen

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of California, Santa Barbara

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I cleaned up the merge conflicts.  That online editor is pretty slick!

**Comment by smwindecker** [comment]
Hi there, is the vector-compatible _rng functionality available somewhere yet? Using rstan, but looks like the newest install is still before this merge.

(by the way, love this addition!)

**Comment by seantalts** [comment]
It will be in 2.18, not sure if there's an easy way to get access to it before that. We were thinking about releasing soon.

**Comment by smwindecker** [comment]
how soon? =) 

all good, I guess I will have to for loop it!

**Comment by seantalts** [comment]
Unclear - aiming for this week, but we might wait for MPI to get in.

**Comment by bbbales2** [comment]
Eek, @seantalts @smwindecker this is only the Math library stuff -- the linkage for the actual Stan language isn't in place yet (and won't be by this Thursday ^^).

**Comment by smwindecker** [comment]
I've managed without for now so no pressure for Thursday! But definitely putting in my support for it whenever it can be done =)

**Comment by bbbales2** [comment]
Oooh, don't wait for vector rngs on 2.18. I've been weirdly busy with stuff this quarter. Not gonna get em' done in a short time.

**Pull request merged**
