### PR TITLE
Bugfix/issue 603 ubuntu clang failure+test failure

### PR DESCRIPTION
**Pull request by sakrejda**
#### Submission Checklist

- [X] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below
 test/unit/math/prim/scal/err/check_positive_test` work again.

#### Summary:
make/local include moves down in makefile, minor changes to test files
to explicitely create `nan` values.

#### Intended Effect:
make it possible to overwrite build variables from make/local, make `
`

#### How to Verify:
tests should still pass

#### Side Effects:
`test/unit/math/prim/scal/err/check_positive_test` was passing previously regardless of 
input, now it's doing its job.

#### Documentation:
NA

#### Copyright and Licensing

Krzysztof Sakrejda

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by sakrejda** [comment]
@seantalts so... this build is failing on Jenkins because it's trying to pass `-stdlib=libc++` to `g++`... does Jenkins have something funky in `make/local`? I can't check where this comes from, I did check I didn't add it myself (in the file diff there's nothing I can see triggering this except for changing the include order in the makefile).

```
g++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.64.0 -isystem lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe  -c -O0 -include stan/math/rev/mat/functor/integrate_ode_bdf.hpp test/dummy.cpp -o /dev/null
g++: error: unrecognized command line option ‘-stdlib=libc++’
```

**Comment by seantalts** [comment]
Nothing funky in make/local - the workspaces are wiped between builds and you can see in the job config what gets echo'd to make/local. This is because make/local sets the C compiler (with "CC=g++") which `detect_cc` uses to determine which compiler is being used.

**Comment by sakrejda** [comment]
I didn't realize how much touchy order dependence there was.  I'll just do a local hack for now and do this PR for the test fix.

**Comment by sakrejda** [comment]
Not quite right, closing.

**Pull request closed without merging**
