### PR TITLE
fixes #698, renamed multi-caps tparam in algebra system

### LINKED ISSUE #698: Remove all caps typenames for Solaris compilation
#### Summary:

Solaris fails to compile Stan with all-caps type names.

#### Description:

From @bgoodri on http://discourse.mc-stan.org/t/stan-broken-on-solaris-need-fix-today/2826:

Stan models don't compile on Solaris 

It has something to do with using all capital letters for a typename. For more detail, see

https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/bayesplot-00check.html
Describe the issue as clearly as possible.

#### Current Output:

```
> 
> stan/math/rev/mat/functor/algebra_system.hpp:97:24: error: expected nested-name-specifier before numeric constant
>      template <typename FS, typename F, typename T0, typename T1>
>                         ^
> /home/ripley/R/Lib32/StanHeaders/include/stan/math/rev/mat/functor/algebra_system.hpp:97:24: error: expected ‘>’ before numeric constant
> /home/ripley/R/Lib32/StanHeaders/include/stan/math/rev/mat/functor/algebra_system.hpp:100:7: error: expected unqualified-id before numeric constant
>        FS fs_;
>        ^
```

#### Expected Output:

Compiler not complaining.

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py -j4 test/unit/math/rev/mat/functor/algebra_solver_test.cpp 
`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Renamed template parameter `TS` to `S`.

#### Intended Effect:

Allow Solaris compilation.

#### How to Verify:

Unit tests.

#### Side Effects:

no

#### Documentation:

n/a

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
Is this fix likely to work without changing anything in Stan Library? Also, do we have any other all capital problems, something like

```
git grep -E "typename [[:upper:]]{2}" stan/math
```

**Comment by bob-carpenter** [comment]
The template parameters are just local variable names, so the name doesn't matter (except apparently to Solaris).

Thanks for the grep ju ju.  I'll go back in and fix the rest.  I may not have computer power to run tests locally befor I have to leave tonight, but I'll push.

```
stan/math/prim/scal/fun/lb_constrain.hpp:template <typename T, typename TL>
stan/math/prim/scal/fun/lb_constrain.hpp:template <typename T, typename TL>
stan/math/prim/scal/fun/lb_free.hpp:template <typename T, typename TL>
stan/math/prim/scal/fun/lub_constrain.hpp:template <typename T, typename TL, typename TU>
stan/math/prim/scal/fun/lub_constrain.hpp:template <typename T, typename TL, typename TU>
stan/math/prim/scal/fun/lub_free.hpp:template <typename T, typename TL, typename TU>
stan/math/prim/scal/fun/ub_constrain.hpp:template <typename T, typename TU>
stan/math/prim/scal/fun/ub_constrain.hpp:template <typename T, typename TU>
stan/math/prim/scal/fun/ub_free.hpp:template <typename T, typename TU>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int RA, int CA, typename TB, int CB>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int CA, typename TB>
stan/math/rev/mat/fun/multiply.hpp:template <int RA, int CA, typename TB, int CB>
stan/math/rev/mat/fun/multiply.hpp:template <int CA, typename TB>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int RA, int CA, int CB>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int CA>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int RA, int CA, typename TB, int CB>
stan/math/rev/mat/fun/multiply.hpp:template <typename TA, int CA, typename TB>
stan/math/rev/mat/fun/quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB>
stan/math/rev/mat/fun/quad_form_sym.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/quad_form_sym.hpp:template <typename TA, int RA, int CA, typename TB, int RB>
stan/math/rev/mat/fun/trace_gen_quad_form.hpp:template <typename TD, int RD, int CD, typename TA, int RA, int CA, typena
stan/math/rev/mat/fun/trace_gen_quad_form.hpp:template <typename TD, int RD, int CD, typename TA, int RA, int CA, typena
stan/math/rev/mat/fun/trace_gen_quad_form.hpp:template <typename TD, int RD, int CD, typename TA, int RA, int CA, typena
stan/math/rev/mat/fun/trace_quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/trace_quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/fun/trace_quad_form.hpp:template <typename TA, int RA, int CA, typename TB, int RB, int CB>
stan/math/rev/mat/functor/algebra_solver.hpp:template <typename FS, typename F, typename T, typename FX>
```

**Comment by bob-carpenter** [comment]
OK, just fixed all those and ran local unit tests for the files I changed.

**Comment by bob-carpenter** [comment]
@bgoodri  Passed tests, so feel free to review and merge.

**Comment by bob-carpenter** [comment]
What's this new pr-merge job?  It's failing due to some kind of I/O problem.

**Comment by bob-carpenter** [comment]
@seantalts  How do I restart the pr-merge Jenkins job?  It looks like some kind of I/O flakiness.  This passed before I updated the readme, but I'm not sure that pr-merge thing ever ran the first time around.

**Comment by seantalts** [comment]
Jenkins, retest this please. 

I'm trying to finally switch us over to pipelines in the Math repo but I think I have a couple of final bugs to work out. For now we can use the legacy stuff, which I just re-enabled.

**Comment by bob-carpenter** [comment]
Thanks, @seantalts.  I have the upstream PR resubmitted for this, at which point the PR should work.  I'll kick off testing again then.

**Comment by seantalts** [comment]
At this point the "default" Jenkins build passed, and the "pr-merge" thing will continue to be an "x" until I fix the new Pipeline builds (hopefully today). But you can safely ignore that x since the other two passed and I know what's wrong with that one.

**Comment by bob-carpenter** [comment]
@bgoodri --- Would you mind reviewing this if it passes?  It's just the capitalized types for the Solaris (I think) builds on R.

**Comment by bob-carpenter** [comment]
Thanks, @bgoodri.

**Pull request merged**
