### PR TITLE
Bugfix - OpenCL with Integrated GPU

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

Calling OpenCL Math code with integrated graphics results in a buffer allocation error - due to the use of shared memory between the CPU and GPU.  To resolve this, the data needs an additional copy to be made.

This PR adds the use of `make/local` flag: `INTEGRATED_OPENCL=true` to indicate that integrated graphics is being used and that this additional copy should be made

## Tests

N/A

## Side Effects

N/A

## Release notes

Fixed running OpenCL code with integrated GPUs

## Checklist

- [x] Math issue #2789

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thanks a ton!

**Comment by SteveBronder** [comment]
I think you may need to do something similar with `flags |= CL_MEM_ALLOC_HOST_PTR;` on line 293 as well

**Comment by andrjohns** [comment]
> I think you may need to do something similar with `flags |= CL_MEM_ALLOC_HOST_PTR;` on line 293 as well

So far it looks like only the `CL_MEM_USE_HOST_PTR` usage needed to change, since all the tests passed for me with that

**Comment by andrjohns** [comment]
@serban-nicusor-toptal Can we trigger the buildbot to update the submodules across the Stan and CmdStan repos? Then I can add some instructions on the forum for a user to access the fixed code

**Comment by rok-cesnovar** [comment]
The submodules were not updated right now because the merge to develop tests are failing. I just noticed this. They started failing after https://github.com/stan-dev/math/pull/2546. The difference between the "merge to develop" tests and the PR tests is that these also run with row_vectors. The first failed run: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/develop/77/pipeline

**Comment by andrjohns** [comment]
> The submodules were not updated right now because the merge to develop tests are failing. I just noticed this. They started failing after #2546. The difference between the "merge to develop" tests and the PR tests is that these also run with row_vectors. The first failed run: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/develop/77/pipeline

Ah that's concerning! I'll look into that now

**Comment by andrjohns** [comment]
It looks like the failures are because `pow(Eigen, Eigen)` now always returns an `Eigen::Matrix` type, even if `Eigen::Array` types [were passed in](https://github.com/stan-dev/math/blob/25a0fa1ed2c7064b79563566ac4b58920581aa7f/stan/math/rev/fun/pow.hpp#L125):
```cpp
  using val_type = decltype(as_array_or_scalar(value_of(base))
                                .pow(as_array_or_scalar(value_of(exponent)))
                                .matrix()
                                .eval());
  using ret_type = return_var_matrix_t<val_type, Mat1, Mat2>;
```
This then breaks code that was relying on elementwise multiplication of Eigen objects

The tests compile and pass if I update this to deduce whether to return a `Matrix` or `Array` type:
```cpp
  using expr_type = decltype(as_array_or_scalar(value_of(base))
                                .pow(as_array_or_scalar(value_of(exponent))));
  using val_type = std::conditional_t<
    math::disjunction<is_eigen_array<Mat1>, is_eigen_array<Mat2>>::value,
    decltype(std::declval<expr_type>().eval()),
    decltype(std::declval<expr_type>().matrix().eval())>;
  using ret_type = return_var_matrix_t<val_type, Mat1, Mat2>;
```

I'll open a new PR with the fix and temporarily enable the full distribution tests

**Comment by rok-cesnovar** [comment]
Fantastic! Thank you!

**Pull request merged**
