### PR TITLE
Vectorise inv_Phi calculations and optimise log-scale implementation

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR updates the calculations within the `inv_Phi` function to be on the log-scale and to use vectorised functions (instead of deeply nested multiply-adds).

This also results in an significantly simpler implementation for `std_normal_qf` function.

## Tests

N/A

## Side Effects

N/A

## Release notes

Improved speed of `inv_Phi` and `std_normal_qf` functions

## Checklist

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by spinkney — DISMISSED** [review]
Looks good! Do you have an idea about how much larger the range of values is when using this on the log scale?

**Comment by andrjohns** [comment]
> Looks good! Do you have an idea about how much larger the range of values is when using this on the log scale?

@spinkney I found that the additional `log`/`exp` calls were noticeably slowing down the `inv_Phi` function, so I've reduced the changes to only the `std_normal_log_qf` function.

I'm not whether the range of values would be much changed, but it should be significantly faster - since it reduces the ~14 `log_sum_exp` calls to only 2

**Review by SteveBronder — APPROVED** [review]
I think this looks good! @spinkney can you check the math on this as well?

**Comment by spinkney** [comment]
Looks good, thanks @andrjohns! Feel free to merge

**Pull request merged**
