### PR TITLE
Updated Github templates with stuff from the Stan Math meeting today

### PR DESCRIPTION
**Pull request by bbbales2**
It's somehow appropriate that this pull request governing what is a good pull request doesn't satisfy its own requirements. No Math issue, no tests, and I didn't check the tests in place pass either hahaha.

@roualdes if I messed up what you suggested for the Summary section, go ahead and add it. There's a way you can edit these files inline with Github which might be easier than a full clone pull/push.

I shortened and rearranged things quite aggressively. Hopefully it's okay. Can we move the checklist to the bottom though? And just say you need to fill it out? I think the pulls would look nicer if they started with a description of what was being fixed, rather than a checklist that's basically meant as a way to remind people to run all the tests and write docs. I felt like that was too big a change to make without asking though.

### CODE REVIEW

**Comment by syclik** [comment]
I haven't looked yet, but please move the checklist to the bottom if it
makes more sense. The justification for that sounds good -- making it look
more natural + nicer.

**Comment by roualdes** [comment]
This looks good.  Checklist at bottom sounds good to me.  Thanks @bbbales2!

**Comment by syclik** [comment]
Yeah. Looks great! I agree: checklist at the bottom would be good.

**Comment by bbbales2** [comment]
It looks like this is building haha. I'm happy with it. Merge when you want to @syclik

**Pull request merged**
