### PR TITLE
Bugfix/1669 multiply dim size 0

### PR DESCRIPTION
**Pull request by mitzimorris**
## Summary

Removed restriction on matrix multiply requiring all dimensions to be positive - instead going with Eigen requirement that all dimensions are nonnegative.

## Tests

Existing unit tests for dimensions size 0 changed so that size 0 are OK.

Cannot create test for matrices with negative dimension size because Eigen doesn't allow such objects to be created.

## Side Effects

none.

## Checklist

- [x] Math issue #(issue number) 1669

- [x] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses: Columbia University

      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by mcol** [comment]
This is failing for `mdivide_left_spd` because if `check_multiplicable` doesn't throw anymore on size 0 input, then we get straight into Eigen code, so we'll need an explicit check for size 0 and return early. I think `mdivide_left_tri` has the same problem, and probably a few more headers. If you need help with this let me know.

**Comment by mitzimorris** [comment]
> This is failing for `mdivide_left_spd` because if `check_multiplicable` doesn't throw anymore on size 0 input, then we get straight into Eigen code, so we'll need an explicit check for size 0 and return early. I think `mdivide_left_tri` has the same problem, and probably a few more headers. If you need help with this let me know.

looks like there's 40 files that call `check_multiplicable`.
```
stan/math/fwd/fun/trace_quad_form.hpp
stan/math/fwd/fun/mdivide_left_tri_low.hpp
stan/math/fwd/fun/mdivide_left_ldlt.hpp
stan/math/fwd/fun/multiply.hpp
stan/math/fwd/fun/quad_form_sym.hpp
stan/math/fwd/fun/mdivide_left.hpp
stan/math/fwd/fun/mdivide_right_tri_low.hpp
stan/math/fwd/fun/mdivide_right.hpp
stan/math/rev/fun/trace_quad_form.hpp
stan/math/rev/fun/quad_form.hpp
stan/math/rev/fun/mdivide_left_spd.hpp
stan/math/rev/fun/mdivide_left_ldlt.hpp
stan/math/rev/fun/multiply.hpp
stan/math/rev/fun/mdivide_left_tri.hpp
stan/math/rev/fun/trace_gen_quad_form.hpp
stan/math/rev/fun/trace_inv_quad_form_ldlt.hpp
stan/math/rev/fun/quad_form_sym.hpp
stan/math/rev/fun/mdivide_left.hpp
stan/math/rev/fun/trace_gen_inv_quad_form_ldlt.hpp
stan/math/rev/fun/matrix_exp_multiply.hpp
stan/math/opencl/prim/mdivide_left_tri_low.hpp
stan/math/opencl/prim/mdivide_right_tri_low.hpp
stan/math/prim/fun/trace_quad_form.hpp
stan/math/prim/fun/quad_form.hpp
stan/math/prim/fun/mdivide_left_spd.hpp
stan/math/prim/fun/mdivide_left_tri_low.hpp
stan/math/prim/fun/mdivide_left_ldlt.hpp
stan/math/prim/fun/multiply.hpp
stan/math/prim/fun/mdivide_left_tri.hpp
stan/math/prim/fun/trace_gen_quad_form.hpp
stan/math/prim/fun/mdivide_right_ldlt.hpp
stan/math/prim/fun/trace_inv_quad_form_ldlt.hpp
stan/math/prim/fun/quad_form_sym.hpp
stan/math/prim/fun/mdivide_right_spd.hpp
stan/math/prim/fun/scale_matrix_exp_multiply.hpp
stan/math/prim/fun/mdivide_left.hpp
stan/math/prim/fun/trace_gen_inv_quad_form_ldlt.hpp
stan/math/prim/fun/mdivide_right_tri.hpp
stan/math/prim/fun/matrix_exp_multiply.hpp
stan/math/prim/fun/mdivide_right.hpp
```

**Comment by mitzimorris** [comment]
> This is failing for `mdivide_left_spd` because if `check_multiplicable` doesn't throw anymore on size 0 input, then we get straight into Eigen code, so we'll need an explicit check for size 0 and return early. I think `mdivide_left_tri` has the same problem, and probably a few more headers. If you need help with this let me know

@mcol - definitely need help.

`check_multiplicable` currently enforces the following 3 things, in order

1.  dims on result are not 0 (A.rows > 0, B.cols > 0)
2. compatible size- A.cols == B.rows
3. inner dimension also > 0 (A.cols > 0, therefore B.rows > 0, by previous condition)

- if both A and B can be empty, then the only requirement is that A.cols == B.rows
- if A must be positive, then the check multiplicable does the right thing
- if B must be positive but A can be empty, allow A.rows == 0

I think that the direction I started going in is wrong - the current PR has reduced `check_multiplicable` to a wrapper around `check_size_match`.
instead we need to look at the 19 functions which call `check_multiplicable` and determine whether or not A or B can be empty and if so, what should the function return.

**Comment by mitzimorris** [comment]
should I close this PR and revise the issue?

**Comment by mitzimorris** [comment]
the other option is to just fix the multiply function for now.

**Comment by mitzimorris** [comment]
hi @mcol 

- Added file `stan/math/prim/err/check_multiplicable_positive.hpp` which does what current develop branch version of `check_multiplicable` does, plus corresponding unit test.

- Changed `stan/math/prim/err/check_multiplicable.hpp` so that it just wraps the call to `check_size_match` - allows either matrix A or B to have rows, columns of size 0.

- Reviewed all stan_math functions which call `check_multiplicable` - all `mdivide*` functions now call `check_multiplicable_positive`; the rest are unchanged and will now allow matrices and vectors of size 0, note that there are several places in the code - e.g., `matrix_exp_multiply` which explicitly allow matrices of size 0 - perhaps these should have unit tests to exercise this condition?

**Comment by mitzimorris** [comment]
updated issue - closing this PR.

**Pull request closed without merging**
