### PR TITLE
Split out travis tests further

### PR DESCRIPTION
**Pull request by seantalts**
Seeing timeouts even on develop now.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Okay, something totally crazy is going on - Travis is claiming the jobs I created by splitting these tests up BOTH timed out at 49 minutes. But the build has been executing for 13 minutes!

**Comment by seantalts** [comment]
It might just be time to ditch Travis once and for all...

**Comment by syclik** [comment]
I think all we really care about is test coverage under:
- linux (with one or maybe two compilers)
- mac (with one compiler)
- Windows (with one compiler)

and as we go forward:
- mac with GPU (just one configuration for now)
- optional: linux with GPU
- mac with MPI
- optional: linux with GPU

If we can get that coverage without travis, then we're good.

**Comment by seantalts** [comment]
Don't we want Linux with MPI instead of Mac with MPI?

**Comment by syclik** [comment]
(edited the typo above)

Yes. Maybe both? We just want test coverage where it works.

Ideally, we'll have a grid of compilers + OS + GPU + MPI, but I sure as hell don't have the patience to maintain that mess!

**Comment by syclik** [comment]
I just changed the `.travis.yml` with this:
```
git:
  depth: 2
```

to change the git clone depth. See: https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth

**Comment by seantalts** [comment]
Seems good!

**Comment by syclik** [comment]
I really have no idea why it's failing on Travis. I was trying to see if
the checkout times were drastically different, which could indicate either
network or disk i/o issues. In both cases, a less deep checkout might help?

**Pull request merged**
