### PR TITLE
Feature/issue xxx add matern 3/2 prim

### PR DESCRIPTION
**Pull request by drezap**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Add matern 3/2 kernel to prim.

This is consistent with with both GMPL (Rasmussen & Williams) and our current quadratic exponential covariance function. Users will be able to switch back and forth between covariance functions easily, per Mike's suggestion on discourse. Please see the latex documentation for description of how I calculate the function and ARD.
#### How to Verify:
testing:
vec double
vec double double
vec double ARD
vec eigen
vec eigen eigen
vec eigen ARD
vec double double ARD
rvec eigen
rvec eigen ARD
vec eigen rvec eigen
vec eigen rvec eigen ARD
rvec eigen rvec eigen
rvec eigen rvec eigen ARD
eigen mixed
eigen mixed ARD
double domain err training
nan error training
differing x lengths

#### Copyright and Licensing
Copywrite<2018><Andre Zapico>

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by drezap** [comment]
@seantalts when you get a chance, can you restart this PR as well? Thanks.

**Comment by drezap** [comment]
on the old GUI do I hit "build with parameters" on the left? and if so, what parameters should I build with? @seantalts

**Comment by seantalts** [comment]
Yep - should have decent doc on screen suggesting defaults are fine, if not
let me know

**Comment by drezap** [comment]
Hi can some one please review this PR?

**Comment by drezap** [comment]
same issue, I'm closing this and then re-opening after I pull from upstream develop.

**Pull request closed without merging**
