### PR TITLE
Feature/issue 331 clean up

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This pull request does these things:
- Removes `using stan::math::*;` lines from code
- Changes fully qualified (`stan::math::*`) calls to the math library to unqualified calls
- Removes extra whitespace
- Removes end-of-namespace comments. (`}  // stan`)
- Changed arguments that accepted `const double&` and `const int&` to the plain primitive type
- Changed variables names with leading underscore to trailing underscore.

#### Intended Effect:

Make the math library more consistent stylistically without changing behavior.

#### How to Verify:

All tests pass.

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions: 

Anyone

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
This passed tests. Anyone want to take a look?

There are way too many files, but I scripted most of it. Each of the individual commits is focused and tries to only do one particular thing, so it might be easier looking at those.

**Comment by sakrejda** [comment]
I checked that the first two do as indicated on the sticker. I'll go ahead and check the rest.

**Comment by sakrejda** [comment]
commenting here since there are too many files for github to allow line comments: stan/math/prim/mat/fun/autocorrelation.hpp has a chunk of commented-out code (with no comment about why it's commenteed out), should that go away since this is a clean-up? I only noticed b/c you changed indentation.

**Comment by bob-carpenter** [comment]
Yes, we shouldn't have any commented-out code other
than perhaps comments to show a simpler form to explain
an optimized form.

- Bob

**Comment by sakrejda** [comment]
Is this TODO either meaningful or current? 

`    template <typename T1, typename T2, int R, int C>
    Eigen::Matrix<typename boost::math::tools::promote_args<T1, T2>::type, R, C>
    elt_divide(const Eigen::Matrix<T1, R, C>& m, T2 s) {
      return divide(m, s);  // TODO(carp): divide(m, s);
    }
`

**Comment by syclik** [comment]
No, that can definitely be removed.

**Comment by sakrejda** [comment]
More commented code that got re-indented. This is from prim/mat/fun/mdivide_right.hpp

```
     check_square("mdivide_right", "A", A);
      check_multiplicable("mdivide_right", "b", b, "A", A);
      // FIXME: This is nice and general but likely slow.
      return transpose(mdivide_left(transpose(A), transpose(b)));
      //      return promote_common<Eigen::Matrix<T1, R2, C2>,
      //                            Eigen::Matrix<T2, R2, C2> >(A)
      //        .transpose()
      //        .lu()
      //        .solve(promote_common<Eigen::Matrix<T1, R1, C1>,
      //                              Eigen::Matrix<T2, R1, C1> >(b)
      //               .transpose())
      //        .transpose();
```

**Comment by sakrejda** [comment]
There are more of these FIXME's scattered around that should really be issues but I haven't figured out how they're related to each other.  Maybe they should be a separate pull request that also moved the comments to relevant issues.

**Comment by syclik** [comment]
Let's make the comments another issue. Looks like we'll need to walk
through them by hand.

On Tue, Aug 2, 2016 at 7:00 PM, Krzysztof Sakrejda <notifications@github.com

**Comment by sakrejda** [comment]
Makes sense to me.  Just out of curiosity, what is this construct in the stan/math/prim/mat/prob/categorical_log.hpp:

```
   static const char* function("categorical_log");
```
It was initally 

```
   static const char* function("stan::math::categorical_log");
```

.. but I don't understand what it's doing there so.. ?

**Comment by sakrejda** [comment]
In /stan/math/prim/mat/prob/multi_student_t_rng.hpp

```
 double w = stan::math::inv_gamma_rng(nu / 2, nu / 2, rng);
```

Officially those should be .5*nu (?)

**Comment by sakrejda** [comment]
So there are a lot of these changes like: 

```
--- a/stan/math/prim/scal/fun/grad_reg_inc_gamma.hpp
+++ b/stan/math/prim/scal/fun/grad_reg_inc_gamma.hpp
@@ -31,7 +31,7 @@ namespace stan {
         s *= - z / k;
         delta = s / ((k + a) * (k + a));
         if (isinf(delta))
-          throw domain_error("stan::math::gradRegIncGamma not converging");
+          throw domain_error("gradRegIncGamma not converging");
```

The errors being thrown should still give the full stan::math::* version of the name so that it's clear when Stan aborts that it's our library causing a problem.  Otherwise you get situations like with BLAS where functions with obscure four-letter names abort and you can't tell which library is responsible.

**Comment by sakrejda** [comment]
Throws modified unnecessarily in: 
- stan/math/prim/scal/fun/grad_reg_inc_gamma.hpp
- stan/math/prim/scal/fun/inc_beta_dda.hpp
- stan/math/prim/scal/fun/inc_beta_ddb.hpp

Same concern about comments but I don't think it's as important, we should just choose if comments/doc should refer to functions with namespace spec or not.

**Comment by bob-carpenter** [comment]
Yes, 0.5 * nu for efficiency and put it in a local so you
don't need to do the division twice.  

Also, nothing needs a stan::math qualifier because everything's
in the stan::math namespace now rather than in stan::prob
as it originally was.

- Bob

**Comment by bob-carpenter** [comment]
Either way, these are going to be super confusing if users ever
see them because there's nothing about this function in the language
or our manuals.  But with stan::math at least they'll know it's one
of our functions and it's probably better for users including
the math lib in their C++.

- Bob

**Comment by bob-carpenter** [comment]
We don't need namespace qualifications in the doc, but
I agree we should qualify in user-facing exceptions.

- Bob

**Comment by sakrejda** [comment]
In prim/scal/prob/logistic_ccdf_log:

```
    template <typename T_y, typename T_loc, typename T_scale>
    typename return_type<T_y, T_loc, T_scale>::type
    logistic_ccdf_log(const T_y& y, const T_loc& mu, const T_scale& sigma) {
      typedef typename stan::partials_return_type<T_y, T_loc, T_scale>::type
        T_partials_return;

      // Size checks
      if ( !( stan::length(y) && stan::length(mu) && stan::length(sigma) ) )
        return 0.0;

      // Error checks
      static const char* function("logistic_cdf_log");
```

Unnecessary comments. Also, how is that last bit an error check?

**Comment by sakrejda** [comment]
prim/scal/prob/logistic_ccdf_log has a lot more extraneous comments if you're enthusiastic about clean-up...

**Comment by sakrejda** [comment]
prim/scal/prob/neg_binomial_2_rng:

Unnecessary comment:

```
    // gamma_rng params must be positive and finite
      check_positive_finite(function,
                            "Location parameter divided by the "
                            "precision parameter",
                            mu_div_phi);
```

Around line 69, probably not as intended:

```
      // same as the constraints for poisson_rng
      check_less(function,
                 "Random number that came from gamma distribution",
                 rng_from_gamma, POISSON_MAX_RATE);
      check_not_nan(function,
                    "Random number that came from gamma distribution",
                    rng_from_gamma);
      check_nonnegative(function,
                        "Random number that came from gamma distribution",
                        rng_from_gamma);
```

**Comment by sakrejda** [comment]
Same as above in prim/scal/prob/neg_binomial_rng

**Comment by sakrejda** [comment]
rev/mat/fun/multiply_lower_tri_self_transpose.hpp: comments duplicate code and commented out code in if/elseif cascade:

```
    inline matrix_v
    multiply_lower_tri_self_transpose(const matrix_v& L) {
      // check_square("multiply_lower_tri_self_transpose",
      // L, "L", (double*)0);
      int K = L.rows();
      int J = L.cols();
      matrix_v LLt(K, K);
      if (K == 0) return LLt;
      // if (K == 1) {
      //   LLt(0, 0) = L(0, 0) * L(0, 0);
      //   return LLt;
      // }
      int Knz;
      if (K >= J)
        Knz = (K-J)*J + (J * (J + 1)) / 2;
      else  // if (K < J)
        Knz = (K * (K + 1)) / 2;
```

**Comment by sakrejda** [comment]
Various functions that I can't now recall seem to re-define stan::math::INV_SQRT_TWO_PI locally, or maybe they were just similar constants.  I think there should just be one collection of these constants in stan::math that gets used everywhere. Not part of this issue.

**Comment by sakrejda** [comment]
rev/scal/fun/Phi.hpp, the following comment is now confusing (without the stan::math):

```
   * See Phi() for the double-based version.
```

**Comment by sakrejda** [comment]
prim/scal/prob/neg_binomial_2_log_test.cpp, error messages modified unnecessarily, keep fully qualified name for error messages/exceptions:

```
diff --git a/test/unit/math/prim/scal/prob/neg_binomial_2_log_test.cpp b/test/unit/math/prim/scal/prob/neg_binomial_2_log_test.cpp
index a552abe..efcea01 100644
--- a/test/unit/math/prim/scal/prob/neg_binomial_2_log_test.cpp
+++ b/test/unit/math/prim/scal/prob/neg_binomial_2_log_test.cpp
@@ -29,7 +29,7 @@ TEST(ProbDistributionsNegBinomial, error_check) {
 
   std::string error_msg;
 
-  error_msg = "stan::math::neg_binomial_2_log_rng: Exponential "
+  error_msg = "neg_binomial_2_log_rng: Exponential "
               "of the log-location parameter divided by the precision "
               "parameter is inf, but must be finite!";
   try {
@@ -43,7 +43,7 @@ TEST(ProbDistributionsNegBinomial, error_check) {
     SUCCEED();
   }
 
-  error_msg = "stan::math::neg_binomial_2_log_rng: Random number that "
+  error_msg = "neg_binomial_2_log_rng: Random number that "
               "came from gamma distribution is";
   try {
     stan::math::neg_binomial_2_log_rng(log(1e10), 1e20, rng);
```

**Comment by sakrejda** [comment]
I guess for tests fully qualified names inerrors are not important in the same way, maybe I'm being too consistent here.  I will skip the rest.

**Comment by sakrejda** [comment]
Bunch of commented-out code equivalent (or close to equivalent) to uncommented code:

```
diff --git a/stan/math/prim/mat/fun/LDLT_factor.hpp b/stan/math/prim/mat/fun/LDLT_factor.hpp
index 03692ae..ad950ab 100644
--- a/stan/math/prim/mat/fun/LDLT_factor.hpp
+++ b/stan/math/prim/mat/fun/LDLT_factor.hpp
@@ -57,31 +57,31 @@ namespace stan {
     class LDLT_factor<T, R, C> {
     public:
       LDLT_factor()
-        : N_(0), _ldltP(new Eigen::LDLT< Eigen::Matrix<T, R, C> >()) {}
+        : N_(0), ldltP_(new Eigen::LDLT< Eigen::Matrix<T, R, C> >()) {}
 
       explicit LDLT_factor(const Eigen::Matrix<T, R, C> &A)
-        : N_(0), _ldltP(new Eigen::LDLT< Eigen::Matrix<T, R, C> >()) {
+        : N_(0), ldltP_(new Eigen::LDLT< Eigen::Matrix<T, R, C> >()) {
         compute(A);
       }
 
       inline void compute(const Eigen::Matrix<T, R, C> &A) {
         check_square("LDLT_factor", "A", A);
         N_ = A.rows();
-        _ldltP->compute(A);
+        ldltP_->compute(A);
       }
 
       inline bool success() const {
         // bool ret;
-        // ret = _ldltP->info() == Eigen::Success;
-        // ret = ret && _ldltP->isPositive();
-        // ret = ret && (_ldltP->vectorD().array() > 0).all();
+        // ret = ldltP_->info() == Eigen::Success;
+        // ret = ret && ldltP_->isPositive();
+        // ret = ret && (ldltP_->vectorD().array() > 0).all();
         // return ret;

```

**Comment by sakrejda** [comment]
Looks like your sed clobbered some header guards, there are likely more of these:

```
diff --git a/stan/math/prim/mat/fun/welford_covar_estimator.hpp b/stan/math/prim/mat/fun/welford_covar_estimator.hpp
index 349630a..fc2b4f1 100644
--- a/stan/math/prim/mat/fun/welford_covar_estimator.hpp
+++ b/stan/math/prim/mat/fun/welford_covar_estimator.hpp
@@ -1,5 +1,5 @@
-#ifndef STAN_MATH_PRIM_MAT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
-#define STAN_MATH_PRIM_MAT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
+#ifndef STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
+#define STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
```

**Comment by sakrejda** [comment]
sed clobbers in:

```
krzysztof@hagrid:~/packages/stan-dev/math$ grep 'STANm_' -R ./stan
./stan/math/prim/mat/fun/welford_var_estimator.hpp:#ifndef STANm_ATH_PRIMm_AT_FUN_WELFORD_VAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_var_estimator.hpp:#define STANm_ATH_PRIMm_AT_FUN_WELFORD_VAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_covar_estimator.hpp:#ifndef STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_covar_estimator.hpp:#define STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
krzysztof@hagrid:~/packages/stan-dev/math$ grep 'm_AT_' -R ./stan
./stan/math/prim/mat/fun/welford_var_estimator.hpp:#ifndef STANm_ATH_PRIMm_AT_FUN_WELFORD_VAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_var_estimator.hpp:#define STANm_ATH_PRIMm_AT_FUN_WELFORD_VAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_covar_estimator.hpp:#ifndef STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
./stan/math/prim/mat/fun/welford_covar_estimator.hpp:#define STANm_ATH_PRIMm_AT_FUN_WELFORD_COVAR_ESTIMATOR_HPP
```

**Comment by sakrejda** [comment]
Looks like you're only getting the first variable changed over, and you need every instance on a line. If this is passing tests it's by luck or lack of test coverage:

```
-        Eigen::VectorXd delta(q - _m);
-        _m  += delta / _num_samples;
-        _m2 += (q - _m) * delta.transpose();
+        Eigen::VectorXd delta(q - m_);
+        m_  += delta / _num_samples;
+        m2_ += (q - m_) * delta.transpose();
       }
```

**Comment by sakrejda** [comment]
Now I'm confused, prim/mat/fun/welford_var_estimator.hpp has the problem with num_samples not being converted but it's internally consistent. I guess just check this file to make sure the underscore got moved around correctly:

stan/math/prim/mat/fun/welford_var_estimator.hpp

**Comment by sakrejda** [comment]
@syclik  I looked at all of it and it looks like it does what it says on the box with the exceptions above.  If you scripted the thing where underscores got moved around my best guess is that prim/mat/fun/welford_var_estimator.hpp was modified by an earlier script version that had some problems.  I didn't see those issues anywhere else (nor did grep).

**Comment by syclik** [comment]
@sakrejda, thanks for looking at it so closely!

Here's what we'll do:
1. I'll fix the header guards. (I'm going to do a git diff and see which ones have changed and change them back.) I'll walk through and change any inconsistent header guards -- I have a script somewhere for them.
2. Regarding error messages -- removing `stan::math::` from the output is more consistent. We don't have it in most of the error handling. The main use case for these messages are the rejection messages from CmdStan / RStan / PyStan and I think it's better if we leave it off. The secondary use case is from clients of the math library. They can easily catch and throw with a different message. If we had it in most of the error messages, I'd want to put it in -- I'm more concerned with consistency here and leaving it off is more consistent. 
3. I'll fix the other leading / trailing underscore issues. I'll walk through each file by hand to make sure I'm doing everything right.
4. We should add a new issue for removing unused comments. I think this pull request is big enough. Although it's just removing comments, I think we'll need to walk through them, so I think it's outside the scope of this pull request.

Thoughts? I differ in opinion regarding the error messages. If we added the fully qualified name everywhere, the rejection messages would change for RStan, CmdStan, and PyStan. 
Instead of:
```
Exception thrown at line 24: normal_log: Scale parameter is 0, but must be positive! 
```

We would see:
```
Exception thrown at line 24: stan::math::normal_log: Scale parameter is 0, but must be positive! 
```
I don't think we need that. I could be convinced otherwise.

**Comment by sakrejda** [comment]
No problem, a few thoughts: 
1. Sounds good, I think I've seen those few examples before but maybe you'll find more.
2. Makes sense to go with consistency for now, would be nice to make this flexible later. As mentioned above I just recall looking at messages about "dgemm" or some other BLAS function with an obscure name being missing when it got spat out by an R package and wondering how/where I would search for it.  
3. I'm pretty sure that was the only file with the issue but maybe worth another look.
4. Agree, I just marked commented code them b/c I was looking through so many diffs anyway and a few of them looked like they were pointing out actual issues (aside from removing unused comments).
The plan looks good, glad somebody had the energy for doing this!

**Comment by syclik** [comment]
1. Done.
2. Understood. If you feel strongly about it, open up an issue and we can make all the error messages more consistent.
3. That was the only file. Thanks!
4. I'll open up a new issue right now.

**Comment by sakrejda** [comment]
:+1:

**Comment by syclik** [comment]
Great. For 3, I've rewritten every `#define` and `#ifndef` just to be sure
and found no changes.

On Wed, Aug 3, 2016 at 7:31 AM, Krzysztof Sakrejda <notifications@github.com

**Comment by bob-carpenter** [comment]
Better to be consistent, but we haven't been so picky
with test code as it's going to mostly be read by our
developers, not users.

**Comment by bob-carpenter** [comment]
Those code comments are technically right, but it'd
be better to also say that we're generating neg binomial
by compound gamma-Poisson.  And I don't know what POISSON_MAX_RATE
is, but we don't want anything about Poisson or gamma in
any error message returned to user.

**Comment by bob-carpenter** [comment]
Could you create a separate issue for this.  Thanks.

**Comment by bob-carpenter** [comment]
The function variable is just the anme of what gets returned.

I'd also rather remove all those redundant spaces.  I also
prefer tighter negations for less nesting and to make it clear
that if any of the lengths is zero, the result should be zero.
So I'd write that as:

  if (!length(y) || !length(mu) || !length(sigma)) return 0;

And that test should go after the mismatched size tests, which
would indicate a bug, right?

We don't need the stan:: qualifier because we're in the stan namespace,
but you may want to leave it if you think there's a chance someone
is going to do a using ...::* somewhere and might introduce an
ambiguity.

**Comment by bob-carpenter** [comment]
Yes, please change all the leading _ cases.  I don't see that
it's a problem for tests --- if it's compiling then _num_samples
must be consistent at least.

**Comment by bob-carpenter** [comment]
That should be a ternary operator.  And there should be
spaces around operators.  

  int Knz = K >= J
          ? ...
          : ...;

or squeeze it onto one line if it'll fit.  And definitely remove
the K == 1 conditional comment --- it's fine to have it default
to generic implementation here because we probably won't see many
K == 1 matrices.

**Comment by bob-carpenter** [comment]
I'm OK either way with qualified names in error messages.
It's worse for stan::math, but better for stan::lang.

**Comment by bob-carpenter** [comment]
I think it's fine w/o stan::math, but either way is OK.

**Comment by bob-carpenter** [comment]
Thanks guys.  The neat freak in me loves to see
these kinds of changes.

**Comment by syclik** [comment]
Thanks for pointing out the length 0 error checking being a bug. That does seem fishy. I'm opening up a new issue for it.

**Pull request merged**
