### PR TITLE
Bugfix/599 upgrade boost 1.64.0

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
see https://github.com/stan-dev/math/issues/599

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Mitzi Morris

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@mitzimoris I have no idea what happened here but it looks like this pull request touches 55K files.

**Comment by bob-carpenter** [comment]
@bgoodri --- @mitzimorris says that's just Boost libs.  The commits should say what is touhed.  I'm not going to be able to review this until around 12:00 EST today, so if you want to review and merge sooner, please do.

**Comment by bob-carpenter** [comment]
Oops, accidentally closed this.  That's what I get for trying to deal with Git on a rush out the door.

**Comment by syclik** [comment]
@mitzimorris, I'm guessing we've been trimming some of boost before adding it to Stan. Unless Boost 1.64 adds a whole bunch. I'm happy just committing everything as-is since RStan and PyStan already have a process for trimming the library.

But... regarding this pull request, is there a reason that the change to inverse hyperbolic functions is included here? Is that due to a change in the behavior in Boost between 1.62 and 1.64? Was there already a test that checked for the correct behavior of NaN that failed?

**Comment by mitzimorris** [comment]
the change to the inverse hyperbolic functions is due to the fact that the tests which check the correct behavior of NaN were failing.

sorry about adding all of Boost - I didn't know that we were trimming it before adding.

**Comment by syclik** [comment]
Re: inverse hyperbolic functions. Got it.

Re: Boost; I didn't even realize it until I saw the diff. If I did it last,
I was just following the pattern that was there before. (I would have gone
with simplicity or scripting so there's no thinking involved; maybe we can
do that.)

**Comment by mitzimorris** [comment]
PR failed upstream perfomance test -
```
src/test/performance/logistic_test.cpp:111: Failure
Value of: first_run[0]
  Actual: -65.7658
Expected: -65.508499
lp__: index 0
src/test/performance/logistic_test.cpp:114: Failure
Value of: first_run[1]
  Actual: 0.94406301
Expected: 0.78501701
accept_stat__: index 1
src/test/performance/logistic_test.cpp:120: Failure
Value of: first_run[3]
  Actual: 2
Expected: 1
treedepth__: index 3
src/test/performance/logistic_test.cpp:129: Failure
Value of: first_run[6]
  Actual: 65.778999
Expected: 68.208702
energy__: index 6
src/test/performance/logistic_test.cpp:132: Failure
Value of: first_run[7]
  Actual: 1.37067
Expected: 1.4087501
beta.1: index 7
src/test/performance/logistic_test.cpp:135: Failure
Value of: first_run[8]
  Actual: -0.77160603
Expected: -0.69222099
beta.2: index 8
[  FAILED  ] performance.values_from_tagged_version (0 ms)
```

@syclik or @seantalts what is this test and what needs to be done next?

**Comment by syclik** [comment]
It's a test that serves two purposes: 1) rough timing of a simple model just to make sure we don't do anything silly that accidentally makes our performance suffer and 2) compares the output against a previous run to verify that the output is identical. (this will eventually be replaced with better gold master tests)

It's failing to reproduce the values before and after the boost upgrade. I'll need to check to see if this was run on a different machine and if so, running on the Mac pro might have the same behavior. If not, we should do a little digging. We should be able to state why the draws are different by just replacing the boost library. Was it a particular function call? Are we misapplying one of the policies? Did the rng change?

**Comment by mitzimorris** [comment]
for https://github.com/stan-dev/stan/pull/2384, on my machine I ran all the stan unit tests using a math lib built with Boost 1.64.0.

**Comment by syclik** [comment]
I just verified that on my machine, swapping the boost 1.64 library for the boost 1.62 library indeed changes runtime behavior. Wow. Here's the model that's running: https://github.com/stan-dev/stan/blob/develop/src/test/test-models/performance/logistic.stan

So the question now is what to do.
1) we just update the tests and move on
2) we find out how this change happened; if it's a function call in boost, we figure that out and determine if that's ok and if it's not, then we figure out why argument dependent lookup or whatever else is having us run something different.

The conservative person in me says we should probably find out why just swapping libraries actually changes runtime behavior.

**Comment by syclik** [comment]
I was just digging a bit deeper and compared the two output files (as would be generated from CmdStan). Interestingly enough, it stays together than starts drifting after a while, so it's subtle. Maybe has to do with some really small differences in floating point accuracy.

Anyone have an opinion (cc: @mitzimorris @bob-carpenter @seantalts @betanalpha)? @betanalpha, if you could, mind running the stat validation tests with this branch to make sure this change in library didn't actually change the statistical properties? I think if it passes that, we can just update the test.

**Comment by betanalpha** [comment]
Look at the RNGs.  Small changes to the RNGs (even just the
seeding behavior) can easily induce the behavior that you describe.
Did any of the RNG code change from 1.62 to 1.64?

**Comment by syclik** [comment]
That was my first thought too. I went to the release notes and there
weren't any changes listed:
http://www.boost.org/users/history/version_1_64_0.html
http://www.boost.org/users/history/version_1_63_0.html

I haven't done a diff of all the RNG files, but I guess that's a reasonable
thing to do.

Mitzi already found a different behavior in the code for some math
functions. I wasn't sure if that was the root of this.

**Comment by syclik** [comment]
Just diffed the random code and there's no change in the code to the RNG
code.

**Comment by syclik** [comment]
I take it back, there's a difference in
boost/random/normal_distribution.hpp and that's used in the metrics within
hmc.

**Comment by syclik** [comment]
I haven't inspected the code well enough, but we could check whether the
random number generator is actually different. If it is and we think that's
what's causing this difference, I think we're good. (It'd still be great to
check the stat valid tests just in case)

**Comment by mitzimorris** [comment]
when running the Stan unit tests, there was different behavior for one test - 
`src/test/unit/variational/eta_adapt_small_test.cpp`
and I had to up the iterations to get the value expected for the test.

is this related?
https://github.com/stan-dev/stan/pull/2384/commits/978a3d8853a9a846a4fecd0a11b30e72d201d529

**Comment by bob-carpenter** [comment]
The other difference was that the inverse hyperbolic trig functions have slightly different NaN values, but that's very unlikely to be the cause of problems here.

**Comment by syclik** [comment]
There are definitely changes in the boost rng for generating unit normal numbers. My guess is that this is what causes the change. Here's how I tested it (one with one version of the boost library and one for the other and I just diffed files):
```
#include <gtest/gtest.h>
#include <boost/random/variate_generator.hpp>
#include <boost/random/normal_distribution.hpp>
#include <stan/services/util/create_rng.hpp>
#include <fstream>

TEST(foo, bar) {
  boost::ecuyer1988 rng = stan::services::util::create_rng(0, 0);
  boost::variate_generator<boost::ecuyer1988&, boost::normal_distribution<> >
    rand_diag_gaus(rng, boost::normal_distribution<>());

  std::ofstream out;
  out.open("boost_162.txt", std::ofstream::out);
  out.precision(10);
  for (int i = 0; i < 10000; ++i)
    out << rand_diag_gaus() << "\n";
  out.close();
}
```

I'm attaching the two files which could just be diffed by something like opendiff on a Mac.
[boost_162.txt](https://github.com/stan-dev/math/files/1228504/boost_162.txt)
[boost_164.txt](https://github.com/stan-dev/math/files/1228506/boost_164.txt)

**Comment by syclik** [comment]
Ok. I swapped out Boost 1.64's random with Boost 1.62's random and I'm getting the same results, so I'm convinced the only change is due to the change to the rng.

@mitzimorris, the next step is to update the Stan test. I think it's ok to merge as-is with the upstream test broken and we can fix it with the Stan PR. That's conditional on whether @betanalpha wants to run the stat validity tests just to make sure the updates to the rng are actually ok. The last thing I'd want is for us to update Boost and have that be the cause of some weird statistical bias. (Of course, there's a good chance that the change does nothing detectable or that it fixes something.)

**Comment by bob-carpenter** [comment]
> On Aug 16, 2017, at 4:44 PM, Daniel Lee <notifications@github.com> wrote:
> 
> Ok. I swapped out Boost 1.64's random with Boost 1.62's random and I'm getting the same results, so I'm convinced the only change is due to the change to the rng.


Nice!

> @mitzimorris, the next step is to update the Stan test. I think it's ok to merge as-is with the upstream test broken and we can fix it with the Stan PR. That's conditional on whether @betanalpha wants to run the stat validity tests just to make sure the updates to the rng are actually ok. The last thing I'd want is for us to update Boost and have that be the cause of some weird statistical bias. (Of course, there's a good chance that the change does nothing detectable or that it fixes something.)

Is it just the normal RNG or is it their whole RNG infrastructure? If it's just normal, it might be easier to independently test that. Stan doesn't care what the source of normal random numbers is as long as they're normal.

**Comment by bgoodri** [comment]
Are we talking about https://github.com/boostorg/random/pull/23 ?

**Comment by mitzimorris** [comment]
@bgoodri and @syclik - I got rid of all the extra boost lib files.   Daniel, could you change the upstream performance test to whatever you think is acceptable?

**Comment by syclik** [comment]
@bgoodri, I think it was a different pull request.

@bob-carpenter, the RNG is the same. I just called the RNG repeatedly and got identical results. And yes, if the normal draws are indeed normal, that'll do. But... I realize there's a lot of subtlety here and just wanted to verify that it's "normal enough" for our purposes.

@mitzimorris, I'll put it up on the corresponding stan branch.

**Comment by syclik** [comment]
@mitzimorris, the Stan branch was updated last week. Is there something else we're waiting on? I couldn't tell if we were compiling with this version yet in RStan.

**Comment by syclik** [comment]
@seantalts, do we have a better process for kicking off the upstream tests with a specified branch? If not, I'll do what I was doing in the past.

**Comment by seantalts** [comment]
I think it's probably the same. You're talking about kicking up upstream tests with custom versions of both the downstream and upstream branch, right? I just click "Build now with parameters" and put in the right git refs in the two spots.

**Comment by syclik** [comment]
Yup. Got it.

**Comment by mitzimorris** [comment]
@syclik the stan branch is ready to go.

**Comment by syclik** [comment]
@seantalts, help? I can't get the upstream branch to accept the two branches. For math, it's `bugfix/599-upgrade-boost-1.64.0` and for Stan, it's `bugfix/2383-boost-lib-1.64.0`.

**Comment by seantalts** [comment]
Lemme give it a shot...

**Comment by seantalts** [comment]
Okay, I got it working - with the changes I made to allow building pull requests from 3rd party forks, it currently expects the name of the github-created pull request branch - so instead of `bugfix/2383-boost-lib-1.64.0` I put in `origin/pr/601/merge`:

screen shot 2017-08-29 at 9 59 26 am

http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20Pull%20Request%20-%20Upstream%20-%20Stan/428/

**Comment by syclik** [comment]
Thanks, @seantalts!

The tests pass with the upstream branch: http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20Pull%20Request%20-%20Upstream%20-%20Stan/428/

@bgoodri, do you want to review / approve this?

**Comment by bob-carpenter** [comment]
Thanks to everyone on this one.  What a pain!

**Comment by syclik** [comment]
Yeah, this is one of the weakest part of the process (where we need an
upstream branch to be ready to go). We don't run into it too often or else
we would have made it much easier by now. But this upgrade was a little
tricky for other reasons.

Thanks, all!

**Comment by seantalts** [comment]
So what's up with this? Is someone reviewing it? Is it ready to go? Trying to get my ducks in order for 2.17.0.

**Comment by seantalts** [comment]
This looks good, just removed boost 1.62.0 and updated the branch to make sure it's not using 1.62.0 somewhere still.

**Comment by mitzimorris** [comment]
thanks for looking after this.  fingers crossed on the tests.

**Pull request merged**
