### PR TITLE
Refactor Jenkins pipeline

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

This PR refactors the Jenkins pipeline to reduce the CPU cycles used in testing. This is part of a bigger plan written in https://github.com/stan-dev/design-docs/pull/22.

This PR adds the following:

- adds faster failing: 

If any of the test stages in parallel stage fail, all the other stages will immediately stop. We currently for example waste 2 hours of CPU cycles on distribution tests if OpenCL tests fail after a few minutes.

- move Windows testing to merges to develop and on request: 

Windows tests have almost never failed if the other tests passed. Given the very unlikely occurrence of fails only on Windows, I think its perfectly fine to only test on merges to develop. We also now run integration tests (compile all Stan test models on Windows) so any compile issues would be caught on PR tests as well. There will also be a way of requesting Windows tests explicitly.

- threading tests only run on one Unix OS:

Given that the threading is done with TBB, there is no sense of running merge tests on both Mac and Linux. So we now run a single test on either Mac or Linux depending on which machine is free at the time.

- moves Windows and OpenCL header checks to Github Actions

The Unix header check remains the first step. Those are simple tests but they do cut of ~15 minutes of potential AWS cycles.

## Tests

/

## Side Effects

/

## Release notes

/

## Checklist

- [x] Copyright holder: Rok Češnovar, Univ. of Ljubljana

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Reducing the compute costs without compromising testing coverage will allow adding additional tests that will increase our coverage. Some of them are already in place: expression tests, integration tests on Windows. Ben Bales has prepared scripts for function-level performance tests we want to run weekly. We might also consider valgrind tests (both run weekly for example).

But we can't just add tests without optimizing the current state a bit first. This PR attempts just that.


Tagging a few devs that might have an opinion here
@syclik  @bbbales2 @t4c1 @SteveBronder @wds15 @bob-carpenter 

I would like to have everyone that has an opinion on this, to be on board here.

**Comment by SteveBronder** [comment]
> move Windows testing to merges to develop and on request:

idk about this one, for c++1y there are some windows specific issues where they have the least implemented c++14 standard. Catching this later would be a bummer

**Comment by rok-cesnovar** [comment]
> idk about this one, for c++1y there are some windows specific issues where they have the least implemented c++14 standard. 

Isnt this with g++ 4.9.3? Jenkins windows machines all have g++ 8.3.

We could move the free Github Actions Windows testing we have now to PRs. I am fine with that.

**Comment by SteveBronder** [comment]
I think for cran we still need to pass on gcc 4.9.3 for R 3.7 tests :-( 

https://cran.r-project.org/web/checks/check_flavors.html#r-oldrel-windows-ix86_x86_64

**Comment by rok-cesnovar** [comment]
Yes, but this PR does not change how we check that (we run that check with Github Actions on merge). 

I will move the g++ 4.9.3 check to run on PRs not on merges only. Thanks for bringing that up.

**Comment by rok-cesnovar** [comment]
Actually, any compile issues would be caught in the Windows integration tests that compile Stan models: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/2005/pipeline/160

**Comment by rok-cesnovar** [comment]
Additionally moved header checks to Github Actions. Ready for review.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal is there a way to set a maximum time limit for a Jenkins stage? Meaning that if it executes for more than X hours (not including waiting for free agents) it stops?

**Comment by bbbales2** [comment]
@SteveBronder can you take a look at this?

**Review by SteveBronder — APPROVED** [review]
Overall this looks good but one quick Q. It looks like we only test mingw now on develop / master. What version of gcc does mingw use? One thing I've worried about in the past is that mingw's c++1y does not have a lot of c++14 features (like multi-line constexpr functions). If we have to support mingw with gcc-4.9 for older versions of R on windows I worry that this won't catch some bugs till later

**Comment by rok-cesnovar** [comment]
Github Actions has 4.9.3. Jenkins has 8.3

So this PR does not change coverage in that sense. I think these kinds of issues are fairly rare and hence we don't need to run it every time. If they do turn out to become more common, we can revisit this policy.

If either the author or the reviewer is unsure whether the code would run on Windows in general, they can run manual Jenkins tests that would use g++ 8.3. That is added to this PR.

For cases when we can check the same with 4.9.3, we would have to add manual checks for gcc 4.9.3. Those could be run manually as we do for release notes: https://github.com/stan-dev/math/actions?query=workflow%3A%22Release+scripts%22

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar you can use [timeout](https://stackoverflow.com/questions/38096004/how-to-add-a-timeout-step-to-jenkins-pipeline) but I can help too.

**Comment by rok-cesnovar** [comment]
> Hey @rok-cesnovar you can use timeout but I can help too.

Thanks! I think the integration stages in /stan would require the timeouts the most so if you have time, please add them there.

**Comment by rok-cesnovar** [comment]
@SteveBronder can I merge this or do you want to discuss the c++1y further? Let me know.

**Review by SteveBronder — APPROVED** [review]
I'm cool with it!

**Comment by bbbales2** [comment]
Under 20 pulls! WOoo, getting the backlog cleared out

**Comment by rok-cesnovar** [comment]
Woop woop. In before Tadej opens 5 more monday :)

**Pull request merged**
