### PR TITLE
Feature/issue 39 univariate normal distribution on sufficient statistics

### PR DESCRIPTION
**Pull request by syclik**
This is an outstanding pull request from the Stan library:
https://github.com/stan-dev/stan/pull/1203
and
https://github.com/stan-dev/stan/pull/1226

### CODE REVIEW

**Comment by jpritikin** [comment]
What is the status of this pull request?

Also, there is a small error in the math I will correct on the next revision.

**Comment by syclik** [comment]
@jpritikin, it's not ok to let math errors in if you know they exist. Could you start by either describing the error or fixing it on that branch? Thanks.

**Comment by jpritikin** [comment]
The sample size of the covariance matrix should be N instead of N-1. I'll correct it in the next revision.

**Comment by bob-carpenter** [comment]
@syclik  Want to take a look at this?  No reason not to have it and it might be usable to make things in RStanArm and elsewhere faster.

**Comment by bob-carpenter** [comment]
I'm closing this long out-of-date pull request given that there hasn't been any activity in over six months.  We'd still be interested in getting this feature in, it's just not a priority.

**Comment by bob-carpenter** [comment]
I did not delete the branch, by the way.

**Pull request closed without merging**
