### PR TITLE
Renaming probability distribution functions

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist
- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below
#### Summary:

Renames the probability distribution functions to match the language definitions. 
#### Intended Effect:
- Renamed `_log` functions to `_lpdf` or `_lpmf` depending on the type of the first argument
- Renamed `_cdf_log` to `_lcdf`
- Renamed ``ccdf_log` to `_lccdf`
- Kept the `_log` functions and had it delegate to the appropriate `_lpdf`, `_lpmf`, `_lcdf`, or `_lccdf` function.
- Added doxygen doc to the `_log` function indicating that the function is deprecated.
#### How to Verify:

Look at the diff. Here are the things we should be careful about:
- check to see the header guard is correct
- check the error message
- check the delegation
#### Side Effects:

None. We've left the old behavior intact.
#### Documentation:

Included in C++.
#### Reviewer Suggestions:

Anyone.
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
I haven't figured out what to do regarding tests. All the distribution tests still test the `_log` function.

It makes sense that the tests are updated. I'm not sure exactly how. Any suggestions? I might pull the tests into a separate pull request. This pull request shouldn't change any existing behavior.

**Comment by bob-carpenter** [comment]
I think a wise engineer once said there should be a test to show how every function is called.  But I don't think we can afford to double the time our distribution tests take to run.  At the same time,  we want to make sure that all the `_lpdf` and related functions have the right names.  A simple test for each one to make sure it matches the `_log` version?

I don't think we want to remove the `_log` functions from the math library until we go to version 3.0 of the library.  And it's going to be some substantial work on the language side in Stan to reference the `_lpdf` and related functions rather than the `_log` functions (no big deal, just lots of awful code that looks at names of functions needs to change---tests should all be in place already).

**Comment by syclik** [comment]
=).

I agree that we don't want to double our test time (+ double size). I think simple tests to make sure the output is the same makes sense. I won't do every permutation since we know it's all the same code.

Agreed with not removing `_log` functions from the math library until 3.0.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Any hints on how to review this beast?  It's 300+ files and won't display in the code reviewer.  If this was tested with the current version of stan-dev/stan, then I'm OK with the change.

**Comment by syclik** [comment]
Good question. It was tested against stan and with all the probability tests still working off the _log version instead of calling the _lpdf/_lpmf. 

I would feel a little more comfortable if someone could put some more eyes on the changes. And the tests. But I'm pretty sure this is ok. 

I think we just need to look at the diff by hand.

**Comment by syclik** [comment]
@bob-carpenter, I just combed through every file. It looks right. I had missed a couple of deprecation comments, so I added that in with the last commit.

Your call on whether this gets into the math library before the release. The only risk I see is the possible timing difference due to the extra function dispatch. I'm going to run through some timing tests and I'll let you know if I can even see a timing difference.

**Comment by syclik** [comment]
I just ran the performance test from the Stan repo, which is super-inefficient, but it does call distributions 130 (2 x cauchy, 128 x bernoulli) per log prob evaluation. I can't see a difference in timing.

**Comment by bob-carpenter** [comment]
No, it should get compiled through.  Let's merge it for
this release.  I'll look it over and merge.

**Comment by bob-carpenter** [comment]
I don't see how this is going to work:

 ```
- return categorical_log<false>(n, theta);
+ return categorical_lpmf<T_prob>(n, theta);
```

I think that second line should just be

```
  return categorical_lpmf<false>(n, theta);
```

or if you want to be specific,

```
  return categorical_lpmf<false, T_prob>(n, theta);
```

I don't even see how what you have compiles.  Does the T_prob get somehow resolved as a `bool` for the propto template parameter to `categorical_lpmf`?

```
template <bool propto,
               typename T_prob>
     typename boost::math::tools::promote_args<T_prob>::type
     categorical_lpmf(int n,
                     const Eigen::Matrix<T_prob, Eigen::Dynamic, 1>& theta) {
```

**Comment by syclik** [comment]
Yup -- I know it "should," but I wanted to make sure it did.

I spent a few hours looking at every file today. I'd say spot check things
-- take a look at a few of the _lpdf / _log, _lcdf / _cdf_log, _lccdf /
_ccdf_log combos. And a few of the tests. I was consistent about
everything: if you spot something wrong in one, the problem would have been
repeated in many.

**Comment by syclik** [comment]
@bob-carpenter, you're right. That shouldn't work! I'm going to check for that everywhere.

**Comment by syclik** [comment]
@bob-carpenter, thanks. That was the only instance of that bug. I'm going to add a test to catch it to be a good citizen. We obviously don't have as much test coverage as we need in the multivariate pdfs.

**Comment by syclik** [comment]
The test that would have caught it is already in place -- the reason this doesn't fail is because we haven't gone through and done a lot of the computational tricks with the multivariate distributions. I think we're ok with the rest of the changed distributions.

**Comment by bob-carpenter** [comment]
It was the very first thing I looked at :-)

I'll take another look now.

- Bob

**Comment by bob-carpenter** [comment]
We're not dropping constants where we can?  We should really
do that, especially for everything involving a covariance
matrix.

- Bob

**Comment by syclik** [comment]
The template parameter, propto, controls that. We drop constants appropriately when propto = true. The bug wasn't a problem because it should have called the function with propto = false and when calling the version of the function without the bool template argument, it's the same as calling it with propto = false.

**Comment by bob-carpenter** [comment]
When you said we hadn't gone through and done the computational
tricks with multivariates, I thought that meant there wasn't
branching on propto in the multivariate distribution code.
Then it should all pass all the tests.

I realize we overload all the density functions with a version
that calls the original implementation with propto=false.  That's
why that code looked fishy to me (replacing "false" with "T_prob").
But maybe it was calling another function and not its own
full-template version, which would make it not show up as you indicate.

- Bob

**Comment by bob-carpenter** [comment]
Safari can barely open the code diff, much less perform a review. 

Should we be breaking these mondo pulls into something smaller and more manageable?

I'm seeing the same problem as before in `stan/math/prim/mat/prob/categorical_log.hpp`:

```
-      return categorical_log<false>(n, theta);
+      return categorical_lpmf<T_prob>(n, theta);
```

Is the reason it's working that `categorical_lpmf` has two overloads, `categorical_lpmf<bool, T>` and `categorical_lpmf<T>` which calls `categorical_lpmf` with the first template parameter equal to `T`?

This is where I was expecting to see 

```
 return categorical_lpmf<false>(n, theta);
```

**Comment by syclik** [comment]
I'll break this apart into multiple pull requests. I agree: I think it'll be much more manageable that way.

**Pull request closed without merging**
