### PR TITLE
Revert "Revert "Add tests for var_value<Matrix> for univariate distributions""

### PR DESCRIPTION
**Pull request by SteveBronder**
Pr to revert revert univariate distributions with var value

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@SteveBronder make sure to start the tests with row vector tests once you think you have the fix: https://jenkins.mc-stan.org/job/Math%20Pipeline/job/PR-2356/build?delay=0sec

But you probably already know this, so sorry for the noise :)

**Comment by SteveBronder** [comment]
Did not know that so ty! Is it possible to have Jenkins make a revert branch / open a PR with the revert up on a failure in dev? I wonder if that would be worth the effort

**Comment by rok-cesnovar** [comment]
Might be, but we have false positive occassionaly (aws throwing us out for example). Might get annoying.

**Comment by SteveBronder** [comment]
Alright looks like we are good! Lemme turn off the row vector flags and we can merge this. I think the fix was just the arena matrix thing

**Comment by rok-cesnovar** [comment]
No need to turn it off, its good.

**Comment by rok-cesnovar** [comment]
Oh you put it jn jenkinsfile, sorry. Yeah we should remove that. I thought you just tickef the checkbox.

**Comment by bbbales2** [comment]
We should throw up tests for the three new arena constructors too. I guess it doesn't have to go here since the merge tests will eventually catch errors with this, but it'd be good to have quick tests not embedded in the distribution stuff.

**Comment by bbbales2** [comment]
I added a test since the other tests were failing (and now they're movin' again)

**Comment by SteveBronder** [comment]
Odd I restarted the full unit tests but it still has an X here

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2356/14/pipeline/

**Comment by rok-cesnovar** [comment]
This is a “stage” restart, it started on the parallel stage. Those restarts dont show up as a orange dot but will give a green light if it passes.

**Comment by SteveBronder** [comment]
Nice! Alright I think this is good to merge!

**Review by bbbales2 — APPROVED** [review]
Good!

**Comment by bbbales2** [comment]
@rok-cesnovar I'll start a new list of compatible functions generating tomorrow.

**Pull request merged**
