### PR TITLE
Use cumulative_sum instead of nested loop in categorical_rng

### LINKED ISSUE #503: slow categorical_rng implementation
#### Summary:

The `categorical_rng` function is very slow for large N-simplexes, due to an unneccessary double loop.

#### Description:

The implementation of the categorical_rng function includes a [double loop](https://github.com/stan-dev/math/blob/aa311f3b329c96c8e47be85126ae9535be104b19/stan/math/prim/mat/prob/categorical_rng.hpp#L34-L37) which, unless I am mistaken, just calculates the cumulative sum of `theta`:

```C++
for (int i = 0; i < theta.rows(); i++) {
    for (int j = i; j < theta.rows(); j++)
        index(j) += theta(i, 0);
}
```

Replacing that with a single loop, or say a call to `cumulative_sum` will speed up the function tremendously for large N.

Additionally replacing the [iteration over the cumulative sum](https://github.com/stan-dev/math/blob/aa311f3b329c96c8e47be85126ae9535be104b19/stan/math/prim/mat/prob/categorical_rng.hpp#L39-L43) of `theta` with a binary search might also provide a small additional speed up.

#### Additional Information:

Just as an annectode: in a simulation model written in Stan, but using only transformed data and generated quantities, the program spent over 90% time (or rather`perf` samples) in `categorical_rng`. Replacing the implementation with a custom version without the double loop (but no binary search) cut down the runtime where the N-simplex was of order 10000, from hours to a few minutes only.

#### Current Version:
v2.14.0

### PR DESCRIPTION
**Pull request by torsti**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

- Header test for [stan/math/prim/arr/fun/promote_elements.hpp](https://github.com/stan-dev/math/blob/f51421b85ece83edca273db623a0659473bac659/stan/math/prim/arr/fun/promote_elements.hpp#L30) fails because `size_t` is not found, but this is independent of the changes in this pull request.

#### Summary:

Fixes #503 by changing a nested loop to a call to `stan::math::cumulative_sum`. This results in a speed-up of `categorical_rng`.

- I believe this reduces the number of operations in calculating the cumulative sum of `theta` approximately from `(N * (N + 1)) / 2` to `2 * N`.

Minor speed improvements might still be gained by changing to a binary search over `index`, or only calculating the cumulative sum up to `c`, but the speed gains would smaller and code changes less transparent.

#### Intended Effect:

- Much faster `categorical_rng` when simplex `theta` is large.

#### How to Verify:

- Unit tests show `categorical_rng` still works correctly.

- To quantify speed gains, compare or profile code using `categorical_rng` with previous version. Absolute runtime and share of time spent in `categorical_rng` will drop steeply as a function of the size of `theta`. Tested for different N in the range 1000 - 15000.

#### Side Effects:

None.

- Performance for small `theta` was not measured, but that too should be faster.

#### Documentation:

No changes to the documentation.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Torsti Schulz

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, ok to test.

**Comment by bob-carpenter** [comment]
@torsti  Thanks for the pull request---it looks good.

There's an upstream merge problem.  I don't know if that's a Jenkins artifact or not.  @syclik or @seantalts should know.  Definitely not a problem with the code here, though---all the includes look right.

**Comment by seantalts** [comment]
re: jenkins upstream test failing - it seems like the scripts for the upstream tests might not work with pull requests from forks, is that possible? I'll see what I can do to make that workflow possible, though I might not get to it until Monday.

**Comment by syclik** [comment]
Thanks. I forgot that in order for Jenkins to find the pull request for the upstream tests, we need the commit on a branch that's on stan-dev/math. I'm sure there's a way to incorporate the pull request branch from forks, but I never was able to figure it out.

**Comment by bob-carpenter** [comment]
@seantalts  Any idea why this is saying it can't be merged?  I'd like to get this in given that the code and tests pass and it shouldn't be affecting anything upstream.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by seantalts** [comment]
Yay! Glad this worked - this used my new mechanism for testing pull requests from forks for the upstream tests on Jenkins. Instead of a `git merge ${math_sha} --ff` it does a `git pull ${math_remote} ${math_sha} --ff`, and `math_remote` is set by the github pull request builder plugin environment variable `ghprbAuthorRepoGitUrl`. Seemed to work but I'll obviously keep an eye on it in future forked pull requests.

Merging!

**Comment by syclik** [comment]
Awesome. Just fyi, I added the commit to a branch on origin, so hopefully it still works. 


Daniel

**Comment by seantalts** [comment]
Oops. We'll see for sure with the next one! But in the output for this one I can see it fetching from torsti's fork, so hopefully that means it'll work next time.

**Pull request merged**
