### PR TITLE
Add Github Actions for Windows RTools 3.5 tests

### LINKED ISSUE #1904: Move Jenkins Windows agents to RTools 4.0
## Description

We discussed this again at the Math meeting and came to the conclusion that the move to RTools 4.0 should be done. There was also no opposition to this in the last month when I was bugging everyone with this.

This can't be solved with a PR, @serban-nicusor-toptal has to upgrade the agents one by one.

Install instructions: 
- remove RTools 3.5
- install RTools 4.0 https://cran.r-project.org/bin/windows/Rtools/
- open Rtools bash and enter `pacman -Sy mingw-w64-x86_64-make`
- make sure C:\rtools40\usr\bin and C:\rtools40\mingw64\bin are in the PATH env. variable

some more details here:
https://discourse.mc-stan.org/t/cmdstanr-with-rtools-4-0-on-windows-10-mingw32-make-exe-missing/14791/7?u=rok_cesnovar

That should be it.

g++ --version  should return 8.1.0

Let's get this running first and then slowly increase the PARALLEL setting.

#### Current Version:
v3.2.0

### LINKED ISSUE #1910: stack_alloc_speed_test.cpp requires 5GB of RAM
The stack_alloc_speed_test.cpp test here: https://github.com/stan-dev/math/blob/develop/test/unit/math/memory/stack_alloc_speed_test.cpp
requires 5GB of RAM to run, which is not really a huge requirement but prevents us from using less powerfull testing instances like the ones Github Actions uses. 

The free instance has 7GB, some of it goes to the OS and such and we are unable to pass this test on such an instance 

Is it actually necessary to allocate as much stack? Could we tests with half that? If n ran to 66000 that would allocate 2GB of RAM.

#### Current Version:
v3.2.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Fixes #1904 and fixes #1910 

Adds Github Actions to Math CI, testing the full unit tests with RTools 3.5 on Windows.

## Side Effects

/

## Release notes

Added Github Actions to CI.

## Checklist

- [x] Math issue #1904 and #1910 

- [x] Copyright holder: Rok Češnovar, Univ. of Ljubljana

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Nice! Let me know if this works as planned asI can have the Windows workers up on RTools 4.0 by tomorrow.

**Comment by rok-cesnovar** [comment]
We need to get others on board, but this would definitely be very nice.

**Comment by ahartikainen** [comment]
For debug I would also call `where gcc` and `where mingw32-make` to see that the correct tools are used.

Or use powershell

    Get-Command gcc | Select-Object -ExpandProperty Definition

**Comment by rok-cesnovar** [comment]
Thanks you @ahartikainen, will add.

Bottom line, this seems to work fine. It is quite slower than Jenkins ( we can't really run parallel tests here) but its really simple to maintain. If we run it parallel to Jenkins tests it doesn't really matter how much time they run as it is not longer than 3 hours. I think running this on merges would be enough.

**Comment by serban-nicusor-toptal** [comment]
Hey, all windows instanced upgraded to Rtools 4.0 besides `gelman-group-win2` which is down for now, will upgrade it when it comes back online.

**Comment by rok-cesnovar** [comment]
Great, thanks! Lets see if everything will run smoothly for awhile (a day or two busy days) and then try to gradually increase the parallel setting.

**Comment by ahartikainen** [comment]
Should the action also upload gtest outputs (maybe only failed ones)? This might help with failed tests if there are any.

I think that can be done with artifacts

      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: gtest_outputs_xml
          path: ./gtest_outputs

You just need to copy all xml files to `gtest_outputs` folder

**Comment by rok-cesnovar** [comment]
Nice, thanks. Yes, that is probably much easier to read than going through the job logs.

**Comment by rok-cesnovar** [comment]
Artifact upload works: https://github.com/stan-dev/math/actions/runs/114978232

This PR also decreases n in stack_alloc_speed_test to fix https://github.com/stan-dev/math/issues/1910

Running once more to check everything works, will then remove pull_request from on and tag you for review @ahartikainen if you dont mind.

**Comment by rok-cesnovar** [comment]
This is ready for review @ahartikainen

**Comment by rok-cesnovar** [comment]
It seems that Ari does not have approve permissions on Math for some reason. So if anyone can approve for him, please. No rush, tests will run for some time.

**Pull request merged**
