### PR TITLE
Update GHA tests to run using RTools44

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

Our Github CI for Windows is significantly out of date with the current RTools windows toolchain, this PR updates the workflows to run using the latest RTools44 toolchain

## Tests

N/A

## Side Effects

N/A

## Release notes

Update Github CI to use RTools44 toolchain on windows

## Checklist

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by andrjohns** [comment]
Turns out the RTools44 GCC has a bug in its `exp(std::complex<double>)` implementation, which is the cause of the `mix` test failures.

The result of `exp(std::complex<double>(inf))` should be `{inf, 0}` [as seen on godbolt](https://godbolt.org/z/hMbT79anv), but the RTools44 gcc returns `{inf, nan}`.

I've notified the toolchain maintainer

**Comment by andrjohns** [comment]
Looks like the reason why the RTools40 toolchain was passing but not Rtools44, is that the msys2-based gcc (like rtools40 and those installed via `pacman`) define `_GLIBCXX11_USE_C99_COMPLEX` by default, but the MXE-based gcc (RTools42-44) don't.

I'm still investigating whether this is an rtools-specific or a general mxe issue, but for now we can just add `-D_GLIBCXX11_USE_C99_COMPLEX` to the windows flags

**Comment by andrjohns** [comment]
> Looks like the reason why the RTools40 toolchain was passing but not Rtools44, is that the msys2-based gcc (like rtools40 and those installed via `pacman`) define `_GLIBCXX11_USE_C99_COMPLEX` by default, but the MXE-based gcc (RTools42-44) don't.
> 
> I'm still investigating whether this is an rtools-specific or a general mxe issue, but for now we can just add `-D_GLIBCXX11_USE_C99_COMPLEX` to the windows flags

I've heard back from the RTools maintainer that they would prefer to wait until the next major RTools release before adding this flag, but that I should report the bug upstream to gcc/libstdc++. So we'll need to manually add the flag in the interim.

@WardBrian / @rok-cesnovar Should I keep the makefile as unconditionally adding the flag on Windows (like it is now)? Alternatives that I can think of would be to:

  - Only add if not already defined (like: `$(echo | g++ -E -dM - | findstr _GLIBCXX11_USE_C99_COMPLEX)`)
  - Only add for MXE toolchain (like: `$(gcc -v | findstr mxe)`)

Thoughts/preferences?

**Comment by WardBrian** [comment]
I think it's fine being unconditional on Windows

**Comment by andrjohns** [comment]
@WardBrian ok to approve and merge before the freeze? Just want to make sure this in now that the next release is recommending the stock RTools toolchain

**Review by WardBrian — APPROVED** [review]
Thought I already had! LGTM

**Pull request merged**
