### PR TITLE
Formatting unit tests to pass cpplint

### PR DESCRIPTION
**Pull request by andrjohns**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
All unit tests formatted to pass cpplint checking. Unit test directory added to the cpplint makefile, new tests/modifications can now be checked at the same time as math functions/distributions.

#### Intended Effect:
Make codebase more consistent and easier to maintain.

#### How to Verify:
```
./runTests.py test/unit
make cpplint
```
For visually inspecting, probably easier to look the changes ignoring whitespace [(add "?w=1" to end of url)](https://github.com/stan-dev/math/pull/654/files?w=1)

#### Side Effects:
None.

#### Documentation:
N/A

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Andrew Johnson

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Jenkins, OK to test.

**Comment by bob-carpenter** [comment]
Jenkins, test this please.

**Comment by bob-carpenter** [comment]
Thanks, this is great.

Any suggestions on how we can review this thing?  It's 1400 files!  @syclik --- any ideas?

**Comment by bob-carpenter** [comment]
Or maybe @seantalts has some suggestions for reviewing?

The one problem we'll run into with this is that it may create a lot of merge conflicts with existing branches.  I have no idea how we should be handling this, which is why I'm asking @seantalts and @syclik

**Comment by seantalts** [comment]
@andrjohns how did you automate this, btw? One of the things on the roadmap is to have the entire codebase under automatic clangformat, maybe even better to check in the automation.

I don't have any suggestions for this, other than to make sure the # of tests is the same before and after and for someone to go through the [w=1 link](https://github.com/stan-dev/math/pull/654/files?w=1) and do a quick visual inspection.

**Comment by seantalts** [comment]
I would guess this isn't a super high priority issue on the roadmap so it might take a while for one of us to actually go through all 1400 files.

**Comment by bob-carpenter** [comment]
Testing number of tests is good idea.

How about a thorough spot check or do you think we should really inspect all 1400 files by hand?  

I'd also have a better feeling if I knew how they were converted (like Ben reported for converting to long in stan-dev/math).

**Comment by seantalts** [comment]
I think seeing the automation + a spot check sounds fine to me. Most of the files don't have non-whitespace changes and are collapsed with the w=1 link above, and the changes in the other files are pretty quick to verify as well.

**Comment by bob-carpenter** [comment]
Nice.  Didn't see that w=1 thing.  Reviewing now.

**Comment by andrjohns** [comment]
Almost no automation on this one actually. The majority was just regex for removing trailing spaces and adding/removing spaces where there should/shouldn't be (e.g. missing space after comma), then addressing line length/includes.

Clangformat looks like it would be much more efficient in the future (hadn't heard of it before!), so I'll start having a look into that as well

**Comment by bob-carpenter** [comment]
Before going down that route, we need to settle on a format.  These changes are disruptive.  Mitzi and I had to spend a few hours yesterday dealing with the merge conflicts in pending pull requests and we didn't even touch the branches without pull requests.

**Comment by seantalts** [comment]
Why did you guys do that? The PR authors should be able to fix merge conflicts, especially really simple ones like this, right?

**Pull request merged**
