### PR TITLE
Bugfix/issue 230 jacobian transposed

### PR DESCRIPTION
**Pull request by wds15**
#### Submisison Checklist

- [X] Run unit tests: `./runTests.py src/test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
align jacobian with common definition, i.e. to return a NxM matrix for a R^N -> R^M function

#### Intended Effect:
Currently the output would the transposed MxN

#### How to Verify:
Run current tests for stan/math/rev/mat/functor/jacobian.hpp 

#### Side Effects:
All user code using the functions now get the correct (but different) sized matrices.

#### Reviewer Suggestions: 
@syclik @bob-carpenter 
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is requiring to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Uh, default says it failed, but there aren't any failed tests.  @syclik --- any idea what's up here?

Also, what this really needs is a test to make sure we're doing this the right way around.  In general, whenever there's a bug, the first thing to do is write a test that fails in the current implementation.  Then fix it so the new implementation passes.

**Comment by bob-carpenter** [comment]
The code looks fine, by the way.

**Comment by syclik** [comment]
It fails this test: `./runTests.py test/unit/math/mix/mat/functor/autodiff_test.cpp`

Not sure what's up with it yet.


Re: Jenkins -- I'm still trying to figure out how to aggregate tests to the project so it shows the right message from GitHub.

**Comment by wds15** [comment]
Hi!

I checked matters and the test needed an update as the to be tested output from the jacobian function is now transposed (sorry, I should have caught this myself, but I was not able to decipher the error messages here). The tests are now successful. However, I had to apply a workaround which I have seen to be necessary when working with NESTED AD things:

The AD nested calculations are WRONG if the AD stack is not initialized. This is why I instantiate a var dummy variable within the test before the jacobian call is done. My guess is that this was not necessary before this patch due to the change from set_zero_all_adjoints() to set_zero_all_adjoints_nested().

My guess is that the set_zero_all_adjoints_nested() may have an issue.

For the purpose of this pull request I guess we have 3 options:

1) Fix the nested system (if my understanding here is correct and we have an issue here and not a misuse from my end)
2) change set_zero_all_adjoints_nested() to set_zero_all_adjoints() in the jacobian function and remove the dummy variable in the test
3) leave things as they are

**Comment by wds15** [comment]
@bob-carpenter : Just for the future: You are pointing towards test-driven development. For this specific case the already existing test was actually wrong. So if I were to redo this again, would it have been ok to CHANGE the existing test which tests for the wrongly transposed output to the correct behavior. That way the old test would be changed, but this would trigger the mis-behavior. Would this be ok from a test-driven dev perspective?

**Comment by wds15** [comment]
Whoa... there is another jacobian function lingering in stan math somewhere which returns a transposed Jacobian. The test code for the

  jacobian<double>(f,x,fx_rev,J_rev);

function still tests for the transposed Jacobian - but I have no clue where this is coming from.

**Comment by wds15** [comment]
Found it. The "fwd" version was what I was looking for. I adapted the test and corrected the fwd jacobian version. BTW, there is another jacobian implementation around in the test system, but that one is ok as far as I can tell.

**Comment by bob-carpenter** [comment]
Thanks, Sebastian; this is good to go.   It looks like all the tests passed on Jenkins and then some aggregator got messed up --- GitHub is obscuring the bottom half of my screen with an annoying overlay modal dialog message about localization I can't remove.

**Comment by syclik** [comment]
All the tests actually passed. Merging.

**Pull request merged**
