### PR TITLE
Feature/issue 161 log falling factorial returns incorrect value

### PR DESCRIPTION
**Pull request by randommm**
#### Summary:
Fix issue #161 

#### Intended Effect:
`falling_factorial`and `log_falling_factorial` were not as described in Stan manual and the API documentation. This pull request puts them in sync with it and adds finite_difference rev/fwd tests to make sure the derivatives were correctly calculated.

Also added finite_difference rev/fwd tests for `rising_factorial` and `log_rising_factorial`.

#### How to Verify:

Check code.

#### Side Effects:

None.

#### Documentation:

Not applicable.

#### Reviewer Suggestions:
Anyone.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
@randommm Would you mind taking another look at what's going on in the build?

**Comment by randommm** [comment]
This one is also stuck with Jenkins' doxygen build problem.

**Comment by syclik** [comment]
I'll look again.

**Comment by syclik** [comment]
This looks great! I made a couple of spacing changes and removed duplicated lines. We'll merge it as soon as it passes tests.

**Comment by randommm** [comment]
What happened here with Jenkins? All tests are blue http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20Pull%20Request/280/

**Comment by syclik** [comment]
Thanks, Marco. Yes, it passes. I tried to fix something on Jenkins that made all the builds fail. This is good to go.

**Pull request merged**
