### PR TITLE
generalized uniform

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Generalizes uniform distribution related functions to accept Eigen expressions. 

## Tests

Tested using expression testing framework.

## Side Effects

None.

## Release notes

Generalized uniform distribution related functions to accept Eigen expressions. 

## Checklist

- [ ] Math issue #1470 

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
Hmm, this is only failing due to tight tolerances (in test_repeat_as_vector second order gradients differ by 2.2e-14). @bbbales2 Is it possible to increase tolerances just for one function?

**Comment by bbbales2** [comment]
Yeah this seems a bit weird. I want some time to look at it.

The error went away when I changed the first lcdf test case to:

```
    param[0] = 1.1;   // y                                                                                                                                                   
    param[1] = -0.1;  // alpha                                                                                                                                               
    param[2] = 5.0;   // beta                                                                                                                                                
    parameters.push_back(param);
    cdf_log.push_back(std::log(1.2 / 5.1));  // expected cdf_log 
```

from:

```
    param[0] = 0.1;   // y                                                                                                                                                   
    param[1] = -0.1;  // alpha                                                                                                                                               
    param[2] = 5.0;   // beta                                                                                                                                                
    parameters.push_back(param);
    cdf_log.push_back(std::log(0.2 / 5.1));  // expected cdf_log 
```

It seems weird that that would have made so much of a difference for such simple functions. Anyway I will get to this after the release is sorted out.

**Comment by t4c1** [comment]
@bbbales2 Do you have time to look into this now?

**Comment by bbbales2** [comment]
@t4c1 yeah. I guess with release out no excuse to procrastinate

**Comment by bbbales2** [comment]
Alright I am confused. I was trying to simplify the computations a bit in the hopes that this went away and I am stuck.

The test I'm running is:
```
./runTests.py test/prob/uniform/uniform_cdf_log_00001_generated_v_test.cpp
```

If I replace:

```
ops_partials.edge1_.partials_ = inv(b_minus_a * cdf_log_n);
```

with:

```
ops_partials.edge1_.partials_ = inv(b_minus_a * (y_val - alpha_val) / b_minus_a);
```

Things work. If I replace it with:

```
ops_partials.edge1_.partials_ = inv(y_val - alpha_val);
```

The test fails. I have tried evaluating this expression to a temporary.

Anyway I'm not sure what is going on. I will come back to this tomorrow with a fresh head and try again.

**Comment by bbbales2** [comment]
Alright got it, but Github didn't let me push to your branch. This code passes for me:

```cpp
  const auto& b_minus_a
      = to_ref_if<!is_constant_all<T_low, T_high>::value>(beta_val
                                                          - alpha_val);
  const auto& y_minus_alpha
      = to_ref_if<!is_constant_all<T_y, T_low>::value>(y_val - alpha_val);
  const auto& cdf_log_n = y_minus_alpha / b_minus_a;
  T_partials_return cdf_log = sum(log(cdf_log_n));

  if (!is_constant_all<T_y>::value) {
    if(!is_vector<T_y>::value &&
       is_vector<T_high>::value &&
       !is_vector<T_low>::value) {
      ops_partials.edge1_.partials_ = size(beta) * inv(y_minus_alpha);
    } else {
      ops_partials.edge1_.partials_ = inv(y_minus_alpha);
    }
  }
  if (!is_constant_all<T_low>::value) {
    ops_partials.edge2_.partials_
        = (y_val - beta_val) / (b_minus_a * y_minus_alpha);
  }
  if (!is_constant_all<T_high>::value) {
    if (is_vector<T_y>::value && !is_vector<T_low>::value
        && !is_vector<T_high>::value) {
      ops_partials.edge3_.partials_
          = inv(-b_minus_a) * size(y);
    } else {
      ops_partials.edge3_.partials_ = inv(-b_minus_a);
    }
  }
```

It replaces `cdf_log_n * b_minus_a` with `y_minus_alpha` (which is `y_val - alpha_val`).

**Review by bbbales2 — APPROVED** [review]
Good!

**Pull request merged**
