### PR TITLE
Flatten: add stan/math/prim/meta.hpp, stan/math/rev/meta.hpp, stan/math/fwd/meta.hpp, stan/math/mix/meta.hpp

### PR DESCRIPTION
**Pull request by syclik**
## Summary

One step in getting closer to the flatten refactor. This PR adds four `meta.hpp` headers that the existing headers can include.

The goal of this PR is to create a seam (described in "Working with Legacy Code") which will allow us to work on flattening meta independently of everything else. The meta traits is the complicated, order-dependent piece of the code, so separating that out will make this easier.

This is only one step in flattening the dependency structure.

## More detail

The four new headers added are:

1. `stan/math/prim/meta.hpp`; included by `stan/math/prim/{scal, arr, mat}.hpp`
2. `stan/math/rev/meta.hpp`; included by `stan/math/rev/{scal, arr, mat}.hpp`
3. `stan/math/fwd/meta.hpp`; included by `stan/math/fwd/{scal, arr, mat}.hpp`
4. `stan/math/mix/meta.hpp`; included by `stan/math/mix/{scal, arr, mat}.hpp`

There is a side effect: by including `stan/math/prim/scal.hpp`, this will now instantiate the meta traits for matrix, so it does include Eigen. This is intended behavior and this is what will happen eventually when the refactor is done.

## Tests

All existing tests pass with this PR.

Two tests had to change, correctly, for this to work:
1. test/unit/math/prim/scal/meta/is_var_or_arihtmetic_test.cpp
2. test/unit/math/rev/scal/meta/VectorBuilderHelper_test.cpp

These tests were explicitly testing that without explicit instantiations of traits for `Eigen::Matrix` or `std::vector` it would call the base templated functions that have different behavior.

## Side Effects

With this PR, all the big header files will include `std::vector` and `Eigen::Matrix`. From a client perspective, the behavior of almost everything won't change. Some of the traits behavior does change (default behavior vs. template instantiation), but we wouldn't have encouraged clients to use these things directly.

This will simplify how add new traits.

## Notes to the reviewer

It's a little hard to see what's going on with the github interface. On a high level, what's happened is:
1. the includes for meta traits in `stan/math/prim/mat.hpp` were moved to `stan/math/prim/meta.hpp` (that's just all the includes). I had to trace through what those meta traits included and also moved all that into `stan/math/prim/meta.hpp`. So you'll see all the meta traits included there.
2. the explicit includes for the meta traits in `stan/math/prim/{scal, arr, mat}.hpp` have now been replaced with `stan/math/prim/meta.hpp`.
3. this process was repeated for `rev`, `fwd`, and `mix`.

## Checklist

- [x] Math issue #937; this is just one part

- [x] Copyright holder: Generable

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by roualdes** [comment]
@syclik, would you double check my understanding of your thinking with this PR with regards to "Working with Legacy Code"?  

This PR creates a seam, ensuring the meta traits are ordered correctly, so that each time we (later) flatten an `#include`, from say `#include <stan/math/prim/scal/meta/contains_std_vector.hpp>` to `#include <stan/math/prim/meta.hpp>`, nothing will break.  Each to-be flattened `#include` is thus an enabling point that is guaranteed to be flattened smoothly.  Correct?

**Comment by drezap** [comment]
I think he's on vacation, let's give him some time

**Comment by syclik** [comment]
@roualdes: yes. This was the first step. I believe the next steps could be:
1. replace all direct includes of any meta traits files inside any test files with the `stan/math/*/meta.hpp` that's appropriate. (this will really complete the seam)
2. flatten the meta source directory
3. (could be done in parallel with 3) flatten every other directory
4. flatten tests

**Comment by drezap** [comment]
Also, forget what I said above. Clearly did not put enough thought into that...

**Comment by drezap** [comment]
Do we want to merge this?

**Comment by syclik** [comment]
Yes, I think it's ok. There are no I'll side effects and it's a stand-alone
change. Do you see any problems with it?

**Comment by drezap** [comment]
@syclik There's no problems. I've added the missing include in the next step (prim/meta.hpp apply_scalar_unary.hpp I think it was).

I've also completed the next step for fwd, rev mix and prim, so after this is merged I can open the next PR immediately. I branched it off of this branch. `feature/issue-937-flatten-meta`.

**Comment by syclik** [comment]
Thanks!

**Pull request merged**
