### PR TITLE
Squashes compiler warnings from a recent PR merge

### PR DESCRIPTION
**Pull request by syclik**
## Summary
Squashing compiler warnings from a recent PR merge. Our continuous integration allowed it to pass. We'll have to find out why that's happening. (It could be a compiler version difference or configuration.)

## Tests

```
$ make stan/math/fwd/scal/fun/log_falling_factorial.hpp-test CXX="clang++ -Werror"
clang++ -Werror -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.66.0 -I lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -O0 -include stan/math/fwd/scal/fun/log_falling_factorial.hpp test/dummy.cpp -o /dev/null
```

This has 0 errors.

## Side Effects

None

## Checklist

- [x] Math issue #1110

- [x] Copyright holder: 

Generable

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by syclik** [comment]
This isn't getting past the `GoodGammaP` tests.

Anyone have an idea why these are failing? Is this an interaction with MPI?

**Comment by seantalts** [comment]
@bgoodri and I were just talking about it / working on it. It's something to do with gcc 7, which the MPI tests use because they always use the system compiler right now (as recommended by @wds15). Ben is running the full unit tests locally with GCC 8 as that compiler doesn't seem to trigger this failure. GCC 7 with `-O2` also doesn't trigger this failure. So a theory is that there is a gcc7 bug we've stumbled into only on high optimization and we may be able to just run tests with 8.

**Comment by seantalts** [comment]
Okay, for now I got us up on a cheaper EC2 spot instance that I think might work. Will test by re-running the tests for this PR :P

**Comment by syclik** [comment]
Thanks!

**Comment by bgoodri** [comment]
There is still some bug with autodiff_tester under mix with g++-8, although it gets past the gamma_p thing and passes test/unit/math/{prim, rev, fwd}. The new error is 
```
make: 'test/unit/math/mix/core/operator_addition_test' is up to date.
Running main() from lib/gtest_1.8.1/src/gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from mathMixCore
[ RUN      ] mathMixCore.opratorAddition
./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102842023e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102842023e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102845976e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102845976e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102849928e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102849928e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(-nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(-nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

[  FAILED  ] mathMixCore.opratorAddition (2 ms)
[----------] 1 test from mathMixCore (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] mathMixCore.opratorAddition

 1 FAILED TEST
------------------------------------------------------------
make -j1 test/unit/math/mix/core/operator_addition_test
------------------------------------------------------------
test/unit/math/mix/core/operator_addition_test --gtest_output="xml:test/unit/math/mix/core/operator_addition_test.xml"
```
which looks like pure uninitialized / undefined mistakes somewhere.

**Comment by seantalts** [comment]
I'm gonna copy all the relevant stuff to #1063, sorry for cross-posting.

**Pull request merged**
