### PR TITLE
makefile cleanup: replace "if [[" syntax with make ifs

### LINKED ISSUE #1839: makefile - specify SHELL=/bin/bash
#### Summary:
Our makefiles use bash syntax for string comparison, therefore set makefile var `SHELL` accordingly.

#### Description:
problem:  https://github.com/stan-dev/cmdstan/issues/852#issuecomment-613713061
solution: https://github.com/stan-dev/cmdstan/issues/852#issuecomment-613717625

#### Reproducible Steps:
Reproduce on Ubuntu - run `make build`

#### Current Output:
see linked comments

#### Expected Output:
make should build without errors or warnings.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.22

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Fixes #1839 by replacing the "if [[ " syntax that uses shell with make ifeq and ifneq syntax.

## Tests

/

## Side Effects

/

## Release notes

Removed the "/bin/sh: 1: [[: not found" warning on Linux.

## Checklist

- [x] Math issue #1836 

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by wds15** [comment]
I am not sure if this will work. The `=~` syntax is a regular expression as I recall. Testing for equality won't work - or is the MAKE variable here standardised?

**Comment by rok-cesnovar** [comment]
Rebooting to Windows right to check exactly that.

**Comment by wds15** [comment]
Windows takes long to boot! :D

**Comment by rok-cesnovar** [comment]
Haha. Didnt follow up. As you said and jenkins also shows, this doesnt work. Trying to workout a solution if possible. Otherwise only the outer if will be reworked.

**Comment by rok-cesnovar** [comment]
Ok, @mitzimorris found a more general solution. Closing this.

**Pull request closed without merging**
