### PR TITLE
[Do Not Merge] update to eigen 3.4-rc1

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

Updates Eigen to 3.4-rc1 to test and report any issues downstream.

## Tests

No new tests

## Side Effects

See the release page for the updates to 3.4

https://eigen.tuxfamily.org/index.php?title=3.4

## Release notes

None

## Checklist

- [x] Math issue #2474 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
uh oh, can anyone with access to rtools 3.5 make a minimum reproducible example of the below? I'm pretty sure this is just because mingw's gcc 4.9.3 does not have a full impl of c++14 (c++1y) so a file that includes `Eigen/Dense` should work and does like an addition should work. 

I'm not sure if this is an Eigen issue or an rtools issue. Eigen says they now require at least a C++14 compliant compiler so that would make this an R issue

```
In file included from lib/eigen_3.4_rc1/Eigen/Core:167:0,
                 from lib/eigen_3.4_rc1/Eigen/Dense:1,
                 from ./stan/math/prim/fun/Eigen.hpp:22,
                 from ./stan/math/prim/meta/append_return_type.hpp:4,
                 from ./stan/math/prim/meta.hpp:176,
                 from ./stan/math/fwd/core/fvar.hpp:4,
                 from ./stan/math/fwd/core.hpp:4,
                 from ./stan/math/mix/meta.hpp:6,
                 from ./stan/math/mix.hpp:8,
                 from ./test/unit/math/test_ad.hpp:4,
                 from test/unit/math/mix/fun/abs_test.cpp:1:
lib/eigen_3.4_rc1/Eigen/src/Core/util/IntegralConstant.h:189:36: error: template declaration of 'const Eigen::internal::FixedInt<N> Eigen::fix'
 static const internal::FixedInt<N> fix{};
                                    ^
In file included from lib/eigen_3.4_rc1/Eigen/Core:265:0,
                 from lib/eigen_3.4_rc1/Eigen/Dense:1,
                 from ./stan/math/prim/fun/Eigen.hpp:22,
                 from ./stan/math/prim/meta/append_return_type.hpp:4,
                 from ./stan/math/prim/meta.hpp:176,
                 from ./stan/math/fwd/core/fvar.hpp:4,
                 from ./stan/math/fwd/core.hpp:4,
                 from ./stan/math/mix/meta.hpp:6,
                 from ./stan/math/mix.hpp:8,
                 from ./test/unit/math/test_ad.hpp:4,
                 from test/unit/math/mix/fun/abs_test.cpp:1:
lib/eigen_3.4_rc1/Eigen/src/Core/util/IndexedViewHelper.h:57:147: error: 'fix' was not declared in this scope
 static const symbolic::AddExpr<symbolic::SymbolExpr<internal::symbolic_last_tag>,symbolic::ValueExpr<Eigen::internal::FixedInt<1> > > lastp1(last+fix<1>());
```

**Comment by rok-cesnovar** [comment]
Can confirm, seeing the same error with the Math tests.

**Comment by SteveBronder** [comment]
@rok-cesnovar should we bump up the r-tools version we are testing against since R bumped up to 4.0 as the last version? I think that would fix the error we are seeing in the RC (but then of course we won't support Rtools 3.5)

**Comment by SteveBronder** [comment]
Wait nvm just realized the 3.4-rc doesn't have the fix I added for the `fix<>` Eigen thing

**Comment by rok-cesnovar** [comment]
> @rok-cesnovar should we bump up the r-tools version we are testing against since R bumped up to 4.0 as the last version? I think that would fix the error we are seeing in the RC (but then of course we won't support Rtools 3.5)

I am definitely all for it, see https://github.com/stan-dev/math/issues/2489

**Pull request closed without merging**
