### PR TITLE
Feature/issue 292 integrate ode

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Changes the names of:
- `integrate_ode` to `integrate_ode_rk45`
- `integrate_cvode` to `integrate_ode_bdf`

Exposes additional parameters to both functions.

#### How to Verify:

Run tests.

#### Side Effects:

Language will need to change. See stan-dev/stan#1886.

#### Documentation:

Some doxygen doc included.

#### Reviewer Suggestions: 

Anyone. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
We should check what happens if users give a negative abs+rel tol or max_num_steps... odeint should throw an error then, I guess.

**Comment by syclik** [comment]
The failure is fine. It's due to the language needing to be updated.

**Comment by syclik** [comment]
@wds15, you're right.

**Comment by bob-carpenter** [comment]
Code looks good, so I'm going to merge because the language needs to be updated from the higher level.

**Pull request merged**
