### PR TITLE
Merge release/v4.6.2 into master

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
## Summary

Merge release/v4.6.2 into master

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by WardBrian** [comment]
https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStan/detail/downstream_hotfix/9/pipeline seems to be holding this up, it's not clear to me why

**Comment by serban-nicusor-toptal** [comment]
I see a bunch of:
```
ld: error: undefined symbol: N_VMake_Serial
ld: error: undefined symbol: SUNDenseMatrix
ld: error: undefined symbol: SUNLinSol_Dense
ld: error: undefined symbol: N_VCloneEmptyVectorArray
ld: error: undefined symbol: CVodeCreate
ld: error: undefined symbol: CVodeInit
ld: error: undefined symbol: CVodeSetUserData
...
```
might be related to https://github.com/stan-dev/cmdstan/issues/716

**Comment by WardBrian** [comment]
It looks like clang just isn't being passed the path to the build sundials libraries. 

What branch of `stan` is the `downstream_hotfix` jenkins being run against?

**Comment by serban-nicusor-toptal** [comment]
`downstream_hotfix` of `stan` is targeting develop.

**Comment by WardBrian** [comment]
I think the issue is because of #2885 etc, when we changed the naming of some of our make variables. Obviously, the fact that `develop` and the releases still work means that the current state of things is a happy one, but this CI seems to be creating an unhappy mix between before/after 

It looks like this is checking out https://github.com/stan-dev/cmdstan/tree/downstream_hotfix, which is ~280 commits behind develop

**Comment by serban-nicusor-toptal** [comment]
Ouch, we have this issue on stan too I think. For now, I can merge develop in so this CI passes.
Now, for the future. Should I make an additional step in the pipeline to always update that branch on a new commit to develop or should we just simply use `develop` instead of `downstream_hotfix` ?

**Pull request merged**
