### PR TITLE
Allow users to specify lib & include paths for all dependencies

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR adds the ability for users to specify the include and library paths for all dependencies, identical to that provided by the `TBB_INC` and `TBB_LIB` flags.

This will also eventually be used for linking against system-installed versions of the dependencies

## Tests

N/A

## Side Effects

N/A

## Release notes
Add ability for users to specify directories for dependencies

## Checklist

- [x] Math issue #2518 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by andrjohns** [comment]
@hsbadr would you mind reviewing this one when you get a minute? The implementation should be consistent with how `TBB_LIB` and `TBB_INC` are handled, so I want to make sure I haven't missed anything. Thanks!

**Comment by hsbadr** [comment]
> @hsbadr would you mind reviewing this one when you get a minute? The implementation should be consistent with how `TBB_LIB` and `TBB_INC` are handled, so I want to make sure I haven't missed anything. Thanks!

@andrjohns Sorry for the late reply. I'm willing to review this, but I'll be available after the 1st week of March.

**Comment by andrjohns** [comment]
No worries at all! There's no rush on any of this, so just whenever you've got the time

**Comment by riddell-stan** [comment]
Thanks for working on this. This would allow one, in theory, to package pystan/httpstan for Debian/Ubuntu/Redhat, etc.

**Comment by andrjohns** [comment]
> Thanks for working on this. This would allow one, in theory, to package pystan/httpstan for Debian/Ubuntu/Redhat, etc.

Yep exactly! I'll initially be packaging `cmdstan` for Debian/Ubuntu, but it shouldn't be too difficult to generalise the same process to `httpstan`/`pystan`

**Comment by hsbadr** [comment]
> identical to that provided by the `TBB_INC` and `TBB_LIB` flags

@andrjohns My concern here is the lack of version compatibility checks. Unlike TBB where we support all versions with `TBB_INTERFACE_NEW` macro, we may need to check if the version of user-provided Eigen, for example, is compatible. We might leave this to the users though, assuming that it's an advanced feature. What do you think?

**Comment by riddell-stan** [comment]
This is somewhat related. If math can support the versions of Eigen etc shipped in the most recent release of Debian and/or Rocky Linux (fka Centos), I suspect you'd have many happy users, even without additional compatibility checks.

**Comment by andrjohns** [comment]
Thanks Hamada! Let me have a look into the version compatibility. From past experience, I believe the issue is mostly with sundials, since the distribution package versions are generally pretty far behind the Stan version. Eigen is pretty fine, since the features we use (AFAIK) have been pretty standard since ~3.3.3, but I'll do some checking for all of them

**Comment by WardBrian** [comment]
I just wanted to add that this approach would be very useful for packaging on Conda as well - the current conda build uses the TBB variables to avoid several issues we had compiling in the conda CI

**Comment by andrjohns** [comment]
Closing for now to clear PR backlog, will re-open once ready for review

**Comment by WardBrian** [comment]
@andrjohns how would you feel about re-opening this before the next release? I'm thinking specifically for Conda, rather than system package managers, which can do the version checking outside our makefiles (and has all the versions we use currently available).

I also think being able to link to an external tbb and sundials might let us compile stan using MSVC. Those have been the biggest road blocks when I tried previously.

**Comment by andrjohns** [comment]
Sounds good to me! When is the next release?

**Comment by WardBrian** [comment]
I believe it will be early November

**Comment by andrjohns** [comment]
Thanks, will look to have this updated over the next couple weeks then

**Comment by rok-cesnovar** [comment]
I was thinking of doing the release candidate on the first Monday in November, which is the 7th.

**Pull request closed without merging**
