### PR TITLE
Feature/0253 sort nan check

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

* `sort_asc()` and `sort_desc()` throw `std::domain_error` when given NaN inputs.
* split `sort_asc` and `sort_desc` into vector and matrix versions in their own files
* removed non-primitive versions (they were redundant)
* added tests for prim, rev, fwd, and mix modes

#### How to Verify:

Unit tests.

#### Side Effects:

Previous programs relying on NaN in sorts not to throw will now reject.

#### Documentation:

No.

#### Reviewer Suggestions: 

Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Looks great. Thanks, Bob.

**Comment by bob-carpenter** [comment]
@syclik Did you abort this build on purpose?  I didn't see where it failed.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Sorry -- that was my fault. It wasn't meant to be aborted.

Something with the Jenkins config got screwed up and it ran out of disk
space. I just restarted it.

**Pull request merged**
