### PR TITLE
solve pde

### PR DESCRIPTION
**Pull request by yizhang-cae**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Support external PDE library through `forward_pde` function.

#### Intended Effect:
Address the issue https://github.com/stan-dev/stan/issues/2567 and #931 for supporting external PDE solvers. The name reflects the functionality of a forward mapping from parameter `theta` to a quantity of interest output. Since the output is not intended to be the numerical solution of PDE, the alternative name `solve_pde` is not adopted.

The effect of the function is to link with external header, issued through makefile option
`EXTERN_PDE_MAKEFILE`, where the PDE functor is defined. The PDE functor takes the form
```Stan
real[,] foobar(real[] theta, int need_sens, real[] x_r, real[] x_i)
```
returning an array of vectors, with each vector in the form
```Stan
[QoI1] /* no-sensitivity version, used for prim */
[QoI1, d(QoI1)/d(theta1), d(QoI1)/d(theta2), ...]/*with-sensitivity version, used for rev*/
```
To make a model `foo` that involves `forward_pde`, use
```bash
make foo WITH_EXTERN_PDE=1 EXTERN_PDE_MAKEFILE=/path/to/user/provided/makefile
```

`WITH_EXTERN_PDE` in `Makefile` defines macro
```bash
CXXFLAGS += -DSTAN_EXTERN_PDE
```
This macro limits the `forward_pde`'s definition:
```c++
#ifdef STAN_EXTERN_PDE
  template<typename F_pde, typename T>
  inline std::vector<T> forward_pde(/*...
*/
#endif
```
so that only when `WITH_EXTERN_PDE` is used and external header is provided will `forward_pde` be effective. This way we can enforce the intended use of `forward_pde`.

#### How to Verify:
Unit test

`forward_pde_dummy_test.cpp` tests `forward_pde` by its function signature. 

#### Side Effects:
None

#### Documentation:
doxygen

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Metrum Research Group, LLC

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@yizhang-cae -- mind if we discussed the use of macros for this PR? I think we're going a bit wild now. Up until recently, we've managed to get by without the use of preprocessor macros and I think we should try to continue that.

What's this macro you've defined? It's not mentioned in your PR comment.

**Comment by yizhang-cae** [comment]
I've added the explanation of the macro use in PR.

**Comment by yizhang-cae** [comment]
renamed to `solve_pde` per @syclik 's comment.

**Comment by syclik** [comment]
@yizhang-cae, what does the user need to do in order to make this work? Are there instructions on installing something before this works? That documentation must be included somewhere. Just adding doxygen doc here isn't sufficient.

**Comment by yizhang-cae** [comment]
@syclik , for math repo, the user does not need to do anything. Just like `integrate_ode`. For Stan lang the user should use `--allow_undefined` switch. But that should go into the doc of Stan repo. Right?

**Comment by syclik** [comment]
I don’t get it. A couple asks:
1. Can you update the original issue to reflect current names and make it
clear what you’re trying to do?
2. Could you explain what you’re trying to do a little clearer?

Based on what I read in the issue, I thought you were trying to integrate a
few PDE libraries into the Math library. The last comment has me very
confused.

How does this affect users? How does this affect our code base?

**Comment by yizhang-cae** [comment]
I've updated the issue.

**Comment by yizhang-cae** [comment]
> How does this affect users? How does this affect our code base?

To users this allows them to run Stan with their own C++ PDE model, without asking them to use `stan::math::var` in their code.

To our code base the impact is minimum, as it does not require Stan to carry new libraries, and the mechanism is largely already available(external C++ code through `user_header.hpp`).

**Comment by syclik** [comment]
can you write an issue in Math with the spec? I still don’t quite understand and I think breaking it down into Math, Stan, CmdStan issues would help immensely. 

For example, there’s no `user_header.hpp` in the math library. I don’t understand how that factors into the math library.

**Comment by yizhang-cae** [comment]
Added issue #931

**Comment by yizhang-cae** [comment]
Changed name to `forward_pde` per discussions at #931 . Also removed the makefile switch `WITH_EXTERN_PDE` and `EXTERN_PDE_MAKEFILE` till further discussion.

**Comment by yizhang-cae** [comment]
Hi @syclik , I've renamed `pde` to `pde_qoi` in `forward_pde`'s signature. Let me know if that's OK. Thx.

**Comment by syclik** [comment]
@yizhang-cae, sorry about the delay on the review.

Can you update the first post in both this and the issue ([#931](https://github.com/stan-dev/math/issues/931#issue-340009898))?

It looks like you didn't push -- hopefully you still have the branch: it's still called `forward_pde`. Would you also be able to document what the function actually does? There's no description of what "solving a PDE" actually means.

(Personally, I'm getting lost in what it's trying to do. There's a PDE, there's a solve_pde function, and then there's a QOI. I want to make sure it's clear in our doc what is going on at the C++ level so there's no confusion.)

**Comment by syclik** [comment]
@yizhang-cae, just checking that you saw that the action is currently on you.

**Comment by syclik** [comment]
@yizhang-cae, I'm closing this PR for now. Please reopen when there's been progress on the makefile.

**Pull request closed without merging**
