### PR TITLE
deleted cvode and replaced by cvodes, still with coupled ode system; all

### PR DESCRIPTION
**Pull request by wds15**
#### Submisison Checklist

- [X] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
swap cvode for cvodes library

#### Intended Effect:
only change library, not any ode stan functions

#### How to Verify:
check source

#### Side Effects:
none

#### Documentation:
none

#### Reviewer Suggestions: 
Anyone

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Sebastian Weber

By submitting this pull request, the copyright holder is requiring to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

cvode tests still work

### CODE REVIEW

**Comment by wds15** [comment]
From what I can see this breaks now because the build systems needs to point to CVODES instead of CVODE in the upstream dependencies stan and cmdstan. On both repos I have opened branches which adjust the build system. If we merge these in sequence then thinks should work again.

**Comment by syclik** [comment]
Thanks, Sebastian. That explains a lot. What order does it need (pull request numbers please)?

I just realized that there should be a way to do this without breaking the builds. Let me look at that. It should be in the makefile in math for the libraries.

**Comment by wds15** [comment]
Yes, the way things are now is not ideal... I created the pulls you ask for:

stan: 1863
cmdstan: 370

**Comment by wds15** [comment]
forgot your order: first math, then stan, then cmdstan

**Comment by syclik** [comment]
I meant just add CVODES without removing CVODE; that would have not caused a build problem. But it should be ok, I think.

**Comment by syclik** [comment]
Which math pull request? There are 3 open ones now.

**Comment by wds15** [comment]
sorry, if I misunderstood. What I did is to remove the CVODE library and I replaced it with CVODES. However, integrate_ode_cvode still works; just now with CVODES sources.

The pull for math is this one, 282.

The outdated pull request on math is 279, but I would keep it for now as the comments are there.

The pull request which adds the integrate_ode_cvodes function in a clean way (and leaves integrate_ode_cvode intact) is 283, but there I still have to add some doc, feedback is very welcome there of course.

**Comment by syclik** [comment]
Great. I looked through it. This is known to break upstream builds. I'm merging.

**Pull request merged**
