### PR TITLE
Fix size() and namespace lookups so that we can compile with C++17

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

This adds `math::` in front of calls to stan math's `apply()`, `size()`, and `for_each()` functions so that C++17's std functions are not used during ADL lookup. This should also fix the bug in #2474 so we can update to Eigen 3.4. This also makes all the `size()` functions return `Eigen::Index` so that we have a consistent definition of the size we use in stan math. If we don't have a consistent return for `size()` we can end up having compiler errors for functions like `std::max({size_t, int, long int})` since there will be different integer types in the initializer list.

NOTE: I'm running this first with C++17 as the default std version in the makefiles just to make sure everything passes. Once we get a green light once I'm going to switch that back to `std=c++1y`

## Tests

No new tests 

## Side Effects

One nice thing is that if we ever want to change the default index type we use we can just override `Eigen::Index` to be another integer type.

## Release notes

Make stan math more easily compilable with C++17

## Checklist

- [ ] Math issue #(issue number)

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Oh man, `std::apply` is also a thing :) 

Minor Q, but should we just use the entire namespace (`stan::math::`) and not `math::`?

**Comment by SteveBronder** [comment]
@hsbadr Thanks, done!

**Comment by hsbadr** [comment]
> @hsbadr Thanks, done!

Thank you! I confirm that the above model is successfully compiled after c5e7916dda3fbe1adaa524b69707c1f087360fec. I'll let you know if I run into any related issue.

**Comment by SteveBronder** [comment]
@rok-cesnovar very odd, on develop if I add the `CXXFLAGS+= -fsanitize=memory` and run 

```
./runTests.py -j24 ./test/unit/math/rev/core/accumulate_adjoints_test.cpp
```

I'm getting the same error as jenkins with this PR? It looks like it's something deep in gtest and nothing to do with us?

```
==529809==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x537339 in testing::internal::FilePath::Normalize() /home/steve/stan/origin/math/lib/benchmark_1.5.1/googletest/googletest/src/gtest-filepath.cc:358:16
    #1 0x540ee6 in testing::internal::FilePath::FilePath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/steve/stan/origin/math/lib/benchmark_1.5.1/googletest/googletest/include/gtest/internal/gtest-filepath.h:68:5
    #2 0x536403 in testing::internal::FilePath::GetCurrentDir() /home/steve/stan/origin/math/lib/benchmark_1.5.1/googletest/googletest/src/gtest-filepath.cc:112:10
    #3 0x546327 in testing::internal::UnitTestImpl::AddTestInfo(void (*)(), void (*)(), testing::TestInfo*) /home/steve/stan/origin/math/lib/benchmark_1.5.1/googletest/googletest/src/gtest-internal-inl.h:693:33
    #4 0x510b1b in testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*) /home/steve/stan/origin/math/lib/benchmark_1.5.1/googletest/googletest/src/gtest.cc:2770:22
    #5 0x423530 in __cxx_global_var_init.14 /home/steve/stan/origin/math/test/unit/math/rev/core/accumulate_adjoints_test.cpp:6:1
    #6 0x426c11 in _GLOBAL__sub_I_accumulate_adjoints_test.cpp /home/steve/stan/origin/math/test/unit/math/rev/core/accumulate_adjoints_test.cpp
    #7 0x575f2c in __libc_csu_init (/home/steve/stan/origin/math/test/unit/math/rev/core/accumulate_adjoints_test+0x575f2c)
    #8 0x7f39bee9f03f in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:264:6
    #9 0x4282fd in _start (/home/steve/stan/origin/math/test/unit/math/rev/core/accumulate_adjoints_test+0x4282fd)
```

This seems to happen when I tested it on clang-12 and 10

**Comment by SteveBronder** [comment]
Oh sorry ignore the above that's a different error with `-fsanitize=memory`. I can't replicate the wild pointer thing locally?

**Comment by andrjohns** [comment]
Anything else to go into this one? I can review when it's ready

**Comment by andrjohns** [comment]
@serban-nicusor-toptal I'm running into the leak sanitizer CI issues with this PR that haven't been resolved by the switch to Docker and that I can't reproduce locally - even when I run the same commands in the same docker image (`stanorg/ci:gpu`):
```
test/unit/math_c11_test --gtest_output="xml:test/unit/math_c11_test.xml"
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MathMeta
[ RUN      ] MathMeta.ensure_c11_features_present
[       OK ] MathMeta.ensure_c11_features_present (0 ms)
[----------] 1 test from MathMeta (0 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
==14091==LeakSanitizer has encountered a fatal error.
==14091==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==14091==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
test/unit/math_c11_test --gtest_output="xml:test/unit/math_c11_test.xml" failed
exit now (03/27/22 09:52:55 EDT)
script returned exit code 1
```

When you've got a minute, would you mind having a look to see if anything obvious stands out or if you're able to reproduce?

**Comment by serban-nicusor-toptal** [comment]
I will run some tests and try to see what's different.
Could this be affected by the CPU? If I remember right we had some issues with OpenCL tests because some instructions are not supported by the CPU.
You can also take a look at the [CI Dockerfile](https://github.com/stan-dev/ci-scripts/blob/master/docker/ci/Dockerfile-gpu) maybe something stands out?

**Comment by rok-cesnovar** [comment]
We probably don't need the test that is causing the sanitizer failures, though it doesn't seem like it should cause issues here.

**Comment by andrjohns** [comment]
The strange thing is that it doesn't fail when I run the tests in the docker image locally, so I'm not sure what's different about the Jenkins setup

**Comment by andrjohns** [comment]
I'll also try splitting this out into smaller PRs to see if I can narrow down the issue, and also make it easier to review and merge

**Comment by serban-nicusor-toptal** [comment]
It might be either a permission issue or a hardware component.

**Pull request closed without merging**
