### PR TITLE
update Eigen to 3.3.7

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

Update to [Eigen 3.3.7](https://gitlab.com/libeigen/eigen/-/releases)

## Tests

Nope

## Side Effects

See [changelog](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.7) for Eigen-3.3.7 to 3.3.4

## Release notes

Updates to Eigen 3.3.7

## Checklist

- [x] Math issue #1831 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
Interesting I ran this locally and it had differences in the performance test values. Though just the gp regressions

```
'stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan' had fails '[
('alpha', 2.920135049999999, 18.540298341060065, 2.9283748499999995), 
('f.1', 3.627528409999997, 0.756913153171094, 3.6401974300000024), 
('f.10', 4.41315604, 0.270125859853313, 4.41202603), 
('f.11', 3.503555349999998, 0.850970751982515, 3.5037961699999984), 
('f.2', 3.688993120000003, 0.530362834944364, 3.6886584700000027), 
('f.3', 3.25337608999999, 0.664171997709137, 3.249774899999996), 
('f.4', 2.403422409999997, 1.145131596752016, 2.4005031500000023), 
('f.5', 1.557477504999999, 1.730479258131914, 1.5553106479999974), 
('f.6', 1.297967311, 2.09885634209109, 1.2966479270000015), 
('f.7', 1.935838380000001, 1.605790860449542, 1.9381271730000005), 
('f.8', 3.179500100000007, 0.691365096442897, 3.1863363000000033), 
('f.9', 4.249456869999999, 0.302184045899602, 4.255285080000002), 
('f_tilde.1', 1.323766740999999, 3.494304439588376, 1.3296791219999993), 
('f_tilde.10', -0.156594395485, 27.45328717289587, -0.1743439654100001), 
('f_tilde.11', -0.0054466386, 29.8711903373676, -0.0028911465369999925), 
('f_tilde.2', 0.307209402191, 1.349968592575885, 0.29279222066099964), 
('f_tilde.3', -0.171471833563, 8.394883794269306, -0.14112206251099998), 
('f_tilde.4', -0.208914547139, 12.755676430619914, -0.2519115671526003), 
('f_tilde.5', 1.13457613868, 21.753280995337246, 1.1651720248099997), 
('f_tilde.6', 1.428728819000002, 20.666757028605048, 1.410099512349999), 
('f_tilde.7', 0.63805414797, 26.338792486337937, 0.6605756808100002), 
('f_tilde.8', -0.16909139756, 24.889478667880606, -0.1745231609899998), 
('f_tilde.9', -0.47228225771, 19.479238435583238, -0.4615194775170006), 
('rho', 5.670243959999998, 14.009375369434585, 5.662270539999999)]' and errors '[]'
'stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan' had fails '[
('alpha', 2.426651183, 21.19973924035896, 2.4497043740000013), 
('rho', 6.884837290000009, 53.93639364660384, 6.838392209999993), 
('sigma', 1.822472106000002, 7.936252311143344, 1.8462506189999985)]' and errors '[]'
```

**Comment by SteveBronder** [comment]
It must be something in `gp_exp_quad_cov` since alpha and rho are the offenders between the two

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal is the number on the right of the abs bars the alternative branch's result when running `compare-git-hashes.sh`?
```
FAIL: golds/stat_comp_benchmarks_benchmarks_gp_pois_regr_gp_pois_regr.gold param f.3 |3.2497749 - 3.25337609| not within 2e-08
```

Cuz staring at those and the given estimated expectation values from [here](https://github.com/stan-dev/stat_comp_benchmarks/blob/master/empirical_results/nuts/gp_pois_regr.fit) in stat_comp_benchmarks it looks like the results with the new eigen are actually closer? @betanalpha are those numbers in `empirical results` the actual numbers we are shooting for?

**Comment by serban-nicusor-toptal** [comment]
It's base and target, if you're talking about this PR should be develop and this pr.

**Comment by SteveBronder** [comment]
Huh! If that's the case then I think this update gives much better estimations then before!

**Comment by serban-nicusor-toptal** [comment]
Hmh I think lower is better if I'm not wrong.

**Comment by SteveBronder** [comment]
I need to check with @betanalpha whether the values we are estimated mean values from [here](https://github.com/stan-dev/stat_comp_benchmarks/blob/master/empirical_results/nuts/gp_pois_regr.fit) are what we are trying to estimate.

The stuff above checks the current version of Stan vs. the PR, but the values in the link above are the estimated mean values we are actually targeting. If I'm reading this all correct then it looks like Eigen had some bug fixes that get us closer to the mean estimates

**Comment by betanalpha** [comment]
This is weird -- the `stat_comp_benchmarks` are based on expectation value estimators from very long Stan chains.  The original baseline values are saved in https://github.com/stan-dev/stat_comp_benchmarks/blob/master/empirical_results/nuts/gp_pois_regr.fit, but they don't seem to line up with either value in the current tests.

I would be surprised if Eigen had a bug that affected Cholesky or matrix multiplication this much.  Can you spot check to see what the before/after log density and gradient values are to decouple all of the Markov chain effects?

**Comment by betanalpha** [comment]
> The stuff above checks the current version of Stan vs. the PR, but the values in the link above are the estimated mean values we are actually targeting.

Sorry, I missed this last message.  

Yes we are trying to recover the values in the `stat_comp_benchmark` repo, but if that's the behavior of the current test then it's really just serving as a poorly-calibrated regression test.  Even small changes to the math library will cause at the MCMC estimators to fluctuate, and all we can expect is that the estimators are fluctuating within the MCMC standard errors (assuming a MCMC CLT exists).  

`2e-8` looks like a heuristic value, and one that is likely to be much smaller than the MCMC standard errors that we would get when running with Stan defaults.  I'm guess that this is a false positive and the variation between versions is completely within the MCMC standard error, but I would recommend fitting locally to investigate the quoted MCMC standard errors to be sure.

**Comment by SteveBronder** [comment]
> but I would recommend fitting locally to investigate the quoted MCMC standard errors to be sure.

Thanks Michael! I ran the tests locally, is there another script somewhere to update the params in `stat_comp_benchmarks` to then run `./evaluate`? I just eyeballed them and, relative to the current develop branch they seem closer.

**Comment by SteveBronder** [comment]
So I ran this locally for gp_pois_regr to look at the sample mcse [gist](https://gist.github.com/SteveBronder/8b2cff6d4eb32b283d205b90d264c2b0)


I think that these results are fine. My guess is that there were some stability improvements in Eigen's decomposition methods as most of the estimates now have a smaller mcse.

### Develop Cmdstan Summary

```
                    Mean     MCSE   StdDev        5%       50%    95%    N_Eff  N_Eff/s    R_hat
lp__             9.7e+02  7.9e-02  2.8e+00   9.6e+02   9.7e+02    973  1.3e+03  2.6e+02  1.0e+00
accept_stat__    9.3e-01  1.6e-02  1.2e-01   7.1e-01   9.7e-01   1.00  5.3e+01  1.1e+01  1.0e+00
stepsize__       2.7e-02  2.9e-03  4.2e-03   2.3e-02   2.8e-02  0.033  2.0e+00  4.1e-01  3.5e+13
treedepth__      7.1e+00  1.6e-01  5.8e-01   6.0e+00   7.0e+00    8.0  1.3e+01  2.6e+00  1.1e+00
n_leapfrog__     1.7e+02  2.4e+01  6.6e+01   7.6e+01   1.3e+02    255  7.3e+00  1.5e+00  1.2e+00
divergent__      2.7e-03      nan  5.2e-02   0.0e+00   0.0e+00   0.00      nan      nan      nan
energy__        -9.6e+02  1.1e-01  3.7e+00  -9.7e+02  -9.6e+02   -956  1.2e+03  2.5e+02  1.0e+00
rho              5.6e+00  1.8e-02  6.8e-01   4.6e+00   5.6e+00    6.8  1.5e+03  3.0e+02  1.0e+00
alpha            2.9e+00  2.0e-02  7.6e-01   1.8e+00   2.8e+00    4.3  1.5e+03  3.0e+02  1.0e+00
f_tilde[1]       1.3e+00  9.3e-03  3.5e-01   8.3e-01   1.3e+00    2.0  1.4e+03  2.9e+02  1.0e+00
f_tilde[2]       3.0e-01  4.3e-03  2.0e-01  -3.3e-03   2.9e-01   0.65  2.1e+03  4.3e+02  1.0e+00
f_tilde[3]      -1.3e-01  1.1e-02  5.0e-01  -9.8e-01  -1.1e-01   0.65  2.0e+03  4.1e+02  1.0e+00
f_tilde[4]      -2.5e-01  1.3e-02  6.1e-01  -1.2e+00  -2.5e-01   0.77  2.4e+03  4.8e+02  1.0e+00
f_tilde[5]       1.1e+00  1.7e-02  8.1e-01  -1.4e-01   1.1e+00    2.5  2.2e+03  4.4e+02  1.0e+00
f_tilde[6]       1.4e+00  1.5e-02  7.7e-01   1.7e-01   1.4e+00    2.7  2.6e+03  5.2e+02  1.0e+00
f_tilde[7]       6.9e-01  2.1e-02  9.4e-01  -9.4e-01   7.2e-01    2.2  2.1e+03  4.2e+02  1.0e+00
f_tilde[8]      -1.9e-01  1.8e-02  9.2e-01  -1.7e+00  -2.0e-01    1.3  2.5e+03  5.1e+02  1.0e+00
f_tilde[9]      -4.2e-01  1.4e-02  8.4e-01  -1.8e+00  -4.2e-01   0.93  3.7e+03  7.5e+02  1.0e+00
f_tilde[10]     -1.9e-01  1.6e-02  9.4e-01  -1.8e+00  -1.8e-01    1.3  3.5e+03  7.1e+02  1.0e+00
f_tilde[11]      4.1e-05  1.5e-02  9.7e-01  -1.6e+00  -4.2e-03    1.6  4.1e+03  8.3e+02  1.0e+00
f[1]             3.6e+00  2.3e-03  1.5e-01   3.4e+00   3.6e+00    3.9  4.2e+03  8.6e+02  1.0e+00
f[2]             3.7e+00  2.2e-03  1.3e-01   3.5e+00   3.7e+00    3.9  3.4e+03  6.9e+02  1.0e+00
f[3]             3.3e+00  2.1e-03  1.4e-01   3.0e+00   3.3e+00    3.5  4.5e+03  9.1e+02  1.0e+00
f[4]             2.4e+00  3.1e-03  1.9e-01   2.1e+00   2.4e+00    2.7  3.9e+03  7.9e+02  1.0e+00
f[5]             1.6e+00  4.0e-03  2.5e-01   1.1e+00   1.6e+00    1.9  3.8e+03  7.6e+02  1.0e+00
f[6]             1.3e+00  4.4e-03  2.7e-01   8.4e-01   1.3e+00    1.7  3.7e+03  7.4e+02  1.0e+00
f[7]             1.9e+00  3.8e-03  2.2e-01   1.6e+00   1.9e+00    2.3  3.5e+03  7.0e+02  1.0e+00
f[8]             3.2e+00  2.3e-03  1.5e-01   2.9e+00   3.2e+00    3.4  3.9e+03  7.9e+02  1.0e+00
f[9]             4.3e+00  1.5e-03  9.6e-02   4.1e+00   4.3e+00    4.4  3.9e+03  7.9e+02  1.0e+00
f[10]            4.4e+00  1.4e-03  9.1e-02   4.3e+00   4.4e+00    4.6  4.4e+03  8.9e+02  1.0e+00
f[11]            3.5e+00  2.6e-03  1.6e-01   3.2e+00   3.5e+00    3.8  4.0e+03  8.1e+02  1.0e+00
```

### This Branch Cmdstan Summary

```
                    Mean     MCSE   StdDev        5%    50%    95%    N_Eff  N_Eff/s    R_hat
lp__             9.7e+02  7.8e-02  2.8e+00   9.6e+02    969    973  1.3e+03  2.8e+02  1.0e+00
accept_stat__    9.2e-01  7.9e-03  1.3e-01   6.6e-01   0.97   1.00  2.7e+02  5.9e+01  1.0e+00
stepsize__       2.8e-02  1.4e-03  1.9e-03   2.6e-02  0.029  0.030  2.0e+00  4.4e-01  1.8e+13
treedepth__      7.0e+00  6.9e-02  4.8e-01   6.0e+00    7.0    8.0  4.9e+01  1.1e+01  1.0e+00
n_leapfrog__     1.5e+02  1.2e+01  6.0e+01   7.9e+01    127    255  2.3e+01  5.1e+00  1.1e+00
divergent__      3.5e-03      nan  5.9e-02   0.0e+00   0.00   0.00      nan      nan      nan
energy__        -9.6e+02  1.1e-01  3.8e+00  -9.7e+02   -963   -956  1.2e+03  2.6e+02  1.0e+00
rho              5.6e+00  2.0e-02  6.8e-01   4.5e+00    5.6    6.8  1.2e+03  2.7e+02  1.0e+00
alpha            2.9e+00  2.0e-02  7.7e-01   1.9e+00    2.8    4.3  1.4e+03  3.1e+02  1.0e+00
f_tilde[1]       1.3e+00  8.7e-03  3.4e-01   8.4e-01    1.3    1.9  1.5e+03  3.4e+02  1.0e+00
f_tilde[2]       3.0e-01  4.5e-03  2.0e-01  -1.7e-03   0.28   0.66  2.1e+03  4.5e+02  1.0e+00
f_tilde[3]      -1.3e-01  1.2e-02  5.0e-01  -9.9e-01  -0.11   0.68  1.7e+03  3.8e+02  1.0e+00
f_tilde[4]      -2.6e-01  1.3e-02  6.2e-01  -1.3e+00  -0.28   0.75  2.2e+03  4.8e+02  1.0e+00
f_tilde[5]       1.1e+00  1.6e-02  7.9e-01  -9.7e-02    1.1    2.5  2.4e+03  5.3e+02  1.0e+00
f_tilde[6]       1.4e+00  1.5e-02  7.8e-01   1.4e-01    1.4    2.7  2.8e+03  6.2e+02  1.0e+00
f_tilde[7]       6.9e-01  2.0e-02  9.3e-01  -8.9e-01   0.71    2.2  2.2e+03  4.8e+02  1.0e+00
f_tilde[8]      -1.8e-01  1.8e-02  9.0e-01  -1.6e+00  -0.19    1.3  2.4e+03  5.3e+02  1.0e+00
f_tilde[9]      -4.2e-01  1.4e-02  8.3e-01  -1.8e+00  -0.40   0.92  3.5e+03  7.7e+02  1.0e+00
f_tilde[10]     -1.9e-01  1.4e-02  9.1e-01  -1.7e+00  -0.19    1.2  4.2e+03  9.2e+02  1.0e+00
f_tilde[11]      7.9e-03  1.4e-02  1.0e+00  -1.7e+00  0.035    1.6  5.1e+03  1.1e+03  1.0e+00
f[1]             3.6e+00  2.4e-03  1.5e-01   3.4e+00    3.6    3.9  3.9e+03  8.6e+02  1.0e+00
f[2]             3.7e+00  2.3e-03  1.3e-01   3.5e+00    3.7    3.9  3.2e+03  7.1e+02  1.0e+00
f[3]             3.3e+00  2.2e-03  1.4e-01   3.0e+00    3.3    3.5  4.3e+03  9.6e+02  1.0e+00
f[4]             2.4e+00  3.1e-03  1.9e-01   2.1e+00    2.4    2.7  3.7e+03  8.3e+02  1.0e+00
f[5]             1.6e+00  3.9e-03  2.4e-01   1.2e+00    1.6    1.9  4.0e+03  8.8e+02  1.0e+00
f[6]             1.3e+00  4.2e-03  2.7e-01   8.3e-01    1.3    1.7  4.0e+03  8.9e+02  1.0e+00
f[7]             1.9e+00  3.6e-03  2.3e-01   1.5e+00    1.9    2.3  3.8e+03  8.4e+02  1.0e+00
f[8]             3.2e+00  2.3e-03  1.5e-01   2.9e+00    3.2    3.4  4.1e+03  9.1e+02  1.0e+00
f[9]             4.3e+00  1.6e-03  9.8e-02   4.1e+00    4.3    4.4  3.9e+03  8.7e+02  1.0e+00
f[10]            4.4e+00  1.4e-03  9.3e-02   4.3e+00    4.4    4.6  4.4e+03  9.6e+02  1.0e+00
f[11]            3.5e+00  2.6e-03  1.6e-01   3.2e+00    3.5    3.8  3.7e+03  8.1e+02  1.0e+00
```
Looking at a basic histogram there's nothing glaring that pops out

image

The below shows the difference mcse mean, median, 5th and 95th quantile, and sd mcse estimates as (pr - develop). So a negative number means the mcse of this pr is smaller than the develops mcse

|par         | x_mcse_mean| x_mcse_med| x_mcse_quan_low| x_mcse_quan_high|  x_mcse_sd|
|:-----------|-----------:|----------:|---------------:|----------------:|----------:|
|rho         |   0.0016149|  0.0026400|      -0.0111750|        0.0072950|  0.0011682|
|alpha       |   0.0004707|  0.0025500|      -0.0054700|        0.0188450|  0.0005084|
|f_tilde[1]  |  -0.0007515|  0.0036150|       0.0005795|       -0.0011050| -0.0005748|
|f_tilde[2]  |   0.0002290|  0.0003385|      -0.0040714|        0.0018375|  0.0003390|
|f_tilde[3]  |   0.0010961| -0.0015315|       0.0039490|        0.0002895|  0.0005837|
|f_tilde[4]  |   0.0008323| -0.0020420|      -0.0023050|        0.0090440|  0.0005887|
|f_tilde[5]  |  -0.0010557| -0.0023350|      -0.0049265|       -0.0236150| -0.0013425|
|f_tilde[6]  |  -0.0004923|  0.0030150|       0.0087766|       -0.0003450| -0.0006819|
|f_tilde[7]  |  -0.0007512|  0.0001575|       0.0026810|        0.0000350| -0.0004992|
|f_tilde[8]  |   0.0001869| -0.0050185|      -0.0111150|       -0.0165850| -0.0005529|
|f_tilde[9]  |   0.0004457|  0.0034875|      -0.0144900|       -0.0006610| -0.0003619|
|f_tilde[10] |  -0.0018495| -0.0105595|      -0.0143800|       -0.0053850| -0.0003755|
|f_tilde[11] |  -0.0009328|  0.0023429|      -0.0076650|       -0.0005500|  0.0015098|
|f[1]        |   0.0000940| -0.0000800|      -0.0008500|       -0.0002850|  0.0000652|
|f[2]        |   0.0001040| -0.0005400|      -0.0007600|       -0.0005900|  0.0000735|
|f[3]        |   0.0000878| -0.0002350|       0.0007650|       -0.0000400|  0.0000629|
|f[4]        |   0.0000140| -0.0012150|      -0.0027750|       -0.0008950|  0.0000076|
|f[5]        |  -0.0001335|  0.0005650|       0.0002350|       -0.0035600| -0.0000944|
|f[6]        |  -0.0001651| -0.0009750|       0.0033805|        0.0002700| -0.0001144|
|f[7]        |  -0.0001307| -0.0000150|       0.0013750|       -0.0034300| -0.0000917|
|f[8]        |  -0.0000433| -0.0001550|       0.0005500|        0.0016350| -0.0000363|
|f[9]        |   0.0000203| -0.0006250|       0.0006300|        0.0005350|  0.0000143|
|f[10]       |   0.0000327|  0.0006150|       0.0004300|        0.0003300|  0.0000231|
|f[11]       |   0.0000515| -0.0004650|      -0.0009550|        0.0008600|  0.0000392|
|lp__        |  -0.0012836|  0.0270000|       0.0300000|       -0.0080000| -0.0009081|

Skimming this over it seems like it's mostly the quantiles that differ and since they are negative I'm interpreting that as the mcse for the quantiles in this pr is smaller than develop.

Does all this make sense? @bob-carpenter and @betanalpha if yinz agree with the above looking okay than @serban-nicusor-toptal  can we turn off the perf tests for this branch then update them after it's merged?

**Comment by serban-nicusor-toptal** [comment]
Hey @SteveBronder I've added an [exception](https://github.com/stan-dev/jenkins-shared-libraries/blob/master/src/org/stan/Utils.groovy#L73) for this PR, please remind me to remove it when not needed anymore. Thanks!

**Comment by betanalpha** [comment]
These look completely consistent — I don’t think there’s really been any
systematic change to the Eigen calcs, just the expected variation from 
tweaking the floating point calculations that manifest in different Markov 
chain realizations.  This is all good to go in terms of the computational 
perspective.

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal it looks like this is failing in the windows section because it can't find a sundials intermediate file?

```
stan/lib/stan_math/lib/sundials_5.2.0/src/sunnonlinsol/newton/sunnonlinsol_newton.o stan/lib/stan_math/lib/sundials_5.2.0/src/sunnonlinsol/fixedpoint/sunnonlinsol_fixedpoint.o
ar: creating stan/lib/stan_math/lib/sundials_5.2.0/lib/libsundials_nvecserial.a
ar: creating stan/lib/stan_math/lib/sundials_5.2.0/lib/libsundials_idas.a
ar: creating stan/lib/stan_math/lib/sundials_5.2.0/lib/libsundials_cvodes.a
ar: unable to rename 'stan/lib/stan_math/lib/sundials_5.2.0/lib/libsundials_cvodes.a'; reason: No such file or directory
```

https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/downstream_tests/1587/pipeline

**Comment by serban-nicusor-toptal** [comment]
Hey @SteveBronder I will take a look a bit later after the release, sorry for waiting!

**Comment by SteveBronder** [comment]
No worries! This can def wait till after the release

**Comment by rok-cesnovar** [comment]
Also want to point out that this move to 3.3.7 fixes warnings on model compilation when using Rtools 4.0 on Windows.

**Comment by serban-nicusor-toptal** [comment]
@SteveBronder Everything should be fine now!

**Comment by SteveBronder** [comment]
Thank you! Can someone approve this?

**Comment by SteveBronder** [comment]
Thanks!

**Pull request merged**
