### PR TITLE
[For Sebastian] Multivariate operands_and_partials

### PR DESCRIPTION
**Pull request by seantalts**
@wds15 This is how I think we should probably do it... keeps the size at 0 and seems to work.

The only thing is that I had to change the tests because I think that maybe there was a mistake somewhere. I'm going to annotate the two places where I made these changes in the PR so we can talk about them there.

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Hold on, I maybe am thinking about the tests I changed incorrectly....

**Comment by seantalts** [comment]
Yep, I was. So we need another edge specialization that will be used for both nested/multivariate cases as well as univariate, which means it needs both a `partials_` and a `partials_vec_`. But in this version we're able to do this with just one extra pointer, so size is now 6 (from 5). I think this is a reasonable increase and I'm not sure if it's worth trying to get it lower.

I changed your tests back to your version. I'll resolve this merge conflict.

**Comment by wds15** [comment]
Yup, I think the tests I wrote were right as is. Note that I updated my branch after you did these changes; but I get where you go which could be possible as well. However, in addition to a `ops_partials_edge<double, std::vector<Eigen::Matrix<double, R, C>>>` specialization we also need one for ops_partials_edge<double, Eigen::Matrix<double, R, C>>` as these are usually allowed arguments as well to the mvn functions.

Oh, you are too fast... could be outdated what I wrote...

**Comment by seantalts** [comment]
Ah yeah. We're on the same page now about what's needed and your tests being right, sorry about that.

**Comment by wds15** [comment]
cool.

If you want to see the mvn stuff being used, you can [look here](https://github.com/stan-dev/math/blob/41c4a296710175f13f931557546c8aafa977376e/stan/math/prim/mat/prob/multi_normal_cholesky_lpdf.hpp).

Curious what you suggest as its not clear to me; but having `partials_` and `partials_vec_` in the very basic `prim` definition is the right thing to me. It would be very odd to have an interaface change so dramatically internally based what type gets used.

Note that I also had to add a few operators to the `empty_broadcast_array` specialization for Eigen matrices. Otherwise you end up with compiler errors again.

**Comment by seantalts** [comment]
So this PR is based on your branch, and just shows the diff of changes to what you already have written (though it doesn't have your latest commit with the nested empty broadcast array).

I see your new commit and I like your thinking. But adding that `partials_vec_` pointer takes up extra space for all operands_and_partials use-cases including the standard "empty" edge configuration (which is fairly common - all unspecific `operands_and_partials` type arguments get this empty edge that now has an extra pointer for each one). So the version in this PR, which seems more complicated (but is just boilerplate) has specializations for nested container cases, so we're able to avoid that overhead most of the time and keep the sizes down a little more.

The idea behind `partials_` is that it's only present in univariate cases and `partials_vec_` is only present in multivariate cases intentionally. The overlap that is confusing is when you have an Eigen type and there's no good way of distinguishing whether you are in a multivariate or univariate case. This might actually argue for a separate `multivariate_operands_and_partials`, but we'd end up duplicating quite a lot there. The benefit is that maybe each of those implementations could become a little simpler and smaller. The confusion over `partials_` vs. `partials_vec_` only comes in when we're only with Eigen types in our tests (and, unfortunately, when reading the operands_and_partials implementation).

**Comment by wds15** [comment]
Well, I am fine with it. Should I just merge this into my branch and then we merge that?

(before the final merge to develop I would like to test the multi variate normal)

**Comment by seantalts** [comment]
That works for me - you might want to put your branch back a commit first with something like `git reset --hard HEAD^`. (or --soft if you want to get the last commit uncommitted but staged in your working directory for inspection)

**Comment by seantalts** [comment]
I'm dumb - we can also turn this into a PR into `develop` which might be easier. Should have your commits too.

**Comment by wds15** [comment]
I just went through a git hell... whatever is better; you will see my pull in a sec

**Comment by wds15** [comment]
I hope git is not messed up now.

Anyway, I already applied this stuff to the multi normal cholesky branch and all is fine. Once this is in I can make the pull for the analytic multi variate normal.

**Comment by seantalts** [comment]
Yeesh, sorry about that.

**Pull request closed without merging**
