### PR TITLE
adds cumulative_sum for the new matrix type

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

Adds a `cumulative_sum` that accept a `var<Matrix>` type

## Tests

Tests added to the mix tests using the `expect_ad` framework.

```cpp
./runTests.py ./test/unit/math/mix/fun/cumulative_sum_test.cpp
```

## Side Effects

Nope!

## Release notes

Adds a `cumulative_sum` that accept a `var<Matrix>` type

## Checklist

- [x] Math issue #1805 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by andrjohns — APPROVED** [review]
LGTM!

**Comment by SteveBronder** [comment]
@serban-nicusor-toptal it looks like the Jenkins is hanging, could you take a look?

**Comment by serban-nicusor-toptal** [comment]
Hey @SteveBronder [Jenkins ](https://jenkins.flatironinstitute.org/) is scheduled for a maintenance restart and all new jobs will have to wait for that. Sorry for the inconvenience!

**Comment by SteveBronder** [comment]
Alrighty no worries at all ty!

**Comment by SteveBronder** [comment]
Yep, done!

**Pull request merged**
