### PR TITLE
pow() for varmat

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

This adds pow for `var<Matrix>` types. I thought it would be better as it's own PR since this is a vectorized binary functions that takes in all combinations of matrices and scalars (and `std::vector<int>/std::vector<std::vector<int>>`)

## Tests

Tests added in mix for pow with varmat as well as all of the vectorizable input types.

```
./': ./runTests.py -j28 ./test/unit/math/mix/fun/ -f /pow
```
## Side Effects

Nope!

## Release notes

Replace this text with a short note on what will change if this pull request is merged in which case this will be included in the release notes.

## Checklist

- [x] Math issue #1805 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@andrjohns would you mind taking a look at this?

**Review by andrjohns — COMMENTED** [review]
Sorry for taking so long to get to this! I think with these binary functions where we need overloads for the various combinations of scalar/matrix/arith/var, we're going to end up with a lot of code duplication if we're not careful.

I know you've mentioned before that you're not a huge fan of the `forward_as` approach because it's more abstract, but I think we're going to end up with much more code to maintain otherwise

**Comment by syclik** [comment]
@SteveBronder, I merged `develop` back in... let's see if the tests get kicked off again.

**Comment by andrjohns** [comment]
@SteveBronder this was something I was keen to have in, so I made some changes and updates after merging develop. Feel absolutely free to revert/change anything you disagree with!

**Comment by SteveBronder** [comment]
Thanks @andrjohns those changes look good to me!

**Review by rok-cesnovar — APPROVED** [review]

**Pull request merged**
