### PR TITLE
Bugfix functions accepting Eigen expressions

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Previously I was adding support for Eigne expressions without tests. Now the testing framework is ready https://github.com/stan-dev/stan/pull/2933, the bugs left in can be fixed.

This PR also adds list of function signatures that do not work with expressions yet. It will be used in expression testing framework to skip those functions. I'm putting it in this repo so it can be updated in same PR as functions are generalized. This is the reason this PR looks huge - only ~200 lines are actually C++ that needs review. This list is intended to only grow shorter with time - no adding allowed, so any new fucntions added must support expressions.

## Tests
are in https://github.com/stan-dev/stan/pull/2933

## Side Effects
None

## Checklist

- [x] Math issue #1470

- [x] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by t4c1** [comment]
@andrjohns Did you miss the requiest to review this, or are you too busy?

**Comment by andrjohns** [comment]
It's been on the backburner, but will have it finished off this arvo

**Comment by rok-cesnovar** [comment]
I discussed this one with Tadej and in order to do testing of Eigen expressions automatically and thoroughly, we need to keep an updated list of functions that do not yet support Eigen expressions so those are not tested with them. 

We thought about adding this to the Stan repo but then each PR that would add support for Eigen expressions to another function would require doing 2 PRs. The list will go away once the move to Eigen expressions is done so I am fine with it.

I know it kind of doesn't belong in Math if we look at it as its own entity. The other option would be putting it on a wiki and removing signatures there. But I don't like wiki's dealing with history and easily accessible tracking of changes.

**Comment by andrjohns** [comment]
Works for me, I'll approve and merge these now

**Pull request merged**
