### PR TITLE
add boost mpi, boost build and dependencies

### PR DESCRIPTION
**Pull request by wds15**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [ ] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
Add boost MPI and boost build.

#### Intended Effect:
Prepare for MPI codes. In it's current proposed form a conservative approach has been chosen wrt to including all dependencies which are possibly used by boost MPI. This is the default by `bcp` which was used to import these sources. A minimal amount of pruning has been used to cut down a little bit the size of what we include:

```
bcp mpi build stan-math/lib/boost_BOOST_VERSION
cd stan-math/lib/boost_BOOST_VERSION
find . -name "doc" -type d -exec rm -rf {} ;
find . -name "example" -type d -exec rm -rf {} ;
find libs -name "test" -type d -exec rm -rf {} ;
```

This pulls in MPI and as dependencies also a number of additional libraries:

For sure needed:
- atomic
- chrono
- date_time
- exception
- serialization
- timer
- system
- boost build system (to deal with fancy MPI installations)

Possibly optional. So it depends on the exact feature set we use from MPI (currently I am not using this for map_rect):

- graph
- python
- thread

The safe approach is to just go with what `bcp` pulls in; so all of the above.

I leave it to the reviewer to decide if we should do more efforts to prune the included sources. I would also suggest to include in this pull a script which automatically imports mpi from some boost distribution in order to ease future upgrading. There just wasn't any obvious place where I can put the above script.

#### Side Effects:
Our source distribution gets bigger

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): boost

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
the sources were added with the commands below... should we document that somewhere?

bcp mpi build stan-math/lib/boost_BOOST_VERSION
cd stan-math/lib/boost_BOOST_VERSION
find . -name "doc" -type d -exec rm -rf {} \;
find . -name "example" -type d -exec rm -rf {} \;
find libs  -name "test" -type d -exec rm -rf {} \;

**Comment by bob-carpenter** [comment]
What that import?  And why are there 1000 files changed on this?  It looks like a lot of build specific then but the also a lot of .hpp and .cpp files from different libraries.  Is this bringing in all the non-header-only libs?  Were those not included before?  Also, any idea if they're in BH on CRAN so that we could use them in R?

**Comment by wds15** [comment]
I think my clang-format went over these files such that many touched files are reformated versions of boost which is should have never happened. Maybe @seantalts can advise on how to avoid that?

BH on CRAN is a header only library. I think @bgoodri has a way to distribute parts of boost which are not part of BH. However, it is not clear to me how MPI is going to work in the context of R. It is possible to do as there is Rmpi on CRAN. However, I looked some time at the APIs, but I was not able to figure it out in the time I allocated for it.

I thought we concentrate on cmdstan primarily first and go from there.

**Comment by seantalts** [comment]
@wds15 You're right, there was a version of the pre-commit hook that would format if you added things to lib. The version on develop doesn't do that anymore. I'm happy to re-run the commands and change the branch for this PR so they aren't formatted - mind if I go ahead and do that?

**Comment by wds15** [comment]
sure, go ahead.

I think you need to restore big parts of the boost headers and the extra libs, of course.

I will update my hook then.

Thanks!

**Comment by seantalts** [comment]
The 1000 files is not going to go away though - this PR introduces a ton of new files.

**Comment by seantalts** [comment]
Including e.g. tools for building the boost website... Can we trim it down some more? I'm not a boost expert but that seems weird

**Comment by seantalts** [comment]
There are also test directories in build that we didn't delete - should we delete those?

**Comment by seantalts** [comment]
Sorry to keep piling on but I'm also curious about the Boost Python library's inclusion here

**Comment by syclik** [comment]
I just took a quick peak at the files changed. It would make sense to stage this into a pull request just including the new Boost headers, then a pull request for updating make and the setup of MPI (so it doesn't get lost within the PR), then a pull request with the MPI implementation itself.

This pull request touches a lot of headers, including tests and `hooks/pre-commit`. Perhaps the branch is out of synch with develop?

@seantalts, yes, that's something we'll have to deal with. And rstan's use of boost too.

**Comment by seantalts** [comment]
I think this was supposed to be the PR of just the new boost header sources (the first stage you mentioned). I just force pushed a new version that wasn't autoformatted and shouldn't have changes to the hooks or anything else.

**Comment by syclik** [comment]
@seantalts: looks like you overwrote the history. Did @wds15 update any of the makefile stuff in the original PR?

**Comment by seantalts** [comment]
From what I understand this was just the sources. @wds15 did you have other stuff in there?

**Comment by wds15** [comment]
I haven't added any makefile stuff for stan-math. I do have on another branch some edits for the makefiles, but I have not included them here as you, @syclik , request for the GPU stuff to only include the extra sources first and I also understood you would be working on the makefile additions for MPI. Was I wrong in my understanding?

I am happy to add my makefile bits and pieces here if we think it should go in now and be part of the PR. Just let me know what is best here to proceed.

**Comment by syclik** [comment]
@wds15, that's fine. I thought the original file diff had changes in Jenkinsfile and one of the makefiles and I couldn't recover the old hash to see if that was true. Glad to hear it's on a different branch. Let's do that in a separate PR.

**Comment by wds15** [comment]
I guess this pull should figure out how we pull in mpi and its dependencies. I used bcp as stated above and bcp is very conservative in pulling in any possible dependency. I already tried with the find commands above to counter this a little bit. It is still a bigger amount of files.

Another attempt I did was to use the scan option from bcp. If you scan the mpi_cluster.hpp file from the mpi branch it will come up with a slightly smaller set of libraries, but not a lot smaller though. If we want to minimize what we include, then we will probably need to put a bit more effort into this. I figured going the safe way and include more than less is fine.

**Comment by seantalts** [comment]
@syclik I feel like Sebastian's question is maybe for you as Math Tsar - how do you feel about how strict we are in adding these headers? Should we try to eliminate some of them by scanning what we're currently using in the MPI branch? Or just put everything we might need in now? I'm kind of leaning towards the latter as well, though maybe we need to do some of that header elimination work eventually for RStan anyway.

**Comment by bob-carpenter** [comment]
For RStan, we're going to need to get changes into the BH package.  I don't know if they only do the header-only ones. @bgoodri will probably know.

**Comment by wds15** [comment]
@bob-carpenter BH is header only. I think we would need to deploy these with StanHeaders which also includes CVODES.

@seantalts Do I need to update anything locally to avoid autoformatting of libs? The hooks seem to have not changed, so I guess that this is part of other config files which are updated whenever I merge develop, right?

**Comment by bob-carpenter** [comment]
I'll ping Dirk about BH before doing it ourselves, but I'm OK either way.

**Comment by seantalts** [comment]
There was a commit[ (here)](https://github.com/stan-dev/math/commit/2256cf672be6d19c9629054fc842c4e84664768e) that changed the hooks to not touch libraries. If you have develop up to date and your hook was installed via the script (or otherwise symlinks to `hooks/pre-commit` then you should be good to go.

**Comment by wds15** [comment]
@bob-carpenter and @bgoodri are we going to support MPI under R anytime soon? Like I said, I am concentrating on cmdstan which I thought we all agreed on.

**Comment by bob-carpenter** [comment]
I think it's fine to roll it our initially for CmdStan and Linux.

As far as stan-dev/math goes, we need to include everything we need from Boost there.  R is a different question.  I was responding to the  previous message about StanHeaders, which is the R package.

**Comment by bgoodri** [comment]
If it can be built for Stan Math, it is fair to assume it can be built for
R, although we likely have to do it ourselves because it is not header-only
at that point.

**Comment by bob-carpenter** [comment]
Dirk confirmed on the BH issue tracker that BH is going to remain header only.

**Comment by bgoodri** [comment]
We're already building a shared object for CVODES. We'll probably
instantiate the model class whenever it is ready. So, building part of
Boost is not that big of a deal.

**Comment by syclik** [comment]
In response to @wds15 in https://github.com/stan-dev/math/pull/737#issuecomment-362175793
> I guess this pull should figure out how we pull in mpi and its dependencies.

Yes, is that not what this pull request does? If not, can you update the original PR comment to mention what this PR does?

> If we want to minimize what we include, then we will probably need to put a bit more effort into this. I figured going the safe way and include more than less is fine.

Yes, that's fine.

From @seantalts in https://github.com/stan-dev/math/pull/737#issuecomment-362301276
> how do you feel about how strict we are in adding these headers? Should we try to eliminate some of them by scanning what we're currently using in the MPI branch? Or just put everything we might need in now? I'm kind of leaning towards the latter as well, though maybe we need to do some of that header elimination work eventually for RStan anyway.

I think we should just include everything. But that puts additional work on RStan and PyStan, so we've done some ad hoc trimming of includes in the math library. We may want to do something different for how we manage dependencies in the near future with MPI / GPU + optional headers + minimal includes. Our current includes weren't put together with that sort of complexity in mind.

**Comment by syclik** [comment]
@wds15, I'll review this one.

**Comment by syclik** [comment]
@wds15, can you update to `develop` which includes Boost 1.66.0?

**Comment by seantalts** [comment]
@syclik This is ready for review again

**Pull request merged**
