### PR TITLE
Feature/issue 864 exponential prim

### PR DESCRIPTION
**Pull request by drezap**
## Summary
Add a primitive for the exponential covariance function

## Tests

instantiations, zero size, error throws and accurate calculations.

## Side Effects

A new covariance function

## Checklist

- [x] Math issue #864 

- [x] Copyright holder: (Copyright 2019 Andre Zapico)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by drezap** [comment]
yo @syclik not ready for review, just a quick question. Which instantiations did you want tested, for `var` data types? I think I should have some test cases in `rev` as well.

I remember you mentioning this and we might have lost sight of this in the other PR's

**Comment by syclik** [comment]
So, I'm looking at these PRs and seeing you're only implementing them in
prim using autodiff. If that's the case, we don't really need to test with
rev: we trust that the individual functions are tested for rev so we're
good.

If you were planning on implementing the reverse mode specializations, then
we'd need more tests. But that can wait until you start introducing those
PRs.

**Comment by drezap** [comment]
@syclik cool, with that said, this is ready for review as soon as tests pass.

> If you were planning on implementing the reverse mode specializations

yep, I do. I'll start getting those going after this gets in

**Comment by syclik** [comment]
Cool. I'll check in after the weekend to see if it's passed everything.

**Comment by drezap** [comment]
sounds good, much appreciated

**Pull request merged**
