### PR TITLE
Vectorise ordered logistic & categorical RNGs

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR vectorises:

 -  ```ordered_logistic_rng```
 -  ```categorical_rng```
 -  ```categorical_logit_rng```

To accept arrays of vectors as inputs (so that an array of ```int``` can be returned). This enables the following additional signatures:
```
int[] ordered_logistic(real, vector[])
int[] ordered_logistic(vector, vector[])
int[] ordered_logistic(vector[], vector[])
int[] ordered_logistic(vector, vector)

int[] categorical_rng(vector[])

int[] categorical_logit_rng(vector[])
```

I'll adding the Stanc3 sigs once this PR goes in.

## Tests

Tests are added to ensure that the vectorised forms are equivalent to looping

## Side Effects

N/A

## Release notes

Vectorised the ordered logistic, categorical, and categorical_logit RNG functions

## Checklist

- [x] Math issue #2132 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by andrjohns** [comment]
@t4c1 I tried to make sure that these implementations are expression-compatible, did I miss anything?

**Comment by rok-cesnovar** [comment]
Probably the best way to test for expressions is to use the expressions tests framework. You can also run them for currently non-existent signatures.
To do that place the new signatures in a file and run

`./runTests.py test/expressions --only-function new_sigs.txt`

**Comment by andrjohns** [comment]
Oh of course, I should have already known that

**Comment by andrjohns** [comment]
Closing this for now since I need to debug the Windows failures locally and I won't have time for a week or two

**Pull request closed without merging**
