### PR TITLE
Inverse of the complementary error function

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR adds the inverse of the complementary error function: `erfc_inv(x)`, which will be needed for the quantile functions of the normal and log-normal distributions

## Tests
`prim` and `mix` tests are added

## Side Effects

N/A

## Release notes

Added the inverse of the complementary error function

## Checklist

- [x] Math issue #2517

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by rok-cesnovar — CHANGES_REQUESTED** [review]
The code and tests look good. I know that boost calls this function erfc_inv, but given that all the other inverse functions are defined with a prefix (`inv_Phi`, `inv_cloglog`, `inv_logit`, `inv_sqrt`, `inv_square`) we should do the same with inv_erfc? I am guessing the intention was to expose it right? I guess its less of an issue if it was not meant to be exposed in the language.

**Comment by andrjohns** [comment]
Ah that's a good point, that would be more consistent naming. I'll update the incomplete beta inverse PR with that as well

**Comment by andrjohns** [comment]
@rok-cesnovar looks like downstream is failing because of the `von_mises` stuff

**Comment by rok-cesnovar** [comment]
Sorry about that, will fix asap.

**Comment by andrjohns** [comment]
No worries at all, thanks!

**Comment by bob-carpenter** [comment]
This is super cool.  And thanks for catching the naming, @rok-cesnovar.

**Review by rok-cesnovar — APPROVED** [review]
Thanks Andrew!

**Pull request merged**
