### PR TITLE
Feature/issue 221 boost 1.60

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Summary:

Upgrade to Boost 1.60.0

#### Intended Effect:

Bring us in line with BH package on CRAN for R.

#### How to Verify:

Unit tests.

#### Side Effects:

Causes deprecation warnings upstream in `stan-dev/stan` in grammars.

#### Documentation:

None.

#### Reviewer Suggestions: 

Anyone.

#### Licensing

The submitted code is governed by the Eigen license; the change to README is released under CC-BY 4.0.  Copyright owner: Columbia University.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
The header test works on my Mac, so I don't know what's up with Windows.  Looks like it went into some kind of infinite loop?

**Comment by bob-carpenter** [comment]
I don't understand the Travis errors.  What is it running?

**Comment by syclik** [comment]
I'll look into it.

**Comment by bob-carpenter** [comment]
Never mind.  Forgot to push the new 1.60 boost and remove 1.58.

**Comment by bob-carpenter** [comment]
@syclik Any clue as to what's going on here?  Everything passes locally for me.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
