### PR TITLE
range checks throw std::out_of_range

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
I reviewed all the `check_*` functions and make sure all the ones that should throw `std::out_of_range` throws that exception. I documented the ones that throw `std::out_of_range` and the functions that call these functions.

#### Intended Effect:
We need to update Stan to stop when it sees an exception other than `std::domain_error`.

#### How to Verify:
Run tests.

#### Side Effects:
One of the functions, `length_mvt()`, was changed from throwing `std::out_of_range` to `std::invalid_argument`.

#### Documentation:
Included.

#### Reviewer Suggestions: 
Anyone.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Don't the services catch any std::exception?  Should they
even try to catch just `...`?

**Comment by bob-carpenter** [comment]
Looks good.  Thanks for all the careful documentation.

**Comment by syclik** [comment]
I don't know off the top of my head. They should catch everything we can.

**Comment by syclik** [comment]
I'm just not sure if they do.

**Comment by syclik** [comment]
This fixed #193.

**Pull request merged**
