### PR TITLE
Update to OpenCL 2.0

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

This updates the OpenCL headers that allow for up to version 2.2 support. We use the flags `-DCL_HPP_TARGET_OPENCL_VERSION=200` so that our code base uses OpenCL 2.0 by default.

There are a few code changes to update us from some deprecated functions.

1. `to_size_t` was removed and instead we use `cl::array<size_t, 3>`
2. We no longer need to pass a pair to the OpenCL program to compile kernels (ex [here](https://github.com/stan-dev/math/compare/develop...bstatcomp:update/opencl-2.0?expand=1#diff-f48e30891ae00ab80f64217ec2e213bcL83))
3. `cl::make_kernel` was deprecated so we now use `KernelFunctor` when constructing kernels.
4. The OpenCL header is now just a single file and so I removed the `CL` folder in the dependency library folder. Now we just do `#include <cl.hpp>`

## Tests

All basic opencl tests pass

## Side Effects

We are not using any of the OpenCL 2.0 kernel features and so this should have no side effects for the kernels.

## Checklist

- [x] Math issue #1276

- [x] Copyright holder: (fill in copyright holder information)

Steve Bronder
The Khronos Group Inc.

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Can we somehow check what OpenCL version is supported on the test Mac machine?

**Comment by SteveBronder** [comment]
Ughhh I totally forgot about metal and Mojave. When I get home I think I can set `CL_HPP_MINIMUM_OPENCL_VERSION=120` to let this compile with 1.2 and 2.0

**Comment by rok-cesnovar** [comment]
I tried to google this awhile a go, but had not luck finding an anwser. On pre-Mojave OSx with an AMD/NVIDIA GPU, do the GPU OpenCL runtimes that come with the drivers support OpenCL 1.2.x or 2.0?

**Comment by SteveBronder** [comment]
I'm pretty sure it's only 1.2 (mby even 1.1) that are supported on the pre-installed drivers before Mojave

**Comment by SteveBronder** [comment]
Gonna close this until I write the dependency wiki

**Pull request closed without merging**
