### PR TITLE
Feature/issue 175 add cvode

### PR DESCRIPTION
**Pull request by betanalpha**
#### Summary:
Exposes a stiff CVODE solver using a diagonal Jacobian approximation as the ```integrate_ode_cvode''' function.  The test makefile compiles CVODE into a shared library from source to allow the function to be tested, and the compilation has been tested on OS X and Windows.  Addresses Issue #175 and Issue #52.

#### Intended Effect:
Introduces a new ODE integrator capable of handling stiff systems.

#### How to Verify:
test/unit/math/prim/arr/functor/coupled_ode_system_cvode_test.cpp	test/unit/math/prim/arr/functor/integrate_ode_cvode_test.cpp
test/unit/math/rev/arr/functor/coupled_ode_system_cvode_test.cpp	test/unit/math/rev/arr/functor/integrate_ode_cvode_test.cpp
test/unit/math/rev/arr/functor/integrate_ode_cvode_grad_test.cpp	test/unit/math/rev/arr/functor/util_cvode.hpp

#### Side Effects
Makefile now compiles CVODE from source and installs a shared library in lib/cvode_2.8.2/.

#### Documentation:
None

#### Reviewer Suggestions:

@syclik @bob-carpenter

### CODE REVIEW

**Comment by betanalpha** [comment]
cpplint is complaining about the use of ``long int'' but a C++ equivalent like ``int_least32_t'' won't compile as it doesn't match the necessary C callbacks.  Should we just block the cpplint warnings here?

**Comment by betanalpha** [comment]
@syclik What's going on with the dependency errors?

**Comment by syclik** [comment]
I'm working on it. I was trying out size_t.

**Comment by betanalpha** [comment]
I think it has to be long for the C methods to match, no?

**Comment by syclik** [comment]
Re: cpplint, I got that figured out last night.
Re: dependency errors. I was working on it when I fell asleep.

**Comment by betanalpha** [comment]
I just pushed a bunch of cpplint fixes, lemme know if I can help otherwise.  But the unit tests all passed, right?

**Comment by bob-carpenter** [comment]
long int is perfectly OK C++.  The reason cpplint complains
is that it's size is platform dependent.  As long as we don't
go into long long int, we're OK --- just block the cpplint warning.
That's what we did everywhere else.  As far as I can tell, there's
no way to cover all the possible native types without ambiguity
using the explicitly sized types.

- Bob

**Comment by betanalpha** [comment]
I cleaned up the last lint warnings and took a look at math-dependencies.  The test fails because of a hardcoded warning threshold of 72 (I couldn't find where this threshold is set and hence couldn't change it).  2 of the warnings are necessary because of the new code (1 because we're adding a new coupled_ode_system, and one because even the prim version of coupled_ode_system_cvode needs to include rev/core to automatically compute the Jacobian of the ODE system).  I can see an argument for moving prim/arr/functor/coupled_ode_system_cvode somewhere else because of this rev dependence, but where would we put it?  mix?

**Comment by syclik** [comment]
If it needs to move, it goes in rev. Mix is for mixed mode: both rev and fwd dependencies. 

(How did you find time to do this???)

**Comment by betanalpha** [comment]
> If it needs to move, it goes in rev. Mix is for mixed mode: both rev and fwd dependencies. 

The problem is that the double instantiation requires rev to do the (nested) Jacobian calculation.  So it's prim but it needs rev.  A unique situation that does tangle things up a bit.  That said everything works....

> (How did you find time to do this???)

None of these workshops start on time...

**Comment by bob-carpenter** [comment]
Threshold for what?

The rule is that we only allow dependencies

  mixed -> fwd -> prim
        -> rev -> prim

And on the structure side

 Eigen -> std::vector -> scalar

**Comment by betanalpha** [comment]
So the dependencies test makes a rough check for violations
of these rules, but it�s not exact and there are false positives.
The actual Jenkins test has a limit for these false positives
which is currently set at 72.  The new CVODE code introduces
2 more false positives which is causing the test to fail.  I�m
just not sure where that Jenkins configuration is.

> Threshold for what?
> 
> The rule is that we only allow dependencies
> 
> mixed -> fwd -> prim
> -> rev -> prim
> 
> And on the structure side
> 
> Eigen -> std::vector -> scalar

**Comment by betanalpha** [comment]
The upstream test failed, but that�s to be expected because we
need to modify both stan and cmdstan to point to the new lib.
Can we go ahead and merge and get those corresponding
updates in?

**Comment by syclik** [comment]
I'll test it with the upstream branches just to make sure it's ok. Shouldn't take long.

**Comment by syclik** [comment]
I had to update the makefiles for Math, Stan, and CmdStan. I've just kicked off the tests to use the updated upstream branch for the upstream projects. Hopefully that works. I've also disabled the distribution tests since we haven't been changing any code. Should run fairly quickly.

**Comment by betanalpha** [comment]
yeah, but we already have these changes in Stan and CmdStan branches,
plus all of the other changes needed to expose these new functions.  This is
one of those “changing math such that everything will have to update” changes
which makes an upstream test irrelevant.

**Comment by syclik** [comment]
Nope. Without the include directive to the cvode library, compilation fails.

**Comment by betanalpha** [comment]
I know, but that’s why we have 

https://github.com/stan-dev/stan/tree/feature/issue-1735-cvode

and

https://github.com/stan-dev/cmdstan/tree/feature/issue-262-cvode

ready and waiting to go.  Upstream tests don’t make sense for code that 
explicitly breaks the interfaces.  Fixing the makefiles (which is already 
done in the above two branches) is just introducing unnecessary updates.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Pull request merged**
