### PR TITLE
remove adj_jac_apply

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

All uses of `adj_jac_apply` were replaced by either `reverse_pass_callback` or `make_callback_var`. As it is unused now, we can remove it.

## Tests
Removed `adj_jac_apply` tests.

## Side Effects
None.

## Release notes
Removed `adj_jac_apply`.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
-2,900 lines of code. Gotta love that!

**Comment by SteveBronder** [comment]
Oh wait, so I think the Julia diffeq folks have used this in the past. @ChrisRackauckas would removing this break any current code / are you able to use the new `reverse_pass_callback`?

**Comment by ChrisRackauckas** [comment]
We'd be good.

**Comment by SteveBronder** [comment]
Word! This has been posted about on the discourse forums though, maybe it would just be better to tag as deprecated for a release? Then let people know in 2 releases or something we are going to remove it from the library

**Comment by rok-cesnovar** [comment]
That depends whether we think `adj_jac_apply` is part of the official API of Stan Math? I would argue its not.

**Comment by bbbales2** [comment]
I'm happy to remove this. We're technically incompatible with the last Math release cause the LDLT_factor changes, so major version bump anyway?

**Comment by SteveBronder** [comment]
I'm fine with removing it!

**Comment by wds15** [comment]
Are we about to get a Math 4.0 release?

**Comment by rok-cesnovar** [comment]
I need to open an issue to get everyone's thoughts on that but based on what Ben said yes, Math 4.0 :)

**Review by bbbales2 — APPROVED** [review]
I'll just make that merge button more tempting for whoever comes here next :P.

**Pull request merged**
