### PR TITLE
Add a manually triggerable Github Action for generating release notes

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

This PR adds a manually triggerable Github Action job to generate release notes. 

An example of how you can start it can be seen here: https://github.com/bstatcomp/math/actions?query=workflow%3A%22Release+notes%22

The result of the job can be seen here: https://github.com/bstatcomp/math/actions/runs/284867780 

This script lived on my computer, but I think its better if it lives in the repository so anyone can run it without actually having to do anythin locally.

## Tests
/
## Side Effects
/
## Checklist

- [x] Copyright holder: Rok Češnovar, Univ. of Ljubljana

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by bbbales2 — COMMENTED** [review]
I guess there's no way for me to test this until it's merged? If so let's merge and then test the Git action. Certainly it looks like it works on the other page. The function removal looks fine.

**Comment by rok-cesnovar** [comment]
The only way we can test this is if we run it "on PR", and then revert that change.

**Comment by rok-cesnovar** [comment]
There you go: https://github.com/stan-dev/math/actions/runs/285971782

Will revert back to only trigger manually.

**Review by bbbales2 — APPROVED** [review]
Very cool! Thanks for the test

**Comment by bbbales2** [comment]
Oof I guess that means poor Jenkins gets to sweat another 8 hours, but thanks for the test.

**Comment by bbbales2** [comment]
Oh wait it says it is passed, great.

**Comment by rok-cesnovar** [comment]
Jenkins skips if the change is not source code or tests or Jenkins config.

**Comment by rok-cesnovar** [comment]
Now that I have you here. I want to add something similar for math benchmarks (manually triggered job). When you have a minute: https://github.com/bbbales2/math-benchmarks/issues/1

**Pull request merged**
