### PR TITLE
Generalize dot_product

### PR DESCRIPTION
**Pull request by t4c1**
## Summary

Enables expression testing for `dot_product` and related functions. These were generalized before the testing was implemented, but than a regression happened in reverse mode `dot_product` when `reverse_pass_callback` was added. `to_arena_if` was designed in a way that made handling expressions without evaluating them multiple times virtually impossible. This is fixed, but `to_arena_if` is not used in `dot_product` anymore, as Steve's implementation without turned out to be a bit faster in some cases.

## Tests

Tested using expression testing framework.

## Side Effects

None.

## Release notes

Fixed how `dot_product` handles expressions.

## Checklist

- [ ] Math issue #1470 

- [ ] Copyright holder: Tadej Ciglarič, Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
I'm fine with this being in a seperate PR though I did add this in #2106 as well. Is this to fix a regression? If so then yeah it makes sense to have in it's own PR

**Comment by t4c1** [comment]
Well, it does fix a regression, but the reason for it being in another PR is simply that I did not know you already put it in one. Now that it is in this PR too, I would just leave it here, as it is required for other changes in this PR to work.

Also this is nothing that affects users so it does not need to be merged before the release.

**Review by bbbales2 — DISMISSED** [review]
Looks good. `to_arena_if` is now unused. I guess we should deprecate or remove it if it doesn't end up getting used anywhere. (presumably we wait until we have more functions converted so we aren't just adding it back at some point).

**Comment by bbbales2** [comment]
@t4c1 merge conflict.

**Comment by t4c1** [comment]
If I was implementing rev functions, I would still use `to_arena_if`.

**Comment by bbbales2** [comment]
Cool beans, then no deprecating.

**Review by bbbales2 — APPROVED** [review]
Good!

**Pull request merged**
