### PR TITLE
GPU with stanMathCL [WIP]

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [ ] Run cpplint: `make cpplint`
- [ ] Declare copyright holder and open-source license: see below

#### Summary:

Brings in GPU based functions for

1. Multiplication
2. Cholesky Decomposition
3. Matrix Inversion
4. Passing data back and forth from the GPU
5. error checking

#### Intended Effect:

Users will be able to access the GPU based functions

#### How to Verify:

TODO

#### Side Effects:

Unknown

#### Documentation:

TODO

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 

@rok-cesnovar can you fill this part in

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
ftr, once I get everything working I will break this PR into several smaller PRs for review

**Comment by syclik** [comment]
@SteveBronder, is there any specific thing that you could use help with?

**Comment by SteveBronder** [comment]
@syclik not yet, apologies for the delay I was on a business trip all week

**Comment by syclik** [comment]
No worries. Just wanted to make sure there wasn’t something that you needed.

**Comment by syclik** [comment]
@SteveBronder, this PR is still WIP, right? I'm trying to figure out which one to review next. I think it should be the build issues next, but maybe there's an easier one to deal with first.

**Comment by SteveBronder** [comment]
Srry this is an older branch. I'm going to close this and will label the branches in the order to be reviewed

**Pull request closed without merging**
