### PR TITLE
Only build tbbmalloc[_proxy] if requested

### PR DESCRIPTION
**Pull request by WardBrian**
## Summary

We have a make variable called TBB_LIBRARIES which controls whether tbb is built or if tbbmalloc and tbbmalloc_proxy are as well. This variable is supposed to be set up such that these optional packages are only built on mac (see [our docs](https://mc-stan.org/math/md_doxygen_2parallelism__support_2threading__tbb.html)). However, at the moment, they are always built due to a misconfigured(?) make dependency.

This leads to https://github.com/stan-dev/cmdstan/issues/1218, which is resolved by this PR.

## Side Effects

As far as I can tell, none, but I wouldn't be shocked if we had baked in some accidental assumption about these libraries being available.

## Release notes

Fixed a build configuration issue where the optional tbbmalloc and tbbmalloc_proxy libraries were built unconditionally.

## Checklist

- [x] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by WardBrian** [comment]
Jenkins seems to be having some unrelated config issues, the first run of this passed all the relevant things to confirm we don't accidentally rely on this

**Comment by syclik** [comment]
Great! (That sucks that it fails incorrectly at times.)

**Comment by WardBrian** [comment]
I'd never seen that one before, but there seem to be at least a couple sources of nondeterminism in the math pipeline that I have not been able to pin down

**Comment by syclik** [comment]
Nondeterministic behavior is tough to pin down, for sure. 

Maybe an easy-ish on dev fix is retry on failure? Like 1 retry?

**Comment by WardBrian** [comment]
I'm not sure if that is something we could automate or not - good question for @serban-nicusor-toptal

**Comment by serban-nicusor-toptal** [comment]
I think we can just move the step that's failing inside a [retry](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/) block. [stanc3 example ](https://github.com/stan-dev/stanc3/blob/master/Jenkinsfile#L101)
I'll create a PR early tomorrow for Math to retry the headers check.

**Comment by WardBrian** [comment]
The other thing that sometimes randomly fails is the thread tests sometimes don't build.

If this is due to some sort of runner incompatibility, will the retry pick up the same runner again?

**Comment by serban-nicusor-toptal** [comment]
I couldn't find anything for sure but I think it will just pick a different executor based on availability. Looks like there's an agent conditional too -> https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times
I'll read a bit more about it and then try it out in a PR.

**Pull request merged**
