### PR TITLE
More stable implementation of neg_binomial_2_log_lpmf 

### PR DESCRIPTION
**Pull request by martinmodrak**
## Summary

These changes mirror those done for `neg_binomial_2_lpmf` in #1497, `binomial_coefficient_log` is used to avoid the necessity to delegate to Poisson.

## Tests

- Precomputed values and gradients in Mathematice
- Derivatives via complex step
- Matches `neg_binomial_2_lpmf(n, exp(eta), phi)`
- Tests of values and derivatives against analytical solutions for `n = 0` and `n = 1`

## Side Effects

The way the density is computed changed to improve stability, at the cost of tangling `eta` and `phi` together earlier, so less computation can be avoided when `propto=true` and `phi` is fixed.

## Release notes

More stable implementation of neg_binomial_2_log_lpmf 

## Checklist

- [x] Math issue #1495 

- [x] Copyright holder: Institute of Microbiology of the Czech Academy of Sciences

By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by martinmodrak** [comment]
Ready for review. Maybe @bbbales2  could take care of it? Hopefully we can get this in for the 2.23 release... Thanks!

**Comment by rok-cesnovar** [comment]
I am sure we can get it in. Note that this is a bugfix so the deadline is actually 20th of April. But if we can get it for the release candidate that would be even better.

**Comment by bbbales2** [comment]
@serban-nicusor-toptal Looks like this test is popping up in downstream performance:
```
Cannot contact old-imac: java.lang.InterruptedException
make: mkdir: Exec format error
make -j6 test/performance/logistic_test failed
exit now (04/11/20 09:29:58 EDT)
```

Does that mean a computer crashed? Anything we can do to un-crash that haha?

@martinmodrak this looks good to me. I'll merge after we get the tests figured out.

**Comment by serban-nicusor-toptal** [comment]
Hey, reduced the parallel variable from 6 to 4 so we rule out that the load may crash the machine. Gonna restart the build.

**Comment by bbbales2** [comment]
@serban-nicusor-toptal looks like it failed again. Ideas?

**Comment by serban-nicusor-toptal** [comment]
There is a known but for Jenkins with github, builds that are replayed won't show up here ( in the bottom continous-integration ).
The [build](https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1830/8/pipeline/) looks like running for now.

**Comment by bbbales2** [comment]
Thanks @martinmodrak, it's in! And thanks for the help @serban-nicusor-toptal!

**Pull request merged**
