### PR TITLE
Automatic reverse mode autodiff testing (Issue #993)

### PR DESCRIPTION
**Pull request by bbbales2**
## Summary

This is my first take at implementing the automatic testing described in issue #993.

**This only tests reverse mode autodiff.** I want to make the interface on this feature complete first, because I think testing `fvar`s and `fvar<var>`s will be much the same.

I discussed with Bob and decided not to force the test all argument combos things on people. The interface is basically:

```
test_autodiff(functor, arg1, arg2, ...);
```

Where the arguments are passed in as non-autodiff types (`int`, `double`, `std::vector<int>`, `std::vector<double>`, `Eigen::VectorXd`, `Eigen::RowVectorXd`, and `Eigen::MatrixXd`)

The test code will test reverse mode autodiff with all valid combos of autodiff and non-autodiff types on the calling function against finite difference approximations.

It checks that when the function called with non-autodiff types throws, the autodiff versions throw as well. It tries to verify that the exception types are the same, but it cannot guarantee it.

It checks that the returned values from the autodiff and non-autodiff implementations match.

A complete set of reverse mode autodiff tests for a function should just be calling:

```
test_autodiff(functor, arg1, arg2, ...);
```

With all combinations of prim-types for arg1, arg2, etc. Since this will have already been done for the prim tests, presumably this is just some copy and paste so it's easy. The rest can be handled by test_autodiff.

## Tests

The main features can be tested with

```
./runTests.py test/unit/math/rev/mat/util/test_autodiff_test.cpp
```

The various extra bits and pieces I added can be tested with
```
./runTests.py test/unit/math/prim/scal/fun/promote_double_to_T_test.cpp
./runTests.py test/unit/math/prim/mat/fun/promote_double_to_T_test.cpp
./runTests.py test/unit/math/rev/mat/fun/promote_double_to_T_test.cpp 
./runTests.py test/unit/math/prim/mat/fun/variable_adapter_test.cpp
./runTests.py test/unit/math/prim/scal/functor/apply_test.cpp
./runTests.py test/unit/math/prim/scal/functor/call_all_argument_combos_test.cpp
./runTests.py test/unit/math/rev/mat/fun/adj_jac_apply_test.cpp // I'm actually not sure what this change is about, but it seems fine
```

## Checklist

- [x] Math issue #993 

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by wds15** [comment]
+1

**Comment by bob-carpenter** [comment]
Thanks!  I can talk to Ben about this early next week and review it.

**Comment by syclik** [comment]
@bbbales2, I'm sorry it's taken so long to review. I've run into a slight problem -- I can't compile it on my local machine. When I run
```
./runTests.py test/unit/math/rev/mat/util/test_autodiff_test.cpp
```

I get a compiler error novel:
```
clang++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -Wno-unknown-warning-option -Wno-tautological-compare -Wsign-compare -DGTEST_USE_OWN_TR1_TUPLE -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DGTEST_USE_OWN_TR1_TUPLE -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O3 -DNO_FPRINTF_OUTPUT -pipe  -c -o test/unit/math/rev/mat/util/test_autodiff_test.o test/unit/math/rev/mat/util/test_autodiff_test.cpp
In file included from test/unit/math/rev/mat/util/test_autodiff_test.cpp:1:
In file included from ./test/unit/math/rev/mat/util/test_autodiff.hpp:4:
In file included from ./stan/math/rev/mat.hpp:4:
In file included from ./stan/math/rev/core.hpp:4:
In file included from ./stan/math/rev/core/autodiffstackstorage.hpp:4:
In file included from ./stan/math/memory/stack_alloc.hpp:10:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/sstream:174:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__locale:15:
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1887:5: error: no matching member function for call to '__init'
    __init(__first, __last);
    ^~~~~~
./test/unit/math/rev/mat/util/test_autodiff.hpp:288:48: note: in instantiation of function template specialization 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >::basic_string<std::__1::basic_string<char> >' requested here
    std::vector<std::string> argument_types = {{type_as_string(args)...}};
                                               ^
./test/unit/math/rev/mat/util/test_autodiff.hpp:329:11: note: in instantiation of function template specialization 'stan::math::test::test_var<(lambda at
      test/unit/math/rev/mat/util/test_autodiff_test.cpp:75:15), int, double>' requested here
          test_var(f, 1e-4, relative_tolerance, absolute_tolerance, args...);
          ^
test/unit/math/rev/mat/util/test_autodiff_test.cpp:77:37: note: in instantiation of function template specialization 'stan::math::test::test_autodiff<(lambda at
      test/unit/math/rev/mat/util/test_autodiff_test.cpp:75:15), int, double>' requested here
  EXPECT_NO_THROW(stan::math::test::test_autodiff(func, 1e-9, 1e-9, 1, 1.0));
                                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1373:10: note: candidate function not viable: no known conversion from 'std::__1::basic_string<char>' to 'const
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') for 1st argument
    void __init(const value_type* __s, size_type __sz);
         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1375:10: note: candidate function not viable: no known conversion from 'std::__1::basic_string<char>' to
      'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size_type' (aka 'unsigned long') for 1st argument
    void __init(size_type __n, value_type __c);
         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1384:5: note: candidate template ignored: requirement '__is_exactly_input_iterator<basic_string<char> >::value' was not
      satisfied [with _InputIterator = std::__1::basic_string<char>]
    __init(_InputIterator __first, _InputIterator __last);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1393:5: note: candidate template ignored: requirement '__is_forward_iterator<basic_string<char> >::value' was not satisfied
      [with _ForwardIterator = std::__1::basic_string<char>]
    __init(_ForwardIterator __first, _ForwardIterator __last);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:1371:10: note: candidate function not viable: requires 3 arguments, but 2 were provided
    void __init(const value_type* __s, size_type __sz, size_type __reserve);
...
```

I'll try to hunt it down.

**Comment by syclik** [comment]
So weird... this fails to compile with clang++ on Mac with the error message above:
```
$ clang++ -v
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

This compiler compiles, but has runtime errors:
```
$ g++-8 -v
Using built-in specs.
COLLECT_GCC=g++-8
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/8.2.0/libexec/gcc/x86_64-apple-darwin18.0.0/8.2.0/lto-wrapper
Target: x86_64-apple-darwin18.0.0
Configured with: ../configure --build=x86_64-apple-darwin18.0.0 --prefix=/usr/local/Cellar/gcc/8.2.0 --libdir=/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 8.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 8.2.0 (Homebrew GCC 8.2.0)
```

It has a bunch of these messages:
```
[ RUN      ] AgradRevMatrix.test_autodiff_scalar_bad
test/unit/math/rev/mat/util/test_autodiff_test.cpp:208: Failure
Expected equality of these values:
  1
  count_matches("does not match the value from the reverse mode call", e.what())
    Which is: 0
expected message: does not match the value from the reverse mode call
found message:
[  FAILED  ] AgradRevMatrix.test_autodiff_scalar_bad (0 ms)
```

**Comment by syclik** [comment]
But before I get too much further into debug mode, I'm going to take a look at the design and how you intend for it to be used.

**Comment by syclik** [comment]
@bbbales2, I was mistaken. It compiles and runs fine with `g++-8`. I had some local changes on my branch as I was trying to debug why it was failing.

**Comment by syclik** [comment]
For whatever reason, it's still not compiling on my machine. I'm using the stock XCode clang++ compiler on Mac, though. Is there any reason this wouldn't work on that? (I'll try to find a workaround anyway.)

**Comment by syclik** [comment]
So... I tracked down one failure. @bbbales2, thank you for unit testing these. It's really making it much easier to figure out what's going on.

I'm inside the prim version of `promote_double_to_VectorXd` test and I just found that using the default compiler on Mac, that test fails. This line doesn't pass: `EXPECT_EQ(1, std::tuple_size<decltype(y)>::value);`. And the awesome / unawesome thing is that when it fails, instead of it being a runtime error, it spits out an awful compiler novel. That's what I've been seeing.

So... it turns out that the version of libc++ that comes with the default clang++ implements this differently and `promote_double_to<float>(std::make_tuple(Eigen::VectorXf)))` returns something of length 0 (and that's known at compile time!).

There's still more digging to do to see what's going on.

**Comment by syclik** [comment]
There’s definitely some weirdness in the implementation. The latest is coming from Windows. I’ll keep at it. 

But before I get too deep into implementation details, I wanted to talk about some of the design aspects. 

First, I think the overall abstraction is great. It would be nice to test autodiff in this way. Some things I’d like to get your take on:
- renaming `test_autodiff` to something like `test_rev_ad` or `test_reverse_ad` or something like that? I don’t think this one function is supposed to test it all? Or is that the intention?
- mind if I change some of the doc that’s supposed to face the developer? I see what you’re trying to do, but I think it’s not as clear as it could be. 
- the PR doc is off; this version has tolerances. 
- I think maybe we have default tolerances and then a different function to set tolerances? Like `test_rev_ad_tol`?

How are the test errors shown? Do we want to run through admins collect errors or do we want to quit at the first error? What’s being done now?

**Comment by bob-carpenter** [comment]
This function doesn't test everything yet.  There is a design question about whether to have different tests for every autodiff level or just have one top-level call.  I sort of did both in the other test frameworks.

Tolerances need to be set on a function-by-function basis.  Would it be possible to just have a tolerance argument with a default that could be set in specific cases.  That's what I did for other tests like this.

**Comment by bbbales2** [comment]
> renaming test_autodiff to something like test_rev_ad or test_reverse_ad or something like that

Sounds good. I like test_rev_autodiff, but I'll go with whatever.

> mind if I change some of the doc that’s supposed to face the developer?

By all means

> the PR doc is off; this version has tolerances.

Good catch!

> I think maybe we have default tolerances

I don't like how I did the tolerances now. After actually using this,
I think one argument should be a generic tolerance (assuming absolute
tolerance == relative tolerance) and the other argument should be the
delta for the finite difference.

I can make this change.

I don't think we should add any state to the testing apparatus or
it'll just get confusing. It's annoying but not too annoying to just
add a couple extra arguments to the end of everything.

> instead of it being a runtime error, it spits out an awful compiler novel

Yeah, that's the tragedy of doing testing like this :P. I'll leave the
Mac fix for you, or I'll be back around Macs in early January and can
futz with it then.

**Comment by syclik** [comment]
Looks like we're on the same page.

Re: design of different tests for autodiff. There are two things that makes me think they should be separate:
1. having runtime errors masked because the traits are instantiated for mixed mode and that somehow interacts with how it'll run in reverse-mode only. We can fix this if we really locked down the traits and got that really solidly tested, but we're far from that and I think we're going to see some hard-to-diagnose problems before we lock all of that down.
2. compilation time and issues. On the old g++ for Windows, we'd run into problems compiling mixed mode. They were terrible failures; silent failures that just didn't run. I don't know what the status is on the new compiler. But beyond that, we'll essentially be instantiating everything with mixed mode to get it done. Maybe that's ok, I'd just want to evaluate it before dismissing this concern.

Tolerances: I agree.

**Comment by syclik** [comment]
@bbbales2, thanks. Agreed with everything, including `test_rev_autodiff`.

Question: what state were you thinking of? I wasn't thinking about adding state, but now I'm curious what you thought I was suggesting.

and also... thanks! I'm really looking forward to having a version of this in. This would make life so much easier.

**Comment by bob-carpenter** [comment]
> On Dec 19, 2018, at 10:09 AM, Daniel Lee <notifications@github.com> wrote:
> 
> @bbbales2, thanks. Agreed with everything, including test_rev_autodiff.
> 
> Question: what state were you thinking of? I wasn't thinking about adding state, but now I'm curious what you thought I was suggesting.

It sounded to me like you were suggesting a stateful set-tolerance.

**Comment by bbbales2** [comment]
> It sounded to me like you were suggesting a stateful set-tolerance.

Yup, this was with respect to the tolerances. I like just being
verbose with the arguments in this situation.

**Comment by syclik** [comment]
> It sounded to me like you were suggesting a stateful set-tolerance.

Maybe? I was thinking of this (in pseudocode that isn't going to work in any language):
```
test_reverse_autodiff_with_tolerances(f, rel_tol, abs_tol, ...);

test_reverse_autodif(f, ...) {
    test_reverse_autodiff_with_tolerances(f, 1e-8, 1e-8, ...);
}
```

**Comment by syclik** [comment]
(Sorry, read back through the comments. Yeah, my bad; I wasn't careful with how I stated what I intended.)

**Comment by syclik** [comment]
@bbbales2, I like the level of abstraction.

Re: design. I think we should separate out testing of exceptions from the values and gradients. I think by autodetecting whether the prim throws and using that as a baseline for the autodiff can mask programmer error. If a function throws when it's not supposed to, but it throws consistently (for both prim and rev), then this gets masked. I think the way to solve this is to split out the testing of exceptions. By doing this, I think we can make the testing of the exceptional case more precise and provide the developer with better tooling. Here are the two things we can add: 1) the type of the exception (and indicate if it isn't properly throwing the correct exception) 2) checking for error messages. The error messages are part of the user experience, both for the math library, but we know it trickles through to users of Stan. We should care what it looks like. It might be too ambitious to have regular expressions for the message, but ideally, we should check that the messages look the way we expect it to look.

Re: implementation. I think the nested autodiff is at the wrong level. I can help clean that up. It'll just take a little bit of time. I'm seeing things like the value test and the exception test not having nested calls. I think we should nest, then add things to the stack, then remove leaving the stack as we found it at the end of each test. (We might have to assume that they're actually on the unnested stack, but that's an implementation detail. We could always add functionality to zero out the stack above.)

**Comment by bob-carpenter** [comment]
What's the advantage of running the tests in a nested config?  Is it to test the nested autodiff?

Do the autodiff versions ever throw their own exceptions?  If they delegate to the double version, they just get the domain checks there and the messages are automatically consistent.  Are there cases where autodiff version of function should throw different exceptions for the same input value as the double version?  

Automatically catching the type and checking for it is tricky.  There's a hack I put into the language for rethrow_located that tries to enumerate all possible exception types that are known---but the list is technically open ended so you need cleanup anyway.

**Comment by syclik** [comment]
> What's the advantage of running the tests in a nested config? Is it to test the nested autodiff? 

There isn't an advantage, as far as I can tell.

The way this implementation works is that it calls a function `call_all_argument_combos()` that promotes all the `double`s to `stan::math::var` s before ever calling the function. That's why nesting is necessary. We can't clean out the whole autodiff stack or else we lose the promoted variables on the stack. I don't know if that made sense... it doesn't have to be done this way, but that's what the current implementation does.


> Do the autodiff versions ever throw their own exceptions? If they delegate to the double version, they just get the domain checks there and the messages are automatically consistent. Are there cases where autodiff version of function should throw different exceptions for the same input value as the double version?

Since we can write custom specializations for templated functions (and we do), it's possible that the specialized versions are not written consistently. This would be programmer error and I think we just want to prevent that. Especially if someone makes a change to one instantiation and not the other.

There should be no cases where the autodiff version should throw a different exception as the double version. I can imagine it happening where in computing the gradient we throw an exception (maybe through Boost).... I'm not sure what we should do if we can't compute the gradient for parameters that are valid.

> Automatically catching the type and checking for it is tricky. There's a hack I put into the language for rethrow_located that tries to enumerate all possible exception types that are known---but the list is technically open ended so you need cleanup anyway.

Yes. In this implementation, it just checks to see that an exception was thrown. The types are ignored.

**Comment by bbbales2** [comment]
> I think the nested autodiff is at the wrong level
> What's the advantage of running the tests in a nested config?

It's quite likely I got it all wrong. I don't think it's necessary (or
desirable). I wouldn't mind if we just axed it.

> I think by autodetecting whether the prim throws and using that as a baseline for the autodiff can mask programmer error
> Automatically catching the type and checking for it is tricky.

Not checking that the autodiff version throws in the same places the
prim does masks programming errors too. If there is some sort of
function that breaks this assumption, then we'd just have to test that
the old school way.

My first try at this had fancier error checking, but it became clear
pretty quickly (from talking to Bob and coding with it) that being
specific was more confusing.

There's real limitations to the error checking stuff. The idea is that
someone can take all the error-check tests they wrote for prim (which
don't use this framework), copy paste them over to their rev tests,
and just wrap em' up in these calls.

I guess we could ask them to specify what error should be thrown as
well and that wouldn't be any harder? I might be forgetting something.
The difficult thing this is handling is instantiating all the
different autodiff types and shuffling around test values, but I guess
they all should be throwing the same error. So maybe splitting of the
error checking is fine in that regard? I could be forgetting
something.

**Comment by bob-carpenter** [comment]
...

> The way this implementation works is that it calls a function call_all_argument_combos() that promotes all the doubles to stan::math::var s before ever calling the function.

I see.  That's unfortunate, because it leads to this kind of problem. Can it be done lazily?


> That's why nesting is necessary. We can't clean out the whole autodiff stack or else we lose the promoted variables on the stack. I don't know if that made sense... it doesn't have to be done this way, but that's what the current implementation does.

I get it.  I don't think we want to be abusing the autodiff stacks this
way.  At least that wasn't what I intended them for.  I really meant it
to be literally used in a nested way, not for variables on the nested
stack to point out of the nested stack.  We should be careful about what
we are guaranteeing for nested autodiff.  I think Sebastian may be running
into similar testing issues.


> Do the autodiff versions ever throw their own exceptions? If they delegate to the double version, they just get the domain checks there and the messages are automatically consistent. Are there cases where autodiff version of function should throw different exceptions for the same input value as the double version?
> 
> Since we can write custom specializations for templated functions (and we do), it's possible that the specialized versions are not written consistently. This would be programmer error and I think we just want to prevent that. Especially if someone makes a change to one instantiation and not the other.

I was trying to ask if there were cases where we want different answers.  Otherwise we can
test that the autodiff versions match the throws of the double versions.  That's what
I did for the basic operator testing framework.  I was *not* testing type of exception or
message, though.


> There should be no cases where the autodiff version should throw a different exception as the double version. I can imagine it happening where in computing the gradient we throw an exception (maybe through Boost).... I'm not sure what we should do if we can't compute the gradient for parameters that are valid.

Right---that's the case I was thinking about.  It didn't come up
for the basic arithmetic.


> Automatically catching the type and checking for it is tricky. There's a hack I put into the language for rethrow_located that tries to enumerate all possible exception types that are known---but the list is technically open ended so you need cleanup anyway.
> 
> Yes. In this implementation, it just checks to see that an exception was thrown. The types are ignored.

That's probably OK.  At least it's what I did for the operator tests.

**Comment by syclik** [comment]
> I think the nested autodiff is at the wrong level What's the advantage of running the tests in a nested config?
> It's quite likely I got it all wrong. I don't think it's necessary (or desirable). I wouldn't mind if we just axed it.

Thanks. I don't think it's that far off. I feel like this is going to be one of those things where we each make improvements until it looks good enough. What you've done is really neat. I think I can take a pass and make some changes that take care of the nesting, etc. And if that isn't good enough (which it probably won't be), then hopefully someone can make improvements to that.

Having the ability to write in C++11 and on is awesome. I wish we had this when we started the project.

**Comment by syclik** [comment]
On Fri, Dec 21, 2018 at 8:06 PM Bob Carpenter <notifications@github.com>
wrote:

> ...
>
> > The way this implementation works is that it calls a function
> call_all_argument_combos() that promotes all the doubles to stan::math::var
> s before ever calling the function.
>
> I see. That's unfortunate, because it leads to this kind of problem. Can
> it be done lazily?
>

Yes, it can.

Instead of expanding the arguments by promoting double to vars, we can just
expand the types of the arguments and within each call, promote if
necessary. (This is so hard to talk about, but instead of the having a
double variable x be put into a tuple as tuple<double, var>(x, var(x)), we
could pass all the args and a type list.)

> That's why nesting is necessary. We can't clean out the whole autodiff
> stack or else we lose the promoted variables on the stack. I don't know if
> that made sense... it doesn't have to be done this way, but that's what the
> current implementation does.
>
> I get it. I don't think we want to be abusing the autodiff stacks this
> way. At least that wasn't what I intended them for. I really meant it
> to be literally used in a nested way, not for variables on the nested
> stack to point out of the nested stack. We should be careful about what
> we are guaranteeing for nested autodiff. I think Sebastian may be running
> into similar testing issues.
>

Agreed.


>
> > Do the autodiff versions ever throw their own exceptions? If they
> delegate to the double version, they just get the domain checks there and
> the messages are automatically consistent. Are there cases where autodiff
> version of function should throw different exceptions for the same input
> value as the double version?
> >
> > Since we can write custom specializations for templated functions (and
> we do), it's possible that the specialized versions are not written
> consistently. This would be programmer error and I think we just want to
> prevent that. Especially if someone makes a change to one instantiation and
> not the other.
>
> I was trying to ask if there were cases where we want different answers.
> Otherwise we can
> test that the autodiff versions match the throws of the double versions.
> That's what
> I did for the basic operator testing framework. I was *not* testing type
> of exception or
> message, though.
>

I don't think so. The only place that I know where we violate this is in
the fvar with the nan check. But creating these things with nans is usually
a user error and we're not really supporting forward and mixed mode yet.

**Comment by bbbales2** [comment]
I had a look at the nesting stuff. Are we talking about moving all the actual type promotion into test_exceptions, test_values, and test_gradients so that they can actually use the nested autodiff without depending on any vars passed in from the outside?

And @syclik , you were suggesting we could change them to look something like:
```c++
test_exceptions<P_args>(f, args...);
test_values<P_args>(f, relative_tolerance, absolute_tolerance, args...);
test_gradients<P_args>(f, dx, relative_tolerance, absolute_tolerance, args...);
```

Where P_args is a tuple of types we want things promoted to and args are just ints and doubles (haven't been promoted to vars yet)? And call_all_argument_combos is no longer calling a function with all combinations of input arguments, but is now juggling different combinations of types n' such?

**Comment by syclik** [comment]
@bbbales2, close. What I'm thinking is that we have two test functions, which you've laid out.

This is in terrible pseudocode, but hopefully you get the idea.

```
test_exception<exception_type>(f, args..., "expected message");
test_reverse_mode(f, args...);
```

(I think technically, the expected message might have to come in before the `args...`)

Within `test_reverse_mode(f, args...)`, I'd want to do something like this:
1. Make sure the world is ok. Check that the autodiff stack has 0 elements.
2. Call a version of your `call_all_combos()`, but with something like... `call_all_combos<tuple_of_args<Targs...>::type>(f, args...)` where `struct tuple_of_args` is a template metaprogram that has the typedef `type` that is a tuple that contains all the ways we want to instantiate it. For example, if we pass in `double, double`, then I'd want that `type` to be: `tuple< tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var> >` (order doesn't matter).
3. Within the function that calls the function, we'd start by using `promote_to<T>` for each argument. That put things on the autodiff stack at that time. Then call `f(promoted_args...)`. Then check all the things we want to check: value, gradient, no throw, etc. After each call to `f`, I want to make sure we clean the autodiff stack and leave it with 0 elements.

Does that make sense? It's hard to communicate without actually implementing this stuff.

**Comment by syclik** [comment]
When I say you got close, I really mean it... instead of the building a template metaprogram for the types, you've actually instantiated a `std::tuple` that contains all the arg combinations. We just need the types for that and we're good to do it lazily.

**Comment by bob-carpenter** [comment]
> On Jan 8, 2019, at 5:10 PM, Daniel Lee <notifications@github.com> wrote:
> 
> @bbbales2, close. What I'm thinking is that we have two test functions, which you've laid out.
> 
> This is in terrible pseudocode, but hopefully you get the idea.
> 
> test_exception<exception_type>(f, args..., "expected message");
> test_reverse_mode(f, args...);
> 
> (I think technically, the expected message might have to come in before the args...)

Parameter packs are more general than that.  But it makes sense to put the expectation first anyway, like in our other tests.

> 
> Within test_reverse_mode(f, args...), I'd want to do something like this:
> 
> 	• Make sure the world is ok. Check that the autodiff stack has 0 elements.

Can we just start fresh instead?

> 	• Call a version of your call_all_combos(), but with something like... call_all_combos<tuple_of_args<Targs...>::type>(f, args...) where struct tuple_of_args is a template metaprogram that has the typedef type that is a tuple that contains all the ways we want to instantiate it. For example, if we pass in double, double, then I'd want that type to be: tuple< tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var> > (order doesn't matter).

I don't think this will work---the explicit instantiations grow exponentially in number of arguments.  It's not so out of hand we can't run the tests, but it will be prohibitive to write them all out manually like this.  Is there ever a reason we wouldn't test everything at a given autodiff order?  So at most, it seems like we'd need to specify which instantiation of the scalar we want to test, and all will assume double has already been tested e.g., 1st order: var, fvar<double>;  2nd order: fvar<fvar<double>>, fvar<var>;  3rd order: fvar<fvar<var>>

> 	• Within the function that calls the function, we'd start by using promote_to<T> for each argument. That put things on the autodiff stack at that time. Then call f(promoted_args...). Then check all the things we want to check: value, gradient, no throw, etc. After each call to f, I want to make sure we clean the autodiff stack and leave it with 0 elements.
> Does that make sense? It's hard to communicate without actually implementing this stuff.

**Comment by syclik** [comment]
@bob-carpenter, quoting on GitHub is a bit hard... hopefully I can get enough context in so it's easy to follow.

> Can we just start fresh instead?
That's what I'm suggesting, but I'd really want to throw an error if the autodiff stack isn't fresh. That's definitely a programmer error and the person writing the test might be expecting those variables to still be on the stack after the test is done. They would have been destroyed in the process.

I'd rather just quit with a reasonable message notifying the programmer that the usage of the test framework is incorrect rather than move on. 

> • Call a version of your call_all_combos(), but with something like... call_all_combos<tuple_of_args<Targs...>::type>(f, args...) where struct tuple_of_args is a template metaprogram that has the typedef type that is a tuple that contains all the ways we want to instantiate it. For example, if we pass in double, double, then I'd want that type to be: tuple< tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var> > (order doesn't matter).
> I don't think this will work---the explicit instantiations grow exponentially in number of arguments. It's not so out of hand we can't run the tests, but it will be prohibitive to write them all out manually like this. Is there ever a reason we wouldn't test everything at a given autodiff order? So at most, it seems like we'd need to specify which instantiation of the scalar we want to test, and all will assume double has already been tested e.g., 1st order: var, fvar<double>; 2nd order: fvar<fvar<double>>, fvar<var>; 3rd order: fvar<fvar<var>>

Sorry, something got lost in translation. I'm not suggesting writing it manually! I'm suggesting we have a template metaprogram that does this. So... something like:
```
reverse_args<double, double>::type
```

should be the type:
```
tuple<
  tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var>
>
```
(And we can skip the all-double case too.)

@bbbales2's implementation already does that... it's just that he implicitly carries the type by building out an instantiation of the tuple. What I mean is that he's building a tuple where let's say the args are two doubles of `(2.0, 3.0)`:
```
make_tuple( 
  make_tuple(2.0, 3.0), make_tuple(2.0, var(3.0)), make_tuple(var(2.0), 3.0), make_tuple(var(2.0), var(3.0))
)
```
That's all instantiated before calling the function so the types are already there, and unfortunately, all the `var`s now live on the stack before calling the function the first time. The first call to the gradient is fine, but the second and third is undefined since we've essentially messed with the variables on the stack.

**Comment by wds15** [comment]
Yack... quite involved as it sounds. Can we setup tuples of types and access these? I think the boost fusion library allows to do stuff like that.

Another solution could be to run the tests in another thread. This will always give you a clean AD tape.

**Comment by bob-carpenter** [comment]
> On Jan 9, 2019, at 11:03 AM, Daniel Lee <notifications@github.com> wrote:
> 
> @bob-carpenter, quoting on GitHub is a bit hard... hopefully I can get enough context in so it's easy to follow.
> 
> Can we just start fresh instead?
> That's what I'm suggesting, but I'd really want to throw an error if the autodiff stack isn't fresh. That's definitely a programmer error and the person writing the test might be expecting those variables to still be on the stack after the test is done. They would have been destroyed in the process.
> 
> I'd rather just quit with a reasonable message notifying the programmer that the usage of the test framework is incorrect rather than move on.
> 
> • Call a version of your call_all_combos(), but with something like... call_all_combos<tuple_of_args<Targs...>::type>(f, args...) where struct tuple_of_args is a template metaprogram that has the typedef type that is a tuple that contains all the ways we want to instantiate it. For example, if we pass in double, double, then I'd want that type to be: tuple< tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var> > (order doesn't matter).
> I don't think this will work---the explicit instantiations grow exponentially in number of arguments. It's not so out of hand we can't run the tests, but it will be prohibitive to write them all out manually like this. Is there ever a reason we wouldn't test everything at a given autodiff order? So at most, it seems like we'd need to specify which instantiation of the scalar we want to test, and all will assume double has already been tested e.g., 1st order: var, fvar; 2nd order: fvar<fvar>, fvar; 3rd order: fvar<fvar>
> 
> Sorry, something got lost in translation. I'm not suggesting writing it manually! I'm suggesting we have a template metaprogram that does this. So... something like:
> 
> reverse_args<double, double>::type
> 
> should be the type:
> 
> tuple<
>   tuple<double, double>, tuple<double, var>, tuple<var, double>, tuple<var, var>

I'm just saying I don't think we ever want to build up such a type.
Even if done automatically.  At least not if it can be avoided.  I could
be convinced otherwise if it's not as slow as I'm imagining it'll be.

> >
> 
> (And we can skip the all-double case too.)
> 
> @bbbales2's implementation already does that... it's just that he implicitly carries the type by building out an instantiation of the tuple. What I mean is that he's building a tuple where let's say the args are two doubles of (2.0, 3.0):
> 
> make_tuple( 
>   make_tuple(2.0, 3.0), make_tuple(2.0, var(3.0)), make_tuple(var(2.0), 3.0), make_tuple(var(2.0), var(3.0))
> )
> 
> That's all instantiated before calling the function so the types are already there, and unfortunately, all the vars now live on the stack before calling the function the first time.

I didn't realize that's what was happening. That seems really unfortunate.  Is there
no way to do this lazily?

> The first call to the gradient is fine, but the second and third is undefined since we've essentially messed with the variables on the stack.

Ack!  I see the problem now.  Thanks.

**Comment by syclik** [comment]
What part of it do you think will be slow? The compilation?

It shouldn't be any slower than what happens now. Right now that tuple of tuples type is implicitly built using the instantiated tuple. 

And to do the conversion lazily all we need are the types. That's what's motivating me to think about how to build the type and pass that along. When I get back to a computer, I'll come up with an example.

**Comment by bob-carpenter** [comment]
Yes, the compilation.  Are there three-argument functions being tested with all the instantiations?  If so, I wouldn't worry about it, too much---we don't have many functions with more than three arguments we want to test this way.

**Comment by syclik** [comment]
Closing for now. Not getting rid of the branch.

**Pull request closed without merging**
