### PR TITLE
updating gitignore

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Fixes our issues with gitignore, especially for the `test/` directory.

#### Intended Effect:

Allows new files to be detected.

#### How to Verify:

Add a file to the test directory: see if it shows up in git.

#### Side Effects:

None. Doesn't touch code.

#### Documentation:

None.

#### Reviewer Suggestions: 

@bgoodri, can you verify that this has the right behavior?

### CODE REVIEW

**Comment by bgoodri** [comment]
This seems to unignore the src/ directory. Is that intended?

**Comment by syclik** [comment]
I don't understand the question.

There's no src/ directory.

**Comment by bgoodri** [comment]
I do
```
goodrich@T540p:/opt/stan/lib/stan_math_2.7.0$ ls -R src/ | head
src/:
test

src/test:
prob

src/test/prob:
bernoulli
beta
beta_binomial
```

It has generated tests inside of it like
```
src/test/prob/bernoulli:
bernoulli_00000_generated_fd_test.cpp
```

**Comment by syclik** [comment]
I think you're pretty far behind on that branch. Maybe update and clean
untracked files?

**Comment by bgoodri** [comment]
I just checked it out
```
goodrich@T540p:/opt/stan/lib/stan_math_2.7.0$ make clean-all
rm -f -r doc/api
 removing test executables
 removing dependency files
rm -f
 removing generated test files
rm -f
goodrich@T540p:/opt/stan/lib/stan_math_2.7.0$ git pull -ff
Already up-to-date.
goodrich@T540p:/opt/stan/lib/stan_math_2.7.0$ ls -R src/ | head
src/:
test

src/test:
prob

src/test/prob:
bernoulli
beta
beta_binomial

```
I could rm -rf src/ but how did it get there in the first place?

**Comment by syclik** [comment]
could you checkout the develop branch? I wonder if you're still on the tag.

It used to be under src/. Do you have a stan/ folder at that level? That's
where everything moved to.

**Comment by bgoodri** [comment]
The src/ folder is still there if I checkout develop and do a fast-forward
merge. There is a stan/ folder right next to it.

**Comment by syclik** [comment]
not sure what to tell you... it doesn't exist on the develop branch as of now:
https://github.com/stan-dev/math

**Comment by bgoodri** [comment]
The born-on date is August 21 but it only has *_generated_test.cpp files.
```
src/test/prob:
total 508K
drwxr-xr-x 2 goodrich goodrich 4.0K Aug 21 16:26 bernoulli
```

**Comment by betanalpha** [comment]
git won’t delete old, untracked folders on a merge.
You have to do that yourself with git-clean.

**Comment by syclik** [comment]
not sure what that means. `git clean -d -x -f`? I don't know if you want to do that, but if you do, see if it removes `src/`?

**Comment by bgoodri** [comment]
git-clean -i src/ didn't do anything so I just removed the folder. We'll
figure it out if it comes back.

**Comment by bob-carpenter** [comment]
I also found the gitignore very confusing on math.  It showed
me all the auto-generated test files (wow, there are a lot of them)
when I did "git status".

- Bob

**Comment by syclik** [comment]
@bgoodri, are you good with this pull request?

**Comment by syclik** [comment]
Bob, on that branch, it shouldn't show the auto-generated test files. If it
does, there's some behavior differences with git versions that I didn't
take into account.

**Comment by bob-carpenter** [comment]
This was on the inv_Phi branch --- I didn't try the gitignore branch.

Warning:  there was a change to the .gitignore file on the inv_Phi branch.

- Bob

**Comment by syclik** [comment]
Thanks for the heads up.

**Comment by bgoodri** [comment]
That was probably on the inv_Phi branch.

**Comment by bgoodri** [comment]
Yeah, it is fine.

**Pull request merged**
