### PR TITLE
Fix Aliasing issue in OpenCL

### LINKED ISSUE #2942: Aliasing issue in OpenCL `assignment_impl`
## Description

Given the following test of addition of the same matrix together we get the wrong adjoints. This is caused by an aliasing issue, the inputs adjoint is reassigned instead of readded to the adjoints of the input.

```c++
TEST(OpenCLPrim, add_aliasing) {
  stan::math::matrix_d d1(3, 3);
  d1 << 1, 2, 3, 4, 5, 6, 7, 8, 9;
  using stan::math::matrix_cl;
  using stan::math::var_value;
  using stan::math::var;
  using varmat_cl = var_value<matrix_cl<double>>;
  varmat_cl d11 = stan::math::to_matrix_cl(d1);
  // Add the same matrix as the left and right hand side
  var res = stan::math::sum(stan::math::add(d11, d11));
  res.grad();
  // Get back adjoints
  Eigen::MatrixXd grad_res = stan::math::from_matrix_cl(d11.adj());
  stan::math::recover_memory();
  Eigen::Matrix<var, -1, -1> d_host = d1;
  // Same op as above but on the host
  var res_host = stan::math::sum(stan::math::add(d_host, d_host));
  res_host.grad();
  Eigen::MatrixXd grad_res_host = d_host.adj();
  std::cout << "OpenCL Adjoints: " << std::endl;
  std::cout << grad_res << std::endl;
  std::cout << "CPU Adjoints: " << std::endl;
  std::cout << grad_res_host << std::endl;
}
```

```
OpenCL Adjoints: 
1 1 1
1 1 1
1 1 1
CPU Adjoints: 
2 2 2
2 2 2
2 2 2
```

The issue here is in the `+=` operator of `adjoint_result`, where internally the `assignment_impl` is generating code. When the below code generates the OpenCL code, it does not know that the left and right hand side are the same matrix

```c++
template <typename T_a, typename T_b,
          require_all_prim_or_rev_kernel_expression_t<T_a, T_b>* = nullptr,
          require_any_var_t<T_a, T_b>* = nullptr,
          require_any_not_stan_scalar_t<T_a, T_b>* = nullptr>
inline auto add(T_a&& a, T_b&& b) {
  arena_t<T_a> a_arena = std::forward<T_a>(a);
  arena_t<T_b> b_arena = std::forward<T_b>(b);

  return make_callback_var(
      value_of(a_arena) + value_of(b_arena),
      [a_arena, b_arena](vari_value<matrix_cl<double>>& res) mutable {
        adjoint_results(a_arena, b_arena) += expressions(res.adj(), res.adj());
      });
}
```

Below is the generated OpenCL code with comments to show what is happening and where the issues are. The the very last two lines `var2_global` is being reassigned where it should be readded 

```opencl
/**
 * A kernel for the equivalent of Matrix += Matrix
 * @param[in/out] var2_global Pointer to array of doubles representing matrix
 * @param[in] var2_rows Rows of var2
 * @param[in] var2_view Whether the matrix is upper or lower triangular or plain
 * @param[in] var3_global Pointer to array of doubles representing matrix
 * @param[in] var3_rows Rows of var3
 * @param[in] var3_view Whether the matrix is upper or lower triangular or plain
 */
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var3_global, int var3_rows, int var3_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    // If var2 is lower or upper triangular and this cell is 
    //  not in the range of work, assign it a value of zero
    //  Otherwise assign it the value of var2 the cell works with
    double var2 = 0; 
    if (!((!contains_nonzero(var2_view, LOWER) && j < i) || (!contains_nonzero(var2_view, UPPER) && j > i))) {
        var2 = var2_global[i + var2_rows * j];
    }
    // Same for var3
    double var3 = 0; 
    if (!((!contains_nonzero(var3_view, LOWER) && j < i) || (!contains_nonzero(var3_view, UPPER) && j > i))) {
        var3 = var3_global[i + var3_rows * j];
    }
    // Make a temporary storing value of var2 + var3
    double var1 = var2 + var3;
    // Assign temp to var2
    var2_global[i + var2_rows * j] = var1;
    // PROBLEM HERE: Do the same thing
    double var4 = var2 + var3;
    var2_global[i + var2_rows * j] = var4;
}
```

```opencl
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var3_global, int var3_rows, int var3_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    var2_global[i + var2_rows * j] += var3;
    var2_global[i + var2_rows * j] += var3;
}
```

@t4c1 I'm going through the OpenCL codegen right now picking apart where/how I could get something like the above. I think the pattern I'd to generate would be something like the below where the output is just `+=`'d into and not stored as part of the temporaries leading to an assignment. I'm having trouble reading in the `+=` operator on how the codegen is happening here. Any tips or time you can take to look at this would be appreciated!

```opencl
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var{N}_global, int var{N}_rows, int var{N}_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    // Get the scalar for each input op
    double var{N} = 0; 
    if (!((!contains_nonzero(var3_view, LOWER) && j < i) || (!contains_nonzero(var3_view, UPPER) && j > i))) {
        var{N} = var{N}_global[i + var{N}_rows * j];
    }
    // Perform operations on each scalars
    double var{M} = OP(var{1:N}...);
    // Assign result to output
    var2_global[i + var2_rows * j] += var{M};
    // Assign next result to output
    double var{J} = OP(var{1:N}...);
    var2_global[i + var2_rows * j] += var{J};
}
```

I think adjoint accumulation is the only place where this is an issue. It's an issue in any place that's possible to have aliasing in the multi assignment, but for Stan's purposes that only really happens in the adjoint accumulation. An easy fix would just be to take anywhere we do a multi assign in adjoint ops and break it up into two separate kernels

```
adjoint_results(a_arena) += expressions(res.adj());
adjoint_results(b_arena) += expressions(res.adj());
```

## Expected Output

Adjoint accumulation is aliasing safe on for OpenCL

#### Current Version:
v4.7.0

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

Fixes #2942 by adding compound assignment operators to `result_cl` so that assignments in the generated OpenCL for adjoint calculations use `+=` such as the below 

```opencl
/**
 * A kernel for the equivalent of Matrix += Matrix
 * @param[in/out] var2_global Pointer to array of doubles representing matrix
 * @param[in] var2_rows Rows of var2
 * @param[in] var2_view Whether the matrix is upper or lower triangular or plain
 * @param[in] var3_global Pointer to array of doubles representing matrix
 * @param[in] var3_rows Rows of var3
 * @param[in] var3_view Whether the matrix is upper or lower triangular or plain
 */
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var3_global, int var3_rows, int var3_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    // If var2 is lower or upper triangular and this cell is 
    //  not in the range of work, assign it a value of zero
    //  Otherwise assign it the value of var2 the cell works with
    double var2 = 0; 
    if (!((!contains_nonzero(var2_view, LOWER) && j < i) || (!contains_nonzero(var2_view, UPPER) && j > i))) {
        var2 = var2_global[i + var2_rows * j];
    }
    // Same for var3
    double var3 = 0; 
    if (!((!contains_nonzero(var3_view, LOWER) && j < i) || (!contains_nonzero(var3_view, UPPER) && j > i))) {
        var3 = var3_global[i + var3_rows * j];
    }
    // Make a temporary storing value of var2 + var3
    double var1 = var2 + var3;
    // Compound Assign var1 to var2
    var2_global[i + var2_rows * j] += var1;
    double var4 = var2 + var3;
// Compound Assign var4 to var2
    var2_global[i + var2_rows * j] += var4;
}
``` 

## Tests

Tests are added for the compound assignment and can be run via 

```bash
python ./runTests.py -j12 ./test/unit/math/opencl/kernel_generator/assignment_ops_test.cpp 
```

## Side Effects

Locally I've been getting spurious errors for some of the reverse mode pdf distributions not matching the cpu versions? Though none of those touch the compound operators so I'm not sure why that is happening

## Release notes
  
Fixes aliasing issue in adjoint acccumulation for OpenCL

## Checklist

- [x] Math issue #2942 

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by SteveBronder** [comment]
@rok-cesnovar or @t4c1 would one of you have time to look at this?

**Comment by rok-cesnovar** [comment]
Sure thing, will have a look in the next days.

**Comment by SteveBronder** [comment]
@rok-cesnovar can you take a look at this?

**Review by rok-cesnovar — APPROVED** [review]
Looks great. I was not getting any issues running the tests locally, so I think this is good to go.

**Pull request merged**
