### PR TITLE
Feature/issue 864 matern32 prim

### PR DESCRIPTION
**Pull request by drezap**
#### Submission Checklist
- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Add matern 3/2 kernel to prim, ARD support.

I included all review comment updates from #867 to make less work for everyone.

#### How to Verify:
tested error throws, std::vector<double> and all combinations of vec/rvec, etc.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Copyright 2018 Andre Zapico

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by drezap** [comment]
closing until ready

**Comment by drezap** [comment]
some install failure on this machine? restarting

**Comment by drezap** [comment]
can someone reset the travis build for me? I have permission on jenkins, but not here. Thank you!

**Comment by drezap** [comment]
@syclik mind checking this out.

Really sorry to ram stuff into this bottle neck! I have more coming...

**Comment by bob-carpenter** [comment]
Just a heads up that we're getting 2.18 ready and any day now, we're going to stop reviewing new code and package 2.18.

**Comment by drezap** [comment]
alright sounds good thanks

**Comment by drezap** [comment]
closing until some edits are made, not ready for review

**Pull request closed without merging**
