### PR TITLE
Keeping `5.0-breaking-changes` up-to-date with `develop`

### PR DESCRIPTION
**Pull request by syclik**
## Summary

Updating the `5.0-breaking-changes` branch with the latest updates to `develop`.

### CODE REVIEW

**Review by SteveBronder — APPROVED** [review]

**Comment by SteveBronder** [comment]
Should we merge this to the 5.0 branch?

**Comment by SteveBronder** [comment]
Confused with what we are doing on this branch? Should we just be updating the 5.0 breaking changes branch directly?

**Comment by syclik** [comment]
Sorry about that. I thought the 5.0 branch was protected. If it's not, we should just keep it up to date.

And we can close this PR.

**Comment by SteveBronder** [comment]
Yes sorry I did that and forgot to say something. I removed the protection because I wanted to update it. I was going to do it this way, but then it involves making the pr originally to the develop branch and then switching to the 5.0 branch which imo is kind of annoying. Since the 5.0 branch runs the tests we can just update it locally, run the tests, and when the tests pass push up the merge

**Comment by syclik** [comment]
No worries! Makes sense.

**Pull request closed without merging**
