### PR TITLE
Feature/issue 125 cholesky derivative

### PR DESCRIPTION
**Pull request by syclik**
This is Rob's pull request.

Summary:

Introduces var specialization of cholesky_decompose
Intended Effect:

Wall-time boost of about about 30% to 50% over currently implemented naive autodiff-through-Eigen version, memory use O(D^2) instead of O(D^3).
How to Verify:

./runTests.py test/unit/math/rev/mat/fun/cholesky_decompose_test.cpp

runs two gradient tests comparing results to finite diff.
Side Effects:

None.
Documentation:

Included in code.
Reviewer Suggestions:

Anyone

### CODE REVIEW

**Comment by bgoodri** [comment]
This should be fine now.

**Comment by syclik** [comment]
@rtrangucci texted me last night saying he needs to add the file to the
math.hpp header, so we'll wait for that.

**Comment by bgoodri** [comment]
OK, but we should really be generating math.hpp with a script that does
```
find stan/math -type f -name "*.hpp" -print | \
grep -v -F -e "stan/math/fwd" -e "stan/math/mix" | \
sed 's@\(^.*$\)@#include <\1>@g'
```

**Comment by syclik** [comment]
Sure. I'd gladly take that. New issue / pull request?

**Comment by bgoodri** [comment]
Let's do it after the release. Wouldn't want to mess anything up at this
point. It might uncover some previously unincluded .hpp files.

**Comment by syclik** [comment]
@rtrangucci still waiting. It just needs to be added to math.hpp, right? If so, I can take care of it.

**Comment by rtrangucci** [comment]
Right, as long as that gets included into model_header.hpp. 

Rob

**Comment by syclik** [comment]
I added the header to `math.hpp`.
@bgoodri ok'ed this pull request.

**Pull request merged**
