### PR TITLE
Order arguments in matrix_normal_prec tests correctly

### LINKED ISSUE #828: Order of arguments to `matrix_normal_prec_log` appears reversed in multiple places
#### Description:

We have a definition of 

~~~
matrix_normal_prec_log(
    const Eigen::Matrix<T_y, Eigen::Dynamic, Eigen::Dynamic>& y,
    const Eigen::Matrix<T_Mu, Eigen::Dynamic, Eigen::Dynamic>& Mu,
    const Eigen::Matrix<T_Sigma, Eigen::Dynamic, Eigen::Dynamic>& Sigma,
    const Eigen::Matrix<T_D, Eigen::Dynamic, Eigen::Dynamic>& D)
~~~

but the calls to this function in `matrix_normal_test.cpp` (actually multiple files due to the directory hierarchy) and `matrix_normal_prec_log_test` look like:

~~~
var<double> lp_ref = stan::math::matrix_normal_prec_log(y, mu, D, Sigma);
~~~

Either these are named confusingly or `D` and `Sigma` have been swapped. 

The tests hardcode some unexpected values, but it's not clear to me where those numbers came from:

~~~
EXPECT_FLOAT_EQ(-2132.07482, lp_ref.val_);
EXPECT_FLOAT_EQ(-2075.1274, lp_ref.d_);
~~~

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by mcol**
## Summary

The tests for `matrix_normal_prec_lpdf` and `matrix_normal_prec_rng` used argument names in the wrong order, which is confusing. This sorts that out and also cleans up those files a little. Fixes #828.

## Tests

Besides clean up, no changes to tests were made.

## Side Effects

None.

## Checklist

- [X] Math issue #828

- [X] Copyright holder: Marco Colombo

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

**Comment by mcol** [comment]
Potentially the test names could be modified to be called `matrix_normal_prec_log_test` rather than `matrix_normal_test`. Also, `prim/mat/prob/matrix_normal_prec_log_test.cpp` and `prim/mat/prob/matrix_normal_test.cpp` could be merged. I'm just waiting to hear if those renames are correct before messing up this PR.

**Comment by rok-cesnovar** [comment]
This looks good to me. Do you want to also do the requested name changes before merging?

**Comment by mcol** [comment]
Sure, I'm going to rename them the way I described above.

**Comment by mcol** [comment]
Actually, I now understand the naming convention: files with names ending with `_log` only contain tests for equality between _log and _lpdf functions, while those without actually test the function. The only change to do is renaming `matrix_normal_test.cpp` to `matrix_normal_prec_test.cpp`.

**Pull request merged**
