### PR TITLE
Add complex types to signature expression tests

### LINKED ISSUE #2676: Stan signature expression tests should support complex numbers
Some math tests are triggered off the output of signatures from stanc. These were never updated to include complex numbers as a scalar, and particularly with complex_matrix etc coming we should add this.

See: 
https://github.com/stan-dev/math/blob/01dd2e7487236880bfc7282119d1355fdfd9dc48/test/sig_utils.py#L15-L27

This will need to add mappings for complex (`std::complex<SCALAR>`) and similar for the container types

### PR DESCRIPTION
**Pull request by WardBrian**
Closes #2676 

## Summary

This adds `complex`, `complex_matrix`, `complex_vector`, and `complex_row_vector` to the types automatically tested by the expression tests based on stanc3's signatures.

## Checklist

- [x] Math issue #2676

- [x] Copyright holder: Simons Foundation

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Review by rok-cesnovar — DISMISSED** [review]
Looks good. Merge once tests pass. Thanks for formatting as well!

**Comment by WardBrian** [comment]
This requires some C++ work before it's all correct. We need to add complex specializations for most of the functions in `expression_test_helpers.hpp`

We also might need better definitions of `stan::math::sum` for complex types

**Review by rok-cesnovar — APPROVED** [review]

**Comment by andrjohns** [comment]
It looks like this PR has broken our CI unfortunately.

Running `varmat_compatibility_summary_test` on `develop` fails:
```
python ./test/varmat_compatibility_summary_test.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.001s

OK
root@0fdfdbc352be:/workdir# python ./test/varmat_compatibility_test.py
curl -L https://github.com/stan-dev/stanc3/releases/download/nightly/linux-stanc -o test/expressions/stanc --retry 5 --retry-delay 10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   650  100   650    0     0   1454      0 --:--:-- --:--:-- --:--:--  1454
100 13.2M  100 13.2M    0     0  4196k      0  0:00:03  0:00:03 --:--:-- 6568k
chmod +x test/expressions/stanc
/workdir/test/varmat_compatibility.py:114: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  all_signatures = get_signatures()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/workdir/test/code_generator.py:78: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if number_nested_arrays > 0 and isinstance(value, collections.Iterable):
sum(array[] int) => int ... Irrelevant
sum(array[] complex) => complex ... Irrelevant
sum(array[] real) => real ... Irrelevant
Results of test 0 / 6, sum(row_vector) => real ... Success
Results of test 1 / 6, sum(complex_vector) => complex ... Fail
Results of test 2 / 6, sum(matrix) => real ... Success
Results of test 3 / 6, sum(complex_matrix) => complex ... Fail
Results of test 4 / 6, sum(complex_row_vector) => complex ... Fail
Results of test 5 / 6, sum(vector) => real ... Success
F
======================================================================
FAIL: test_sum_works (__main__.VarmatCompatibilityMainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/varmat_compatibility_test.py", line 19, in test_sum_works
    self.assertEqual(len(results["incompatible_signatures"]), 0)
AssertionError: 3 != 0

----------------------------------------------------------------------
Ran 1 test in 71.617s
```

**Comment by rok-cesnovar** [comment]
I am yeah, should have a PR open soon.

**Pull request merged**
