### PR TITLE
Revert GPU caching

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Reverts GPU caching merged in #1320 and removes the `::constant` call inside normal_id_glm_lpdf. We are reverting this because we discovered issues that could arise with this implementation of caching mainly because the const qualifier restriction for cached matrices can be avoided fairly easy. 

See the discussion in the original PR for detailed reasons and examples.

## Tests

Just a revert.

## Side Effects

GPU normal_id_glm_lpdf is now slow for the time being. That will be resolved separately.

## Checklist

- [x] Math issue #1319 

- [x] Copyright holder: Rok Češnovar

- [x] the basic tests are passing

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@SteveBronder sorry, I re-reverted back the constructor from buffer which is needed and isnt really a "caching thing". You will need to re-approve :/

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal The "Cannot contact i-05db9d95f4c43b264: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on i-05db9d95f4c43b264 failed. The channel is closing down or has closed down" error is back again.

**Comment by serban-nicusor-toptal** [comment]
Argh, looking into it.

**Comment by rok-cesnovar** [comment]
Ready to be merged now.

**Pull request merged**
