### PR TITLE
Add *-test to the patterns to ignore

### LINKED ISSUE #1504: add generated *-test files to .gitignore
## Description

The current `.gitignore` file for math does not include `*-test`. This makes `git status` unusable, as all generated `*-test` files are marked as uncommitted. The simple fix is to just ignore them always, as we don't want to track them (or commit) them anyway.

### PR DESCRIPTION
**Pull request by mcol**
## Summary

Fixes #1504 by adding `*-test` to the `.gitignore` file.

## Tests

Not required.

## Side Effects

None.

## Checklist

- [X] Math issue #1504

- [X] Copyright holder: Marco Colombo

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Just curious, what do you run to get the *-test files? Are you on Linux/Windows/Mac? 

Building tests doesn't produce those files to me and the built test files do not cause an issue with `git status` for me. Not saying this should not get in, just wondering. If it's causing issues for you during development and doesn't cost us anything then its definitely green lights as far as I am concerned.

**Comment by syclik** [comment]
One other question: what version of git are you running? I know older versions have a little trouble with gitignore and that's gotten better over time.

**Comment by mcol** [comment]
I'm using git version 2.17.1 on Linux. To be honest I don't know how they were created, but I have a ton of `*.hpp-test` files lying around. They are all empty, and they don't seem to be have been changed in about a month.

I have removed them to see find out if I can get to regenerate them. These lines in `make/tests` seem to be responsible, although I can't seem to trigger them now, even if running `make test-headers`:
```
HEADER_TESTS := $(addsuffix -test,$(shell find stan -name '*.hpp' -type f))

%.hpp-test : %.hpp test/dummy.cpp
        $(COMPILE.cpp) $(CXXFLAGS) -O0 -include $^ -o $(DEV_NULL)
```

**Comment by syclik** [comment]
Ah... those shouldn't have been generated. If you look at the target, it
doesn't actually output to anywhere except DEV_NULL. So I don't know where
you're getting those files from. If you find out what causes it to happen,
please post so we can track it down.

**Comment by mcol** [comment]
Ok, I'm closing this now as I must have messed up something on my side. If I ever get to reproduce it again, it's easy enough to reopen and fix.

**Pull request closed without merging**
