### PR TITLE
Feature/issue 180 clean up ode

### PR DESCRIPTION
**Pull request by betanalpha**
#### Summary:

Addresses Issue #180.  The rev implementation of coupled_ode_system::operator() now features consistent notation making it easier to understand.  Additionally the autodiff stack is now built only once instead of the N (size of the base ODE system) times, which should lead to a pretty noticeable speed up.

Additionally a new test of the resulting ODE sensitivies was added to complement the ODE state tests in integrated_ode_test.cpp.

#### Intended Effect:

More easily maintained code, faster execution of ODE derivatives.

#### How to Verify:

./runTests.py test/unit/math/rev/arr/functor/*test.cpp

#### Side Effects:

Faster execution.

#### Documentation:

None, nothing user facing.

#### Reviewer Suggestions:

@syclik @bob-carpenter

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Awesome!  Thanks much.

- Bob

**Comment by wds15** [comment]
ähmm... I was hoping to get the ultimate speedup and combined this branch with the robust-integrator branch, but instead of a speedup, I was getting a 2.6x slow down which I should not happen if the AD effort is reduced:

feature-179-robust-integrator branch merged with feature-179-robust-integrator branch ./test/unit/math/rev/arr/functor/integrate_ode_test
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (7700 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (20449 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (28150 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (28150 ms total)
[  PASSED  ] 2 tests.


feature-179-robust-integrator branch ./test/unit/math/rev/arr/functor/integrate_ode_test
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (701 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (477 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (1178 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (1178 ms total)
[  PASSED  ] 2 tests.

**Comment by betanalpha** [comment]
This is an irrelevant comparison because it convolves the controlled stepper
which can be expensive itself.  Only performance comparisons of this branch
are relevant here.

**Comment by wds15** [comment]
Point taken. Here is the branch vs develop:

issue-180-clean_up_ode:
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (4507 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (28725 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (33232 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (33233 ms total)
[  PASSED  ] 2 tests.


develop:
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (644 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (602 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (1246 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (1246 ms total)
[  PASSED  ] 2 tests.

**Comment by betanalpha** [comment]
Bob, Dan, have you had a chance to look at the PR?

**Comment by bob-carpenter** [comment]
I get a factor of 20 slowdown using g++ -O3 (see below).  I stared at the code
for half an hour and am totally perplexed as to how the original could
be faster.  I don't see how the problem could be anywhere other than
set_zero_all_adjoints() unless those copies with the insert() are WAY slower.
Otherwise, it's the same damn work in both places, only with set_zero replacing
the rebuilding of the function.

That's just this:

  static void set_zero_all_adjoints() {
      for (size_t i = 0; i < ChainableStack::var_stack_.size(); ++i)
        ChainableStack::var_stack_[i]->set_zero_adjoint();
      for (size_t i = 0; i < ChainableStack::var_nochain_stack_.size(); ++i)
        ChainableStack::var_nochain_stack_[i]->set_zero_adjoint();
    }

I worried that it was the fact that set_zero_adjoint() was virtual, so I made
it non-virtual, but no difference.

So then I instrumented the inner loop to track the var_stack


      std::cout << ChainableStack::var_stack_.size() << "   "
                << ChainableStack::var_nochain_stack_.size() 
                << std::endl;

and it looks like something is causing the var_stack_ to keep
growing from around 7 entries to around 30,000 during the tests. 
Is that expected?

This happens in both the original version and the new version.
So it still doesn't help with why the new one's faster.

- Bob

~/stan-dev/math(feature/issue-180-clean_up_ode)$ ./runTests.py -j4 test/unit/math/rev/arr/functor/integrate_ode_test.cpp 
...
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (2325 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (11067 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (13392 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (13392 ms total)
[  PASSED  ] 2 tests.


~/stan-dev/math(develop)$ ./runTests.py -j4 test/unit/math/rev/arr/functor/integrate_ode_test.cpp 
...
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from StanAgradRevOde_integrate_ode
[ RUN      ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.harmonic_oscillator_finite_diff (412 ms)
[ RUN      ] StanAgradRevOde_integrate_ode.lorenz_finite_diff
[       OK ] StanAgradRevOde_integrate_ode.lorenz_finite_diff (379 ms)
[----------] 2 tests from StanAgradRevOde_integrate_ode (791 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (791 ms total)
[  PASSED  ] 2 tests.


- Bob

**Comment by bob-carpenter** [comment]
I instrumented the code, and the culprit's clearly the
set_zero_all_adjoints() function.

for (size_t i = 0; i < N_; i++) {
            clock_t cl1 = clock();
            set_zero_all_adjoints();
            clock_t cl2 = clock();
            dy_dt_vars[i].grad(z_vars, grad);
            clock_t cl3 = clock();

            for (size_t j = 0; j < M_; j++) {
              // orders derivatives by equation (i.e. if there are 2 eqns
              // (y1, y2) and 2 parameters (a, b), dy_dt will be ordered as:
              // dy1_dt, dy2_dt, dy1_da, dy2_da, dy1_db, dy2_db
              double temp_deriv = grad[N_ + j];
              for (size_t k = 0; k < N_; k++)
                temp_deriv += z[N_ + N_ * j + k] * grad[k];

              coupled_sys[i + j * N_] = temp_deriv;
            }
            clock_t cl4 = clock();
            double cps = CLOCKS_PER_SEC;
            std::cout << "set_zero=" << (cl2 - cl1)/cps
                      << " grad=" << (cl3 - cl2)/cps
                      << " coupled_sys=" << (cl4 - cl3)/cps
                      << std::endl;
          }


First few calls:

set_zero=2e-06 grad=1e-06 coupled_sys=0
set_zero=2e-06 grad=0 coupled_sys=0
set_zero=1e-06 grad=0 coupled_sys=1e-06
set_zero=2e-06 grad=0 coupled_sys=0
set_zero=1e-06 grad=0 coupled_sys=0
set_zero=1e-06 grad=0 coupled_sys=2e-06


Last few calls:

set_zero=0.000106 grad=0 coupled_sys=0
set_zero=0.000108 grad=0 coupled_sys=1e-06
set_zero=0.000106 grad=0 coupled_sys=2e-06
set_zero=0.000105 grad=2e-06 coupled_sys=0
set_zero=0.000105 grad=2e-06 coupled_sys=0

I haven't dived down into the tests themselves enough to
know whether the stack size (and hence set_zero) time is
expected to keep growing.  What I don't get is that the time
of set_zero should grow with the time of computing the whole
expression graph ---- there may be a bug in resizing
somewhere.

- Bob

**Comment by betanalpha** [comment]
But the expression graph size isn’t changing here, right?
At least because everything is wrapped in a 
start_nested/recover_nested_memory block.  Is the problem
just that the expression graph surrounding the nested ODE
graph is huge so that set_zero_all_adjoints() is doing lots
of unnecessary work? 

If so what would a set_zero_all_nested_adjoints() look like?

**Comment by betanalpha** [comment]
> If so what would a set_zero_all_nested_adjoints() look like?

In other words, how does one loop over the nested part of the autodiff stack?

static void set_zero_all_nested_adjoints() {
  // How much of the stack to loop over?
  for (size_t i = ?; i < ?; ++i) 
    ChainableStack::var_stack_[i]->set_zero_adjoint();
}

**Comment by bob-carpenter** [comment]
Good point --- we only need to zero the adjoints for the nested part
of the stack here!  You can see how to loop over the nested part in
the nested recover memory.

So maybe it's two things:

1)  get rid of useless chainable object making things 
    neeedless virtual, and

2)  write a set_zero_adjoints_nested() that only zeroes the nested
    part so we can do efficient nested Jacobians!

But with (2) we may not even need (1).

- Bob

**Comment by bob-carpenter** [comment]
Success, sort of.  With a new set_zero_adjoints_nested() and
removing the virtual calls, it's now 750ms on the
new branch vs. 800ms on develop.  So it cut 30% of the
time for removing virtuals and then 90% of the remaining time
just doing the nested.  But it doesn't look much faster to do
the resets than to just rebuild.  At least not with a lot else
going on in the program.

**Comment by bob-carpenter** [comment]
I pushed a new set_zero_adjoints_nested() function and updated the coupled ODE system to call it.

**Comment by bob-carpenter** [comment]
I'm going to fix the underlying virtual issue in another issue, which should then get merged into develop first, and then into this branch:

https://github.com/stan-dev/math/issues/183

**Comment by bob-carpenter** [comment]
This is currently failing because of doxygen warnings about parameters.  Some of the doc got past the parameter declarations.  But we'll still have problems because the doc didn't get updated to match the functions in the coupled ode class.

**Comment by betanalpha** [comment]
Thanks, Bob!

The speed difference might not be huge, but I think that’s because the ODE systems
in the tests are really simple so the additional stack construction/zeroing is pretty
small compared to solving/other overhead.  It’ll have more impact in larger systems.
Even if it’s just a small change the new code is much cleaner and the logic more 
transparent.

I updated the doyxgen so that everything’s compatible now.

**Comment by wds15** [comment]
Hi!

For me this change makes quite a difference in speed. The benchmark I care about comes down from 2h to 1.25h - that's a reasonable speed increase. Amazing.

Great work.

**Comment by bob-carpenter** [comment]
It'll be faster when the virtual function calls are removed.
But probably not as much as the 30% I promised, because that
number was when we were inadvertently marching down the whole
stack.

I agree with Michael that it's independently worth it to make
the code cleaner.  The tests are still chugging away on the
underlying refactor, but that should be relatively independent of
the change in this branch.

- Bob

**Comment by wds15** [comment]
Awesome!

If you drop me note which branch to test when the virtual evilness is gone, then I am happy to run the benchmark above again on it. This is great news all together.

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by bob-carpenter** [comment]
Now that the virtual calls are gone from the develop branch,
that just needs to get merged into this.  I don't think it'll
make a big difference now that we have a nested adjoint reset
function.  

One of the reasons I wanted to remove chainable and the virtual
call is just to simplify and clean up the code.  The generality
was vestigial --- the actual functionality got rolled directly
into vari.

- Bob

**Comment by betanalpha** [comment]
I merged develop this morning -- it's ready to be merged once tests pass.

**Comment by betanalpha** [comment]
Did the remove-virtual-function tests actually pass?  The current
failures are all related to that merge,

In file included from test/unit/math_include_test.cpp:1:
In file included from ./stan/math.hpp:39:
In file included from ./stan/math/prim/scal/meta/OperandsAndPartials.hpp:21:
In file included from ./stan/math/rev/core.hpp:43:
./stan/math/rev/core/set_zero_all_adjoints_nested.hpp:4:10: fatal error: 'stan/math/rev/core/chainable.hpp' file not found
#include <stan/math/rev/core/chainable.hpp>


In file included from ./stan/math/rev/core.hpp:43:
./stan/math/rev/core/set_zero_all_adjoints_nested.hpp:4:10: fatal error: 'stan/math/rev/core/chainable.hpp' file not found
#include <stan/math/rev/core/chainable.hpp>

Also, anyone else not getting Jenkins emails anymore?

**Comment by syclik** [comment]
Yes, all the tests passed on develop.


GitHub has been messing with its notifications. Do you still want failures
to be comments? Emails? Something else? It's a matter of config and I can
make it do stuff.


On Fri, Oct 2, 2015 at 4:40 AM, Michael Betancourt <notifications@github.com
> wrote:

> Did the remove-virtual-function tests actually pass? The current
> failures are all related to that merge,
>
> In file included from test/unit/math_include_test.cpp:1:
> In file included from ./stan/math.hpp:39:
> In file included from
> ./stan/math/prim/scal/meta/OperandsAndPartials.hpp:21:
> In file included from ./stan/math/rev/core.hpp:43:
> ./stan/math/rev/core/set_zero_all_adjoints_nested.hpp:4:10: fatal error:
> 'stan/math/rev/core/chainable.hpp' file not found
> #include <stan/math/rev/core/chainable.hpp>
>
>
> In file included from ./stan/math/rev/core.hpp:43:
> ./stan/math/rev/core/set_zero_all_adjoints_nested.hpp:4:10: fatal error:
> 'stan/math/rev/core/chainable.hpp' file not found
> #include <stan/math/rev/core/chainable.hpp>
>
> Also, anyone else not getting Jenkins emails anymore?
>
> On Oct 1, 2015, at 6:04 PM, Bob Carpenter <notifications@github.com>
> wrote:
>
> > Now that the virtual calls are gone from the develop branch,
> > that just needs to get merged into this. I don't think it'll
> > make a big difference now that we have a nested adjoint reset
> > function.
> >
> > One of the reasons I wanted to remove chainable and the virtual
> > call is just to simplify and clean up the code. The generality
> > was vestigial --- the actual functionality got rolled directly
> > into vari.
> >
> > - Bob
> >

**Comment by betanalpha** [comment]
Jenkins, retest this please.

**Comment by betanalpha** [comment]
Emails preferable.  Otherwise I have no idea when the tests fail/pass.

**Comment by betanalpha** [comment]
How is this test failing?  Nothing in math/mix was touched and it passes locally.

[ RUN      ] AgradMixMatrixMdivideLeftSPD.fv_exceptions
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:506: Failure
Expected: mdivide_left_spd(fd1, fv2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:510: Failure
Expected: mdivide_left_spd(fd1, fv2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:523: Failure
Expected: mdivide_left_spd(fd1, rvf2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:524: Failure
Expected: mdivide_left_spd(fd1, rvf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:525: Failure
Expected: mdivide_left_spd(fd1, vf2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.fv_exceptions (2 ms)

**Comment by bob-carpenter** [comment]
That is odd.  I feel like I've seen that throws a different type
thing before in our tests vs. locally.  This branch changes behavior
in math/rev, so it does touch math/max in that sense.

- Bob

**Comment by betanalpha** [comment]
Wha?  Now it’s failing because it can’t checkout the branch?

**Comment by syclik** [comment]
I'll look into it.

**Comment by syclik** [comment]
The tests all pass. The failure was a false-positive.

I'm trying to configure it so it triggers upstream builds. I'm still
figuring that out.

**Comment by betanalpha** [comment]
Great, thanks for checking it out.  Mergy mergy?

**Comment by syclik** [comment]
yup.

**Comment by syclik** [comment]
woohoo!

**Pull request merged**
